// This code is auto-generated by Qul's qmltocpp tool from the file 'AnimatingItemLayer.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include <qul/image.h>
#include <qul/private/animation.h>
#include <qul/private/items.h>
#include <qul/private/layers/layers.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>

struct AnimatingItemLayer : Qul::Private::Items::ItemLayer , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::ItemLayer  > {
    AnimatingItemLayer();


    Qul::Property<Qul::Private::String> state;
    struct numberanimation_NumberAnimation : Qul::Private::Items::NumberAnimation <Qul::qreal>, public Qul::Private::Items::Animation ::ExtraStorage_animationExtraProperties<Qul::Private::Items::NumberAnimation <Qul::qreal> > {
        numberanimation_NumberAnimation()
            : Qul::Private::Items::Animation ::ExtraStorage_animationExtraProperties<Qul::Private::Items::NumberAnimation <Qul::qreal> >(this)
        {}
    } numberanimation;
    struct text__Text : Qul::Private::Items::TextLight  {
    } text_;
    struct text__2_Text : Qul::Private::Items::TextLight  {
    } text__2;
    struct textColumn_Column : Qul::Private::Items::Column  {
    } textColumn;
    struct textBox_Rectangle : Qul::Private::Items::Rectangle  {
    } textBox;
    struct image_Image : Qul::Private::Items::Image  {
    } image;
    struct rectangle_2_Rectangle : Qul::Private::Items::Rectangle  {
        Qul::Property<int> redBoxWidth;
    } rectangle_2;
    struct rectangle_Rectangle : Qul::Private::Items::Rectangle  {
    } rectangle;
    Qul::Property<int> colorDepth;
    Qul::Property<Qul::qreal> t;
    struct _onTChanged_bindingFunctor {
        AnimatingItemLayer *self;
        _onTChanged_bindingFunctor(AnimatingItemLayer *self) : self(self) {}
        void operator()() const;
    };
    Qul::Private::ChangedEvent<_onTChanged_bindingFunctor, Qul::qreal > _onTChanged_binding;
    struct _depth_bindingFunctor {
        Qul::Private::Items::LayerBase::ColorDepth operator()(AnimatingItemLayer *self) const;
    };
    Qul::Private::Binding<Qul::Private::Items::LayerBase::ColorDepth, _depth_bindingFunctor, 0> _depth_binding;
    struct rectangle_width_anchor_bindingFunctor {
    int operator()(AnimatingItemLayer *self) const;
};
    Qul::Private::Binding<int,rectangle_width_anchor_bindingFunctor, 1> rectangle_width_anchor_binding;
    struct rectangle_height_anchor_bindingFunctor {
    int operator()(AnimatingItemLayer *self) const;
};
    Qul::Private::Binding<int,rectangle_height_anchor_bindingFunctor, 1> rectangle_height_anchor_binding;
    struct textBox_height_bindingFunctor {
        int operator()(AnimatingItemLayer *self) const;
    };
    Qul::Private::Binding<QUL_PROPERTY_TYPE(textBox.height), textBox_height_bindingFunctor, 0> textBox_height_binding;
    struct textBox_width_bindingFunctor {
        int operator()(AnimatingItemLayer *self) const;
    };
    Qul::Private::Binding<QUL_PROPERTY_TYPE(textBox.width), textBox_width_bindingFunctor, 0> textBox_width_binding;
    struct textColumn_x_anchor_bindingFunctor {
    int operator()(AnimatingItemLayer *self) const;
};
    Qul::Private::Binding<int,textColumn_x_anchor_bindingFunctor, 2> textColumn_x_anchor_binding;
    struct textColumn_y_anchor_bindingFunctor {
    int operator()(AnimatingItemLayer *self) const;
};
    Qul::Private::Binding<int,textColumn_y_anchor_bindingFunctor, 0> textColumn_y_anchor_binding;
    struct text__x_anchor_bindingFunctor {
    int operator()(AnimatingItemLayer *self) const;
};
    Qul::Private::Binding<int,text__x_anchor_bindingFunctor, 2> text__x_anchor_binding;
    struct text__text_bindingFunctor {
        Qul::Private::String operator()(AnimatingItemLayer *self) const;
    };
    Qul::Private::Binding<QUL_PROPERTY_TYPE(text_.text), text__text_bindingFunctor, 0> text__text_binding;
    struct text__2_x_anchor_bindingFunctor {
    int operator()(AnimatingItemLayer *self) const;
};
    Qul::Private::Binding<int,text__2_x_anchor_bindingFunctor, 2> text__2_x_anchor_binding;
    struct text__2_text_bindingFunctor {
        Qul::Private::String operator()(AnimatingItemLayer *self) const;
    };
    Qul::Private::Binding<QUL_PROPERTY_TYPE(text__2.text), text__2_text_bindingFunctor, 0> text__2_text_binding;
    struct image_x_anchor_bindingFunctor {
    int operator()(AnimatingItemLayer *self) const;
};
    Qul::Private::Binding<int,image_x_anchor_bindingFunctor, 2> image_x_anchor_binding;
    struct image_y_anchor_bindingFunctor {
    int operator()(AnimatingItemLayer *self) const;
};
    Qul::Private::Binding<int,image_y_anchor_bindingFunctor, 3> image_y_anchor_binding;
    struct rectangle_2_x_bindingFunctor {
        int operator()(AnimatingItemLayer *self) const;
    };
    Qul::Private::Binding<QUL_PROPERTY_TYPE(rectangle_2.x), rectangle_2_x_bindingFunctor, 0> rectangle_2_x_binding;
    struct rectangle_2_y_anchor_bindingFunctor {
    int operator()(AnimatingItemLayer *self) const;
};
    Qul::Private::Binding<int,rectangle_2_y_anchor_bindingFunctor, 2> rectangle_2_y_anchor_binding;
    struct rectangle_2_height_bindingFunctor {
        int operator()(AnimatingItemLayer *self) const;
    };
    Qul::Private::Binding<QUL_PROPERTY_TYPE(rectangle_2.height), rectangle_2_height_bindingFunctor, 0> rectangle_2_height_binding;
    struct rectangle_2_width_bindingFunctor {
        int operator()(AnimatingItemLayer *self) const;
    };
    Qul::Private::Binding<QUL_PROPERTY_TYPE(rectangle_2.width), rectangle_2_width_bindingFunctor, 0> rectangle_2_width_binding;
    struct rectangle_2_redBoxWidth_bindingFunctor {
        int operator()(AnimatingItemLayer *self) const;
    };
    Qul::Private::Binding<QUL_PROPERTY_TYPE(rectangle_2.redBoxWidth), rectangle_2_redBoxWidth_bindingFunctor, 0> rectangle_2_redBoxWidth_binding;
};
