// This code is auto-generated by Qul's qmltocpp tool from the file 'MovingImageLayer.qml'
// WARNING! All changes made in this file will be lost!
// NOTE: This generated API is to be considered implementation detail for Qul.
//       It may change from version to version and should not be relied upon.
#pragma once
#include <qul/image.h>
#include <qul/private/animation.h>
#include <qul/private/builtins.h>
#include <qul/private/items.h>
#include <qul/private/layers/layers.h>
#include <qul/private/qulrcc_lookup.h>
#include <qul/private/unicodestring.h>
#include <qul/signal.h>

struct MovingImageLayer : Qul::Private::Items::ImageLayer , public Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::ImageLayer  > {
    MovingImageLayer();


    Qul::Property<Qul::Private::String> state;
    struct numberanimation_NumberAnimation : Qul::Private::Items::NumberAnimation <Qul::qreal>, public Qul::Private::Items::Animation ::ExtraStorage_animationExtraProperties<Qul::Private::Items::NumberAnimation <Qul::qreal> > {
        numberanimation_NumberAnimation()
            : Qul::Private::Items::Animation ::ExtraStorage_animationExtraProperties<Qul::Private::Items::NumberAnimation <Qul::qreal> >(this)
        {}
    } numberanimation;
    Qul::Property<Qul::qreal> vx;
    Qul::Property<Qul::qreal> vy;
    Qul::Property<Qul::Private::Items::ItemBase *> container;
    Qul::Property<Qul::qreal> t;
    Qul::Private::Items::ComponentAttachedType  ComponentAttachedType_node;
    struct _onTChanged_bindingFunctor {
        MovingImageLayer *self;
        _onTChanged_bindingFunctor(MovingImageLayer *self) : self(self) {}
        void operator()() const;
    };
    Qul::Private::ChangedEvent<_onTChanged_bindingFunctor, Qul::qreal > _onTChanged_binding;
    struct ComponentAttachedType_node_onCompleted_bindingFunctor {
        MovingImageLayer *self;
        ComponentAttachedType_node_onCompleted_bindingFunctor(MovingImageLayer *self) : self(self) {}
        void operator()() const;
    };
    static void ComponentAttachedType_node_onCompleted_binding_slot(MovingImageLayer *self) { return ComponentAttachedType_node_onCompleted_bindingFunctor(self)(); }
    Qul::Private::Slot<MovingImageLayer, void()> ComponentAttachedType_node_onCompleted_binding;
};
