#ifndef __build_ospi_handover_d9_ref_kernel_lk_wrapper_module_config_h_H
#define __build_ospi_handover_d9_ref_kernel_lk_wrapper_module_config_h_H
#define MODULE_COMPILEFLAGS "__WNO_FORMAT__FNO_BUILTIN__WNO_UNUSED_VARIABLE__WNO_SIGN_COMPARE__WNO_FORMAT__WNO_POINTER_TO_INT_CAST"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_INCLUDES ""
#define MODULE_SRCDEPS ""
#define MODULE_DEPS ""
#define MODULE_SRCS "_KERNEL_LK_WRAPPER_LK_EVENT_C_KERNEL_LK_WRAPPER_LK_MUTEX_C_KERNEL_LK_WRAPPER_LK_SEMAPHORE_C_KERNEL_LK_WRAPPER_LK_TIMERS_C_KERNEL_LK_WRAPPER_LK_THREAD_C"
#endif
