/*
 * Generated by erpcgen 1.7.0 on Sun Feb  2 16:49:53 2020.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_virComCbk_server_h_)
#define _virComCbk_server_h_

#ifdef __cplusplus
#include "erpc_server.h"
#include "erpc_codec.h"
extern "C"
{
#include "virComCbk.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 10700 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for virComCbk.
 */
class virComCbk_service : public erpc::Service
{
public:
    virComCbk_service() : Service(kvirComCbk_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for virCan_ControllerBusOff of virComCbk interface. */
    erpc_status_t virCan_ControllerBusOff_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for virCan_SetWakeupEvent of virComCbk interface. */
    erpc_status_t virCan_SetWakeupEvent_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for virCan_RxIndication of virComCbk interface. */
    erpc_status_t virCan_RxIndication_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for virCan_TxConfirmation of virComCbk interface. */
    erpc_status_t virCan_TxConfirmation_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "virComCbk.h"
#endif // __cplusplus

typedef void * erpc_service_t;

erpc_service_t create_virComCbk_service(void);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _virComCbk_server_h_
