/*
 * Generated by erpcgen 1.7.0 on Sun Feb  2 16:49:53 2020.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_virComCbk_h_)
#define _virComCbk_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10700 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief virComCbk identifiers */
enum _virComCbk_ids
{
    kvirComCbk_service_id = 1,
    kvirComCbk_virCan_ControllerBusOff_id = 1,
    kvirComCbk_virCan_SetWakeupEvent_id = 2,
    kvirComCbk_virCan_RxIndication_id = 3,
    kvirComCbk_virCan_TxConfirmation_id = 4,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name virComCbk
//@{
/******************* CAN callback function interface *********************/
void virCan_ControllerBusOff(uint8_t Controller);

void virCan_SetWakeupEvent(uint8_t Controller);

void virCan_RxIndication(uint16_t Hrh, uint32_t CanId, uint8_t CanDlc, uint8_t * CanSduPtr);

void virCan_TxConfirmation(uint16_t canTxPduId);
//@} 

#if defined(__cplusplus)
}
#endif

#endif // _virComCbk_h_
