#ifndef __build_safety_d9_ref_framework_service_base_module_config_h_H
#define __build_safety_d9_ref_framework_service_base_module_config_h_H
#define MODULE_COMPILEFLAGS "__WALL"
#define MODULE_CFLAGS ""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_INCLUDES ""
#define MODULE_SRCDEPS ""
#define MODULE_DEPS "_FRAMEWORK_COMMUNICATION_FRAMEWORK_SERVICE_PROPERTY_FRAMEWORK_SERVICE_RPMSG"
#define MODULE_SRCS "_FRAMEWORK_SERVICE_BASE_DCF_COMMON_C_FRAMEWORK_SERVICE_BASE_DCF_FILE_C_FRAMEWORK_SERVICE_BASE_DCF_SELECT_C_FRAMEWORK_SERVICE_BASE_DCF_NOTIFY_C_FRAMEWORK_SERVICE_BASE_DCF_SERVICE_C"
#endif
