#!/bin/bash
if [ -L $0 ]
then
    BASE_DIR=`dirname $(readlink $0)`
else
    BASE_DIR=`dirname $0`
fi #

if [ ! -n "$2" ] ;then
	echo "Need specify Image Base."
	exit 1
fi
#../../../romc/atb_signer sign --sec_ver 1234 --pkg_ver 1 --rcp key=test/keys/TestRSA512_ossl.pem rot=2 --iib img=$1 to=0x100000 entry=0x100000 ctl=12345678900d900d uuid=12345678ab --dgst sha256 aes_key_id=1 --of $1.safe.signed
atb_signer sign --sec_ver 1234 --pkg_ver 1 --rcp key=$BASE_DIR/test/keys/TestRSA1024_ossl.pem rot=2 --iib img=$1 to=$2 entry=$2 ctl=12345678900d900d uuid=12345678ab --dgst sha256 aes_key_id=1 --of $1.signed_$2.rsa1024
