include $(MKDIR)/build.mk

# specify SUBDIRS here

MODULE_CFLAGS += -I$(TOPDIR)/bt_dev/usb/inc
MODULE_CFLAGS += -I./include
MODULE_CFLAGS += -I./include/usb/class/
MODULE_CFLAGS += -I$(TOPDIR)/ip/dw_usb/include

include $(MKDIR)/objs_subdir.mk
include $(MKDIR)/rules.mk
