// This code is auto-generated by Qul's qmltocpp tool from the file 'layers.qml'
// WARNING! All changes made in this file will be lost!
#include "layers.h"
#include <qul/private/graphicsdevice.h>
#include <qul/imageprovider.h>

extern const Qul::Private::RasterBuffer *qul_rasterBuffer_2_200_qt_2Dmove_handle;
extern const Qul::Private::RasterBuffer *qul_rasterBuffer_2_200_qt_2Dmove_handle;
extern const Qul::Private::RasterBuffer *qul_rasterBuffer_0_0_background_2Dbig_handle;
extern const Qul::Private::RasterBuffer *qul_rasterBuffer_2_200_qt_2Dmove_handle;

namespace {
struct TranslationIndexBindingFunctor {
   int operator()() const {
       Qul::Private::String id = Qul::Private::Builtins::GlobalQtObject::uiLanguage.value();
       if (id == Qul::Private::Latin1String("", 0)) return 0;
       return 0;
   }
};
static Qul::Private::Binding<int, TranslationIndexBindingFunctor, 0> translationIndexBinding((TranslationIndexBindingFunctor()), Qul::Private::BindingFunctorNoParameters());
static Qul::Property<int> translationIndex(&translationIndexBinding);
}



int layers::screen_marginWidth_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED screen_Screen * r2;
    int r2__width;
    Qul::qreal r2_1;
    int r7__width;
    int r8;
    // property int marginWidth: screen.width * 4 / 100
    // line 34  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2 = &self->screen;
    r2__width = r2->width.value();
    r7__width = r2__width;
    r2__width = 4;
    r2__width = r7__width * r2__width;
    r8 = r2__width;
    r2__width = 100;
    r2_1 = Qul::qreal(r8) / r2__width;
    return int(r2_1);

}
int layers::screen_boxHeight_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED screen_Screen * r2;
    int r2__height;
    Qul::qreal r2_1;
    int r7__height;
    int r8;
    // property int boxHeight: screen.height * 40 / 100
    // line 33  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2 = &self->screen;
    r2__height = r2->height.value();
    r7__height = r2__height;
    r2__height = 40;
    r2__height = r7__height * r2__height;
    r8 = r2__height;
    r2__height = 100;
    r2_1 = Qul::qreal(r8) / r2__height;
    return int(r2_1);

}
int layers::screen_boxWidth_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED screen_Screen * r2;
    int r2__width;
    Qul::qreal r2_1;
    int r7__width;
    int r8;
    // property int boxWidth: screen.width * 43 / 100
    // line 32  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2 = &self->screen;
    r2__width = r2->width.value();
    r7__width = r2__width;
    r2__width = 43;
    r2__width = r7__width * r2__width;
    r8 = r2__width;
    r2__width = 100;
    r2_1 = Qul::qreal(r8) / r2__width;
    return int(r2_1);

}
int layers::spriteLayer32bpp_width_anchor_bindingFunctor::operator()(layers *self) const {
        return int(self->screen.width.value());
};
int layers::spriteLayer32bpp_height_anchor_bindingFunctor::operator()(layers *self) const {
        return int(self->screen.height.value());
};
int layers::animatingitemlayer_x_anchor_bindingFunctor::operator()(layers *self) const {
    struct marginsFunctor {
        layers *self;
        int operator()() const {
            QUL_DECL_UNUSED screen_Screen * r2;
            int r2__marginWidth;
            // anchors.margins: screen.marginWidth
            // line 82  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
            r2 = &self->screen;
            r2__marginWidth = r2->marginWidth.value();
            return r2__marginWidth;

        }
    } margins = { self };
        return int(self->spriteLayer32bpp.width.value() - (margins()) - (self->animatingitemlayer.width.value()));
};
int layers::animatingitemlayer_height_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED screen_Screen * r2;
    int r2__boxHeight;
    // height: screen.boxHeight
    // line 79  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2 = &self->screen;
    r2__boxHeight = r2->boxHeight.value();
    return r2__boxHeight;

}
int layers::animatingitemlayer_width_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED screen_Screen * r2;
    int r2__boxWidth;
    // width: screen.boxWidth
    // line 78  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2 = &self->screen;
    r2__boxWidth = r2->boxWidth.value();
    return r2__boxWidth;

}
Qul::Private::Items::ItemBase * layers::move1_container_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED spriteLayer32bpp_SpriteLayer * r2;
    // container: spriteLayer32bpp
    // line 92  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2 = &self->spriteLayer32bpp;
    return r2;

}
Qul::Private::Items::ItemBase * layers::move2_container_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED spriteLayer32bpp_SpriteLayer * r2;
    // container: spriteLayer32bpp
    // line 99  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2 = &self->spriteLayer32bpp;
    return r2;

}
Qul::Private::Items::LayerBase::ColorDepth layers::spriteLayer16bpp_depth_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED Qul::Private::Items::LayerBase::ColorDepth r2__Bpp16;
    // depth: ItemLayer.Bpp16
    // line 110  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2__Bpp16 = Qul::Private::Items::LayerBase::Bpp16;
    return r2__Bpp16;

}
int layers::spriteLayer16bpp_width_anchor_bindingFunctor::operator()(layers *self) const {
        return int(self->screen.width.value());
};
int layers::spriteLayer16bpp_height_anchor_bindingFunctor::operator()(layers *self) const {
        return int(self->screen.height.value());
};
Qul::Private::Items::LayerBase::ColorDepth layers::animatingitemlayer_2_depth_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED Qul::Private::Items::LayerBase::ColorDepth r2__Bpp16;
    // depth: ItemLayer.Bpp16
    // line 127  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2__Bpp16 = Qul::Private::Items::LayerBase::Bpp16;
    return r2__Bpp16;

}
int layers::animatingitemlayer_2_x_anchor_bindingFunctor::operator()(layers *self) const {
    struct marginsFunctor {
        layers *self;
        int operator()() const {
            QUL_DECL_UNUSED screen_Screen * r2;
            int r2__marginWidth;
            // anchors.margins: screen.marginWidth
            // line 124  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
            r2 = &self->screen;
            r2__marginWidth = r2->marginWidth.value();
            return r2__marginWidth;

        }
    } margins = { self };
        return int(margins());
};
int layers::animatingitemlayer_2_height_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED screen_Screen * r2;
    int r2__boxHeight;
    // height: screen.boxHeight
    // line 121  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2 = &self->screen;
    r2__boxHeight = r2->boxHeight.value();
    return r2__boxHeight;

}
int layers::animatingitemlayer_2_width_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED screen_Screen * r2;
    int r2__boxWidth;
    // width: screen.boxWidth
    // line 120  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2 = &self->screen;
    r2__boxWidth = r2->boxWidth.value();
    return r2__boxWidth;

}
Qul::Private::Items::ItemBase * layers::move3_container_bindingFunctor::operator()(layers *self) const
{
    (void) self;
    QUL_DECL_UNUSED spriteLayer16bpp_SpriteLayer * r2;
    // container: spriteLayer16bpp
    // line 134  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    r2 = &self->spriteLayer16bpp;
    return r2;

}

layers::layers()

    : Qul::Private::Items::ItemBase ::ExtraStorage_itemExtraProperties<Qul::Private::Items::Application  >(this)
    , screen_marginWidth_binding(screen_marginWidth_bindingFunctor())
    , screen_boxHeight_binding(screen_boxHeight_bindingFunctor())
    , screen_boxWidth_binding(screen_boxWidth_bindingFunctor())
    , spriteLayer32bpp_width_anchor_binding(spriteLayer32bpp_width_anchor_bindingFunctor())
    , spriteLayer32bpp_height_anchor_binding(spriteLayer32bpp_height_anchor_bindingFunctor())
    , animatingitemlayer_x_anchor_binding(animatingitemlayer_x_anchor_bindingFunctor())
    , animatingitemlayer_height_binding(animatingitemlayer_height_bindingFunctor())
    , animatingitemlayer_width_binding(animatingitemlayer_width_bindingFunctor())
    , move1_container_binding(move1_container_bindingFunctor())
    , move2_container_binding(move2_container_bindingFunctor())
    , spriteLayer16bpp_depth_binding(spriteLayer16bpp_depth_bindingFunctor())
    , spriteLayer16bpp_width_anchor_binding(spriteLayer16bpp_width_anchor_bindingFunctor())
    , spriteLayer16bpp_height_anchor_binding(spriteLayer16bpp_height_anchor_bindingFunctor())
    , animatingitemlayer_2_depth_binding(animatingitemlayer_2_depth_bindingFunctor())
    , animatingitemlayer_2_x_anchor_binding(animatingitemlayer_2_x_anchor_bindingFunctor())
    , animatingitemlayer_2_height_binding(animatingitemlayer_2_height_bindingFunctor())
    , animatingitemlayer_2_width_binding(animatingitemlayer_2_width_bindingFunctor())
    , move3_container_binding(move3_container_bindingFunctor())
{
    // Screen {
    // line 26  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    appendChild(this, &screen);
    screen_marginWidth_binding.init<layers, &layers::screen_marginWidth_binding>();
    // property int marginWidth: screen.width * 4 / 100
    // line 34  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    screen.marginWidth.setBinding(&screen_marginWidth_binding);
    screen_boxHeight_binding.init<layers, &layers::screen_boxHeight_binding>();
    // property int boxHeight: screen.height * 40 / 100
    // line 33  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    screen.boxHeight.setBinding(&screen_boxHeight_binding);
    screen_boxWidth_binding.init<layers, &layers::screen_boxWidth_binding>();
    // property int boxWidth: screen.width * 43 / 100
    // line 32  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    screen.boxWidth.setBinding(&screen_boxWidth_binding);
    // height: 720
    // line 30  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    screen.height.setValue(720);
    // width: 1920
    // line 29  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    screen.width.setValue(1920);
    // SpriteLayer {
    // line 68  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    appendChild(&this->screen, &spriteLayer32bpp);
    spriteLayer32bpp.x.setValue(int());
    spriteLayer32bpp_width_anchor_binding.init<layers, &layers::spriteLayer32bpp_width_anchor_binding>();
    spriteLayer32bpp.width.setBinding(&spriteLayer32bpp_width_anchor_binding);
    spriteLayer32bpp.y.setValue(int());
    spriteLayer32bpp_height_anchor_binding.init<layers, &layers::spriteLayer32bpp_height_anchor_binding>();
    spriteLayer32bpp.height.setBinding(&spriteLayer32bpp_height_anchor_binding);
    // opacity: 0.6
    // line 71  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    spriteLayer32bpp.opacity.setValue(0.6);
    // z: 1
    // line 70  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    spriteLayer32bpp.itemExtraProperties->z.setValue(1);
    // AnimatingItemLayer {
    // line 75  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    appendChild(&this->spriteLayer32bpp, &animatingitemlayer);
    // refreshInterval: 1
    // line 85  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer.refreshInterval.setValue(1);
    // colorDepth: 32
    // line 84  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer.colorDepth.setValue(32);
    animatingitemlayer_x_anchor_binding.init<layers, &layers::animatingitemlayer_x_anchor_binding>();
    animatingitemlayer.x.setBinding(&animatingitemlayer_x_anchor_binding);
    animatingitemlayer_height_binding.init<layers, &layers::animatingitemlayer_height_binding>();
    // height: screen.boxHeight
    // line 79  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer.height.setBinding(&animatingitemlayer_height_binding);
    animatingitemlayer_width_binding.init<layers, &layers::animatingitemlayer_width_binding>();
    // width: screen.boxWidth
    // line 78  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer.width.setBinding(&animatingitemlayer_width_binding);
    // y: 300
    // line 77  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer.y.setValue(300);
    // z: 1
    // line 76  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer.itemExtraProperties->z.setValue(1);
    // MovingImageLayer {
    // line 88  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    appendChild(&this->spriteLayer32bpp, &move1);
    // source: "qt-move.png"
    // line 93  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    //move1.source.setValue(Qul::Private::ImagePrivate::fromRasterBuffer(qul_rasterBuffer_2_200_qt_2Dmove_handle));
    move1.source.setValue(Qul::Private::dispatchToImageProvider("fatlocation", 11, "qt-move.png", 11));
    move1_container_binding.init<layers, &layers::move1_container_binding>();
    // container: spriteLayer32bpp
    // line 92  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    move1.container.setBinding(&move1_container_binding);
    // x: 900
    // line 91  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    move1.x.setValue(900);
    // z: 2
    // line 89  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    move1.itemExtraProperties->z.setValue(2);
    // MovingImageLayer {
    // line 96  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    appendChild(&this->spriteLayer32bpp, &move2);
    // source: "qt-move.png"
    // line 100  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    //move2.source.setValue(Qul::Private::ImagePrivate::fromRasterBuffer(qul_rasterBuffer_2_200_qt_2Dmove_handle));
    move2.source.setValue(Qul::Private::dispatchToImageProvider("fatlocation", 11, "qt-move.png", 11));
    move2_container_binding.init<layers, &layers::move2_container_binding>();
    // container: spriteLayer32bpp
    // line 99  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    move2.container.setBinding(&move2_container_binding);
    // z: 0
    // line 97  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    move2.itemExtraProperties->z.setValue(0);
    // SpriteLayer {
    // line 104  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    appendChild(&this->screen, &spriteLayer16bpp);
    spriteLayer16bpp_depth_binding.init<layers, &layers::spriteLayer16bpp_depth_binding>();
    // depth: ItemLayer.Bpp16
    // line 110  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    spriteLayer16bpp.depth.setBinding(&spriteLayer16bpp_depth_binding);
    spriteLayer16bpp.x.setValue(int());
    spriteLayer16bpp_width_anchor_binding.init<layers, &layers::spriteLayer16bpp_width_anchor_binding>();
    spriteLayer16bpp.width.setBinding(&spriteLayer16bpp_width_anchor_binding);
    spriteLayer16bpp.y.setValue(int());
    spriteLayer16bpp_height_anchor_binding.init<layers, &layers::spriteLayer16bpp_height_anchor_binding>();
    spriteLayer16bpp.height.setBinding(&spriteLayer16bpp_height_anchor_binding);
    // z: 0
    // line 106  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    spriteLayer16bpp.itemExtraProperties->z.setValue(0);
    // ImageLayer {
    // line 112  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    appendChild(&this->spriteLayer16bpp, &imagelayer);
    // source: "background-big.png"
    // line 114  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    //imagelayer.source.setValue(Qul::Private::ImagePrivate::fromRasterBuffer(qul_rasterBuffer_0_0_background_2Dbig_handle));
    imagelayer.source.setValue(Qul::Private::dispatchToImageProvider("fatlocation", 11, "background-big.png", 18));
    // z: 0
    // line 113  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    imagelayer.itemExtraProperties->z.setValue(0);
    // AnimatingItemLayer {
    // line 117  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    appendChild(&this->spriteLayer16bpp, &animatingitemlayer_2);
    // opacity: 0.6
    // line 128  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer_2.opacity.setValue(0.6);
    animatingitemlayer_2_depth_binding.init<layers, &layers::animatingitemlayer_2_depth_binding>();
    // depth: ItemLayer.Bpp16
    // line 127  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer_2.depth.setBinding(&animatingitemlayer_2_depth_binding);
    // colorDepth: 16
    // line 126  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer_2.colorDepth.setValue(16);
    animatingitemlayer_2_x_anchor_binding.init<layers, &layers::animatingitemlayer_2_x_anchor_binding>();
    animatingitemlayer_2.x.setBinding(&animatingitemlayer_2_x_anchor_binding);
    animatingitemlayer_2_height_binding.init<layers, &layers::animatingitemlayer_2_height_binding>();
    // height: screen.boxHeight
    // line 121  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer_2.height.setBinding(&animatingitemlayer_2_height_binding);
    animatingitemlayer_2_width_binding.init<layers, &layers::animatingitemlayer_2_width_binding>();
    // width: screen.boxWidth
    // line 120  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer_2.width.setBinding(&animatingitemlayer_2_width_binding);
    // y: 0
    // line 119  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer_2.y.setValue(0);
    // z: 1
    // line 118  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    animatingitemlayer_2.itemExtraProperties->z.setValue(1);
    // MovingImageLayer {
    // line 130  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    appendChild(&this->spriteLayer16bpp, &move3);
    // source: "qt-move.png"
    // line 135  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    //move3.source.setValue(Qul::Private::ImagePrivate::fromRasterBuffer(qul_rasterBuffer_2_200_qt_2Dmove_handle));
    move3.source.setValue(Qul::Private::dispatchToImageProvider("fatlocation", 11, "qt-move.png", 11));
    move3_container_binding.init<layers, &layers::move3_container_binding>();
    // container: spriteLayer16bpp
    // line 134  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    move3.container.setBinding(&move3_container_binding);
    // x: 1200
    // line 133  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    move3.x.setValue(1200);
    // z: 2
    // line 131  "D:/0_install/Qul1.7/QtMCUs/1.7.0/examples/layers/layers.qml"
    move3.itemExtraProperties->z.setValue(2);
}
