// This code is auto-generated by Qul's qulrcc tool.
// WARNING! All changes made in this file will be lost!

#include <qul/private/qulrcc_lookup.h>

#ifdef QUL_RUNTIME_RESOURCE_LOOKUP_SUPPORT
extern const Qul::Private::RasterBuffer* qul_rasterBuffer_1_0_qt_2Dlogo_handle;
extern const Qul::Private::RasterBuffer* qul_rasterBuffer_2_200_qt_2Dmove_handle;
extern const Qul::Private::RasterBuffer* qul_rasterBuffer_0_0_background_2Dbig_handle;


namespace Qul {
namespace Private {

const ImageAssetLookupEntry qrcImageLookupSize[] = {

    {11, 0, 1},
    {18, 2, 2}
#if defined(QUL_CC_MSVC) || defined(QUL_CC_GHS) || defined(QUL_CC_IAR)
    , {0, 0, 0}
#endif
};

const ImageAssetLookupEntry qrcImageLookupHash[] = {

    {13297, 0, 65535},
    {37675, 1, 65535},
    {41917, 2, 65535}
#if defined(QUL_CC_MSVC) || defined(QUL_CC_GHS) || defined(QUL_CC_IAR)
    , {0, 0, 0}
#endif
};

const ImageAssetEntry qrcImageLookupPath[] = {

#if defined(QUL_CC_MSVC) || defined(QUL_CC_GHS) || defined(QUL_CC_IAR)
    {NULL, NULL}
#endif
};

const RasterBuffer *qrcImageLookupDirect[] = {

    qul_rasterBuffer_1_0_qt_2Dlogo_handle,
    qul_rasterBuffer_2_200_qt_2Dmove_handle,
    qul_rasterBuffer_0_0_background_2Dbig_handle
#if defined(QUL_CC_MSVC) || defined(QUL_CC_GHS) || defined(QUL_CC_IAR)
    , NULL
#endif
};

const quint16 qrcImageLookupSizeLength = 2;


} // namespace Private
} // namespace Qul

#endif
