/*
 * dw_dmac_mux.c
 *
 * Copyright (c) 2019 Semidrive Semiconductor.
 * All rights reserved.
 *
 * dw dma controller mux c file
 * This file define dmac table for hand shaking selection.
 * Revision History:
 * -----------------
 * 0.1, 4/8/2019 yishao init version
 */
#ifndef __DW_DMAC_MUX_C
#define __DW_DMAC_MUX_C
#include "dw_dmac_mux.h"
#include "res.h"
#include "stdio.h"
#include "stdlib.h"
#include <debug.h>
#include <platform/debug.h>
/**
 * @description:
 * A DMA mux table, used to calculate hand shark number.
 * This init version, different version will use different table.
 */
dmac_mux_param_t dma_mux_tbl[] = {
    {DMA_MUX_CAN5, APB_CAN5_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN6, APB_CAN6_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN7, APB_CAN7_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN8, APB_CAN8_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_DC1, APB_DC1_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_DC2, APB_DC2_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_DC3, APB_DC3_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_DC4, APB_DC4_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_DC5, APB_DC5_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_DDR_SS, APB_DDR_PERF_MON_BASE, 0xFFFF,
     DMA_MUX_BOTH}, /* DDR_PERF_MON */
    {DMA_MUX_DP1, APB_DP1_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_DP2, APB_DP2_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_DP3, APB_DP3_BASE, 0xFFFF, DMA_MUX_BOTH},
    /**
     * @description:
     *  Dwc ether qos databook. bi-direction dma for reg
     * MAC_PPS(#i)_Target_Time_Seconds. Size: 32bits Offset: 0x0010*i +0x0b80
     */
    {DMA_MUX_ENET2_REQ0, APB_ENET_QOS2_BASE + 0xb80, 4,
     DMA_MUX_BOTH}, /* APB_ENET_QOS2_BASE */
    {DMA_MUX_ENET2_REQ1, APB_ENET_QOS2_BASE + 0xb80 + 0x10, 4, DMA_MUX_BOTH},
    {DMA_MUX_ENET2_REQ2, APB_ENET_QOS2_BASE + 0xb80 + 0x20, 4, DMA_MUX_BOTH},
    {DMA_MUX_ENET2_REQ3, APB_ENET_QOS2_BASE + 0xb80 + 0x30, 4, DMA_MUX_BOTH},
    {DMA_MUX_I2C5_TX, APB_I2C5_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C5_RX, APB_I2C5_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2C6_TX, APB_I2C6_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C6_RX, APB_I2C6_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2C7_TX, APB_I2C7_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C7_RX, APB_I2C7_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2C8_TX, APB_I2C8_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C8_RX, APB_I2C8_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2C9_TX, APB_I2C9_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C9_RX, APB_I2C9_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2C10_TX, APB_I2C10_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C10_RX, APB_I2C10_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2C11_TX, APB_I2C11_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C11_RX, APB_I2C11_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2C12_TX, APB_I2C12_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C12_RX, APB_I2C12_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2C13_TX, APB_I2C13_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C13_RX, APB_I2C13_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2C14_TX, APB_I2C14_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C14_RX, APB_I2C14_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2C15_TX, APB_I2C15_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C15_RX, APB_I2C15_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2C16_TX, APB_I2C16_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2C16_RX, APB_I2C16_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2S_MC1_RX, APB_I2S_MC1_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2S_MC1_TX, APB_I2S_MC1_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2S_MC2_RX, APB_I2S_MC2_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2S_MC2_TX, APB_I2S_MC2_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2S_SC3_RX, APB_I2S_SC3_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2S_SC3_TX, APB_I2S_SC3_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2S_SC4_RX, APB_I2S_SC4_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2S_SC4_TX, APB_I2S_SC4_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2S_SC5_RX, APB_I2S_SC5_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2S_SC5_TX, APB_I2S_SC5_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2S_SC6_RX, APB_I2S_SC6_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2S_SC6_TX, APB_I2S_SC6_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2S_SC7_RX, APB_I2S_SC7_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2S_SC7_TX, APB_I2S_SC7_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_I2S_SC8_RX, APB_I2S_SC8_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_I2S_SC8_TX, APB_I2S_SC8_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_OSPI2_RX, OSPI2_BASE, 0x03FFFFFF, DMA_MUX_RD},
    {DMA_MUX_OSPI2_TX, OSPI2_BASE, 0x03FFFFFF, DMA_MUX_WR},
    {DMA_MUX_PWM3_REQ, APB_PWM3_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_PWM4_REQ, APB_PWM4_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_PWM5_REQ, APB_PWM5_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_PWM6_REQ, APB_PWM6_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_PWM7_REQ, APB_PWM7_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_PWM8_REQ, APB_PWM8_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_SPDIF1_REQ, APB_SPDIF1_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_SPDIF2_REQ, APB_SPDIF2_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_SPDIF3_REQ, APB_SPDIF3_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_SPDIF4_REQ, APB_SPDIF4_BASE, 0xFFFF, DMA_MUX_BOTH},
    {DMA_MUX_SPI5_RX, APB_SPI5_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_SPI5_TX, APB_SPI5_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_SPI6_RX, APB_SPI6_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_SPI6_TX, APB_SPI6_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_SPI7_RX, APB_SPI7_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_SPI7_TX, APB_SPI7_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_SPI8_RX, APB_SPI8_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_SPI8_TX, APB_SPI8_BASE, 0xFFFF, DMA_MUX_WR},
    /**
     * @description:
     * REQA for CNT_LOCAL_A_OVF 0x30 size 4 bytes
     *      and FIFO_A 0xA0 size 4 bytes
     * REQB for CNT_LOCAL_B_OVF 0x34 size 4 bytes
     *      and FIFO_B 0xA4 size 4 bytes
     * REQC for CNT_LOCAL_C_OVF 0x38 size 4 bytes
     *      and FIFO_C 0xA8 size 4 bytes
     * REQD for CNT_LOCAL_D_OVF 0x3C size 4 bytes
     *      and FIFO_D 0xAC size 4 bytes
     * OVF for CNT_G0_OVF 0x28 size 4 bytes
     *      and CNT_G1_OVF 0x3C size 4 bytes
     */
    {DMA_MUX_TIMER3_REQA, APB_TIMER3_BASE + 0x30, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER3_REQA, APB_TIMER3_BASE + 0xA0, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER3_REQB, APB_TIMER3_BASE + 0x34, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER3_REQB, APB_TIMER3_BASE + 0xA4, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER3_REQC, APB_TIMER3_BASE + 0x38, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER3_REQC, APB_TIMER3_BASE + 0xA8, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER3_REQD, APB_TIMER3_BASE + 0x3C, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER3_REQD, APB_TIMER3_BASE + 0xAC, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER3_OVF, APB_TIMER3_BASE + 0x28, 0x8, DMA_MUX_BOTH},

    {DMA_MUX_TIMER4_REQA, APB_TIMER4_BASE + 0x30, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER4_REQA, APB_TIMER4_BASE + 0xA0, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER4_REQB, APB_TIMER4_BASE + 0x34, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER4_REQB, APB_TIMER4_BASE + 0xA4, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER4_REQC, APB_TIMER4_BASE + 0x38, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER4_REQC, APB_TIMER4_BASE + 0xA8, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER4_REQD, APB_TIMER4_BASE + 0x3C, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER4_REQD, APB_TIMER4_BASE + 0xAC, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER4_OVF, APB_TIMER4_BASE + 0x28, 0x8, DMA_MUX_BOTH},

    {DMA_MUX_TIMER5_REQA, APB_TIMER5_BASE + 0x30, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER5_REQA, APB_TIMER5_BASE + 0xA0, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER5_REQB, APB_TIMER5_BASE + 0x34, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER5_REQB, APB_TIMER5_BASE + 0xA4, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER5_REQC, APB_TIMER5_BASE + 0x38, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER5_REQC, APB_TIMER5_BASE + 0xA8, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER5_REQD, APB_TIMER5_BASE + 0x3C, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER5_REQD, APB_TIMER5_BASE + 0xAC, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER5_OVF, APB_TIMER5_BASE + 0x28, 0x8, DMA_MUX_BOTH},

    {DMA_MUX_TIMER6_REQA, APB_TIMER6_BASE + 0x30, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER6_REQA, APB_TIMER6_BASE + 0xA0, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER6_REQB, APB_TIMER6_BASE + 0x34, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER6_REQB, APB_TIMER6_BASE + 0xA4, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER6_REQC, APB_TIMER6_BASE + 0x38, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER6_REQC, APB_TIMER6_BASE + 0xA8, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER6_REQD, APB_TIMER6_BASE + 0x3C, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER6_REQD, APB_TIMER6_BASE + 0xAC, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER6_OVF, APB_TIMER6_BASE + 0x28, 0x8, DMA_MUX_BOTH},

    {DMA_MUX_TIMER7_REQA, APB_TIMER7_BASE + 0x30, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER7_REQA, APB_TIMER7_BASE + 0xA0, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER7_REQB, APB_TIMER7_BASE + 0x34, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER7_REQB, APB_TIMER7_BASE + 0xA4, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER7_REQC, APB_TIMER7_BASE + 0x38, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER7_REQC, APB_TIMER7_BASE + 0xA8, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER7_REQD, APB_TIMER7_BASE + 0x3C, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER7_REQD, APB_TIMER7_BASE + 0xAC, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER7_OVF, APB_TIMER7_BASE + 0x28, 0x8, DMA_MUX_BOTH},

    {DMA_MUX_TIMER8_REQA, APB_TIMER8_BASE + 0x30, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER8_REQA, APB_TIMER8_BASE + 0xA0, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER8_REQB, APB_TIMER8_BASE + 0x34, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER8_REQB, APB_TIMER8_BASE + 0xA4, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER8_REQC, APB_TIMER8_BASE + 0x38, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER8_REQC, APB_TIMER8_BASE + 0xA8, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER8_REQD, APB_TIMER8_BASE + 0x3C, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER8_REQD, APB_TIMER8_BASE + 0xAC, 0x4, DMA_MUX_BOTH},
    {DMA_MUX_TIMER8_OVF, APB_TIMER8_BASE + 0x28, 0x8, DMA_MUX_BOTH},

    {DMA_MUX_UART9_TX, APB_UART9_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_UART9_RX, APB_UART9_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_UART10_TX, APB_UART10_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_UART10_RX, APB_UART10_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_UART11_TX, APB_UART11_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_UART11_RX, APB_UART11_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_UART12_TX, APB_UART12_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_UART12_RX, APB_UART12_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_UART13_TX, APB_UART13_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_UART13_RX, APB_UART13_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_UART14_TX, APB_UART14_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_UART14_RX, APB_UART14_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_UART15_TX, APB_UART15_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_UART15_RX, APB_UART15_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_UART16_TX, APB_UART16_BASE, 0xFFFF, DMA_MUX_WR},
    {DMA_MUX_UART16_RX, APB_UART16_BASE, 0xFFFF, DMA_MUX_RD},
    {DMA_MUX_ADC, APB_ADC_BASE, 0x23F, DMA_MUX_RD},
    {DMA_MUX_CAN9, APB_CAN9_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN10, APB_CAN10_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN11, APB_CAN11_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN12, APB_CAN12_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN13, APB_CAN13_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN14, APB_CAN14_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN15, APB_CAN15_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN16, APB_CAN16_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN17, APB_CAN17_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN18, APB_CAN18_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN19, APB_CAN19_BASE, 0x3FFF, DMA_MUX_RD},
    {DMA_MUX_CAN20, APB_CAN20_BASE, 0x3FFF, DMA_MUX_RD},

};

#define DMAC_MUX_PARAM_NUM (sizeof(dma_mux_tbl) / sizeof(dma_mux_tbl[0]))

/* from address get hs number. */
int get_dma_hs_id(u64 addr, DMR_MUX_DIRECT direct)
{
  for (unsigned int i = 0; i < DMAC_MUX_PARAM_NUM; i++)
  {
    if ((addr >= p2ap(dma_mux_tbl[i].start_addr)) &&
        (addr < (p2ap(dma_mux_tbl[i].start_addr) + dma_mux_tbl[i].len)))
    {
      if ((direct & dma_mux_tbl[i].direct) > 0)
      {
        return dma_mux_tbl[i].port;
      }
    }
  }
  dprintf(ALWAYS,
          "ERROR: get_dma_hs_id missed with direction(%d) and addr(0x%llx) \n",
          direct, addr);
  return DMA_MUX_ERR_NO;
}

#endif
