/********************************************************
 *          Copyright(c) 2019   Semidrive               *
 ********************************************************/

/* Generated by tool. Do not modify manually. */

#ifndef __WDT_REG_H__
#define __WDT_REG_H__

#define WDT_CTRL_OFF    0x0U

#define FM_WDT_CTRL_PRE_DIV_NUM (0xffffU << 16U)
#define FV_WDT_CTRL_PRE_DIV_NUM(v) \
    (((v) << 16U) & FM_WDT_CTRL_PRE_DIV_NUM)
#define GFV_WDT_CTRL_PRE_DIV_NUM(v) \
    (((v) & FM_WDT_CTRL_PRE_DIV_NUM) >> 16U)

#define BM_WDT_CTRL_WDT_EN_STA      (0x01U << 10)

#define BM_WDT_CTRL_SELFTEST_TRIG   (0x01U << 9U)

#define BM_WDT_CTRL_WDT_EN_SRC  (0x01U << 8U)

#define BM_WDT_CTRL_DBG_HALT_EN (0x01U << 7U)

#define BM_WDT_CTRL_AUTO_RESTART    (0x01U << 6U)

#define BM_WDT_CTRL_WTC_SRC (0x01U << 5U)

#define FM_WDT_CTRL_CLK_SRC (0x7U << 2U)
#define FV_WDT_CTRL_CLK_SRC(v) \
    (((v) << 2U) & FM_WDT_CTRL_CLK_SRC)
#define GFV_WDT_CTRL_CLK_SRC(v) \
    (((v) & FM_WDT_CTRL_CLK_SRC) >> 2U)

#define BM_WDT_CTRL_WDT_EN  (0x01U << 1U)

#define BM_WDT_CTRL_SOFT_RST    (0x01U << 0U)

#define WDT_WTC_OFF 0x4U

#define FM_WDT_WTC_WTC_VAL  (0xffffffffU << 0U)
#define FV_WDT_WTC_WTC_VAL(v) \
    (((v) << 0U) & FM_WDT_WTC_WTC_VAL)
#define GFV_WDT_WTC_WTC_VAL(v) \
    (((v) & FM_WDT_WTC_WTC_VAL) >> 0U)

#define WDT_WRC_CTL_OFF 0x8U

#define BM_WDT_WRC_CTL_REFR_TRIG    (0x01U << 3U)

#define BM_WDT_WRC_CTL_SEQ_REFR_EN  (0x01U << 2U)

#define BM_WDT_WRC_CTL_MODE1_EN (0x01U << 1U)

#define BM_WDT_WRC_CTL_MODE0_EN (0x01U << 0U)

#define WDT_WRC_VAL_OFF 0xcU

#define FM_WDT_WRC_VAL_WIN_LOW_LIMIT    (0xffffffffU << 0U)
#define FV_WDT_WRC_VAL_WIN_LOW_LIMIT(v) \
    (((v) << 0U) & FM_WDT_WRC_VAL_WIN_LOW_LIMIT)
#define GFV_WDT_WRC_VAL_WIN_LOW_LIMIT(v) \
    (((v) & FM_WDT_WRC_VAL_WIN_LOW_LIMIT) >> 0U)

#define WDT_WRC_SEQ_OFF 0x10U

#define FM_WDT_WRC_SEQ_SEQ_DELTA    (0xffffffffU << 0U)
#define FV_WDT_WRC_SEQ_SEQ_DELTA(v) \
    (((v) << 0U) & FM_WDT_WRC_SEQ_SEQ_DELTA)
#define GFV_WDT_WRC_SEQ_SEQ_DELTA(v) \
    (((v) & FM_WDT_WRC_SEQ_SEQ_DELTA) >> 0U)

#define WDT_RST_CTL_OFF 0x14U

#define FM_WDT_RST_CTL_RST_WIN  (0xffU << 20U)
#define FV_WDT_RST_CTL_RST_WIN(v) \
    (((v) << 20U) & FM_WDT_RST_CTL_RST_WIN)
#define GFV_WDT_RST_CTL_RST_WIN(v) \
    (((v) & FM_WDT_RST_CTL_RST_WIN) >> 20U)

#define BM_WDT_RST_CTL_WDT_RST_EN   (0x01U << 18U)

#define BM_WDT_RST_CTL_INT_RST_MODE (0x01U << 17U)

#define BM_WDT_RST_CTL_INT_RST_EN   (0x01U << 16U)

#define FM_WDT_RST_CTL_RST_CNT  (0xffffU << 0U)
#define FV_WDT_RST_CTL_RST_CNT(v) \
    (((v) << 0U) & FM_WDT_RST_CTL_RST_CNT)
#define GFV_WDT_RST_CTL_RST_CNT(v) \
    (((v) & FM_WDT_RST_CTL_RST_CNT) >> 0U)

#define WDT_EXT_RST_CTL_OFF 0x18U

#define FM_WDT_EXT_RST_CTL_RST_WIN  (0xffU << 20U)
#define FV_WDT_EXT_RST_CTL_RST_WIN(v) \
    (((v) << 20U) & FM_WDT_EXT_RST_CTL_RST_WIN)
#define GFV_WDT_EXT_RST_CTL_RST_WIN(v) \
    (((v) & FM_WDT_EXT_RST_CTL_RST_WIN) >> 20U)

#define BM_WDT_EXT_RST_CTL_EXT_RST_MODE (0x01U << 17U)

#define BM_WDT_EXT_RST_CTL_EXT_RST_EN   (0x01U << 16U)

#define FM_WDT_EXT_RST_CTL_RST_CNT  (0xffffU << 0U)
#define FV_WDT_EXT_RST_CTL_RST_CNT(v) \
    (((v) << 0U) & FM_WDT_EXT_RST_CTL_RST_CNT)
#define GFV_WDT_EXT_RST_CTL_RST_CNT(v) \
    (((v) & FM_WDT_EXT_RST_CTL_RST_CNT) >> 0U)

#define WDT_CNT_OFF 0x1cU

#define FM_WDT_CNT_WDT_CNT  (0xffffffffU << 0U)
#define FV_WDT_CNT_WDT_CNT(v) \
    (((v) << 0U) & FM_WDT_CNT_WDT_CNT)
#define GFV_WDT_CNT_WDT_CNT(v) \
    (((v) & FM_WDT_CNT_WDT_CNT) >> 0U)

#define WDT_TSW_OFF 0x20U

#define FM_WDT_TSW_TSW  (0xffffffffU << 0U)
#define FV_WDT_TSW_TSW(v) \
    (((v) << 0U) & FM_WDT_TSW_TSW)
#define GFV_WDT_TSW_TSW(v) \
    (((v) & FM_WDT_TSW_TSW) >> 0U)

#define WDT_INT_OFF 0x24U

#define BM_WDT_INT_OVFLOW_INT_CLR   (0x01U << 8U)

#define BM_WDT_INT_ILL_SEQ_REFR_INT_CLR (0x01U << 7U)

#define BM_WDT_INT_ILL_WIN_REFR_INT_CLR (0x01U << 6U)

#define BM_WDT_INT_OVFLOW_INT_STA   (0x01U << 5U)

#define BM_WDT_INT_ILL_SEQ_REFR_INT_STA (0x01U << 4U)

#define BM_WDT_INT_ILL_WIN_REFR_INT_STA (0x01U << 3U)

#define BM_WDT_INT_OVFLOW_INT_EN    (0x01U << 2U)

#define BM_WDT_INT_ILL_SEQ_REFR_INT_EN  (0x01U << 1U)

#define BM_WDT_INT_ILL_WIN_REFR_INT_EN  (0x01U << 0U)

#define WDT_LOCK_OFF    0x40U

#define BM_WDT_LOCK_CLK_SRC_LOCK    (0x01U << 6U)

#define BM_WDT_LOCK_INT_LOCK    (0x01U << 5U)

#define BM_WDT_LOCK_EXT_RST_LOCK    (0x01U << 4U)

#define BM_WDT_LOCK_RST_LOCK    (0x01U << 3U)

#define BM_WDT_LOCK_WRC_LOCK    (0x01U << 2U)

#define BM_WDT_LOCK_WTC_LOCK    (0x01U << 1U)

#define BM_WDT_LOCK_CTL_LOCK    (0x01U << 0U)

typedef struct {
    volatile U32 wdt_ctrl;  /* offset: 0x0 */
    volatile U32 wdt_wtc;  /* offset: 0x4 */
    volatile U32 wdt_wrc_ctl;  /* offset: 0x8 */
    volatile U32 wdt_wrc_val;  /* offset: 0xc */
    volatile U32 wdt_wrc_seq;  /* offset: 0x10 */
    volatile U32 wdt_rst_ctl;  /* offset: 0x14 */
    volatile U32 wdt_ext_rst_ctl;  /* offset: 0x18 */
    volatile U32 wdt_cnt;  /* offset: 0x1c */
    volatile U32 wdt_tsw;  /* offset: 0x20 */
    volatile U32 wdt_int;  /* offset: 0x24 */
    U8 rsvd0[24];
    volatile U32 wdt_lock;  /* offset: 0x40 */
} wdt_t;

#endif  /* __WDT_REG_H__ */
