/*
 * Copyright (c) Semidrive
 */

#ifndef _AP_APB_MPC_REG_H
#define _AP_APB_MPC_REG_H
//--------------------------------------------------------------------------
// IP Ref Info     : REG_AP_APB_MPC
// RTL version     :
//--------------------------------------------------------------------------

//--------------------------------------------------------------------------
// Address Block Name : MPC_APB_MPC_APB_AB_0
// Description        :
//--------------------------------------------------------------------------
#if WITH_VIRT_PLATFORM
#define MPC_APB_MPC_APB_AB_0_BASE_ADDR 0x41000000
#else
#if ARM_CPU_CORTEX_R5
#define MPC_APB_MPC_APB_AB_0_BASE_ADDR 0xF0BC1000
#else
#define MPC_APB_MPC_APB_AB_0_BASE_ADDR 0x30BC1000
#endif
#endif
//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_DOM
// Register Offset : 0x0
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_DOM (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x0<<0))
#define DOM_LOCK_FIELD_OFFSET 31
#define DOM_LOCK_FIELD_SIZE 1
#define DOM_SET_FIELD_OFFSET 4
#define DOM_SET_FIELD_SIZE 1
#define DOM_DID_FIELD_OFFSET 0
#define DOM_DID_FIELD_SIZE 4

#define BIT_AP_APB_MPC_DOM_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_DOM_SET    (BIT_(4))
#define BIT_AP_APB_MPC_DOM_DID_3    (BIT_(3))
#define BIT_AP_APB_MPC_DOM_DID_2    (BIT_(2))
#define BIT_AP_APB_MPC_DOM_DID_1    (BIT_(1))
#define BIT_AP_APB_MPC_DOM_DID_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_DOM_PER0
// Register Offset : 0x4
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_DOM_PER0 (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x4<<0))
#define DOM_PER0_DOM7_LOCK_FIELD_OFFSET 31
#define DOM_PER0_DOM7_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM7_PER_FIELD_OFFSET 29
#define DOM_PER0_DOM7_PER_FIELD_SIZE 2
#define DOM_PER0_DOM7_EN_FIELD_OFFSET 28
#define DOM_PER0_DOM7_EN_FIELD_SIZE 1
#define DOM_PER0_DOM6_LOCK_FIELD_OFFSET 27
#define DOM_PER0_DOM6_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM6_PER_FIELD_OFFSET 25
#define DOM_PER0_DOM6_PER_FIELD_SIZE 2
#define DOM_PER0_DOM6_EN_FIELD_OFFSET 24
#define DOM_PER0_DOM6_EN_FIELD_SIZE 1
#define DOM_PER0_DOM5_LOCK_FIELD_OFFSET 23
#define DOM_PER0_DOM5_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM5_PER_FIELD_OFFSET 21
#define DOM_PER0_DOM5_PER_FIELD_SIZE 2
#define DOM_PER0_DOM5_EN_FIELD_OFFSET 20
#define DOM_PER0_DOM5_EN_FIELD_SIZE 1
#define DOM_PER0_DOM4_LOCK_FIELD_OFFSET 19
#define DOM_PER0_DOM4_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM4_PER_FIELD_OFFSET 17
#define DOM_PER0_DOM4_PER_FIELD_SIZE 2
#define DOM_PER0_DOM4_EN_FIELD_OFFSET 16
#define DOM_PER0_DOM4_EN_FIELD_SIZE 1
#define DOM_PER0_DOM3_LOCK_FIELD_OFFSET 15
#define DOM_PER0_DOM3_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM3_PER_FIELD_OFFSET 13
#define DOM_PER0_DOM3_PER_FIELD_SIZE 2
#define DOM_PER0_DOM3_EN_FIELD_OFFSET 12
#define DOM_PER0_DOM3_EN_FIELD_SIZE 1
#define DOM_PER0_DOM2_LOCK_FIELD_OFFSET 11
#define DOM_PER0_DOM2_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM2_PER_FIELD_OFFSET 9
#define DOM_PER0_DOM2_PER_FIELD_SIZE 2
#define DOM_PER0_DOM2_EN_FIELD_OFFSET 8
#define DOM_PER0_DOM2_EN_FIELD_SIZE 1
#define DOM_PER0_DOM1_LOCK_FIELD_OFFSET 7
#define DOM_PER0_DOM1_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM1_PER_FIELD_OFFSET 5
#define DOM_PER0_DOM1_PER_FIELD_SIZE 2
#define DOM_PER0_DOM1_EN_FIELD_OFFSET 4
#define DOM_PER0_DOM1_EN_FIELD_SIZE 1
#define DOM_PER0_DOM0_LOCK_FIELD_OFFSET 3
#define DOM_PER0_DOM0_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM0_PER_FIELD_OFFSET 1
#define DOM_PER0_DOM0_PER_FIELD_SIZE 2
#define DOM_PER0_DOM0_EN_FIELD_OFFSET 0
#define DOM_PER0_DOM0_EN_FIELD_SIZE 1

#define BIT_AP_APB_MPC_DOM_PER0_DOM7_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_DOM_PER0_DOM7_PER_1    (BIT_(30))
#define BIT_AP_APB_MPC_DOM_PER0_DOM7_PER_0    (BIT_(29))
#define BIT_AP_APB_MPC_DOM_PER0_DOM7_EN    (BIT_(28))
#define BIT_AP_APB_MPC_DOM_PER0_DOM6_LOCK    (BIT_(27))
#define BIT_AP_APB_MPC_DOM_PER0_DOM6_PER_1    (BIT_(26))
#define BIT_AP_APB_MPC_DOM_PER0_DOM6_PER_0    (BIT_(25))
#define BIT_AP_APB_MPC_DOM_PER0_DOM6_EN    (BIT_(24))
#define BIT_AP_APB_MPC_DOM_PER0_DOM5_LOCK    (BIT_(23))
#define BIT_AP_APB_MPC_DOM_PER0_DOM5_PER_1    (BIT_(22))
#define BIT_AP_APB_MPC_DOM_PER0_DOM5_PER_0    (BIT_(21))
#define BIT_AP_APB_MPC_DOM_PER0_DOM5_EN    (BIT_(20))
#define BIT_AP_APB_MPC_DOM_PER0_DOM4_LOCK    (BIT_(19))
#define BIT_AP_APB_MPC_DOM_PER0_DOM4_PER_1    (BIT_(18))
#define BIT_AP_APB_MPC_DOM_PER0_DOM4_PER_0    (BIT_(17))
#define BIT_AP_APB_MPC_DOM_PER0_DOM4_EN    (BIT_(16))
#define BIT_AP_APB_MPC_DOM_PER0_DOM3_LOCK    (BIT_(15))
#define BIT_AP_APB_MPC_DOM_PER0_DOM3_PER_1    (BIT_(14))
#define BIT_AP_APB_MPC_DOM_PER0_DOM3_PER_0    (BIT_(13))
#define BIT_AP_APB_MPC_DOM_PER0_DOM3_EN    (BIT_(12))
#define BIT_AP_APB_MPC_DOM_PER0_DOM2_LOCK    (BIT_(11))
#define BIT_AP_APB_MPC_DOM_PER0_DOM2_PER_1    (BIT_(10))
#define BIT_AP_APB_MPC_DOM_PER0_DOM2_PER_0    (BIT_(9))
#define BIT_AP_APB_MPC_DOM_PER0_DOM2_EN    (BIT_(8))
#define BIT_AP_APB_MPC_DOM_PER0_DOM1_LOCK    (BIT_(7))
#define BIT_AP_APB_MPC_DOM_PER0_DOM1_PER_1    (BIT_(6))
#define BIT_AP_APB_MPC_DOM_PER0_DOM1_PER_0    (BIT_(5))
#define BIT_AP_APB_MPC_DOM_PER0_DOM1_EN    (BIT_(4))
#define BIT_AP_APB_MPC_DOM_PER0_DOM0_LOCK    (BIT_(3))
#define BIT_AP_APB_MPC_DOM_PER0_DOM0_PER_1    (BIT_(2))
#define BIT_AP_APB_MPC_DOM_PER0_DOM0_PER_0    (BIT_(1))
#define BIT_AP_APB_MPC_DOM_PER0_DOM0_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_DOM_PER1
// Register Offset : 0x8
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_DOM_PER1 (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x8<<0))
#define DOM_PER1_DOM15_LOCK_FIELD_OFFSET 31
#define DOM_PER1_DOM15_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM15_PER_FIELD_OFFSET 29
#define DOM_PER1_DOM15_PER_FIELD_SIZE 2
#define DOM_PER1_DOM15_EN_FIELD_OFFSET 28
#define DOM_PER1_DOM15_EN_FIELD_SIZE 1
#define DOM_PER1_DOM14_LOCK_FIELD_OFFSET 27
#define DOM_PER1_DOM14_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM14_PER_FIELD_OFFSET 25
#define DOM_PER1_DOM14_PER_FIELD_SIZE 2
#define DOM_PER1_DOM14_EN_FIELD_OFFSET 24
#define DOM_PER1_DOM14_EN_FIELD_SIZE 1
#define DOM_PER1_DOM13_LOCK_FIELD_OFFSET 23
#define DOM_PER1_DOM13_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM13_PER_FIELD_OFFSET 21
#define DOM_PER1_DOM13_PER_FIELD_SIZE 2
#define DOM_PER1_DOM13_EN_FIELD_OFFSET 20
#define DOM_PER1_DOM13_EN_FIELD_SIZE 1
#define DOM_PER1_DOM12_LOCK_FIELD_OFFSET 19
#define DOM_PER1_DOM12_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM12_PER_FIELD_OFFSET 17
#define DOM_PER1_DOM12_PER_FIELD_SIZE 2
#define DOM_PER1_DOM12_EN_FIELD_OFFSET 16
#define DOM_PER1_DOM12_EN_FIELD_SIZE 1
#define DOM_PER1_DOM11_LOCK_FIELD_OFFSET 15
#define DOM_PER1_DOM11_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM11_PER_FIELD_OFFSET 13
#define DOM_PER1_DOM11_PER_FIELD_SIZE 2
#define DOM_PER1_DOM11_EN_FIELD_OFFSET 12
#define DOM_PER1_DOM11_EN_FIELD_SIZE 1
#define DOM_PER1_DOM10_LOCK_FIELD_OFFSET 11
#define DOM_PER1_DOM10_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM10_PER_FIELD_OFFSET 9
#define DOM_PER1_DOM10_PER_FIELD_SIZE 2
#define DOM_PER1_DOM10_EN_FIELD_OFFSET 8
#define DOM_PER1_DOM10_EN_FIELD_SIZE 1
#define DOM_PER1_DOM9_LOCK_FIELD_OFFSET 7
#define DOM_PER1_DOM9_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM9_PER_FIELD_OFFSET 5
#define DOM_PER1_DOM9_PER_FIELD_SIZE 2
#define DOM_PER1_DOM9_EN_FIELD_OFFSET 4
#define DOM_PER1_DOM9_EN_FIELD_SIZE 1
#define DOM_PER1_DOM8_LOCK_FIELD_OFFSET 3
#define DOM_PER1_DOM8_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM8_PER_FIELD_OFFSET 1
#define DOM_PER1_DOM8_PER_FIELD_SIZE 2
#define DOM_PER1_DOM8_EN_FIELD_OFFSET 0
#define DOM_PER1_DOM8_EN_FIELD_SIZE 1

#define BIT_AP_APB_MPC_DOM_PER1_DOM15_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_DOM_PER1_DOM15_PER_1    (BIT_(30))
#define BIT_AP_APB_MPC_DOM_PER1_DOM15_PER_0    (BIT_(29))
#define BIT_AP_APB_MPC_DOM_PER1_DOM15_EN    (BIT_(28))
#define BIT_AP_APB_MPC_DOM_PER1_DOM14_LOCK    (BIT_(27))
#define BIT_AP_APB_MPC_DOM_PER1_DOM14_PER_1    (BIT_(26))
#define BIT_AP_APB_MPC_DOM_PER1_DOM14_PER_0    (BIT_(25))
#define BIT_AP_APB_MPC_DOM_PER1_DOM14_EN    (BIT_(24))
#define BIT_AP_APB_MPC_DOM_PER1_DOM13_LOCK    (BIT_(23))
#define BIT_AP_APB_MPC_DOM_PER1_DOM13_PER_1    (BIT_(22))
#define BIT_AP_APB_MPC_DOM_PER1_DOM13_PER_0    (BIT_(21))
#define BIT_AP_APB_MPC_DOM_PER1_DOM13_EN    (BIT_(20))
#define BIT_AP_APB_MPC_DOM_PER1_DOM12_LOCK    (BIT_(19))
#define BIT_AP_APB_MPC_DOM_PER1_DOM12_PER_1    (BIT_(18))
#define BIT_AP_APB_MPC_DOM_PER1_DOM12_PER_0    (BIT_(17))
#define BIT_AP_APB_MPC_DOM_PER1_DOM12_EN    (BIT_(16))
#define BIT_AP_APB_MPC_DOM_PER1_DOM11_LOCK    (BIT_(15))
#define BIT_AP_APB_MPC_DOM_PER1_DOM11_PER_1    (BIT_(14))
#define BIT_AP_APB_MPC_DOM_PER1_DOM11_PER_0    (BIT_(13))
#define BIT_AP_APB_MPC_DOM_PER1_DOM11_EN    (BIT_(12))
#define BIT_AP_APB_MPC_DOM_PER1_DOM10_LOCK    (BIT_(11))
#define BIT_AP_APB_MPC_DOM_PER1_DOM10_PER_1    (BIT_(10))
#define BIT_AP_APB_MPC_DOM_PER1_DOM10_PER_0    (BIT_(9))
#define BIT_AP_APB_MPC_DOM_PER1_DOM10_EN    (BIT_(8))
#define BIT_AP_APB_MPC_DOM_PER1_DOM9_LOCK    (BIT_(7))
#define BIT_AP_APB_MPC_DOM_PER1_DOM9_PER_1    (BIT_(6))
#define BIT_AP_APB_MPC_DOM_PER1_DOM9_PER_0    (BIT_(5))
#define BIT_AP_APB_MPC_DOM_PER1_DOM9_EN    (BIT_(4))
#define BIT_AP_APB_MPC_DOM_PER1_DOM8_LOCK    (BIT_(3))
#define BIT_AP_APB_MPC_DOM_PER1_DOM8_PER_1    (BIT_(2))
#define BIT_AP_APB_MPC_DOM_PER1_DOM8_PER_0    (BIT_(1))
#define BIT_AP_APB_MPC_DOM_PER1_DOM8_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_SEC_PER0
// Register Offset : 0xc
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_SEC_PER0 (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xc<<0))
#define SEC_PER0_DOM3_LOCK_FIELD_OFFSET 31
#define SEC_PER0_DOM3_LOCK_FIELD_SIZE 1
#define SEC_PER0_DOM3_NSE_PER_FIELD_OFFSET 27
#define SEC_PER0_DOM3_NSE_PER_FIELD_SIZE 2
#define SEC_PER0_DOM3_SEC_PER_FIELD_OFFSET 25
#define SEC_PER0_DOM3_SEC_PER_FIELD_SIZE 2
#define SEC_PER0_DOM3_SEC_EN_FIELD_OFFSET 24
#define SEC_PER0_DOM3_SEC_EN_FIELD_SIZE 1
#define SEC_PER0_DOM2_LOCK_FIELD_OFFSET 23
#define SEC_PER0_DOM2_LOCK_FIELD_SIZE 1
#define SEC_PER0_DOM2_NSE_PER_FIELD_OFFSET 19
#define SEC_PER0_DOM2_NSE_PER_FIELD_SIZE 2
#define SEC_PER0_DOM2_SEC_PER_FIELD_OFFSET 17
#define SEC_PER0_DOM2_SEC_PER_FIELD_SIZE 2
#define SEC_PER0_DOM2_SEC_EN_FIELD_OFFSET 16
#define SEC_PER0_DOM2_SEC_EN_FIELD_SIZE 1
#define SEC_PER0_DOM1_LOCK_FIELD_OFFSET 15
#define SEC_PER0_DOM1_LOCK_FIELD_SIZE 1
#define SEC_PER0_DOM1_NSE_PER_FIELD_OFFSET 11
#define SEC_PER0_DOM1_NSE_PER_FIELD_SIZE 2
#define SEC_PER0_DOM1_SEC_PER_FIELD_OFFSET 9
#define SEC_PER0_DOM1_SEC_PER_FIELD_SIZE 2
#define SEC_PER0_DOM1_SEC_EN_FIELD_OFFSET 8
#define SEC_PER0_DOM1_SEC_EN_FIELD_SIZE 1
#define SEC_PER0_DOM0_LOCK_FIELD_OFFSET 7
#define SEC_PER0_DOM0_LOCK_FIELD_SIZE 1
#define SEC_PER0_DOM0_NSE_PER_FIELD_OFFSET 3
#define SEC_PER0_DOM0_NSE_PER_FIELD_SIZE 2
#define SEC_PER0_DOM0_SEC_PER_FIELD_OFFSET 1
#define SEC_PER0_DOM0_SEC_PER_FIELD_SIZE 2
#define SEC_PER0_DOM0_SEC_EN_FIELD_OFFSET 0
#define SEC_PER0_DOM0_SEC_EN_FIELD_SIZE 1

#define BIT_AP_APB_MPC_SEC_PER0_DOM3_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_SEC_PER0_DOM3_NSE_PER_1    (BIT_(28))
#define BIT_AP_APB_MPC_SEC_PER0_DOM3_NSE_PER_0    (BIT_(27))
#define BIT_AP_APB_MPC_SEC_PER0_DOM3_SEC_PER_1    (BIT_(26))
#define BIT_AP_APB_MPC_SEC_PER0_DOM3_SEC_PER_0    (BIT_(25))
#define BIT_AP_APB_MPC_SEC_PER0_DOM3_SEC_EN    (BIT_(24))
#define BIT_AP_APB_MPC_SEC_PER0_DOM2_LOCK    (BIT_(23))
#define BIT_AP_APB_MPC_SEC_PER0_DOM2_NSE_PER_1    (BIT_(20))
#define BIT_AP_APB_MPC_SEC_PER0_DOM2_NSE_PER_0    (BIT_(19))
#define BIT_AP_APB_MPC_SEC_PER0_DOM2_SEC_PER_1    (BIT_(18))
#define BIT_AP_APB_MPC_SEC_PER0_DOM2_SEC_PER_0    (BIT_(17))
#define BIT_AP_APB_MPC_SEC_PER0_DOM2_SEC_EN    (BIT_(16))
#define BIT_AP_APB_MPC_SEC_PER0_DOM1_LOCK    (BIT_(15))
#define BIT_AP_APB_MPC_SEC_PER0_DOM1_NSE_PER_1    (BIT_(12))
#define BIT_AP_APB_MPC_SEC_PER0_DOM1_NSE_PER_0    (BIT_(11))
#define BIT_AP_APB_MPC_SEC_PER0_DOM1_SEC_PER_1    (BIT_(10))
#define BIT_AP_APB_MPC_SEC_PER0_DOM1_SEC_PER_0    (BIT_(9))
#define BIT_AP_APB_MPC_SEC_PER0_DOM1_SEC_EN    (BIT_(8))
#define BIT_AP_APB_MPC_SEC_PER0_DOM0_LOCK    (BIT_(7))
#define BIT_AP_APB_MPC_SEC_PER0_DOM0_NSE_PER_1    (BIT_(4))
#define BIT_AP_APB_MPC_SEC_PER0_DOM0_NSE_PER_0    (BIT_(3))
#define BIT_AP_APB_MPC_SEC_PER0_DOM0_SEC_PER_1    (BIT_(2))
#define BIT_AP_APB_MPC_SEC_PER0_DOM0_SEC_PER_0    (BIT_(1))
#define BIT_AP_APB_MPC_SEC_PER0_DOM0_SEC_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_SEC_PER1
// Register Offset : 0x10
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_SEC_PER1 (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x10<<0))
#define SEC_PER1_DOM7_LOCK_FIELD_OFFSET 31
#define SEC_PER1_DOM7_LOCK_FIELD_SIZE 1
#define SEC_PER1_DOM7_NSE_PER_FIELD_OFFSET 27
#define SEC_PER1_DOM7_NSE_PER_FIELD_SIZE 2
#define SEC_PER1_DOM7_SEC_PER_FIELD_OFFSET 25
#define SEC_PER1_DOM7_SEC_PER_FIELD_SIZE 2
#define SEC_PER1_DOM7_SEC_EN_FIELD_OFFSET 24
#define SEC_PER1_DOM7_SEC_EN_FIELD_SIZE 1
#define SEC_PER1_DOM6_LOCK_FIELD_OFFSET 23
#define SEC_PER1_DOM6_LOCK_FIELD_SIZE 1
#define SEC_PER1_DOM6_NSE_PER_FIELD_OFFSET 19
#define SEC_PER1_DOM6_NSE_PER_FIELD_SIZE 2
#define SEC_PER1_DOM6_SEC_PER_FIELD_OFFSET 17
#define SEC_PER1_DOM6_SEC_PER_FIELD_SIZE 2
#define SEC_PER1_DOM6_SEC_EN_FIELD_OFFSET 16
#define SEC_PER1_DOM6_SEC_EN_FIELD_SIZE 1
#define SEC_PER1_DOM5_LOCK_FIELD_OFFSET 15
#define SEC_PER1_DOM5_LOCK_FIELD_SIZE 1
#define SEC_PER1_DOM5_NSE_PER_FIELD_OFFSET 11
#define SEC_PER1_DOM5_NSE_PER_FIELD_SIZE 2
#define SEC_PER1_DOM5_SEC_PER_FIELD_OFFSET 9
#define SEC_PER1_DOM5_SEC_PER_FIELD_SIZE 2
#define SEC_PER1_DOM5_SEC_EN_FIELD_OFFSET 8
#define SEC_PER1_DOM5_SEC_EN_FIELD_SIZE 1
#define SEC_PER1_DOM4_LOCK_FIELD_OFFSET 7
#define SEC_PER1_DOM4_LOCK_FIELD_SIZE 1
#define SEC_PER1_DOM4_NSE_PER_FIELD_OFFSET 3
#define SEC_PER1_DOM4_NSE_PER_FIELD_SIZE 2
#define SEC_PER1_DOM4_SEC_PER_FIELD_OFFSET 1
#define SEC_PER1_DOM4_SEC_PER_FIELD_SIZE 2
#define SEC_PER1_DOM4_SEC_EN_FIELD_OFFSET 0
#define SEC_PER1_DOM4_SEC_EN_FIELD_SIZE 1

#define BIT_AP_APB_MPC_SEC_PER1_DOM7_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_SEC_PER1_DOM7_NSE_PER_1    (BIT_(28))
#define BIT_AP_APB_MPC_SEC_PER1_DOM7_NSE_PER_0    (BIT_(27))
#define BIT_AP_APB_MPC_SEC_PER1_DOM7_SEC_PER_1    (BIT_(26))
#define BIT_AP_APB_MPC_SEC_PER1_DOM7_SEC_PER_0    (BIT_(25))
#define BIT_AP_APB_MPC_SEC_PER1_DOM7_SEC_EN    (BIT_(24))
#define BIT_AP_APB_MPC_SEC_PER1_DOM6_LOCK    (BIT_(23))
#define BIT_AP_APB_MPC_SEC_PER1_DOM6_NSE_PER_1    (BIT_(20))
#define BIT_AP_APB_MPC_SEC_PER1_DOM6_NSE_PER_0    (BIT_(19))
#define BIT_AP_APB_MPC_SEC_PER1_DOM6_SEC_PER_1    (BIT_(18))
#define BIT_AP_APB_MPC_SEC_PER1_DOM6_SEC_PER_0    (BIT_(17))
#define BIT_AP_APB_MPC_SEC_PER1_DOM6_SEC_EN    (BIT_(16))
#define BIT_AP_APB_MPC_SEC_PER1_DOM5_LOCK    (BIT_(15))
#define BIT_AP_APB_MPC_SEC_PER1_DOM5_NSE_PER_1    (BIT_(12))
#define BIT_AP_APB_MPC_SEC_PER1_DOM5_NSE_PER_0    (BIT_(11))
#define BIT_AP_APB_MPC_SEC_PER1_DOM5_SEC_PER_1    (BIT_(10))
#define BIT_AP_APB_MPC_SEC_PER1_DOM5_SEC_PER_0    (BIT_(9))
#define BIT_AP_APB_MPC_SEC_PER1_DOM5_SEC_EN    (BIT_(8))
#define BIT_AP_APB_MPC_SEC_PER1_DOM4_LOCK    (BIT_(7))
#define BIT_AP_APB_MPC_SEC_PER1_DOM4_NSE_PER_1    (BIT_(4))
#define BIT_AP_APB_MPC_SEC_PER1_DOM4_NSE_PER_0    (BIT_(3))
#define BIT_AP_APB_MPC_SEC_PER1_DOM4_SEC_PER_1    (BIT_(2))
#define BIT_AP_APB_MPC_SEC_PER1_DOM4_SEC_PER_0    (BIT_(1))
#define BIT_AP_APB_MPC_SEC_PER1_DOM4_SEC_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_SEC_PER2
// Register Offset : 0x14
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_SEC_PER2 (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x14<<0))
#define SEC_PER2_DOM11_LOCK_FIELD_OFFSET 31
#define SEC_PER2_DOM11_LOCK_FIELD_SIZE 1
#define SEC_PER2_DOM11_NSE_PER_FIELD_OFFSET 27
#define SEC_PER2_DOM11_NSE_PER_FIELD_SIZE 2
#define SEC_PER2_DOM11_SEC_PER_FIELD_OFFSET 25
#define SEC_PER2_DOM11_SEC_PER_FIELD_SIZE 2
#define SEC_PER2_DOM11_SEC_EN_FIELD_OFFSET 24
#define SEC_PER2_DOM11_SEC_EN_FIELD_SIZE 1
#define SEC_PER2_DOM10_LOCK_FIELD_OFFSET 23
#define SEC_PER2_DOM10_LOCK_FIELD_SIZE 1
#define SEC_PER2_DOM10_NSE_PER_FIELD_OFFSET 19
#define SEC_PER2_DOM10_NSE_PER_FIELD_SIZE 2
#define SEC_PER2_DOM10_SEC_PER_FIELD_OFFSET 17
#define SEC_PER2_DOM10_SEC_PER_FIELD_SIZE 2
#define SEC_PER2_DOM10_SEC_EN_FIELD_OFFSET 16
#define SEC_PER2_DOM10_SEC_EN_FIELD_SIZE 1
#define SEC_PER2_DOM9_LOCK_FIELD_OFFSET 15
#define SEC_PER2_DOM9_LOCK_FIELD_SIZE 1
#define SEC_PER2_DOM9_NSE_PER_FIELD_OFFSET 11
#define SEC_PER2_DOM9_NSE_PER_FIELD_SIZE 2
#define SEC_PER2_DOM9_SEC_PER_FIELD_OFFSET 9
#define SEC_PER2_DOM9_SEC_PER_FIELD_SIZE 2
#define SEC_PER2_DOM9_SEC_EN_FIELD_OFFSET 8
#define SEC_PER2_DOM9_SEC_EN_FIELD_SIZE 1
#define SEC_PER2_DOM8_LOCK_FIELD_OFFSET 7
#define SEC_PER2_DOM8_LOCK_FIELD_SIZE 1
#define SEC_PER2_DOM8_NSE_PER_FIELD_OFFSET 3
#define SEC_PER2_DOM8_NSE_PER_FIELD_SIZE 2
#define SEC_PER2_DOM8_SEC_PER_FIELD_OFFSET 1
#define SEC_PER2_DOM8_SEC_PER_FIELD_SIZE 2
#define SEC_PER2_DOM8_SEC_EN_FIELD_OFFSET 0
#define SEC_PER2_DOM8_SEC_EN_FIELD_SIZE 1

#define BIT_AP_APB_MPC_SEC_PER2_DOM11_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_SEC_PER2_DOM11_NSE_PER_1    (BIT_(28))
#define BIT_AP_APB_MPC_SEC_PER2_DOM11_NSE_PER_0    (BIT_(27))
#define BIT_AP_APB_MPC_SEC_PER2_DOM11_SEC_PER_1    (BIT_(26))
#define BIT_AP_APB_MPC_SEC_PER2_DOM11_SEC_PER_0    (BIT_(25))
#define BIT_AP_APB_MPC_SEC_PER2_DOM11_SEC_EN    (BIT_(24))
#define BIT_AP_APB_MPC_SEC_PER2_DOM10_LOCK    (BIT_(23))
#define BIT_AP_APB_MPC_SEC_PER2_DOM10_NSE_PER_1    (BIT_(20))
#define BIT_AP_APB_MPC_SEC_PER2_DOM10_NSE_PER_0    (BIT_(19))
#define BIT_AP_APB_MPC_SEC_PER2_DOM10_SEC_PER_1    (BIT_(18))
#define BIT_AP_APB_MPC_SEC_PER2_DOM10_SEC_PER_0    (BIT_(17))
#define BIT_AP_APB_MPC_SEC_PER2_DOM10_SEC_EN    (BIT_(16))
#define BIT_AP_APB_MPC_SEC_PER2_DOM9_LOCK    (BIT_(15))
#define BIT_AP_APB_MPC_SEC_PER2_DOM9_NSE_PER_1    (BIT_(12))
#define BIT_AP_APB_MPC_SEC_PER2_DOM9_NSE_PER_0    (BIT_(11))
#define BIT_AP_APB_MPC_SEC_PER2_DOM9_SEC_PER_1    (BIT_(10))
#define BIT_AP_APB_MPC_SEC_PER2_DOM9_SEC_PER_0    (BIT_(9))
#define BIT_AP_APB_MPC_SEC_PER2_DOM9_SEC_EN    (BIT_(8))
#define BIT_AP_APB_MPC_SEC_PER2_DOM8_LOCK    (BIT_(7))
#define BIT_AP_APB_MPC_SEC_PER2_DOM8_NSE_PER_1    (BIT_(4))
#define BIT_AP_APB_MPC_SEC_PER2_DOM8_NSE_PER_0    (BIT_(3))
#define BIT_AP_APB_MPC_SEC_PER2_DOM8_SEC_PER_1    (BIT_(2))
#define BIT_AP_APB_MPC_SEC_PER2_DOM8_SEC_PER_0    (BIT_(1))
#define BIT_AP_APB_MPC_SEC_PER2_DOM8_SEC_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_SEC_PER3
// Register Offset : 0x18
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_SEC_PER3 (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x18<<0))
#define SEC_PER3_DOM15_LOCK_FIELD_OFFSET 31
#define SEC_PER3_DOM15_LOCK_FIELD_SIZE 1
#define SEC_PER3_DOM15_NSE_PER_FIELD_OFFSET 27
#define SEC_PER3_DOM15_NSE_PER_FIELD_SIZE 2
#define SEC_PER3_DOM15_SEC_PER_FIELD_OFFSET 25
#define SEC_PER3_DOM15_SEC_PER_FIELD_SIZE 2
#define SEC_PER3_DOM15_SEC_EN_FIELD_OFFSET 24
#define SEC_PER3_DOM15_SEC_EN_FIELD_SIZE 1
#define SEC_PER3_DOM14_LOCK_FIELD_OFFSET 23
#define SEC_PER3_DOM14_LOCK_FIELD_SIZE 1
#define SEC_PER3_DOM14_NSE_PER_FIELD_OFFSET 19
#define SEC_PER3_DOM14_NSE_PER_FIELD_SIZE 2
#define SEC_PER3_DOM14_SEC_PER_FIELD_OFFSET 17
#define SEC_PER3_DOM14_SEC_PER_FIELD_SIZE 2
#define SEC_PER3_DOM14_SEC_EN_FIELD_OFFSET 16
#define SEC_PER3_DOM14_SEC_EN_FIELD_SIZE 1
#define SEC_PER3_DOM13_LOCK_FIELD_OFFSET 15
#define SEC_PER3_DOM13_LOCK_FIELD_SIZE 1
#define SEC_PER3_DOM13_NSE_PER_FIELD_OFFSET 11
#define SEC_PER3_DOM13_NSE_PER_FIELD_SIZE 2
#define SEC_PER3_DOM13_SEC_PER_FIELD_OFFSET 9
#define SEC_PER3_DOM13_SEC_PER_FIELD_SIZE 2
#define SEC_PER3_DOM13_SEC_EN_FIELD_OFFSET 8
#define SEC_PER3_DOM13_SEC_EN_FIELD_SIZE 1
#define SEC_PER3_DOM12_LOCK_FIELD_OFFSET 7
#define SEC_PER3_DOM12_LOCK_FIELD_SIZE 1
#define SEC_PER3_DOM12_NSE_PER_FIELD_OFFSET 3
#define SEC_PER3_DOM12_NSE_PER_FIELD_SIZE 2
#define SEC_PER3_DOM12_SEC_PER_FIELD_OFFSET 1
#define SEC_PER3_DOM12_SEC_PER_FIELD_SIZE 2
#define SEC_PER3_DOM12_SEC_EN_FIELD_OFFSET 0
#define SEC_PER3_DOM12_SEC_EN_FIELD_SIZE 1

#define BIT_AP_APB_MPC_SEC_PER3_DOM15_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_SEC_PER3_DOM15_NSE_PER_1    (BIT_(28))
#define BIT_AP_APB_MPC_SEC_PER3_DOM15_NSE_PER_0    (BIT_(27))
#define BIT_AP_APB_MPC_SEC_PER3_DOM15_SEC_PER_1    (BIT_(26))
#define BIT_AP_APB_MPC_SEC_PER3_DOM15_SEC_PER_0    (BIT_(25))
#define BIT_AP_APB_MPC_SEC_PER3_DOM15_SEC_EN    (BIT_(24))
#define BIT_AP_APB_MPC_SEC_PER3_DOM14_LOCK    (BIT_(23))
#define BIT_AP_APB_MPC_SEC_PER3_DOM14_NSE_PER_1    (BIT_(20))
#define BIT_AP_APB_MPC_SEC_PER3_DOM14_NSE_PER_0    (BIT_(19))
#define BIT_AP_APB_MPC_SEC_PER3_DOM14_SEC_PER_1    (BIT_(18))
#define BIT_AP_APB_MPC_SEC_PER3_DOM14_SEC_PER_0    (BIT_(17))
#define BIT_AP_APB_MPC_SEC_PER3_DOM14_SEC_EN    (BIT_(16))
#define BIT_AP_APB_MPC_SEC_PER3_DOM13_LOCK    (BIT_(15))
#define BIT_AP_APB_MPC_SEC_PER3_DOM13_NSE_PER_1    (BIT_(12))
#define BIT_AP_APB_MPC_SEC_PER3_DOM13_NSE_PER_0    (BIT_(11))
#define BIT_AP_APB_MPC_SEC_PER3_DOM13_SEC_PER_1    (BIT_(10))
#define BIT_AP_APB_MPC_SEC_PER3_DOM13_SEC_PER_0    (BIT_(9))
#define BIT_AP_APB_MPC_SEC_PER3_DOM13_SEC_EN    (BIT_(8))
#define BIT_AP_APB_MPC_SEC_PER3_DOM12_LOCK    (BIT_(7))
#define BIT_AP_APB_MPC_SEC_PER3_DOM12_NSE_PER_1    (BIT_(4))
#define BIT_AP_APB_MPC_SEC_PER3_DOM12_NSE_PER_0    (BIT_(3))
#define BIT_AP_APB_MPC_SEC_PER3_DOM12_SEC_PER_1    (BIT_(2))
#define BIT_AP_APB_MPC_SEC_PER3_DOM12_SEC_PER_0    (BIT_(1))
#define BIT_AP_APB_MPC_SEC_PER3_DOM12_SEC_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_PRI_PER0
// Register Offset : 0x1c
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_PRI_PER0 (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x1c<<0))
#define PRI_PER0_DOM3_LOCK_FIELD_OFFSET 31
#define PRI_PER0_DOM3_LOCK_FIELD_SIZE 1
#define PRI_PER0_DOM3_USE_PER_FIELD_OFFSET 27
#define PRI_PER0_DOM3_USE_PER_FIELD_SIZE 2
#define PRI_PER0_DOM3_PRI_PER_FIELD_OFFSET 25
#define PRI_PER0_DOM3_PRI_PER_FIELD_SIZE 2
#define PRI_PER0_DOM3_PRI_EN_FIELD_OFFSET 24
#define PRI_PER0_DOM3_PRI_EN_FIELD_SIZE 1
#define PRI_PER0_DOM2_LOCK_FIELD_OFFSET 23
#define PRI_PER0_DOM2_LOCK_FIELD_SIZE 1
#define PRI_PER0_DOM2_USE_PER_FIELD_OFFSET 19
#define PRI_PER0_DOM2_USE_PER_FIELD_SIZE 2
#define PRI_PER0_DOM2_PRI_PER_FIELD_OFFSET 17
#define PRI_PER0_DOM2_PRI_PER_FIELD_SIZE 2
#define PRI_PER0_DOM2_PRI_EN_FIELD_OFFSET 16
#define PRI_PER0_DOM2_PRI_EN_FIELD_SIZE 1
#define PRI_PER0_DOM1_LOCK_FIELD_OFFSET 15
#define PRI_PER0_DOM1_LOCK_FIELD_SIZE 1
#define PRI_PER0_DOM1_USE_PER_FIELD_OFFSET 11
#define PRI_PER0_DOM1_USE_PER_FIELD_SIZE 2
#define PRI_PER0_DOM1_PRI_PER_FIELD_OFFSET 9
#define PRI_PER0_DOM1_PRI_PER_FIELD_SIZE 2
#define PRI_PER0_DOM1_PRI_EN_FIELD_OFFSET 8
#define PRI_PER0_DOM1_PRI_EN_FIELD_SIZE 1
#define PRI_PER0_DOM0_LOCK_FIELD_OFFSET 7
#define PRI_PER0_DOM0_LOCK_FIELD_SIZE 1
#define PRI_PER0_DOM0_USE_PER_FIELD_OFFSET 3
#define PRI_PER0_DOM0_USE_PER_FIELD_SIZE 2
#define PRI_PER0_DOM0_PRI_PER_FIELD_OFFSET 1
#define PRI_PER0_DOM0_PRI_PER_FIELD_SIZE 2
#define PRI_PER0_DOM0_PRI_EN_FIELD_OFFSET 0
#define PRI_PER0_DOM0_PRI_EN_FIELD_SIZE 1

#define BIT_AP_APB_MPC_PRI_PER0_DOM3_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_PRI_PER0_DOM3_USE_PER_1    (BIT_(28))
#define BIT_AP_APB_MPC_PRI_PER0_DOM3_USE_PER_0    (BIT_(27))
#define BIT_AP_APB_MPC_PRI_PER0_DOM3_PRI_PER_1    (BIT_(26))
#define BIT_AP_APB_MPC_PRI_PER0_DOM3_PRI_PER_0    (BIT_(25))
#define BIT_AP_APB_MPC_PRI_PER0_DOM3_PRI_EN    (BIT_(24))
#define BIT_AP_APB_MPC_PRI_PER0_DOM2_LOCK    (BIT_(23))
#define BIT_AP_APB_MPC_PRI_PER0_DOM2_USE_PER_1    (BIT_(20))
#define BIT_AP_APB_MPC_PRI_PER0_DOM2_USE_PER_0    (BIT_(19))
#define BIT_AP_APB_MPC_PRI_PER0_DOM2_PRI_PER_1    (BIT_(18))
#define BIT_AP_APB_MPC_PRI_PER0_DOM2_PRI_PER_0    (BIT_(17))
#define BIT_AP_APB_MPC_PRI_PER0_DOM2_PRI_EN    (BIT_(16))
#define BIT_AP_APB_MPC_PRI_PER0_DOM1_LOCK    (BIT_(15))
#define BIT_AP_APB_MPC_PRI_PER0_DOM1_USE_PER_1    (BIT_(12))
#define BIT_AP_APB_MPC_PRI_PER0_DOM1_USE_PER_0    (BIT_(11))
#define BIT_AP_APB_MPC_PRI_PER0_DOM1_PRI_PER_1    (BIT_(10))
#define BIT_AP_APB_MPC_PRI_PER0_DOM1_PRI_PER_0    (BIT_(9))
#define BIT_AP_APB_MPC_PRI_PER0_DOM1_PRI_EN    (BIT_(8))
#define BIT_AP_APB_MPC_PRI_PER0_DOM0_LOCK    (BIT_(7))
#define BIT_AP_APB_MPC_PRI_PER0_DOM0_USE_PER_1    (BIT_(4))
#define BIT_AP_APB_MPC_PRI_PER0_DOM0_USE_PER_0    (BIT_(3))
#define BIT_AP_APB_MPC_PRI_PER0_DOM0_PRI_PER_1    (BIT_(2))
#define BIT_AP_APB_MPC_PRI_PER0_DOM0_PRI_PER_0    (BIT_(1))
#define BIT_AP_APB_MPC_PRI_PER0_DOM0_PRI_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_PRI_PER1
// Register Offset : 0x20
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_PRI_PER1 (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x20<<0))
#define PRI_PER1_DOM7_LOCK_FIELD_OFFSET 31
#define PRI_PER1_DOM7_LOCK_FIELD_SIZE 1
#define PRI_PER1_DOM7_USE_PER_FIELD_OFFSET 27
#define PRI_PER1_DOM7_USE_PER_FIELD_SIZE 2
#define PRI_PER1_DOM7_PRI_PER_FIELD_OFFSET 25
#define PRI_PER1_DOM7_PRI_PER_FIELD_SIZE 2
#define PRI_PER1_DOM7_PRI_EN_FIELD_OFFSET 24
#define PRI_PER1_DOM7_PRI_EN_FIELD_SIZE 1
#define PRI_PER1_DOM6_LOCK_FIELD_OFFSET 23
#define PRI_PER1_DOM6_LOCK_FIELD_SIZE 1
#define PRI_PER1_DOM6_USE_PER_FIELD_OFFSET 19
#define PRI_PER1_DOM6_USE_PER_FIELD_SIZE 2
#define PRI_PER1_DOM6_PRI_PER_FIELD_OFFSET 17
#define PRI_PER1_DOM6_PRI_PER_FIELD_SIZE 2
#define PRI_PER1_DOM6_PRI_EN_FIELD_OFFSET 16
#define PRI_PER1_DOM6_PRI_EN_FIELD_SIZE 1
#define PRI_PER1_DOM5_LOCK_FIELD_OFFSET 15
#define PRI_PER1_DOM5_LOCK_FIELD_SIZE 1
#define PRI_PER1_DOM5_USE_PER_FIELD_OFFSET 11
#define PRI_PER1_DOM5_USE_PER_FIELD_SIZE 2
#define PRI_PER1_DOM5_PRI_PER_FIELD_OFFSET 9
#define PRI_PER1_DOM5_PRI_PER_FIELD_SIZE 2
#define PRI_PER1_DOM5_PRI_EN_FIELD_OFFSET 8
#define PRI_PER1_DOM5_PRI_EN_FIELD_SIZE 1
#define PRI_PER1_DOM4_LOCK_FIELD_OFFSET 7
#define PRI_PER1_DOM4_LOCK_FIELD_SIZE 1
#define PRI_PER1_DOM4_USE_PER_FIELD_OFFSET 3
#define PRI_PER1_DOM4_USE_PER_FIELD_SIZE 2
#define PRI_PER1_DOM4_PRI_PER_FIELD_OFFSET 1
#define PRI_PER1_DOM4_PRI_PER_FIELD_SIZE 2
#define PRI_PER1_DOM4_PRI_EN_FIELD_OFFSET 0
#define PRI_PER1_DOM4_PRI_EN_FIELD_SIZE 1

#define BIT_AP_APB_MPC_PRI_PER1_DOM7_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_PRI_PER1_DOM7_USE_PER_1    (BIT_(28))
#define BIT_AP_APB_MPC_PRI_PER1_DOM7_USE_PER_0    (BIT_(27))
#define BIT_AP_APB_MPC_PRI_PER1_DOM7_PRI_PER_1    (BIT_(26))
#define BIT_AP_APB_MPC_PRI_PER1_DOM7_PRI_PER_0    (BIT_(25))
#define BIT_AP_APB_MPC_PRI_PER1_DOM7_PRI_EN    (BIT_(24))
#define BIT_AP_APB_MPC_PRI_PER1_DOM6_LOCK    (BIT_(23))
#define BIT_AP_APB_MPC_PRI_PER1_DOM6_USE_PER_1    (BIT_(20))
#define BIT_AP_APB_MPC_PRI_PER1_DOM6_USE_PER_0    (BIT_(19))
#define BIT_AP_APB_MPC_PRI_PER1_DOM6_PRI_PER_1    (BIT_(18))
#define BIT_AP_APB_MPC_PRI_PER1_DOM6_PRI_PER_0    (BIT_(17))
#define BIT_AP_APB_MPC_PRI_PER1_DOM6_PRI_EN    (BIT_(16))
#define BIT_AP_APB_MPC_PRI_PER1_DOM5_LOCK    (BIT_(15))
#define BIT_AP_APB_MPC_PRI_PER1_DOM5_USE_PER_1    (BIT_(12))
#define BIT_AP_APB_MPC_PRI_PER1_DOM5_USE_PER_0    (BIT_(11))
#define BIT_AP_APB_MPC_PRI_PER1_DOM5_PRI_PER_1    (BIT_(10))
#define BIT_AP_APB_MPC_PRI_PER1_DOM5_PRI_PER_0    (BIT_(9))
#define BIT_AP_APB_MPC_PRI_PER1_DOM5_PRI_EN    (BIT_(8))
#define BIT_AP_APB_MPC_PRI_PER1_DOM4_LOCK    (BIT_(7))
#define BIT_AP_APB_MPC_PRI_PER1_DOM4_USE_PER_1    (BIT_(4))
#define BIT_AP_APB_MPC_PRI_PER1_DOM4_USE_PER_0    (BIT_(3))
#define BIT_AP_APB_MPC_PRI_PER1_DOM4_PRI_PER_1    (BIT_(2))
#define BIT_AP_APB_MPC_PRI_PER1_DOM4_PRI_PER_0    (BIT_(1))
#define BIT_AP_APB_MPC_PRI_PER1_DOM4_PRI_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_PRI_PER2
// Register Offset : 0x24
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_PRI_PER2 (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x24<<0))
#define PRI_PER2_DOM11_LOCK_FIELD_OFFSET 31
#define PRI_PER2_DOM11_LOCK_FIELD_SIZE 1
#define PRI_PER2_DOM11_USE_PER_FIELD_OFFSET 27
#define PRI_PER2_DOM11_USE_PER_FIELD_SIZE 2
#define PRI_PER2_DOM11_PRI_PER_FIELD_OFFSET 25
#define PRI_PER2_DOM11_PRI_PER_FIELD_SIZE 2
#define PRI_PER2_DOM11_PRI_EN_FIELD_OFFSET 24
#define PRI_PER2_DOM11_PRI_EN_FIELD_SIZE 1
#define PRI_PER2_DOM10_LOCK_FIELD_OFFSET 23
#define PRI_PER2_DOM10_LOCK_FIELD_SIZE 1
#define PRI_PER2_DOM10_USE_PER_FIELD_OFFSET 19
#define PRI_PER2_DOM10_USE_PER_FIELD_SIZE 2
#define PRI_PER2_DOM10_PRI_PER_FIELD_OFFSET 17
#define PRI_PER2_DOM10_PRI_PER_FIELD_SIZE 2
#define PRI_PER2_DOM10_PRI_EN_FIELD_OFFSET 16
#define PRI_PER2_DOM10_PRI_EN_FIELD_SIZE 1
#define PRI_PER2_DOM9_LOCK_FIELD_OFFSET 15
#define PRI_PER2_DOM9_LOCK_FIELD_SIZE 1
#define PRI_PER2_DOM9_USE_PER_FIELD_OFFSET 11
#define PRI_PER2_DOM9_USE_PER_FIELD_SIZE 2
#define PRI_PER2_DOM9_PRI_PER_FIELD_OFFSET 9
#define PRI_PER2_DOM9_PRI_PER_FIELD_SIZE 2
#define PRI_PER2_DOM9_PRI_EN_FIELD_OFFSET 8
#define PRI_PER2_DOM9_PRI_EN_FIELD_SIZE 1
#define PRI_PER2_DOM8_LOCK_FIELD_OFFSET 7
#define PRI_PER2_DOM8_LOCK_FIELD_SIZE 1
#define PRI_PER2_DOM8_USE_PER_FIELD_OFFSET 3
#define PRI_PER2_DOM8_USE_PER_FIELD_SIZE 2
#define PRI_PER2_DOM8_PRI_PER_FIELD_OFFSET 1
#define PRI_PER2_DOM8_PRI_PER_FIELD_SIZE 2
#define PRI_PER2_DOM8_PRI_EN_FIELD_OFFSET 0
#define PRI_PER2_DOM8_PRI_EN_FIELD_SIZE 1

#define BIT_AP_APB_MPC_PRI_PER2_DOM11_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_PRI_PER2_DOM11_USE_PER_1    (BIT_(28))
#define BIT_AP_APB_MPC_PRI_PER2_DOM11_USE_PER_0    (BIT_(27))
#define BIT_AP_APB_MPC_PRI_PER2_DOM11_PRI_PER_1    (BIT_(26))
#define BIT_AP_APB_MPC_PRI_PER2_DOM11_PRI_PER_0    (BIT_(25))
#define BIT_AP_APB_MPC_PRI_PER2_DOM11_PRI_EN    (BIT_(24))
#define BIT_AP_APB_MPC_PRI_PER2_DOM10_LOCK    (BIT_(23))
#define BIT_AP_APB_MPC_PRI_PER2_DOM10_USE_PER_1    (BIT_(20))
#define BIT_AP_APB_MPC_PRI_PER2_DOM10_USE_PER_0    (BIT_(19))
#define BIT_AP_APB_MPC_PRI_PER2_DOM10_PRI_PER_1    (BIT_(18))
#define BIT_AP_APB_MPC_PRI_PER2_DOM10_PRI_PER_0    (BIT_(17))
#define BIT_AP_APB_MPC_PRI_PER2_DOM10_PRI_EN    (BIT_(16))
#define BIT_AP_APB_MPC_PRI_PER2_DOM9_LOCK    (BIT_(15))
#define BIT_AP_APB_MPC_PRI_PER2_DOM9_USE_PER_1    (BIT_(12))
#define BIT_AP_APB_MPC_PRI_PER2_DOM9_USE_PER_0    (BIT_(11))
#define BIT_AP_APB_MPC_PRI_PER2_DOM9_PRI_PER_1    (BIT_(10))
#define BIT_AP_APB_MPC_PRI_PER2_DOM9_PRI_PER_0    (BIT_(9))
#define BIT_AP_APB_MPC_PRI_PER2_DOM9_PRI_EN    (BIT_(8))
#define BIT_AP_APB_MPC_PRI_PER2_DOM8_LOCK    (BIT_(7))
#define BIT_AP_APB_MPC_PRI_PER2_DOM8_USE_PER_1    (BIT_(4))
#define BIT_AP_APB_MPC_PRI_PER2_DOM8_USE_PER_0    (BIT_(3))
#define BIT_AP_APB_MPC_PRI_PER2_DOM8_PRI_PER_1    (BIT_(2))
#define BIT_AP_APB_MPC_PRI_PER2_DOM8_PRI_PER_0    (BIT_(1))
#define BIT_AP_APB_MPC_PRI_PER2_DOM8_PRI_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_PRI_PER3
// Register Offset : 0x28
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_PRI_PER3 (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x28<<0))
#define PRI_PER3_DOM15_LOCK_FIELD_OFFSET 31
#define PRI_PER3_DOM15_LOCK_FIELD_SIZE 1
#define PRI_PER3_DOM15_USE_PER_FIELD_OFFSET 27
#define PRI_PER3_DOM15_USE_PER_FIELD_SIZE 2
#define PRI_PER3_DOM15_PRI_PER_FIELD_OFFSET 25
#define PRI_PER3_DOM15_PRI_PER_FIELD_SIZE 2
#define PRI_PER3_DOM15_PRI_EN_FIELD_OFFSET 24
#define PRI_PER3_DOM15_PRI_EN_FIELD_SIZE 1
#define PRI_PER3_DOM14_LOCK_FIELD_OFFSET 23
#define PRI_PER3_DOM14_LOCK_FIELD_SIZE 1
#define PRI_PER3_DOM14_USE_PER_FIELD_OFFSET 19
#define PRI_PER3_DOM14_USE_PER_FIELD_SIZE 2
#define PRI_PER3_DOM14_PRI_PER_FIELD_OFFSET 17
#define PRI_PER3_DOM14_PRI_PER_FIELD_SIZE 2
#define PRI_PER3_DOM14_PRI_EN_FIELD_OFFSET 16
#define PRI_PER3_DOM14_PRI_EN_FIELD_SIZE 1
#define PRI_PER3_DOM13_LOCK_FIELD_OFFSET 15
#define PRI_PER3_DOM13_LOCK_FIELD_SIZE 1
#define PRI_PER3_DOM13_USE_PER_FIELD_OFFSET 11
#define PRI_PER3_DOM13_USE_PER_FIELD_SIZE 2
#define PRI_PER3_DOM13_PRI_PER_FIELD_OFFSET 9
#define PRI_PER3_DOM13_PRI_PER_FIELD_SIZE 2
#define PRI_PER3_DOM13_PRI_EN_FIELD_OFFSET 8
#define PRI_PER3_DOM13_PRI_EN_FIELD_SIZE 1
#define PRI_PER3_DOM12_LOCK_FIELD_OFFSET 7
#define PRI_PER3_DOM12_LOCK_FIELD_SIZE 1
#define PRI_PER3_DOM12_USE_PER_FIELD_OFFSET 3
#define PRI_PER3_DOM12_USE_PER_FIELD_SIZE 2
#define PRI_PER3_DOM12_PRI_PER_FIELD_OFFSET 1
#define PRI_PER3_DOM12_PRI_PER_FIELD_SIZE 2
#define PRI_PER3_DOM12_PRI_EN_FIELD_OFFSET 0
#define PRI_PER3_DOM12_PRI_EN_FIELD_SIZE 1

#define BIT_AP_APB_MPC_PRI_PER3_DOM15_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_PRI_PER3_DOM15_USE_PER_1    (BIT_(28))
#define BIT_AP_APB_MPC_PRI_PER3_DOM15_USE_PER_0    (BIT_(27))
#define BIT_AP_APB_MPC_PRI_PER3_DOM15_PRI_PER_1    (BIT_(26))
#define BIT_AP_APB_MPC_PRI_PER3_DOM15_PRI_PER_0    (BIT_(25))
#define BIT_AP_APB_MPC_PRI_PER3_DOM15_PRI_EN    (BIT_(24))
#define BIT_AP_APB_MPC_PRI_PER3_DOM14_LOCK    (BIT_(23))
#define BIT_AP_APB_MPC_PRI_PER3_DOM14_USE_PER_1    (BIT_(20))
#define BIT_AP_APB_MPC_PRI_PER3_DOM14_USE_PER_0    (BIT_(19))
#define BIT_AP_APB_MPC_PRI_PER3_DOM14_PRI_PER_1    (BIT_(18))
#define BIT_AP_APB_MPC_PRI_PER3_DOM14_PRI_PER_0    (BIT_(17))
#define BIT_AP_APB_MPC_PRI_PER3_DOM14_PRI_EN    (BIT_(16))
#define BIT_AP_APB_MPC_PRI_PER3_DOM13_LOCK    (BIT_(15))
#define BIT_AP_APB_MPC_PRI_PER3_DOM13_USE_PER_1    (BIT_(12))
#define BIT_AP_APB_MPC_PRI_PER3_DOM13_USE_PER_0    (BIT_(11))
#define BIT_AP_APB_MPC_PRI_PER3_DOM13_PRI_PER_1    (BIT_(10))
#define BIT_AP_APB_MPC_PRI_PER3_DOM13_PRI_PER_0    (BIT_(9))
#define BIT_AP_APB_MPC_PRI_PER3_DOM13_PRI_EN    (BIT_(8))
#define BIT_AP_APB_MPC_PRI_PER3_DOM12_LOCK    (BIT_(7))
#define BIT_AP_APB_MPC_PRI_PER3_DOM12_USE_PER_1    (BIT_(4))
#define BIT_AP_APB_MPC_PRI_PER3_DOM12_USE_PER_0    (BIT_(3))
#define BIT_AP_APB_MPC_PRI_PER3_DOM12_PRI_PER_1    (BIT_(2))
#define BIT_AP_APB_MPC_PRI_PER3_DOM12_PRI_PER_0    (BIT_(1))
#define BIT_AP_APB_MPC_PRI_PER3_DOM12_PRI_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_DOM_ASSIGN
// Register Offset : 0x34
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_DOM_ASSIGN (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x34<<0))
#define DOM_ASSIGN_DID_FIELD_OFFSET 0
#define DOM_ASSIGN_DID_FIELD_SIZE 4

#define BIT_AP_APB_MPC_DOM_ASSIGN_DID_3    (BIT_(3))
#define BIT_AP_APB_MPC_DOM_ASSIGN_DID_2    (BIT_(2))
#define BIT_AP_APB_MPC_DOM_ASSIGN_DID_1    (BIT_(1))
#define BIT_AP_APB_MPC_DOM_ASSIGN_DID_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_RGN_START_ADDR
// Register Offset : 0x800
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_RGN_START_ADDR (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x800<<0))
#define RGN_START_ADDR_START_ADDR_FIELD_OFFSET 0
#define RGN_START_ADDR_START_ADDR_FIELD_SIZE 30

#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_29    (BIT_(29))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_28    (BIT_(28))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_27    (BIT_(27))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_26    (BIT_(26))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_25    (BIT_(25))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_24    (BIT_(24))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_23    (BIT_(23))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_22    (BIT_(22))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_21    (BIT_(21))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_20    (BIT_(20))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_19    (BIT_(19))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_18    (BIT_(18))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_17    (BIT_(17))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_16    (BIT_(16))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_15    (BIT_(15))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_14    (BIT_(14))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_13    (BIT_(13))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_12    (BIT_(12))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_11    (BIT_(11))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_10    (BIT_(10))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_9    (BIT_(9))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_8    (BIT_(8))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_7    (BIT_(7))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_6    (BIT_(6))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_5    (BIT_(5))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_4    (BIT_(4))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_3    (BIT_(3))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_2    (BIT_(2))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_1    (BIT_(1))
#define BIT_AP_APB_MPC_RGN_START_ADDR_START_ADDR_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_RGN_END_ADDR
// Register Offset : 0x804
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_RGN_END_ADDR (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x804<<0))
#define RGN_END_ADDR_LOCK_FIELD_OFFSET 31
#define RGN_END_ADDR_LOCK_FIELD_SIZE 1
#define RGN_END_ADDR_RGN_EN_FIELD_OFFSET 30
#define RGN_END_ADDR_RGN_EN_FIELD_SIZE 1
#define RGN_END_ADDR_END_ADDR_FIELD_OFFSET 0
#define RGN_END_ADDR_END_ADDR_FIELD_SIZE 30

#define BIT_AP_APB_MPC_RGN_END_ADDR_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_RGN_END_ADDR_RGN_EN    (BIT_(30))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_29    (BIT_(29))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_28    (BIT_(28))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_27    (BIT_(27))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_26    (BIT_(26))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_25    (BIT_(25))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_24    (BIT_(24))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_23    (BIT_(23))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_22    (BIT_(22))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_21    (BIT_(21))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_20    (BIT_(20))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_19    (BIT_(19))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_18    (BIT_(18))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_17    (BIT_(17))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_16    (BIT_(16))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_15    (BIT_(15))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_14    (BIT_(14))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_13    (BIT_(13))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_12    (BIT_(12))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_11    (BIT_(11))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_10    (BIT_(10))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_9    (BIT_(9))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_8    (BIT_(8))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_7    (BIT_(7))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_6    (BIT_(6))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_5    (BIT_(5))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_4    (BIT_(4))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_3    (BIT_(3))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_2    (BIT_(2))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_1    (BIT_(1))
#define BIT_AP_APB_MPC_RGN_END_ADDR_END_ADDR_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_RGN_LOW_LIM
// Register Offset : 0x808
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_RGN_LOW_LIM (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x808<<0))
#define RGN_LOW_LIM_LOW_LIM_FIELD_OFFSET 0
#define RGN_LOW_LIM_LOW_LIM_FIELD_SIZE 30

#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_29    (BIT_(29))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_28    (BIT_(28))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_27    (BIT_(27))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_26    (BIT_(26))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_25    (BIT_(25))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_24    (BIT_(24))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_23    (BIT_(23))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_22    (BIT_(22))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_21    (BIT_(21))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_20    (BIT_(20))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_19    (BIT_(19))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_18    (BIT_(18))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_17    (BIT_(17))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_16    (BIT_(16))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_15    (BIT_(15))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_14    (BIT_(14))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_13    (BIT_(13))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_12    (BIT_(12))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_11    (BIT_(11))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_10    (BIT_(10))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_9    (BIT_(9))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_8    (BIT_(8))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_7    (BIT_(7))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_6    (BIT_(6))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_5    (BIT_(5))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_4    (BIT_(4))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_3    (BIT_(3))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_2    (BIT_(2))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_1    (BIT_(1))
#define BIT_AP_APB_MPC_RGN_LOW_LIM_LOW_LIM_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_RGN_UP_LIM
// Register Offset : 0x80c
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_RGN_UP_LIM (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0x80c<<0))
#define RGN_UP_LIM_LOCK_FIELD_OFFSET 31
#define RGN_UP_LIM_LOCK_FIELD_SIZE 1
#define RGN_UP_LIM_UP_LIM_FIELD_OFFSET 0
#define RGN_UP_LIM_UP_LIM_FIELD_SIZE 30

#define BIT_AP_APB_MPC_RGN_UP_LIM_LOCK    (BIT_(31))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_29    (BIT_(29))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_28    (BIT_(28))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_27    (BIT_(27))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_26    (BIT_(26))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_25    (BIT_(25))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_24    (BIT_(24))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_23    (BIT_(23))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_22    (BIT_(22))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_21    (BIT_(21))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_20    (BIT_(20))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_19    (BIT_(19))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_18    (BIT_(18))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_17    (BIT_(17))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_16    (BIT_(16))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_15    (BIT_(15))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_14    (BIT_(14))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_13    (BIT_(13))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_12    (BIT_(12))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_11    (BIT_(11))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_10    (BIT_(10))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_9    (BIT_(9))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_8    (BIT_(8))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_7    (BIT_(7))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_6    (BIT_(6))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_5    (BIT_(5))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_4    (BIT_(4))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_3    (BIT_(3))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_2    (BIT_(2))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_1    (BIT_(1))
#define BIT_AP_APB_MPC_RGN_UP_LIM_UP_LIM_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_UNCERR_INT_STA
// Register Offset : 0xf00
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_UNCERR_INT_STA (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf00<<0))
#define UNCERR_INT_STA_BREADY_FIELD_OFFSET 31
#define UNCERR_INT_STA_BREADY_FIELD_SIZE 1
#define UNCERR_INT_STA_BVALID_FIELD_OFFSET 30
#define UNCERR_INT_STA_BVALID_FIELD_SIZE 1
#define UNCERR_INT_STA_BID_FIELD_OFFSET 27
#define UNCERR_INT_STA_BID_FIELD_SIZE 1
#define UNCERR_INT_STA_WREADY_FIELD_OFFSET 26
#define UNCERR_INT_STA_WREADY_FIELD_SIZE 1
#define UNCERR_INT_STA_WVALID_FIELD_OFFSET 25
#define UNCERR_INT_STA_WVALID_FIELD_SIZE 1
#define UNCERR_INT_STA_WCTL_FIELD_OFFSET 22
#define UNCERR_INT_STA_WCTL_FIELD_SIZE 1
#define UNCERR_INT_STA_RREADY_FIELD_OFFSET 20
#define UNCERR_INT_STA_RREADY_FIELD_SIZE 1
#define UNCERR_INT_STA_RVALID_FIELD_OFFSET 19
#define UNCERR_INT_STA_RVALID_FIELD_SIZE 1
#define UNCERR_INT_STA_REOBI_FIELD_OFFSET 18
#define UNCERR_INT_STA_REOBI_FIELD_SIZE 1
#define UNCERR_INT_STA_RCTL_FIELD_OFFSET 16
#define UNCERR_INT_STA_RCTL_FIELD_SIZE 1
#define UNCERR_INT_STA_RID_FIELD_OFFSET 14
#define UNCERR_INT_STA_RID_FIELD_SIZE 1
#define UNCERR_INT_STA_AWREADY_FIELD_OFFSET 13
#define UNCERR_INT_STA_AWREADY_FIELD_SIZE 1
#define UNCERR_INT_STA_AWVALID_FIELD_OFFSET 12
#define UNCERR_INT_STA_AWVALID_FIELD_SIZE 1
#define UNCERR_INT_STA_AWCTL1_FIELD_OFFSET 10
#define UNCERR_INT_STA_AWCTL1_FIELD_SIZE 1
#define UNCERR_INT_STA_AWCTL0_FIELD_OFFSET 9
#define UNCERR_INT_STA_AWCTL0_FIELD_SIZE 1
#define UNCERR_INT_STA_AWADDR_FIELD_OFFSET 8
#define UNCERR_INT_STA_AWADDR_FIELD_SIZE 1
#define UNCERR_INT_STA_AWID_FIELD_OFFSET 7
#define UNCERR_INT_STA_AWID_FIELD_SIZE 1
#define UNCERR_INT_STA_ARREADY_FIELD_OFFSET 6
#define UNCERR_INT_STA_ARREADY_FIELD_SIZE 1
#define UNCERR_INT_STA_ARVALID_FIELD_OFFSET 5
#define UNCERR_INT_STA_ARVALID_FIELD_SIZE 1
#define UNCERR_INT_STA_ARCTL1_FIELD_OFFSET 3
#define UNCERR_INT_STA_ARCTL1_FIELD_SIZE 1
#define UNCERR_INT_STA_ARCTL0_FIELD_OFFSET 2
#define UNCERR_INT_STA_ARCTL0_FIELD_SIZE 1
#define UNCERR_INT_STA_ARADDR_FIELD_OFFSET 1
#define UNCERR_INT_STA_ARADDR_FIELD_SIZE 1
#define UNCERR_INT_STA_ARID_FIELD_OFFSET 0
#define UNCERR_INT_STA_ARID_FIELD_SIZE 1

#define BIT_AP_APB_MPC_UNCERR_INT_STA_BREADY    (BIT_(31))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_BVALID    (BIT_(30))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_BID    (BIT_(27))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_WREADY    (BIT_(26))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_WVALID    (BIT_(25))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_WCTL    (BIT_(22))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_RREADY    (BIT_(20))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_RVALID    (BIT_(19))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_REOBI    (BIT_(18))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_RCTL    (BIT_(16))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_RID    (BIT_(14))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_AWREADY    (BIT_(13))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_AWVALID    (BIT_(12))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_AWCTL1    (BIT_(10))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_AWCTL0    (BIT_(9))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_AWADDR    (BIT_(8))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_AWID    (BIT_(7))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_ARREADY    (BIT_(6))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_ARVALID    (BIT_(5))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_ARCTL1    (BIT_(3))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_ARCTL0    (BIT_(2))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_ARADDR    (BIT_(1))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_ARID    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_UNCERR_INT_STA_EN
// Register Offset : 0xf04
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_UNCERR_INT_STA_EN (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf04<<0))
#define UNCERR_INT_STA_EN_BREADY_FIELD_OFFSET 31
#define UNCERR_INT_STA_EN_BREADY_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_BVALID_FIELD_OFFSET 30
#define UNCERR_INT_STA_EN_BVALID_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_BID_FIELD_OFFSET 27
#define UNCERR_INT_STA_EN_BID_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_WREADY_FIELD_OFFSET 26
#define UNCERR_INT_STA_EN_WREADY_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_WVALID_FIELD_OFFSET 25
#define UNCERR_INT_STA_EN_WVALID_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_WCTL_FIELD_OFFSET 22
#define UNCERR_INT_STA_EN_WCTL_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_RREADY_FIELD_OFFSET 20
#define UNCERR_INT_STA_EN_RREADY_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_RVALID_FIELD_OFFSET 19
#define UNCERR_INT_STA_EN_RVALID_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_REOBI_FIELD_OFFSET 18
#define UNCERR_INT_STA_EN_REOBI_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_RCTL_FIELD_OFFSET 16
#define UNCERR_INT_STA_EN_RCTL_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_RID_FIELD_OFFSET 14
#define UNCERR_INT_STA_EN_RID_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_AWREADY_FIELD_OFFSET 13
#define UNCERR_INT_STA_EN_AWREADY_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_AWVALID_FIELD_OFFSET 12
#define UNCERR_INT_STA_EN_AWVALID_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_AWCTL1_FIELD_OFFSET 10
#define UNCERR_INT_STA_EN_AWCTL1_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_AWCTL0_FIELD_OFFSET 9
#define UNCERR_INT_STA_EN_AWCTL0_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_AWADDR_FIELD_OFFSET 8
#define UNCERR_INT_STA_EN_AWADDR_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_AWID_FIELD_OFFSET 7
#define UNCERR_INT_STA_EN_AWID_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_ARREADY_FIELD_OFFSET 6
#define UNCERR_INT_STA_EN_ARREADY_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_ARVALID_FIELD_OFFSET 5
#define UNCERR_INT_STA_EN_ARVALID_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_ARCTL1_FIELD_OFFSET 3
#define UNCERR_INT_STA_EN_ARCTL1_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_ARCTL0_FIELD_OFFSET 2
#define UNCERR_INT_STA_EN_ARCTL0_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_ARADDR_FIELD_OFFSET 1
#define UNCERR_INT_STA_EN_ARADDR_FIELD_SIZE 1
#define UNCERR_INT_STA_EN_ARID_FIELD_OFFSET 0
#define UNCERR_INT_STA_EN_ARID_FIELD_SIZE 1

#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_BREADY    (BIT_(31))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_BVALID    (BIT_(30))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_BID    (BIT_(27))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_WREADY    (BIT_(26))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_WVALID    (BIT_(25))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_WCTL    (BIT_(22))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_RREADY    (BIT_(20))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_RVALID    (BIT_(19))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_REOBI    (BIT_(18))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_RCTL    (BIT_(16))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_RID    (BIT_(14))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_AWREADY    (BIT_(13))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_AWVALID    (BIT_(12))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_AWCTL1    (BIT_(10))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_AWCTL0    (BIT_(9))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_AWADDR    (BIT_(8))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_AWID    (BIT_(7))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_ARREADY    (BIT_(6))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_ARVALID    (BIT_(5))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_ARCTL1    (BIT_(3))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_ARCTL0    (BIT_(2))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_ARADDR    (BIT_(1))
#define BIT_AP_APB_MPC_UNCERR_INT_STA_EN_ARID    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_UNCERR_INT_SIG_EN
// Register Offset : 0xf08
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_UNCERR_INT_SIG_EN (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf08<<0))
#define UNCERR_INT_SIG_EN_BREADY_FIELD_OFFSET 31
#define UNCERR_INT_SIG_EN_BREADY_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_BVALID_FIELD_OFFSET 30
#define UNCERR_INT_SIG_EN_BVALID_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_BID_FIELD_OFFSET 27
#define UNCERR_INT_SIG_EN_BID_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_WREADY_FIELD_OFFSET 26
#define UNCERR_INT_SIG_EN_WREADY_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_WVALID_FIELD_OFFSET 25
#define UNCERR_INT_SIG_EN_WVALID_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_WCTL_FIELD_OFFSET 22
#define UNCERR_INT_SIG_EN_WCTL_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_RREADY_FIELD_OFFSET 20
#define UNCERR_INT_SIG_EN_RREADY_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_RVALID_FIELD_OFFSET 19
#define UNCERR_INT_SIG_EN_RVALID_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_REOBI_FIELD_OFFSET 18
#define UNCERR_INT_SIG_EN_REOBI_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_RCTL_FIELD_OFFSET 16
#define UNCERR_INT_SIG_EN_RCTL_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_RID_FIELD_OFFSET 14
#define UNCERR_INT_SIG_EN_RID_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_AWREADY_FIELD_OFFSET 13
#define UNCERR_INT_SIG_EN_AWREADY_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_AWVALID_FIELD_OFFSET 12
#define UNCERR_INT_SIG_EN_AWVALID_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_AWCTL1_FIELD_OFFSET 10
#define UNCERR_INT_SIG_EN_AWCTL1_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_AWCTL0_FIELD_OFFSET 9
#define UNCERR_INT_SIG_EN_AWCTL0_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_AWADDR_FIELD_OFFSET 8
#define UNCERR_INT_SIG_EN_AWADDR_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_AWID_FIELD_OFFSET 7
#define UNCERR_INT_SIG_EN_AWID_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_ARREADY_FIELD_OFFSET 6
#define UNCERR_INT_SIG_EN_ARREADY_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_ARVALID_FIELD_OFFSET 5
#define UNCERR_INT_SIG_EN_ARVALID_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_ARCTL1_FIELD_OFFSET 3
#define UNCERR_INT_SIG_EN_ARCTL1_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_ARCTL0_FIELD_OFFSET 2
#define UNCERR_INT_SIG_EN_ARCTL0_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_ARADDR_FIELD_OFFSET 1
#define UNCERR_INT_SIG_EN_ARADDR_FIELD_SIZE 1
#define UNCERR_INT_SIG_EN_ARID_FIELD_OFFSET 0
#define UNCERR_INT_SIG_EN_ARID_FIELD_SIZE 1

#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_BREADY    (BIT_(31))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_BVALID    (BIT_(30))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_BID    (BIT_(27))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_WREADY    (BIT_(26))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_WVALID    (BIT_(25))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_WCTL    (BIT_(22))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_RREADY    (BIT_(20))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_RVALID    (BIT_(19))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_REOBI    (BIT_(18))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_RCTL    (BIT_(16))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_RID    (BIT_(14))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_AWREADY    (BIT_(13))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_AWVALID    (BIT_(12))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_AWCTL1    (BIT_(10))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_AWCTL0    (BIT_(9))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_AWADDR    (BIT_(8))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_AWID    (BIT_(7))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_ARREADY    (BIT_(6))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_ARVALID    (BIT_(5))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_ARCTL1    (BIT_(3))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_ARCTL0    (BIT_(2))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_ARADDR    (BIT_(1))
#define BIT_AP_APB_MPC_UNCERR_INT_SIG_EN_ARID    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_CORERR_INT_STA
// Register Offset : 0xf0c
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_CORERR_INT_STA (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf0c<<0))
#define CORERR_INT_STA_AWADDR_FIELD_OFFSET 1
#define CORERR_INT_STA_AWADDR_FIELD_SIZE 1
#define CORERR_INT_STA_ARADDR_FIELD_OFFSET 0
#define CORERR_INT_STA_ARADDR_FIELD_SIZE 1

#define BIT_AP_APB_MPC_CORERR_INT_STA_AWADDR    (BIT_(1))
#define BIT_AP_APB_MPC_CORERR_INT_STA_ARADDR    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_CORERR_INT_STA_EN
// Register Offset : 0xf10
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_CORERR_INT_STA_EN (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf10<<0))
#define CORERR_INT_STA_EN_AWADDR_FIELD_OFFSET 1
#define CORERR_INT_STA_EN_AWADDR_FIELD_SIZE 1
#define CORERR_INT_STA_EN_ARADDR_FIELD_OFFSET 0
#define CORERR_INT_STA_EN_ARADDR_FIELD_SIZE 1

#define BIT_AP_APB_MPC_CORERR_INT_STA_EN_AWADDR    (BIT_(1))
#define BIT_AP_APB_MPC_CORERR_INT_STA_EN_ARADDR    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_CORERR_INT_SIG_EN
// Register Offset : 0xf14
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_MPC_CORERR_INT_SIG_EN (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf14<<0))
#define CORERR_INT_SIG_EN_AWADDR_FIELD_OFFSET 1
#define CORERR_INT_SIG_EN_AWADDR_FIELD_SIZE 1
#define CORERR_INT_SIG_EN_ARADDR_FIELD_OFFSET 0
#define CORERR_INT_SIG_EN_ARADDR_FIELD_SIZE 1

#define BIT_AP_APB_MPC_CORERR_INT_SIG_EN_AWADDR    (BIT_(1))
#define BIT_AP_APB_MPC_CORERR_INT_SIG_EN_ARADDR    (BIT_(0))



#endif
