/*
 * Copyright (c) Semidrive
 */

#ifndef _AP_APB_PPC_REG_H
#define _AP_APB_PPC_REG_H
//--------------------------------------------------------------------------
// IP Ref Info     : REG_AP_APB_PPC
// RTL version     :
//--------------------------------------------------------------------------

//--------------------------------------------------------------------------
// Address Block Name : PPC_APB_PPC_APB_AB0
// Description        :
//--------------------------------------------------------------------------
#if WITH_VIRT_PLATFORM
#define PPC_APB_PPC_APB_AB0_BASE_ADDR 0x41000000
#else
#if ARM_CPU_CORTEX_R5
#define PPC_APB_PPC_APB_AB0_BASE_ADDR 0xF0BDC000
#else
#define PPC_APB_PPC_APB_AB0_BASE_ADDR 0x30BDC000
#endif
#endif
//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_DOM
// Register Offset : 0x0
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_DOM (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x0)
#define DOM_LOCK_FIELD_OFFSET 31
#define DOM_LOCK_FIELD_SIZE 1
#define DOM_SET_FIELD_OFFSET 4
#define DOM_SET_FIELD_SIZE 1
#define DOM_DID_FIELD_OFFSET 0
#define DOM_DID_FIELD_SIZE 4

#define BIT_AP_APB_PPC_DOM_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_DOM_SET    (BIT_(4))
#define BIT_AP_APB_PPC_DOM_DID_3    (BIT_(3))
#define BIT_AP_APB_PPC_DOM_DID_2    (BIT_(2))
#define BIT_AP_APB_PPC_DOM_DID_1    (BIT_(1))
#define BIT_AP_APB_PPC_DOM_DID_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_DOM_PER0
// Register Offset : 0x4
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_DOM_PER0 (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x4)
#define DOM_PER0_DOM7_LOCK_FIELD_OFFSET 31
#define DOM_PER0_DOM7_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM7_PER_FIELD_OFFSET 29
#define DOM_PER0_DOM7_PER_FIELD_SIZE 2
#define DOM_PER0_DOM7_EN_FIELD_OFFSET 28
#define DOM_PER0_DOM7_EN_FIELD_SIZE 1
#define DOM_PER0_DOM6_LOCK_FIELD_OFFSET 27
#define DOM_PER0_DOM6_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM6_PER_FIELD_OFFSET 25
#define DOM_PER0_DOM6_PER_FIELD_SIZE 2
#define DOM_PER0_DOM6_EN_FIELD_OFFSET 24
#define DOM_PER0_DOM6_EN_FIELD_SIZE 1
#define DOM_PER0_DOM5_LOCK_FIELD_OFFSET 23
#define DOM_PER0_DOM5_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM5_PER_FIELD_OFFSET 21
#define DOM_PER0_DOM5_PER_FIELD_SIZE 2
#define DOM_PER0_DOM5_EN_FIELD_OFFSET 20
#define DOM_PER0_DOM5_EN_FIELD_SIZE 1
#define DOM_PER0_DOM4_LOCK_FIELD_OFFSET 19
#define DOM_PER0_DOM4_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM4_PER_FIELD_OFFSET 17
#define DOM_PER0_DOM4_PER_FIELD_SIZE 2
#define DOM_PER0_DOM4_EN_FIELD_OFFSET 16
#define DOM_PER0_DOM4_EN_FIELD_SIZE 1
#define DOM_PER0_DOM3_LOCK_FIELD_OFFSET 15
#define DOM_PER0_DOM3_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM3_PER_FIELD_OFFSET 13
#define DOM_PER0_DOM3_PER_FIELD_SIZE 2
#define DOM_PER0_DOM3_EN_FIELD_OFFSET 12
#define DOM_PER0_DOM3_EN_FIELD_SIZE 1
#define DOM_PER0_DOM2_LOCK_FIELD_OFFSET 11
#define DOM_PER0_DOM2_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM2_PER_FIELD_OFFSET 9
#define DOM_PER0_DOM2_PER_FIELD_SIZE 2
#define DOM_PER0_DOM2_EN_FIELD_OFFSET 8
#define DOM_PER0_DOM2_EN_FIELD_SIZE 1
#define DOM_PER0_DOM1_LOCK_FIELD_OFFSET 7
#define DOM_PER0_DOM1_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM1_PER_FIELD_OFFSET 5
#define DOM_PER0_DOM1_PER_FIELD_SIZE 2
#define DOM_PER0_DOM1_EN_FIELD_OFFSET 4
#define DOM_PER0_DOM1_EN_FIELD_SIZE 1
#define DOM_PER0_DOM0_LOCK_FIELD_OFFSET 3
#define DOM_PER0_DOM0_LOCK_FIELD_SIZE 1
#define DOM_PER0_DOM0_PER_FIELD_OFFSET 1
#define DOM_PER0_DOM0_PER_FIELD_SIZE 2
#define DOM_PER0_DOM0_EN_FIELD_OFFSET 0
#define DOM_PER0_DOM0_EN_FIELD_SIZE 1

#define BIT_AP_APB_PPC_DOM_PER0_DOM7_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_DOM_PER0_DOM7_PER_1    (BIT_(30))
#define BIT_AP_APB_PPC_DOM_PER0_DOM7_PER_0    (BIT_(29))
#define BIT_AP_APB_PPC_DOM_PER0_DOM7_EN    (BIT_(28))
#define BIT_AP_APB_PPC_DOM_PER0_DOM6_LOCK    (BIT_(27))
#define BIT_AP_APB_PPC_DOM_PER0_DOM6_PER_1    (BIT_(26))
#define BIT_AP_APB_PPC_DOM_PER0_DOM6_PER_0    (BIT_(25))
#define BIT_AP_APB_PPC_DOM_PER0_DOM6_EN    (BIT_(24))
#define BIT_AP_APB_PPC_DOM_PER0_DOM5_LOCK    (BIT_(23))
#define BIT_AP_APB_PPC_DOM_PER0_DOM5_PER_1    (BIT_(22))
#define BIT_AP_APB_PPC_DOM_PER0_DOM5_PER_0    (BIT_(21))
#define BIT_AP_APB_PPC_DOM_PER0_DOM5_EN    (BIT_(20))
#define BIT_AP_APB_PPC_DOM_PER0_DOM4_LOCK    (BIT_(19))
#define BIT_AP_APB_PPC_DOM_PER0_DOM4_PER_1    (BIT_(18))
#define BIT_AP_APB_PPC_DOM_PER0_DOM4_PER_0    (BIT_(17))
#define BIT_AP_APB_PPC_DOM_PER0_DOM4_EN    (BIT_(16))
#define BIT_AP_APB_PPC_DOM_PER0_DOM3_LOCK    (BIT_(15))
#define BIT_AP_APB_PPC_DOM_PER0_DOM3_PER_1    (BIT_(14))
#define BIT_AP_APB_PPC_DOM_PER0_DOM3_PER_0    (BIT_(13))
#define BIT_AP_APB_PPC_DOM_PER0_DOM3_EN    (BIT_(12))
#define BIT_AP_APB_PPC_DOM_PER0_DOM2_LOCK    (BIT_(11))
#define BIT_AP_APB_PPC_DOM_PER0_DOM2_PER_1    (BIT_(10))
#define BIT_AP_APB_PPC_DOM_PER0_DOM2_PER_0    (BIT_(9))
#define BIT_AP_APB_PPC_DOM_PER0_DOM2_EN    (BIT_(8))
#define BIT_AP_APB_PPC_DOM_PER0_DOM1_LOCK    (BIT_(7))
#define BIT_AP_APB_PPC_DOM_PER0_DOM1_PER_1    (BIT_(6))
#define BIT_AP_APB_PPC_DOM_PER0_DOM1_PER_0    (BIT_(5))
#define BIT_AP_APB_PPC_DOM_PER0_DOM1_EN    (BIT_(4))
#define BIT_AP_APB_PPC_DOM_PER0_DOM0_LOCK    (BIT_(3))
#define BIT_AP_APB_PPC_DOM_PER0_DOM0_PER_1    (BIT_(2))
#define BIT_AP_APB_PPC_DOM_PER0_DOM0_PER_0    (BIT_(1))
#define BIT_AP_APB_PPC_DOM_PER0_DOM0_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_DOM_PER1
// Register Offset : 0x8
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_DOM_PER1 (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x8)
#define DOM_PER1_DOM15_LOCK_FIELD_OFFSET 31
#define DOM_PER1_DOM15_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM15_PER_FIELD_OFFSET 29
#define DOM_PER1_DOM15_PER_FIELD_SIZE 2
#define DOM_PER1_DOM15_EN_FIELD_OFFSET 28
#define DOM_PER1_DOM15_EN_FIELD_SIZE 1
#define DOM_PER1_DOM14_LOCK_FIELD_OFFSET 27
#define DOM_PER1_DOM14_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM14_PER_FIELD_OFFSET 25
#define DOM_PER1_DOM14_PER_FIELD_SIZE 2
#define DOM_PER1_DOM14_EN_FIELD_OFFSET 24
#define DOM_PER1_DOM14_EN_FIELD_SIZE 1
#define DOM_PER1_DOM13_LOCK_FIELD_OFFSET 23
#define DOM_PER1_DOM13_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM13_PER_FIELD_OFFSET 21
#define DOM_PER1_DOM13_PER_FIELD_SIZE 2
#define DOM_PER1_DOM13_EN_FIELD_OFFSET 20
#define DOM_PER1_DOM13_EN_FIELD_SIZE 1
#define DOM_PER1_DOM12_LOCK_FIELD_OFFSET 19
#define DOM_PER1_DOM12_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM12_PER_FIELD_OFFSET 17
#define DOM_PER1_DOM12_PER_FIELD_SIZE 2
#define DOM_PER1_DOM12_EN_FIELD_OFFSET 16
#define DOM_PER1_DOM12_EN_FIELD_SIZE 1
#define DOM_PER1_DOM11_LOCK_FIELD_OFFSET 15
#define DOM_PER1_DOM11_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM11_PER_FIELD_OFFSET 13
#define DOM_PER1_DOM11_PER_FIELD_SIZE 2
#define DOM_PER1_DOM11_EN_FIELD_OFFSET 12
#define DOM_PER1_DOM11_EN_FIELD_SIZE 1
#define DOM_PER1_DOM10_LOCK_FIELD_OFFSET 11
#define DOM_PER1_DOM10_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM10_PER_FIELD_OFFSET 9
#define DOM_PER1_DOM10_PER_FIELD_SIZE 2
#define DOM_PER1_DOM10_EN_FIELD_OFFSET 8
#define DOM_PER1_DOM10_EN_FIELD_SIZE 1
#define DOM_PER1_DOM9_LOCK_FIELD_OFFSET 7
#define DOM_PER1_DOM9_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM9_PER_FIELD_OFFSET 5
#define DOM_PER1_DOM9_PER_FIELD_SIZE 2
#define DOM_PER1_DOM9_EN_FIELD_OFFSET 4
#define DOM_PER1_DOM9_EN_FIELD_SIZE 1
#define DOM_PER1_DOM8_LOCK_FIELD_OFFSET 3
#define DOM_PER1_DOM8_LOCK_FIELD_SIZE 1
#define DOM_PER1_DOM8_PER_FIELD_OFFSET 1
#define DOM_PER1_DOM8_PER_FIELD_SIZE 2
#define DOM_PER1_DOM8_EN_FIELD_OFFSET 0
#define DOM_PER1_DOM8_EN_FIELD_SIZE 1

#define BIT_AP_APB_PPC_DOM_PER1_DOM15_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_DOM_PER1_DOM15_PER_1    (BIT_(30))
#define BIT_AP_APB_PPC_DOM_PER1_DOM15_PER_0    (BIT_(29))
#define BIT_AP_APB_PPC_DOM_PER1_DOM15_EN    (BIT_(28))
#define BIT_AP_APB_PPC_DOM_PER1_DOM14_LOCK    (BIT_(27))
#define BIT_AP_APB_PPC_DOM_PER1_DOM14_PER_1    (BIT_(26))
#define BIT_AP_APB_PPC_DOM_PER1_DOM14_PER_0    (BIT_(25))
#define BIT_AP_APB_PPC_DOM_PER1_DOM14_EN    (BIT_(24))
#define BIT_AP_APB_PPC_DOM_PER1_DOM13_LOCK    (BIT_(23))
#define BIT_AP_APB_PPC_DOM_PER1_DOM13_PER_1    (BIT_(22))
#define BIT_AP_APB_PPC_DOM_PER1_DOM13_PER_0    (BIT_(21))
#define BIT_AP_APB_PPC_DOM_PER1_DOM13_EN    (BIT_(20))
#define BIT_AP_APB_PPC_DOM_PER1_DOM12_LOCK    (BIT_(19))
#define BIT_AP_APB_PPC_DOM_PER1_DOM12_PER_1    (BIT_(18))
#define BIT_AP_APB_PPC_DOM_PER1_DOM12_PER_0    (BIT_(17))
#define BIT_AP_APB_PPC_DOM_PER1_DOM12_EN    (BIT_(16))
#define BIT_AP_APB_PPC_DOM_PER1_DOM11_LOCK    (BIT_(15))
#define BIT_AP_APB_PPC_DOM_PER1_DOM11_PER_1    (BIT_(14))
#define BIT_AP_APB_PPC_DOM_PER1_DOM11_PER_0    (BIT_(13))
#define BIT_AP_APB_PPC_DOM_PER1_DOM11_EN    (BIT_(12))
#define BIT_AP_APB_PPC_DOM_PER1_DOM10_LOCK    (BIT_(11))
#define BIT_AP_APB_PPC_DOM_PER1_DOM10_PER_1    (BIT_(10))
#define BIT_AP_APB_PPC_DOM_PER1_DOM10_PER_0    (BIT_(9))
#define BIT_AP_APB_PPC_DOM_PER1_DOM10_EN    (BIT_(8))
#define BIT_AP_APB_PPC_DOM_PER1_DOM9_LOCK    (BIT_(7))
#define BIT_AP_APB_PPC_DOM_PER1_DOM9_PER_1    (BIT_(6))
#define BIT_AP_APB_PPC_DOM_PER1_DOM9_PER_0    (BIT_(5))
#define BIT_AP_APB_PPC_DOM_PER1_DOM9_EN    (BIT_(4))
#define BIT_AP_APB_PPC_DOM_PER1_DOM8_LOCK    (BIT_(3))
#define BIT_AP_APB_PPC_DOM_PER1_DOM8_PER_1    (BIT_(2))
#define BIT_AP_APB_PPC_DOM_PER1_DOM8_PER_0    (BIT_(1))
#define BIT_AP_APB_PPC_DOM_PER1_DOM8_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_SEC_PER0
// Register Offset : 0xc
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_SEC_PER0 (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0xc)
#define SEC_PER0_DOM3_LOCK_FIELD_OFFSET 31
#define SEC_PER0_DOM3_LOCK_FIELD_SIZE 1
#define SEC_PER0_DOM3_NSE_PER_FIELD_OFFSET 27
#define SEC_PER0_DOM3_NSE_PER_FIELD_SIZE 2
#define SEC_PER0_DOM3_SEC_PER_FIELD_OFFSET 25
#define SEC_PER0_DOM3_SEC_PER_FIELD_SIZE 2
#define SEC_PER0_DOM3_SEC_EN_FIELD_OFFSET 24
#define SEC_PER0_DOM3_SEC_EN_FIELD_SIZE 1
#define SEC_PER0_DOM2_LOCK_FIELD_OFFSET 23
#define SEC_PER0_DOM2_LOCK_FIELD_SIZE 1
#define SEC_PER0_DOM2_NSE_PER_FIELD_OFFSET 19
#define SEC_PER0_DOM2_NSE_PER_FIELD_SIZE 2
#define SEC_PER0_DOM2_SEC_PER_FIELD_OFFSET 17
#define SEC_PER0_DOM2_SEC_PER_FIELD_SIZE 2
#define SEC_PER0_DOM2_SEC_EN_FIELD_OFFSET 16
#define SEC_PER0_DOM2_SEC_EN_FIELD_SIZE 1
#define SEC_PER0_DOM1_LOCK_FIELD_OFFSET 15
#define SEC_PER0_DOM1_LOCK_FIELD_SIZE 1
#define SEC_PER0_DOM1_NSE_PER_FIELD_OFFSET 11
#define SEC_PER0_DOM1_NSE_PER_FIELD_SIZE 2
#define SEC_PER0_DOM1_SEC_PER_FIELD_OFFSET 9
#define SEC_PER0_DOM1_SEC_PER_FIELD_SIZE 2
#define SEC_PER0_DOM1_SEC_EN_FIELD_OFFSET 8
#define SEC_PER0_DOM1_SEC_EN_FIELD_SIZE 1
#define SEC_PER0_DOM0_LOCK_FIELD_OFFSET 7
#define SEC_PER0_DOM0_LOCK_FIELD_SIZE 1
#define SEC_PER0_DOM0_NSE_PER_FIELD_OFFSET 3
#define SEC_PER0_DOM0_NSE_PER_FIELD_SIZE 2
#define SEC_PER0_DOM0_SEC_PER_FIELD_OFFSET 1
#define SEC_PER0_DOM0_SEC_PER_FIELD_SIZE 2
#define SEC_PER0_DOM0_SEC_EN_FIELD_OFFSET 0
#define SEC_PER0_DOM0_SEC_EN_FIELD_SIZE 1

#define BIT_AP_APB_PPC_SEC_PER0_DOM3_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_SEC_PER0_DOM3_NSE_PER_1    (BIT_(28))
#define BIT_AP_APB_PPC_SEC_PER0_DOM3_NSE_PER_0    (BIT_(27))
#define BIT_AP_APB_PPC_SEC_PER0_DOM3_SEC_PER_1    (BIT_(26))
#define BIT_AP_APB_PPC_SEC_PER0_DOM3_SEC_PER_0    (BIT_(25))
#define BIT_AP_APB_PPC_SEC_PER0_DOM3_SEC_EN    (BIT_(24))
#define BIT_AP_APB_PPC_SEC_PER0_DOM2_LOCK    (BIT_(23))
#define BIT_AP_APB_PPC_SEC_PER0_DOM2_NSE_PER_1    (BIT_(20))
#define BIT_AP_APB_PPC_SEC_PER0_DOM2_NSE_PER_0    (BIT_(19))
#define BIT_AP_APB_PPC_SEC_PER0_DOM2_SEC_PER_1    (BIT_(18))
#define BIT_AP_APB_PPC_SEC_PER0_DOM2_SEC_PER_0    (BIT_(17))
#define BIT_AP_APB_PPC_SEC_PER0_DOM2_SEC_EN    (BIT_(16))
#define BIT_AP_APB_PPC_SEC_PER0_DOM1_LOCK    (BIT_(15))
#define BIT_AP_APB_PPC_SEC_PER0_DOM1_NSE_PER_1    (BIT_(12))
#define BIT_AP_APB_PPC_SEC_PER0_DOM1_NSE_PER_0    (BIT_(11))
#define BIT_AP_APB_PPC_SEC_PER0_DOM1_SEC_PER_1    (BIT_(10))
#define BIT_AP_APB_PPC_SEC_PER0_DOM1_SEC_PER_0    (BIT_(9))
#define BIT_AP_APB_PPC_SEC_PER0_DOM1_SEC_EN    (BIT_(8))
#define BIT_AP_APB_PPC_SEC_PER0_DOM0_LOCK    (BIT_(7))
#define BIT_AP_APB_PPC_SEC_PER0_DOM0_NSE_PER_1    (BIT_(4))
#define BIT_AP_APB_PPC_SEC_PER0_DOM0_NSE_PER_0    (BIT_(3))
#define BIT_AP_APB_PPC_SEC_PER0_DOM0_SEC_PER_1    (BIT_(2))
#define BIT_AP_APB_PPC_SEC_PER0_DOM0_SEC_PER_0    (BIT_(1))
#define BIT_AP_APB_PPC_SEC_PER0_DOM0_SEC_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_SEC_PER1
// Register Offset : 0x10
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_SEC_PER1 (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x10)
#define SEC_PER1_DOM7_LOCK_FIELD_OFFSET 31
#define SEC_PER1_DOM7_LOCK_FIELD_SIZE 1
#define SEC_PER1_DOM7_NSE_PER_FIELD_OFFSET 27
#define SEC_PER1_DOM7_NSE_PER_FIELD_SIZE 2
#define SEC_PER1_DOM7_SEC_PER_FIELD_OFFSET 25
#define SEC_PER1_DOM7_SEC_PER_FIELD_SIZE 2
#define SEC_PER1_DOM7_SEC_EN_FIELD_OFFSET 24
#define SEC_PER1_DOM7_SEC_EN_FIELD_SIZE 1
#define SEC_PER1_DOM6_LOCK_FIELD_OFFSET 23
#define SEC_PER1_DOM6_LOCK_FIELD_SIZE 1
#define SEC_PER1_DOM6_NSE_PER_FIELD_OFFSET 19
#define SEC_PER1_DOM6_NSE_PER_FIELD_SIZE 2
#define SEC_PER1_DOM6_SEC_PER_FIELD_OFFSET 17
#define SEC_PER1_DOM6_SEC_PER_FIELD_SIZE 2
#define SEC_PER1_DOM6_SEC_EN_FIELD_OFFSET 16
#define SEC_PER1_DOM6_SEC_EN_FIELD_SIZE 1
#define SEC_PER1_DOM5_LOCK_FIELD_OFFSET 15
#define SEC_PER1_DOM5_LOCK_FIELD_SIZE 1
#define SEC_PER1_DOM5_NSE_PER_FIELD_OFFSET 11
#define SEC_PER1_DOM5_NSE_PER_FIELD_SIZE 2
#define SEC_PER1_DOM5_SEC_PER_FIELD_OFFSET 9
#define SEC_PER1_DOM5_SEC_PER_FIELD_SIZE 2
#define SEC_PER1_DOM5_SEC_EN_FIELD_OFFSET 8
#define SEC_PER1_DOM5_SEC_EN_FIELD_SIZE 1
#define SEC_PER1_DOM4_LOCK_FIELD_OFFSET 7
#define SEC_PER1_DOM4_LOCK_FIELD_SIZE 1
#define SEC_PER1_DOM4_NSE_PER_FIELD_OFFSET 3
#define SEC_PER1_DOM4_NSE_PER_FIELD_SIZE 2
#define SEC_PER1_DOM4_SEC_PER_FIELD_OFFSET 1
#define SEC_PER1_DOM4_SEC_PER_FIELD_SIZE 2
#define SEC_PER1_DOM4_SEC_EN_FIELD_OFFSET 0
#define SEC_PER1_DOM4_SEC_EN_FIELD_SIZE 1

#define BIT_AP_APB_PPC_SEC_PER1_DOM7_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_SEC_PER1_DOM7_NSE_PER_1    (BIT_(28))
#define BIT_AP_APB_PPC_SEC_PER1_DOM7_NSE_PER_0    (BIT_(27))
#define BIT_AP_APB_PPC_SEC_PER1_DOM7_SEC_PER_1    (BIT_(26))
#define BIT_AP_APB_PPC_SEC_PER1_DOM7_SEC_PER_0    (BIT_(25))
#define BIT_AP_APB_PPC_SEC_PER1_DOM7_SEC_EN    (BIT_(24))
#define BIT_AP_APB_PPC_SEC_PER1_DOM6_LOCK    (BIT_(23))
#define BIT_AP_APB_PPC_SEC_PER1_DOM6_NSE_PER_1    (BIT_(20))
#define BIT_AP_APB_PPC_SEC_PER1_DOM6_NSE_PER_0    (BIT_(19))
#define BIT_AP_APB_PPC_SEC_PER1_DOM6_SEC_PER_1    (BIT_(18))
#define BIT_AP_APB_PPC_SEC_PER1_DOM6_SEC_PER_0    (BIT_(17))
#define BIT_AP_APB_PPC_SEC_PER1_DOM6_SEC_EN    (BIT_(16))
#define BIT_AP_APB_PPC_SEC_PER1_DOM5_LOCK    (BIT_(15))
#define BIT_AP_APB_PPC_SEC_PER1_DOM5_NSE_PER_1    (BIT_(12))
#define BIT_AP_APB_PPC_SEC_PER1_DOM5_NSE_PER_0    (BIT_(11))
#define BIT_AP_APB_PPC_SEC_PER1_DOM5_SEC_PER_1    (BIT_(10))
#define BIT_AP_APB_PPC_SEC_PER1_DOM5_SEC_PER_0    (BIT_(9))
#define BIT_AP_APB_PPC_SEC_PER1_DOM5_SEC_EN    (BIT_(8))
#define BIT_AP_APB_PPC_SEC_PER1_DOM4_LOCK    (BIT_(7))
#define BIT_AP_APB_PPC_SEC_PER1_DOM4_NSE_PER_1    (BIT_(4))
#define BIT_AP_APB_PPC_SEC_PER1_DOM4_NSE_PER_0    (BIT_(3))
#define BIT_AP_APB_PPC_SEC_PER1_DOM4_SEC_PER_1    (BIT_(2))
#define BIT_AP_APB_PPC_SEC_PER1_DOM4_SEC_PER_0    (BIT_(1))
#define BIT_AP_APB_PPC_SEC_PER1_DOM4_SEC_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_SEC_PER2
// Register Offset : 0x14
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_SEC_PER2 (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x14)
#define SEC_PER2_DOM11_LOCK_FIELD_OFFSET 31
#define SEC_PER2_DOM11_LOCK_FIELD_SIZE 1
#define SEC_PER2_DOM11_NSE_PER_FIELD_OFFSET 27
#define SEC_PER2_DOM11_NSE_PER_FIELD_SIZE 2
#define SEC_PER2_DOM11_SEC_PER_FIELD_OFFSET 25
#define SEC_PER2_DOM11_SEC_PER_FIELD_SIZE 2
#define SEC_PER2_DOM11_SEC_EN_FIELD_OFFSET 24
#define SEC_PER2_DOM11_SEC_EN_FIELD_SIZE 1
#define SEC_PER2_DOM10_LOCK_FIELD_OFFSET 23
#define SEC_PER2_DOM10_LOCK_FIELD_SIZE 1
#define SEC_PER2_DOM10_NSE_PER_FIELD_OFFSET 19
#define SEC_PER2_DOM10_NSE_PER_FIELD_SIZE 2
#define SEC_PER2_DOM10_SEC_PER_FIELD_OFFSET 17
#define SEC_PER2_DOM10_SEC_PER_FIELD_SIZE 2
#define SEC_PER2_DOM10_SEC_EN_FIELD_OFFSET 16
#define SEC_PER2_DOM10_SEC_EN_FIELD_SIZE 1
#define SEC_PER2_DOM9_LOCK_FIELD_OFFSET 15
#define SEC_PER2_DOM9_LOCK_FIELD_SIZE 1
#define SEC_PER2_DOM9_NSE_PER_FIELD_OFFSET 11
#define SEC_PER2_DOM9_NSE_PER_FIELD_SIZE 2
#define SEC_PER2_DOM9_SEC_PER_FIELD_OFFSET 9
#define SEC_PER2_DOM9_SEC_PER_FIELD_SIZE 2
#define SEC_PER2_DOM9_SEC_EN_FIELD_OFFSET 8
#define SEC_PER2_DOM9_SEC_EN_FIELD_SIZE 1
#define SEC_PER2_DOM8_LOCK_FIELD_OFFSET 7
#define SEC_PER2_DOM8_LOCK_FIELD_SIZE 1
#define SEC_PER2_DOM8_NSE_PER_FIELD_OFFSET 3
#define SEC_PER2_DOM8_NSE_PER_FIELD_SIZE 2
#define SEC_PER2_DOM8_SEC_PER_FIELD_OFFSET 1
#define SEC_PER2_DOM8_SEC_PER_FIELD_SIZE 2
#define SEC_PER2_DOM8_SEC_EN_FIELD_OFFSET 0
#define SEC_PER2_DOM8_SEC_EN_FIELD_SIZE 1

#define BIT_AP_APB_PPC_SEC_PER2_DOM11_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_SEC_PER2_DOM11_NSE_PER_1    (BIT_(28))
#define BIT_AP_APB_PPC_SEC_PER2_DOM11_NSE_PER_0    (BIT_(27))
#define BIT_AP_APB_PPC_SEC_PER2_DOM11_SEC_PER_1    (BIT_(26))
#define BIT_AP_APB_PPC_SEC_PER2_DOM11_SEC_PER_0    (BIT_(25))
#define BIT_AP_APB_PPC_SEC_PER2_DOM11_SEC_EN    (BIT_(24))
#define BIT_AP_APB_PPC_SEC_PER2_DOM10_LOCK    (BIT_(23))
#define BIT_AP_APB_PPC_SEC_PER2_DOM10_NSE_PER_1    (BIT_(20))
#define BIT_AP_APB_PPC_SEC_PER2_DOM10_NSE_PER_0    (BIT_(19))
#define BIT_AP_APB_PPC_SEC_PER2_DOM10_SEC_PER_1    (BIT_(18))
#define BIT_AP_APB_PPC_SEC_PER2_DOM10_SEC_PER_0    (BIT_(17))
#define BIT_AP_APB_PPC_SEC_PER2_DOM10_SEC_EN    (BIT_(16))
#define BIT_AP_APB_PPC_SEC_PER2_DOM9_LOCK    (BIT_(15))
#define BIT_AP_APB_PPC_SEC_PER2_DOM9_NSE_PER_1    (BIT_(12))
#define BIT_AP_APB_PPC_SEC_PER2_DOM9_NSE_PER_0    (BIT_(11))
#define BIT_AP_APB_PPC_SEC_PER2_DOM9_SEC_PER_1    (BIT_(10))
#define BIT_AP_APB_PPC_SEC_PER2_DOM9_SEC_PER_0    (BIT_(9))
#define BIT_AP_APB_PPC_SEC_PER2_DOM9_SEC_EN    (BIT_(8))
#define BIT_AP_APB_PPC_SEC_PER2_DOM8_LOCK    (BIT_(7))
#define BIT_AP_APB_PPC_SEC_PER2_DOM8_NSE_PER_1    (BIT_(4))
#define BIT_AP_APB_PPC_SEC_PER2_DOM8_NSE_PER_0    (BIT_(3))
#define BIT_AP_APB_PPC_SEC_PER2_DOM8_SEC_PER_1    (BIT_(2))
#define BIT_AP_APB_PPC_SEC_PER2_DOM8_SEC_PER_0    (BIT_(1))
#define BIT_AP_APB_PPC_SEC_PER2_DOM8_SEC_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_SEC_PER3
// Register Offset : 0x18
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_SEC_PER3 (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x18)
#define SEC_PER3_DOM15_LOCK_FIELD_OFFSET 31
#define SEC_PER3_DOM15_LOCK_FIELD_SIZE 1
#define SEC_PER3_DOM15_NSE_PER_FIELD_OFFSET 27
#define SEC_PER3_DOM15_NSE_PER_FIELD_SIZE 2
#define SEC_PER3_DOM15_SEC_PER_FIELD_OFFSET 25
#define SEC_PER3_DOM15_SEC_PER_FIELD_SIZE 2
#define SEC_PER3_DOM15_SEC_EN_FIELD_OFFSET 24
#define SEC_PER3_DOM15_SEC_EN_FIELD_SIZE 1
#define SEC_PER3_DOM14_LOCK_FIELD_OFFSET 23
#define SEC_PER3_DOM14_LOCK_FIELD_SIZE 1
#define SEC_PER3_DOM14_NSE_PER_FIELD_OFFSET 19
#define SEC_PER3_DOM14_NSE_PER_FIELD_SIZE 2
#define SEC_PER3_DOM14_SEC_PER_FIELD_OFFSET 17
#define SEC_PER3_DOM14_SEC_PER_FIELD_SIZE 2
#define SEC_PER3_DOM14_SEC_EN_FIELD_OFFSET 16
#define SEC_PER3_DOM14_SEC_EN_FIELD_SIZE 1
#define SEC_PER3_DOM13_LOCK_FIELD_OFFSET 15
#define SEC_PER3_DOM13_LOCK_FIELD_SIZE 1
#define SEC_PER3_DOM13_NSE_PER_FIELD_OFFSET 11
#define SEC_PER3_DOM13_NSE_PER_FIELD_SIZE 2
#define SEC_PER3_DOM13_SEC_PER_FIELD_OFFSET 9
#define SEC_PER3_DOM13_SEC_PER_FIELD_SIZE 2
#define SEC_PER3_DOM13_SEC_EN_FIELD_OFFSET 8
#define SEC_PER3_DOM13_SEC_EN_FIELD_SIZE 1
#define SEC_PER3_DOM12_LOCK_FIELD_OFFSET 7
#define SEC_PER3_DOM12_LOCK_FIELD_SIZE 1
#define SEC_PER3_DOM12_NSE_PER_FIELD_OFFSET 3
#define SEC_PER3_DOM12_NSE_PER_FIELD_SIZE 2
#define SEC_PER3_DOM12_SEC_PER_FIELD_OFFSET 1
#define SEC_PER3_DOM12_SEC_PER_FIELD_SIZE 2
#define SEC_PER3_DOM12_SEC_EN_FIELD_OFFSET 0
#define SEC_PER3_DOM12_SEC_EN_FIELD_SIZE 1

#define BIT_AP_APB_PPC_SEC_PER3_DOM15_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_SEC_PER3_DOM15_NSE_PER_1    (BIT_(28))
#define BIT_AP_APB_PPC_SEC_PER3_DOM15_NSE_PER_0    (BIT_(27))
#define BIT_AP_APB_PPC_SEC_PER3_DOM15_SEC_PER_1    (BIT_(26))
#define BIT_AP_APB_PPC_SEC_PER3_DOM15_SEC_PER_0    (BIT_(25))
#define BIT_AP_APB_PPC_SEC_PER3_DOM15_SEC_EN    (BIT_(24))
#define BIT_AP_APB_PPC_SEC_PER3_DOM14_LOCK    (BIT_(23))
#define BIT_AP_APB_PPC_SEC_PER3_DOM14_NSE_PER_1    (BIT_(20))
#define BIT_AP_APB_PPC_SEC_PER3_DOM14_NSE_PER_0    (BIT_(19))
#define BIT_AP_APB_PPC_SEC_PER3_DOM14_SEC_PER_1    (BIT_(18))
#define BIT_AP_APB_PPC_SEC_PER3_DOM14_SEC_PER_0    (BIT_(17))
#define BIT_AP_APB_PPC_SEC_PER3_DOM14_SEC_EN    (BIT_(16))
#define BIT_AP_APB_PPC_SEC_PER3_DOM13_LOCK    (BIT_(15))
#define BIT_AP_APB_PPC_SEC_PER3_DOM13_NSE_PER_1    (BIT_(12))
#define BIT_AP_APB_PPC_SEC_PER3_DOM13_NSE_PER_0    (BIT_(11))
#define BIT_AP_APB_PPC_SEC_PER3_DOM13_SEC_PER_1    (BIT_(10))
#define BIT_AP_APB_PPC_SEC_PER3_DOM13_SEC_PER_0    (BIT_(9))
#define BIT_AP_APB_PPC_SEC_PER3_DOM13_SEC_EN    (BIT_(8))
#define BIT_AP_APB_PPC_SEC_PER3_DOM12_LOCK    (BIT_(7))
#define BIT_AP_APB_PPC_SEC_PER3_DOM12_NSE_PER_1    (BIT_(4))
#define BIT_AP_APB_PPC_SEC_PER3_DOM12_NSE_PER_0    (BIT_(3))
#define BIT_AP_APB_PPC_SEC_PER3_DOM12_SEC_PER_1    (BIT_(2))
#define BIT_AP_APB_PPC_SEC_PER3_DOM12_SEC_PER_0    (BIT_(1))
#define BIT_AP_APB_PPC_SEC_PER3_DOM12_SEC_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_PRI_PER0
// Register Offset : 0x1c
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_PRI_PER0 (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x1c)
#define PRI_PER0_DOM3_LOCK_FIELD_OFFSET 31
#define PRI_PER0_DOM3_LOCK_FIELD_SIZE 1
#define PRI_PER0_DOM3_USE_PER_FIELD_OFFSET 27
#define PRI_PER0_DOM3_USE_PER_FIELD_SIZE 2
#define PRI_PER0_DOM3_PRI_PER_FIELD_OFFSET 25
#define PRI_PER0_DOM3_PRI_PER_FIELD_SIZE 2
#define PRI_PER0_DOM3_PRI_EN_FIELD_OFFSET 24
#define PRI_PER0_DOM3_PRI_EN_FIELD_SIZE 1
#define PRI_PER0_DOM2_LOCK_FIELD_OFFSET 23
#define PRI_PER0_DOM2_LOCK_FIELD_SIZE 1
#define PRI_PER0_DOM2_USE_PER_FIELD_OFFSET 19
#define PRI_PER0_DOM2_USE_PER_FIELD_SIZE 2
#define PRI_PER0_DOM2_PRI_PER_FIELD_OFFSET 17
#define PRI_PER0_DOM2_PRI_PER_FIELD_SIZE 2
#define PRI_PER0_DOM2_PRI_EN_FIELD_OFFSET 16
#define PRI_PER0_DOM2_PRI_EN_FIELD_SIZE 1
#define PRI_PER0_DOM1_LOCK_FIELD_OFFSET 15
#define PRI_PER0_DOM1_LOCK_FIELD_SIZE 1
#define PRI_PER0_DOM1_USE_PER_FIELD_OFFSET 11
#define PRI_PER0_DOM1_USE_PER_FIELD_SIZE 2
#define PRI_PER0_DOM1_PRI_PER_FIELD_OFFSET 9
#define PRI_PER0_DOM1_PRI_PER_FIELD_SIZE 2
#define PRI_PER0_DOM1_PRI_EN_FIELD_OFFSET 8
#define PRI_PER0_DOM1_PRI_EN_FIELD_SIZE 1
#define PRI_PER0_DOM0_LOCK_FIELD_OFFSET 7
#define PRI_PER0_DOM0_LOCK_FIELD_SIZE 1
#define PRI_PER0_DOM0_USE_PER_FIELD_OFFSET 3
#define PRI_PER0_DOM0_USE_PER_FIELD_SIZE 2
#define PRI_PER0_DOM0_PRI_PER_FIELD_OFFSET 1
#define PRI_PER0_DOM0_PRI_PER_FIELD_SIZE 2
#define PRI_PER0_DOM0_PRI_EN_FIELD_OFFSET 0
#define PRI_PER0_DOM0_PRI_EN_FIELD_SIZE 1

#define BIT_AP_APB_PPC_PRI_PER0_DOM3_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_PRI_PER0_DOM3_USE_PER_1    (BIT_(28))
#define BIT_AP_APB_PPC_PRI_PER0_DOM3_USE_PER_0    (BIT_(27))
#define BIT_AP_APB_PPC_PRI_PER0_DOM3_PRI_PER_1    (BIT_(26))
#define BIT_AP_APB_PPC_PRI_PER0_DOM3_PRI_PER_0    (BIT_(25))
#define BIT_AP_APB_PPC_PRI_PER0_DOM3_PRI_EN    (BIT_(24))
#define BIT_AP_APB_PPC_PRI_PER0_DOM2_LOCK    (BIT_(23))
#define BIT_AP_APB_PPC_PRI_PER0_DOM2_USE_PER_1    (BIT_(20))
#define BIT_AP_APB_PPC_PRI_PER0_DOM2_USE_PER_0    (BIT_(19))
#define BIT_AP_APB_PPC_PRI_PER0_DOM2_PRI_PER_1    (BIT_(18))
#define BIT_AP_APB_PPC_PRI_PER0_DOM2_PRI_PER_0    (BIT_(17))
#define BIT_AP_APB_PPC_PRI_PER0_DOM2_PRI_EN    (BIT_(16))
#define BIT_AP_APB_PPC_PRI_PER0_DOM1_LOCK    (BIT_(15))
#define BIT_AP_APB_PPC_PRI_PER0_DOM1_USE_PER_1    (BIT_(12))
#define BIT_AP_APB_PPC_PRI_PER0_DOM1_USE_PER_0    (BIT_(11))
#define BIT_AP_APB_PPC_PRI_PER0_DOM1_PRI_PER_1    (BIT_(10))
#define BIT_AP_APB_PPC_PRI_PER0_DOM1_PRI_PER_0    (BIT_(9))
#define BIT_AP_APB_PPC_PRI_PER0_DOM1_PRI_EN    (BIT_(8))
#define BIT_AP_APB_PPC_PRI_PER0_DOM0_LOCK    (BIT_(7))
#define BIT_AP_APB_PPC_PRI_PER0_DOM0_USE_PER_1    (BIT_(4))
#define BIT_AP_APB_PPC_PRI_PER0_DOM0_USE_PER_0    (BIT_(3))
#define BIT_AP_APB_PPC_PRI_PER0_DOM0_PRI_PER_1    (BIT_(2))
#define BIT_AP_APB_PPC_PRI_PER0_DOM0_PRI_PER_0    (BIT_(1))
#define BIT_AP_APB_PPC_PRI_PER0_DOM0_PRI_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_PRI_PER1
// Register Offset : 0x20
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_PRI_PER1 (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x20)
#define PRI_PER1_DOM7_LOCK_FIELD_OFFSET 31
#define PRI_PER1_DOM7_LOCK_FIELD_SIZE 1
#define PRI_PER1_DOM7_USE_PER_FIELD_OFFSET 27
#define PRI_PER1_DOM7_USE_PER_FIELD_SIZE 2
#define PRI_PER1_DOM7_PRI_PER_FIELD_OFFSET 25
#define PRI_PER1_DOM7_PRI_PER_FIELD_SIZE 2
#define PRI_PER1_DOM7_PRI_EN_FIELD_OFFSET 24
#define PRI_PER1_DOM7_PRI_EN_FIELD_SIZE 1
#define PRI_PER1_DOM6_LOCK_FIELD_OFFSET 23
#define PRI_PER1_DOM6_LOCK_FIELD_SIZE 1
#define PRI_PER1_DOM6_USE_PER_FIELD_OFFSET 19
#define PRI_PER1_DOM6_USE_PER_FIELD_SIZE 2
#define PRI_PER1_DOM6_PRI_PER_FIELD_OFFSET 17
#define PRI_PER1_DOM6_PRI_PER_FIELD_SIZE 2
#define PRI_PER1_DOM6_PRI_EN_FIELD_OFFSET 16
#define PRI_PER1_DOM6_PRI_EN_FIELD_SIZE 1
#define PRI_PER1_DOM5_LOCK_FIELD_OFFSET 15
#define PRI_PER1_DOM5_LOCK_FIELD_SIZE 1
#define PRI_PER1_DOM5_USE_PER_FIELD_OFFSET 11
#define PRI_PER1_DOM5_USE_PER_FIELD_SIZE 2
#define PRI_PER1_DOM5_PRI_PER_FIELD_OFFSET 9
#define PRI_PER1_DOM5_PRI_PER_FIELD_SIZE 2
#define PRI_PER1_DOM5_PRI_EN_FIELD_OFFSET 8
#define PRI_PER1_DOM5_PRI_EN_FIELD_SIZE 1
#define PRI_PER1_DOM4_LOCK_FIELD_OFFSET 7
#define PRI_PER1_DOM4_LOCK_FIELD_SIZE 1
#define PRI_PER1_DOM4_USE_PER_FIELD_OFFSET 3
#define PRI_PER1_DOM4_USE_PER_FIELD_SIZE 2
#define PRI_PER1_DOM4_PRI_PER_FIELD_OFFSET 1
#define PRI_PER1_DOM4_PRI_PER_FIELD_SIZE 2
#define PRI_PER1_DOM4_PRI_EN_FIELD_OFFSET 0
#define PRI_PER1_DOM4_PRI_EN_FIELD_SIZE 1

#define BIT_AP_APB_PPC_PRI_PER1_DOM7_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_PRI_PER1_DOM7_USE_PER_1    (BIT_(28))
#define BIT_AP_APB_PPC_PRI_PER1_DOM7_USE_PER_0    (BIT_(27))
#define BIT_AP_APB_PPC_PRI_PER1_DOM7_PRI_PER_1    (BIT_(26))
#define BIT_AP_APB_PPC_PRI_PER1_DOM7_PRI_PER_0    (BIT_(25))
#define BIT_AP_APB_PPC_PRI_PER1_DOM7_PRI_EN    (BIT_(24))
#define BIT_AP_APB_PPC_PRI_PER1_DOM6_LOCK    (BIT_(23))
#define BIT_AP_APB_PPC_PRI_PER1_DOM6_USE_PER_1    (BIT_(20))
#define BIT_AP_APB_PPC_PRI_PER1_DOM6_USE_PER_0    (BIT_(19))
#define BIT_AP_APB_PPC_PRI_PER1_DOM6_PRI_PER_1    (BIT_(18))
#define BIT_AP_APB_PPC_PRI_PER1_DOM6_PRI_PER_0    (BIT_(17))
#define BIT_AP_APB_PPC_PRI_PER1_DOM6_PRI_EN    (BIT_(16))
#define BIT_AP_APB_PPC_PRI_PER1_DOM5_LOCK    (BIT_(15))
#define BIT_AP_APB_PPC_PRI_PER1_DOM5_USE_PER_1    (BIT_(12))
#define BIT_AP_APB_PPC_PRI_PER1_DOM5_USE_PER_0    (BIT_(11))
#define BIT_AP_APB_PPC_PRI_PER1_DOM5_PRI_PER_1    (BIT_(10))
#define BIT_AP_APB_PPC_PRI_PER1_DOM5_PRI_PER_0    (BIT_(9))
#define BIT_AP_APB_PPC_PRI_PER1_DOM5_PRI_EN    (BIT_(8))
#define BIT_AP_APB_PPC_PRI_PER1_DOM4_LOCK    (BIT_(7))
#define BIT_AP_APB_PPC_PRI_PER1_DOM4_USE_PER_1    (BIT_(4))
#define BIT_AP_APB_PPC_PRI_PER1_DOM4_USE_PER_0    (BIT_(3))
#define BIT_AP_APB_PPC_PRI_PER1_DOM4_PRI_PER_1    (BIT_(2))
#define BIT_AP_APB_PPC_PRI_PER1_DOM4_PRI_PER_0    (BIT_(1))
#define BIT_AP_APB_PPC_PRI_PER1_DOM4_PRI_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_PRI_PER2
// Register Offset : 0x24
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_PRI_PER2 (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x24)
#define PRI_PER2_DOM11_LOCK_FIELD_OFFSET 31
#define PRI_PER2_DOM11_LOCK_FIELD_SIZE 1
#define PRI_PER2_DOM11_USE_PER_FIELD_OFFSET 27
#define PRI_PER2_DOM11_USE_PER_FIELD_SIZE 2
#define PRI_PER2_DOM11_PRI_PER_FIELD_OFFSET 25
#define PRI_PER2_DOM11_PRI_PER_FIELD_SIZE 2
#define PRI_PER2_DOM11_PRI_EN_FIELD_OFFSET 24
#define PRI_PER2_DOM11_PRI_EN_FIELD_SIZE 1
#define PRI_PER2_DOM10_LOCK_FIELD_OFFSET 23
#define PRI_PER2_DOM10_LOCK_FIELD_SIZE 1
#define PRI_PER2_DOM10_USE_PER_FIELD_OFFSET 19
#define PRI_PER2_DOM10_USE_PER_FIELD_SIZE 2
#define PRI_PER2_DOM10_PRI_PER_FIELD_OFFSET 17
#define PRI_PER2_DOM10_PRI_PER_FIELD_SIZE 2
#define PRI_PER2_DOM10_PRI_EN_FIELD_OFFSET 16
#define PRI_PER2_DOM10_PRI_EN_FIELD_SIZE 1
#define PRI_PER2_DOM9_LOCK_FIELD_OFFSET 15
#define PRI_PER2_DOM9_LOCK_FIELD_SIZE 1
#define PRI_PER2_DOM9_USE_PER_FIELD_OFFSET 11
#define PRI_PER2_DOM9_USE_PER_FIELD_SIZE 2
#define PRI_PER2_DOM9_PRI_PER_FIELD_OFFSET 9
#define PRI_PER2_DOM9_PRI_PER_FIELD_SIZE 2
#define PRI_PER2_DOM9_PRI_EN_FIELD_OFFSET 8
#define PRI_PER2_DOM9_PRI_EN_FIELD_SIZE 1
#define PRI_PER2_DOM8_LOCK_FIELD_OFFSET 7
#define PRI_PER2_DOM8_LOCK_FIELD_SIZE 1
#define PRI_PER2_DOM8_USE_PER_FIELD_OFFSET 3
#define PRI_PER2_DOM8_USE_PER_FIELD_SIZE 2
#define PRI_PER2_DOM8_PRI_PER_FIELD_OFFSET 1
#define PRI_PER2_DOM8_PRI_PER_FIELD_SIZE 2
#define PRI_PER2_DOM8_PRI_EN_FIELD_OFFSET 0
#define PRI_PER2_DOM8_PRI_EN_FIELD_SIZE 1

#define BIT_AP_APB_PPC_PRI_PER2_DOM11_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_PRI_PER2_DOM11_USE_PER_1    (BIT_(28))
#define BIT_AP_APB_PPC_PRI_PER2_DOM11_USE_PER_0    (BIT_(27))
#define BIT_AP_APB_PPC_PRI_PER2_DOM11_PRI_PER_1    (BIT_(26))
#define BIT_AP_APB_PPC_PRI_PER2_DOM11_PRI_PER_0    (BIT_(25))
#define BIT_AP_APB_PPC_PRI_PER2_DOM11_PRI_EN    (BIT_(24))
#define BIT_AP_APB_PPC_PRI_PER2_DOM10_LOCK    (BIT_(23))
#define BIT_AP_APB_PPC_PRI_PER2_DOM10_USE_PER_1    (BIT_(20))
#define BIT_AP_APB_PPC_PRI_PER2_DOM10_USE_PER_0    (BIT_(19))
#define BIT_AP_APB_PPC_PRI_PER2_DOM10_PRI_PER_1    (BIT_(18))
#define BIT_AP_APB_PPC_PRI_PER2_DOM10_PRI_PER_0    (BIT_(17))
#define BIT_AP_APB_PPC_PRI_PER2_DOM10_PRI_EN    (BIT_(16))
#define BIT_AP_APB_PPC_PRI_PER2_DOM9_LOCK    (BIT_(15))
#define BIT_AP_APB_PPC_PRI_PER2_DOM9_USE_PER_1    (BIT_(12))
#define BIT_AP_APB_PPC_PRI_PER2_DOM9_USE_PER_0    (BIT_(11))
#define BIT_AP_APB_PPC_PRI_PER2_DOM9_PRI_PER_1    (BIT_(10))
#define BIT_AP_APB_PPC_PRI_PER2_DOM9_PRI_PER_0    (BIT_(9))
#define BIT_AP_APB_PPC_PRI_PER2_DOM9_PRI_EN    (BIT_(8))
#define BIT_AP_APB_PPC_PRI_PER2_DOM8_LOCK    (BIT_(7))
#define BIT_AP_APB_PPC_PRI_PER2_DOM8_USE_PER_1    (BIT_(4))
#define BIT_AP_APB_PPC_PRI_PER2_DOM8_USE_PER_0    (BIT_(3))
#define BIT_AP_APB_PPC_PRI_PER2_DOM8_PRI_PER_1    (BIT_(2))
#define BIT_AP_APB_PPC_PRI_PER2_DOM8_PRI_PER_0    (BIT_(1))
#define BIT_AP_APB_PPC_PRI_PER2_DOM8_PRI_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_PRI_PER3
// Register Offset : 0x28
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_PRI_PER3 (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x28)
#define PRI_PER3_DOM15_LOCK_FIELD_OFFSET 31
#define PRI_PER3_DOM15_LOCK_FIELD_SIZE 1
#define PRI_PER3_DOM15_USE_PER_FIELD_OFFSET 27
#define PRI_PER3_DOM15_USE_PER_FIELD_SIZE 2
#define PRI_PER3_DOM15_PRI_PER_FIELD_OFFSET 25
#define PRI_PER3_DOM15_PRI_PER_FIELD_SIZE 2
#define PRI_PER3_DOM15_PRI_EN_FIELD_OFFSET 24
#define PRI_PER3_DOM15_PRI_EN_FIELD_SIZE 1
#define PRI_PER3_DOM14_LOCK_FIELD_OFFSET 23
#define PRI_PER3_DOM14_LOCK_FIELD_SIZE 1
#define PRI_PER3_DOM14_USE_PER_FIELD_OFFSET 19
#define PRI_PER3_DOM14_USE_PER_FIELD_SIZE 2
#define PRI_PER3_DOM14_PRI_PER_FIELD_OFFSET 17
#define PRI_PER3_DOM14_PRI_PER_FIELD_SIZE 2
#define PRI_PER3_DOM14_PRI_EN_FIELD_OFFSET 16
#define PRI_PER3_DOM14_PRI_EN_FIELD_SIZE 1
#define PRI_PER3_DOM13_LOCK_FIELD_OFFSET 15
#define PRI_PER3_DOM13_LOCK_FIELD_SIZE 1
#define PRI_PER3_DOM13_USE_PER_FIELD_OFFSET 11
#define PRI_PER3_DOM13_USE_PER_FIELD_SIZE 2
#define PRI_PER3_DOM13_PRI_PER_FIELD_OFFSET 9
#define PRI_PER3_DOM13_PRI_PER_FIELD_SIZE 2
#define PRI_PER3_DOM13_PRI_EN_FIELD_OFFSET 8
#define PRI_PER3_DOM13_PRI_EN_FIELD_SIZE 1
#define PRI_PER3_DOM12_LOCK_FIELD_OFFSET 7
#define PRI_PER3_DOM12_LOCK_FIELD_SIZE 1
#define PRI_PER3_DOM12_USE_PER_FIELD_OFFSET 3
#define PRI_PER3_DOM12_USE_PER_FIELD_SIZE 2
#define PRI_PER3_DOM12_PRI_PER_FIELD_OFFSET 1
#define PRI_PER3_DOM12_PRI_PER_FIELD_SIZE 2
#define PRI_PER3_DOM12_PRI_EN_FIELD_OFFSET 0
#define PRI_PER3_DOM12_PRI_EN_FIELD_SIZE 1

#define BIT_AP_APB_PPC_PRI_PER3_DOM15_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_PRI_PER3_DOM15_USE_PER_1    (BIT_(28))
#define BIT_AP_APB_PPC_PRI_PER3_DOM15_USE_PER_0    (BIT_(27))
#define BIT_AP_APB_PPC_PRI_PER3_DOM15_PRI_PER_1    (BIT_(26))
#define BIT_AP_APB_PPC_PRI_PER3_DOM15_PRI_PER_0    (BIT_(25))
#define BIT_AP_APB_PPC_PRI_PER3_DOM15_PRI_EN    (BIT_(24))
#define BIT_AP_APB_PPC_PRI_PER3_DOM14_LOCK    (BIT_(23))
#define BIT_AP_APB_PPC_PRI_PER3_DOM14_USE_PER_1    (BIT_(20))
#define BIT_AP_APB_PPC_PRI_PER3_DOM14_USE_PER_0    (BIT_(19))
#define BIT_AP_APB_PPC_PRI_PER3_DOM14_PRI_PER_1    (BIT_(18))
#define BIT_AP_APB_PPC_PRI_PER3_DOM14_PRI_PER_0    (BIT_(17))
#define BIT_AP_APB_PPC_PRI_PER3_DOM14_PRI_EN    (BIT_(16))
#define BIT_AP_APB_PPC_PRI_PER3_DOM13_LOCK    (BIT_(15))
#define BIT_AP_APB_PPC_PRI_PER3_DOM13_USE_PER_1    (BIT_(12))
#define BIT_AP_APB_PPC_PRI_PER3_DOM13_USE_PER_0    (BIT_(11))
#define BIT_AP_APB_PPC_PRI_PER3_DOM13_PRI_PER_1    (BIT_(10))
#define BIT_AP_APB_PPC_PRI_PER3_DOM13_PRI_PER_0    (BIT_(9))
#define BIT_AP_APB_PPC_PRI_PER3_DOM13_PRI_EN    (BIT_(8))
#define BIT_AP_APB_PPC_PRI_PER3_DOM12_LOCK    (BIT_(7))
#define BIT_AP_APB_PPC_PRI_PER3_DOM12_USE_PER_1    (BIT_(4))
#define BIT_AP_APB_PPC_PRI_PER3_DOM12_USE_PER_0    (BIT_(3))
#define BIT_AP_APB_PPC_PRI_PER3_DOM12_PRI_PER_1    (BIT_(2))
#define BIT_AP_APB_PPC_PRI_PER3_DOM12_PRI_PER_0    (BIT_(1))
#define BIT_AP_APB_PPC_PRI_PER3_DOM12_PRI_EN    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_DOM_ASSIGN
// Register Offset : 0x34
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_DOM_ASSIGN (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x34)
#define DOM_ASSIGN_DID_FIELD_OFFSET 0
#define DOM_ASSIGN_DID_FIELD_SIZE 4

#define BIT_AP_APB_PPC_DOM_ASSIGN_DID_3    (BIT_(3))
#define BIT_AP_APB_PPC_DOM_ASSIGN_DID_2    (BIT_(2))
#define BIT_AP_APB_PPC_DOM_ASSIGN_DID_1    (BIT_(1))
#define BIT_AP_APB_PPC_DOM_ASSIGN_DID_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_RGN_START_ADDR
// Register Offset : 0x1400
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_RGN_START_ADDR (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x1400)
#define RGN_START_ADDR_START_ADDR_FIELD_OFFSET 0
#define RGN_START_ADDR_START_ADDR_FIELD_SIZE 30

#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_29    (BIT_(29))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_28    (BIT_(28))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_27    (BIT_(27))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_26    (BIT_(26))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_25    (BIT_(25))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_24    (BIT_(24))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_23    (BIT_(23))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_22    (BIT_(22))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_21    (BIT_(21))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_20    (BIT_(20))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_19    (BIT_(19))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_18    (BIT_(18))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_17    (BIT_(17))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_16    (BIT_(16))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_15    (BIT_(15))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_14    (BIT_(14))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_13    (BIT_(13))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_12    (BIT_(12))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_11    (BIT_(11))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_10    (BIT_(10))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_9    (BIT_(9))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_8    (BIT_(8))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_7    (BIT_(7))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_6    (BIT_(6))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_5    (BIT_(5))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_4    (BIT_(4))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_3    (BIT_(3))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_2    (BIT_(2))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_1    (BIT_(1))
#define BIT_AP_APB_PPC_RGN_START_ADDR_START_ADDR_0    (BIT_(0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_PPC_RGN_END_ADDR
// Register Offset : 0x1404
// Description     :
//--------------------------------------------------------------------------
#define REG_AP_APB_PPC_RGN_END_ADDR (PPC_APB_PPC_APB_AB0_BASE_ADDR + 0x1404)
#define RGN_END_ADDR_LOCK_FIELD_OFFSET 31
#define RGN_END_ADDR_LOCK_FIELD_SIZE 1
#define RGN_END_ADDR_RGN_EN_FIELD_OFFSET 30
#define RGN_END_ADDR_RGN_EN_FIELD_SIZE 1
#define RGN_END_ADDR_END_ADDR_FIELD_OFFSET 0
#define RGN_END_ADDR_END_ADDR_FIELD_SIZE 30

#define BIT_AP_APB_PPC_RGN_END_ADDR_LOCK    (BIT_(31))
#define BIT_AP_APB_PPC_RGN_END_ADDR_RGN_EN    (BIT_(30))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_29    (BIT_(29))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_28    (BIT_(28))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_27    (BIT_(27))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_26    (BIT_(26))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_25    (BIT_(25))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_24    (BIT_(24))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_23    (BIT_(23))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_22    (BIT_(22))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_21    (BIT_(21))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_20    (BIT_(20))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_19    (BIT_(19))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_18    (BIT_(18))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_17    (BIT_(17))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_16    (BIT_(16))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_15    (BIT_(15))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_14    (BIT_(14))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_13    (BIT_(13))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_12    (BIT_(12))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_11    (BIT_(11))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_10    (BIT_(10))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_9    (BIT_(9))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_8    (BIT_(8))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_7    (BIT_(7))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_6    (BIT_(6))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_5    (BIT_(5))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_4    (BIT_(4))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_3    (BIT_(3))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_2    (BIT_(2))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_1    (BIT_(1))
#define BIT_AP_APB_PPC_RGN_END_ADDR_END_ADDR_0    (BIT_(0))



#endif
