/*
 * Copyright (c) Semidrive
 */

#ifndef _FW_REG_H
#define _FW_REG_H

#include <debug.h>
#include "__regs_ap_mpc.h"

#include <lib/sd_sysdef.h>

#define REG(x)                            (x)
#define MASTER_ID_SIZE                    MAC_MASTER_COUNT / 32
#define REG_SIZE                          0x4
#define DOM_MAX_COUNT                     16

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC/PPC/RPC_DOM
// Register Offset : 0x0
// Description     : register structure are the same, use unified shift/mask
//--------------------------------------------------------------------------
#define DOM_LOCK_SHIFT                  DOM_LOCK_FIELD_OFFSET
#define DOM_LOCK_MASK                   1UL << DOM_LOCK_SHIFT
#define DOM_SET_SHIFT                   DOM_SET_FIELD_OFFSET
#define DOM_SET_MASK                    1UL << DOM_SET_SHIFT
#define DOM_DID_SHIFT                   DOM_DID_FIELD_OFFSET
#define DOM_DID_MASK                    0xF << DOM_DID_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC/PPC/RPC_DOM_PER0
// Register Offset : 0x4
// Description     : register structure are the same, use unified shift/mask
//--------------------------------------------------------------------------
#define DOM_PER0_DOM7_LOCK_SHIFT        DOM_PER0_DOM7_LOCK_FIELD_OFFSET
#define DOM_PER0_DOM7_LOCK_MASK         1UL << DOM_PER0_DOM7_LOCK_SHIFT
#define DOM_PER0_DOM7_PER_SHIFT         DOM_PER0_DOM7_PER_FIELD_OFFSET
#define DOM_PER0_DOM7_PER_MASK          3UL << DOM_PER0_DOM7_PER_SHIFT
#define DOM_PER0_DOM7_EN_SHIFT          DOM_PER0_DOM7_EN_FIELD_OFFSET
#define DOM_PER0_DOM7_EN_MASK           1UL << DOM_PER0_DOM7_EN_SHIFT
#define DOM_PER0_DOM6_LOCK_SHIFT        DOM_PER0_DOM6_LOCK_FIELD_OFFSET
#define DOM_PER0_DOM6_LOCK_MASK         1UL << DOM_PER0_DOM6_LOCK_SHIFT
#define DOM_PER0_DOM6_PER_SHIFT         DOM_PER0_DOM6_PER_FIELD_OFFSET
#define DOM_PER0_DOM6_PER_MASK          3UL << DOM_PER0_DOM6_PER_SHIFT
#define DOM_PER0_DOM6_EN_SHIFT          DOM_PER0_DOM6_EN_FIELD_OFFSET
#define DOM_PER0_DOM6_EN_MASK           1UL << DOM_PER0_DOM6_EN_SHIFT
#define DOM_PER0_DOM5_LOCK_SHIFT        DOM_PER0_DOM5_LOCK_FIELD_OFFSET
#define DOM_PER0_DOM5_LOCK_MASK         1UL << DOM_PER0_DOM5_LOCK_SHIFT
#define DOM_PER0_DOM5_PER_SHIFT         DOM_PER0_DOM5_PER_FIELD_OFFSET
#define DOM_PER0_DOM5_PER_MASK          3UL << DOM_PER0_DOM5_PER_SHIFT
#define DOM_PER0_DOM5_EN_SHIFT          DOM_PER0_DOM5_EN_FIELD_OFFSET
#define DOM_PER0_DOM5_EN_MASK           1UL << DOM_PER0_DOM5_EN_SHIFT
#define DOM_PER0_DOM4_LOCK_SHIFT        DOM_PER0_DOM4_LOCK_FIELD_OFFSET
#define DOM_PER0_DOM4_LOCK_MASK         1UL << DOM_PER0_DOM4_LOCK_SHIFT
#define DOM_PER0_DOM4_PER_SHIFT         DOM_PER0_DOM4_PER_FIELD_OFFSET
#define DOM_PER0_DOM4_PER_MASK          3UL << DOM_PER0_DOM4_PER_SHIFT
#define DOM_PER0_DOM4_EN_SHIFT          DOM_PER0_DOM4_EN_FIELD_OFFSET
#define DOM_PER0_DOM4_EN_MASK           1UL << DOM_PER0_DOM4_EN_SHIFT
#define DOM_PER0_DOM3_LOCK_SHIFT        DOM_PER0_DOM3_LOCK_FIELD_OFFSET
#define DOM_PER0_DOM3_LOCK_MASK         1UL << DOM_PER0_DOM3_LOCK_SHIFT
#define DOM_PER0_DOM3_PER_SHIFT         DOM_PER0_DOM3_PER_FIELD_OFFSET
#define DOM_PER0_DOM3_PER_MASK          3UL << DOM_PER0_DOM3_PER_SHIFT
#define DOM_PER0_DOM3_EN_SHIFT          DOM_PER0_DOM3_EN_FIELD_OFFSET
#define DOM_PER0_DOM3_EN_MASK           1UL << DOM_PER0_DOM3_EN_SHIFT
#define DOM_PER0_DOM2_LOCK_SHIFT        DOM_PER0_DOM2_LOCK_FIELD_OFFSET
#define DOM_PER0_DOM2_LOCK_MASK         1UL << DOM_PER0_DOM2_LOCK_SHIFT
#define DOM_PER0_DOM2_PER_SHIFT         DOM_PER0_DOM2_PER_FIELD_OFFSET
#define DOM_PER0_DOM2_PER_MASK          3UL << DOM_PER0_DOM2_PER_SHIFT
#define DOM_PER0_DOM2_EN_SHIFT          DOM_PER0_DOM2_EN_FIELD_OFFSET
#define DOM_PER0_DOM2_EN_MASK           1UL << DOM_PER0_DOM2_EN_SHIFT
#define DOM_PER0_DOM1_LOCK_SHIFT        DOM_PER0_DOM1_LOCK_FIELD_OFFSET
#define DOM_PER0_DOM1_LOCK_MASK         1UL << DOM_PER0_DOM1_LOCK_SHIFT
#define DOM_PER0_DOM1_PER_SHIFT         DOM_PER0_DOM1_PER_FIELD_OFFSET
#define DOM_PER0_DOM1_PER_MASK          3UL << DOM_PER0_DOM1_PER_SHIFT
#define DOM_PER0_DOM1_EN_SHIFT          DOM_PER0_DOM1_EN_FIELD_OFFSET
#define DOM_PER0_DOM1_EN_MASK           1UL << DOM_PER0_DOM1_EN_SHIFT
#define DOM_PER0_DOM0_LOCK_SHIFT        DOM_PER0_DOM0_LOCK_FIELD_OFFSET
#define DOM_PER0_DOM0_LOCK_MASK         1UL << DOM_PER0_DOM0_LOCK_SHIFT
#define DOM_PER0_DOM0_PER_SHIFT         DOM_PER0_DOM0_PER_FIELD_OFFSET
#define DOM_PER0_DOM0_PER_MASK          3UL << DOM_PER0_DOM0_PER_SHIFT
#define DOM_PER0_DOM0_EN_SHIFT          DOM_PER0_DOM0_EN_FIELD_OFFSET
#define DOM_PER0_DOM0_EN_MASK           1UL << DOM_PER0_DOM0_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC/PPC/RPC_DOM_PER1
// Register Offset : 0x8
// Description     : register structure are the same, use unified shift/mask
//--------------------------------------------------------------------------
#define DOM_PER1_DOM15_LOCK_SHIFT       DOM_PER1_DOM15_LOCK_FIELD_OFFSET
#define DOM_PER1_DOM15_LOCK_MASK        1UL << DOM_PER1_DOM15_LOCK_SHIFT
#define DOM_PER1_DOM15_PER_SHIFT        DOM_PER1_DOM15_PER_FIELD_OFFSET
#define DOM_PER1_DOM15_PER_MASK         3UL << DOM_PER1_DOM15_PER_SHIFT
#define DOM_PER1_DOM15_EN_SHIFT         DOM_PER1_DOM15_EN_FIELD_OFFSET
#define DOM_PER1_DOM15_EN_MASK          1UL << DOM_PER1_DOM15_EN_SHIFT
#define DOM_PER1_DOM14_LOCK_SHIFT       DOM_PER1_DOM14_LOCK_FIELD_OFFSET
#define DOM_PER1_DOM14_LOCK_MASK        1UL << DOM_PER1_DOM14_LOCK_SHIFT
#define DOM_PER1_DOM14_PER_SHIFT        DOM_PER1_DOM14_PER_FIELD_OFFSET
#define DOM_PER1_DOM14_PER_MASK         3UL << DOM_PER1_DOM14_PER_SHIFT
#define DOM_PER1_DOM14_EN_SHIFT         DOM_PER1_DOM14_EN_FIELD_OFFSET
#define DOM_PER1_DOM14_EN_MASK          1UL << DOM_PER1_DOM14_EN_SHIFT
#define DOM_PER1_DOM13_LOCK_SHIFT       DOM_PER1_DOM13_LOCK_FIELD_OFFSET
#define DOM_PER1_DOM13_LOCK_MASK        1UL << DOM_PER1_DOM13_LOCK_SHIFT
#define DOM_PER1_DOM13_PER_SHIFT        DOM_PER1_DOM13_PER_FIELD_OFFSET
#define DOM_PER1_DOM13_PER_MASK         3UL << DOM_PER1_DOM13_PER_SHIFT
#define DOM_PER1_DOM13_EN_SHIFT         DOM_PER1_DOM13_EN_FIELD_OFFSET
#define DOM_PER1_DOM13_EN_MASK          1UL << DOM_PER1_DOM13_EN_SHIFT
#define DOM_PER1_DOM12_LOCK_SHIFT       DOM_PER1_DOM12_LOCK_FIELD_OFFSET
#define DOM_PER1_DOM12_LOCK_MASK        1UL << DOM_PER1_DOM12_LOCK_SHIFT
#define DOM_PER1_DOM12_PER_SHIFT        DOM_PER1_DOM12_PER_FIELD_OFFSET
#define DOM_PER1_DOM12_PER_MASK         3UL << DOM_PER1_DOM12_PER_SHIFT
#define DOM_PER1_DOM12_EN_SHIFT         DOM_PER1_DOM12_EN_FIELD_OFFSET
#define DOM_PER1_DOM12_EN_MASK          1UL << DOM_PER1_DOM12_EN_SHIFT
#define DOM_PER1_DOM11_LOCK_SHIFT       DOM_PER1_DOM11_LOCK_FIELD_OFFSET
#define DOM_PER1_DOM11_LOCK_MASK        1UL << DOM_PER1_DOM11_LOCK_SHIFT
#define DOM_PER1_DOM11_PER_SHIFT        DOM_PER1_DOM11_PER_FIELD_OFFSET
#define DOM_PER1_DOM11_PER_MASK         3UL << DOM_PER1_DOM11_PER_SHIFT
#define DOM_PER1_DOM11_EN_SHIFT         DOM_PER1_DOM11_EN_FIELD_OFFSET
#define DOM_PER1_DOM11_EN_MASK          1UL << DOM_PER1_DOM11_EN_SHIFT
#define DOM_PER1_DOM10_LOCK_SHIFT       DOM_PER1_DOM10_LOCK_FIELD_OFFSET
#define DOM_PER1_DOM10_LOCK_MASK        1UL << DOM_PER1_DOM10_LOCK_SHIFT
#define DOM_PER1_DOM10_PER_SHIFT        DOM_PER1_DOM10_PER_FIELD_OFFSET
#define DOM_PER1_DOM10_PER_MASK         3UL << DOM_PER1_DOM10_PER_SHIFT
#define DOM_PER1_DOM10_EN_SHIFT         DOM_PER1_DOM10_EN_FIELD_OFFSET
#define DOM_PER1_DOM10_EN_MASK          1UL << DOM_PER1_DOM10_EN_SHIFT
#define DOM_PER1_DOM9_LOCK_SHIFT        DOM_PER1_DOM9_LOCK_FIELD_OFFSET
#define DOM_PER1_DOM9_LOCK_MASK         1UL << DOM_PER1_DOM9_LOCK_SHIFT
#define DOM_PER1_DOM9_PER_SHIFT         DOM_PER1_DOM9_PER_FIELD_OFFSET
#define DOM_PER1_DOM9_PER_MASK          3UL << DOM_PER1_DOM9_PER_SHIFT
#define DOM_PER1_DOM9_EN_SHIFT          DOM_PER1_DOM9_EN_FIELD_OFFSET
#define DOM_PER1_DOM9_EN_MASK           1UL << DOM_PER1_DOM9_EN_SHIFT
#define DOM_PER1_DOM8_LOCK_SHIFT        DOM_PER1_DOM8_LOCK_FIELD_OFFSET
#define DOM_PER1_DOM8_LOCK_MASK         1UL << DOM_PER1_DOM8_LOCK_SHIFT
#define DOM_PER1_DOM8_PER_SHIFT         DOM_PER1_DOM8_PER_FIELD_OFFSET
#define DOM_PER1_DOM8_PER_MASK          3UL << DOM_PER1_DOM8_PER_SHIFT
#define DOM_PER1_DOM8_EN_SHIFT          DOM_PER1_DOM8_EN_FIELD_OFFSET
#define DOM_PER1_DOM8_EN_MASK           1UL << DOM_PER1_DOM8_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC/PPC/RPC_SEC_PER0
// Register Offset : 0xc
// Description     : register structure are the same, use unified shift/mask
//--------------------------------------------------------------------------
#define SEC_PER0_DOM3_LOCK_SHIFT        SEC_PER0_DOM3_LOCK_FIELD_OFFSET
#define SEC_PER0_DOM3_LOCK_MASK         1UL << SEC_PER0_DOM3_LOCK_SHIFT
#define SEC_PER0_DOM3_NSE_PER_SHIFT     SEC_PER0_DOM3_NSE_PER_FIELD_OFFSET
#define SEC_PER0_DOM3_NSE_PER_MASK      3UL << SEC_PER0_DOM3_NSE_PER_SHIFT
#define SEC_PER0_DOM3_SEC_PER_SHIFT     SEC_PER0_DOM3_SEC_PER_FIELD_OFFSET
#define SEC_PER0_DOM3_SEC_PER_MASK      3UL << SEC_PER0_DOM3_SEC_PER_SHIFT
#define SEC_PER0_DOM3_SEC_EN_SHIFT      SEC_PER0_DOM3_SEC_EN_FIELD_OFFSET
#define SEC_PER0_DOM3_SEC_EN_MASK       1UL << SEC_PER0_DOM3_SEC_EN_SHIFT
#define SEC_PER0_DOM2_LOCK_SHIFT        SEC_PER0_DOM2_LOCK_FIELD_OFFSET
#define SEC_PER0_DOM2_LOCK_MASK         1UL << SEC_PER0_DOM2_LOCK_SHIFT
#define SEC_PER0_DOM2_NSE_PER_SHIFT     SEC_PER0_DOM2_NSE_PER_FIELD_OFFSET
#define SEC_PER0_DOM2_NSE_PER_MASK      3UL << SEC_PER0_DOM2_NSE_PER_SHIFT
#define SEC_PER0_DOM2_SEC_PER_SHIFT     SEC_PER0_DOM2_SEC_PER_FIELD_OFFSET
#define SEC_PER0_DOM2_SEC_PER_MASK      3UL << SEC_PER0_DOM2_SEC_PER_SHIFT
#define SEC_PER0_DOM2_SEC_EN_SHIFT      SEC_PER0_DOM2_SEC_EN_FIELD_OFFSET
#define SEC_PER0_DOM2_SEC_EN_MASK       1UL << SEC_PER0_DOM2_SEC_EN_SHIFT
#define SEC_PER0_DOM1_LOCK_SHIFT        SEC_PER0_DOM1_LOCK_FIELD_OFFSET
#define SEC_PER0_DOM1_LOCK_MASK         1UL << SEC_PER0_DOM1_LOCK_SHIFT
#define SEC_PER0_DOM1_NSE_PER_SHIFT     SEC_PER0_DOM1_NSE_PER_FIELD_OFFSET
#define SEC_PER0_DOM1_NSE_PER_MASK      3UL << SEC_PER0_DOM1_NSE_PER_SHIFT
#define SEC_PER0_DOM1_SEC_PER_SHIFT     SEC_PER0_DOM1_SEC_PER_FIELD_OFFSET
#define SEC_PER0_DOM1_SEC_PER_MASK      3UL << SEC_PER0_DOM1_SEC_PER_SHIFT
#define SEC_PER0_DOM1_SEC_EN_SHIFT      SEC_PER0_DOM1_SEC_EN_FIELD_OFFSET
#define SEC_PER0_DOM1_SEC_EN_MASK       1UL << SEC_PER0_DOM1_SEC_EN_SHIFT
#define SEC_PER0_DOM0_LOCK_SHIFT        SEC_PER0_DOM0_LOCK_FIELD_OFFSET
#define SEC_PER0_DOM0_LOCK_MASK         1UL << SEC_PER0_DOM0_LOCK_SHIFT
#define SEC_PER0_DOM0_NSE_PER_SHIFT     SEC_PER0_DOM0_NSE_PER_FIELD_OFFSET
#define SEC_PER0_DOM0_NSE_PER_MASK      3UL << SEC_PER0_DOM0_NSE_PER_SHIFT
#define SEC_PER0_DOM0_SEC_PER_SHIFT     SEC_PER0_DOM0_SEC_PER_FIELD_OFFSET
#define SEC_PER0_DOM0_SEC_PER_MASK      3UL << SEC_PER0_DOM0_SEC_PER_SHIFT
#define SEC_PER0_DOM0_SEC_EN_SHIFT      SEC_PER0_DOM0_SEC_EN_FIELD_OFFSET
#define SEC_PER0_DOM0_SEC_EN_MASK       1UL << SEC_PER0_DOM0_SEC_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC/PPC/RPC_SEC_PER1
// Register Offset : 0x10
// Description     : register structure are the same, use unified shift/mask
//--------------------------------------------------------------------------
#define SEC_PER1_DOM7_LOCK_SHIFT        SEC_PER1_DOM7_LOCK_FIELD_OFFSET
#define SEC_PER1_DOM7_LOCK_MASK         1UL << SEC_PER1_DOM7_LOCK_SHIFT
#define SEC_PER1_DOM7_NSE_PER_SHIFT      SEC_PER1_DOM7_NSE_PER_FIELD_OFFSET
#define SEC_PER1_DOM7_NSE_PER_MASK      3UL << SEC_PER1_DOM7_NSE_PER_SHIFT
#define SEC_PER1_DOM7_SEC_PER_SHIFT     SEC_PER1_DOM7_SEC_PER_FIELD_OFFSET
#define SEC_PER1_DOM7_SEC_PER_MASK      3UL << SEC_PER1_DOM7_SEC_PER_SHIFT
#define SEC_PER1_DOM7_SEC_EN_SHIFT      SEC_PER1_DOM7_SEC_EN_FIELD_OFFSET
#define SEC_PER1_DOM7_SEC_EN_MASK       1UL << SEC_PER1_DOM7_SEC_EN_SHIFT
#define SEC_PER1_DOM6_LOCK_SHIFT        SEC_PER1_DOM6_LOCK_FIELD_OFFSET
#define SEC_PER1_DOM6_LOCK_MASK         1UL << SEC_PER1_DOM6_LOCK_SHIFT
#define SEC_PER1_DOM6_NSE_PER_SHIFT     SEC_PER1_DOM6_NSE_PER_FIELD_OFFSET
#define SEC_PER1_DOM6_NSE_PER_MASK      3UL << SEC_PER1_DOM6_NSE_PER_SHIFT
#define SEC_PER1_DOM6_SEC_PER_SHIFT     SEC_PER1_DOM6_SEC_PER_FIELD_OFFSET
#define SEC_PER1_DOM6_SEC_PER_MASK      3UL << SEC_PER1_DOM6_SEC_PER_SHIFT
#define SEC_PER1_DOM6_SEC_EN_SHIFT      SEC_PER1_DOM6_SEC_EN_FIELD_OFFSET
#define SEC_PER1_DOM6_SEC_EN_MASK       1UL << SEC_PER1_DOM6_SEC_EN_SHIFT
#define SEC_PER1_DOM5_LOCK_SHIFT        SEC_PER1_DOM5_LOCK_FIELD_OFFSET
#define SEC_PER1_DOM5_LOCK_MASK         1UL << SEC_PER1_DOM5_LOCK_SHIFT
#define SEC_PER1_DOM5_NSE_PER_SHIFT     SEC_PER1_DOM5_NSE_PER_FIELD_OFFSET
#define SEC_PER1_DOM5_NSE_PER_MASK      3UL << SEC_PER1_DOM5_NSE_PER_SHIFT
#define SEC_PER1_DOM5_SEC_PER_SHIFT     SEC_PER1_DOM5_SEC_PER_FIELD_OFFSET
#define SEC_PER1_DOM5_SEC_PER_MASK      3UL << SEC_PER1_DOM5_SEC_PER_SHIFT
#define SEC_PER1_DOM5_SEC_EN_SHIFT      SEC_PER1_DOM5_SEC_EN_FIELD_OFFSET
#define SEC_PER1_DOM5_SEC_EN_MASK       1UL << SEC_PER1_DOM5_SEC_EN_SHIFT
#define SEC_PER1_DOM4_LOCK_SHIFT        SEC_PER1_DOM4_LOCK_FIELD_OFFSET
#define SEC_PER1_DOM4_LOCK_MASK         1UL << SEC_PER1_DOM4_LOCK_SHIFT
#define SEC_PER1_DOM4_NSE_PER_SHIFT     SEC_PER1_DOM4_NSE_PER_FIELD_OFFSET
#define SEC_PER1_DOM4_NSE_PER_MASK      3UL << SEC_PER1_DOM4_NSE_PER_SHIFT
#define SEC_PER1_DOM4_SEC_PER_SHIFT     SEC_PER1_DOM4_SEC_PER_FIELD_OFFSET
#define SEC_PER1_DOM4_SEC_PER_MASK      3UL << SEC_PER1_DOM4_SEC_PER_SHIFT
#define SEC_PER1_DOM4_SEC_EN_SHIFT      SEC_PER1_DOM4_SEC_EN_FIELD_OFFSET
#define SEC_PER1_DOM4_SEC_EN_MASK       1UL << SEC_PER1_DOM4_SEC_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC/PPC/RPC_SEC_PER2
// Register Offset : 0x14
// Description     : register structure are the same, use unified shift/mask
//--------------------------------------------------------------------------
#define SEC_PER2_DOM11_LOCK_SHIFT       SEC_PER2_DOM11_LOCK_FIELD_OFFSET
#define SEC_PER2_DOM11_LOCK_MASK        1UL << SEC_PER2_DOM11_LOCK_SHIFT
#define SEC_PER2_DOM11_NSE_PER_SHIFT    SEC_PER2_DOM11_NSE_PER_FIELD_OFFSET
#define SEC_PER2_DOM11_NSE_PER_MASK     3UL << SEC_PER2_DOM11_NSE_PER_SHIFT
#define SEC_PER2_DOM11_SEC_PER_SHIFT    SEC_PER2_DOM11_SEC_PER_FIELD_OFFSET
#define SEC_PER2_DOM11_SEC_PER_MASK     3UL << SEC_PER2_DOM11_SEC_PER_SHIFT
#define SEC_PER2_DOM11_SEC_EN_SHIFT     SEC_PER2_DOM11_SEC_EN_FIELD_OFFSET
#define SEC_PER2_DOM11_SEC_EN_MASK      1UL << SEC_PER2_DOM11_SEC_EN_SHIFT
#define SEC_PER2_DOM10_LOCK_SHIFT       SEC_PER2_DOM10_LOCK_FIELD_OFFSET
#define SEC_PER2_DOM10_LOCK_MASK        1UL << SEC_PER2_DOM10_LOCK_SHIFT
#define SEC_PER2_DOM10_NSE_PER_SHIFT    SEC_PER2_DOM10_NSE_PER_FIELD_OFFSET
#define SEC_PER2_DOM10_NSE_PER_MASK     3UL << SEC_PER2_DOM10_NSE_PER_SHIFT
#define SEC_PER2_DOM10_SEC_PER_SHIFT    SEC_PER2_DOM10_SEC_PER_FIELD_OFFSET
#define SEC_PER2_DOM10_SEC_PER_MASK     3UL << SEC_PER2_DOM10_SEC_PER_SHIFT
#define SEC_PER2_DOM10_SEC_EN_SHIFT     SEC_PER2_DOM10_SEC_EN_FIELD_OFFSET
#define SEC_PER2_DOM10_SEC_EN_MASK      1UL << SEC_PER2_DOM10_SEC_EN_SHIFT
#define SEC_PER2_DOM9_LOCK_SHIFT        SEC_PER2_DOM9_LOCK_FIELD_OFFSET
#define SEC_PER2_DOM9_LOCK_MASK         1UL << SEC_PER2_DOM9_LOCK_SHIFT
#define SEC_PER2_DOM9_NSE_PER_SHIFT     SEC_PER2_DOM9_NSE_PER_FIELD_OFFSET
#define SEC_PER2_DOM9_NSE_PER_MASK      3UL << SEC_PER2_DOM9_NSE_PER_SHIFT
#define SEC_PER2_DOM9_SEC_PER_SHIFT     SEC_PER2_DOM9_SEC_PER_FIELD_OFFSET
#define SEC_PER2_DOM9_SEC_PER_MASK      3UL << SEC_PER2_DOM9_SEC_PER_SHIFT
#define SEC_PER2_DOM9_SEC_EN_SHIFT      SEC_PER2_DOM9_SEC_EN_FIELD_OFFSET
#define SEC_PER2_DOM9_SEC_EN_MASK       1UL << SEC_PER2_DOM9_SEC_EN_SHIFT
#define SEC_PER2_DOM8_LOCK_SHIFT        SEC_PER2_DOM8_LOCK_FIELD_OFFSET
#define SEC_PER2_DOM8_LOCK_MASK         1UL << SEC_PER2_DOM8_LOCK_SHIFT
#define SEC_PER2_DOM8_NSE_PER_SHIFT     SEC_PER2_DOM8_NSE_PER_FIELD_OFFSET
#define SEC_PER2_DOM8_NSE_PER_MASK      3UL << SEC_PER2_DOM8_NSE_PER_SHIFT
#define SEC_PER2_DOM8_SEC_PER_SHIFT     SEC_PER2_DOM8_SEC_PER_FIELD_OFFSET
#define SEC_PER2_DOM8_SEC_PER_MASK      3UL << SEC_PER2_DOM8_SEC_PER_SHIFT
#define SEC_PER2_DOM8_SEC_EN_SHIFT      SEC_PER2_DOM8_SEC_EN_FIELD_OFFSET
#define SEC_PER2_DOM8_SEC_EN_MASK       1UL << SEC_PER2_DOM8_SEC_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC/PPC/RPC_SEC_PER3
// Register Offset : 0x18
// Description     : register structure are the same, use unified shift/mask
//--------------------------------------------------------------------------
#define SEC_PER3_DOM15_LOCK_SHIFT       SEC_PER3_DOM15_LOCK_FIELD_OFFSET
#define SEC_PER3_DOM15_LOCK_MASK        1UL << SEC_PER3_DOM15_LOCK_SHIFT
#define SEC_PER3_DOM15_NSE_PER_SHIFT    SEC_PER3_DOM15_NSE_PER_FIELD_OFFSET
#define SEC_PER3_DOM15_NSE_PER_MASK     3UL << SEC_PER3_DOM15_NSE_PER_SHIFT
#define SEC_PER3_DOM15_SEC_PER_SHIFT    SEC_PER3_DOM15_SEC_PER_FIELD_OFFSET
#define SEC_PER3_DOM15_SEC_PER_MASK     3UL << SEC_PER3_DOM15_SEC_PER_SHIFT
#define SEC_PER3_DOM15_SEC_EN_SHIFT     SEC_PER3_DOM15_SEC_EN_FIELD_OFFSET
#define SEC_PER3_DOM15_SEC_EN_MASK      1UL << SEC_PER3_DOM15_SEC_EN_SHIFT
#define SEC_PER3_DOM14_LOCK_SHIFT       SEC_PER3_DOM14_LOCK_FIELD_OFFSET
#define SEC_PER3_DOM14_LOCK_MASK        1UL << SEC_PER3_DOM14_LOCK_SHIFT
#define SEC_PER3_DOM14_NSE_PER_SHIFT    SEC_PER3_DOM14_NSE_PER_FIELD_OFFSET
#define SEC_PER3_DOM14_NSE_PER_MASK     3UL << SEC_PER3_DOM14_NSE_PER_SHIFT
#define SEC_PER3_DOM14_SEC_PER_SHIFT    SEC_PER3_DOM14_SEC_PER_FIELD_OFFSET
#define SEC_PER3_DOM14_SEC_PER_MASK     3UL << SEC_PER3_DOM14_SEC_PER_SHIFT
#define SEC_PER3_DOM14_SEC_EN_SHIFT     SEC_PER3_DOM14_SEC_EN_FIELD_OFFSET
#define SEC_PER3_DOM14_SEC_EN_MASK      1UL << SEC_PER3_DOM14_SEC_EN_SHIFT
#define SEC_PER3_DOM13_LOCK_SHIFT       SEC_PER3_DOM13_LOCK_FIELD_OFFSET
#define SEC_PER3_DOM13_LOCK_MASK        1UL << SEC_PER3_DOM13_LOCK_SHIFT
#define SEC_PER3_DOM13_NSE_PER_SHIFT    SEC_PER3_DOM13_NSE_PER_FIELD_OFFSET
#define SEC_PER3_DOM13_NSE_PER_MASK     3UL << SEC_PER3_DOM13_NSE_PER_SHIFT
#define SEC_PER3_DOM13_SEC_PER_SHIFT    SEC_PER3_DOM13_SEC_PER_FIELD_OFFSET
#define SEC_PER3_DOM13_SEC_PER_MASK     3UL << SEC_PER3_DOM13_SEC_PER_SHIFT
#define SEC_PER3_DOM13_SEC_EN_SHIFT     SEC_PER3_DOM13_SEC_EN_FIELD_OFFSET
#define SEC_PER3_DOM13_SEC_EN_MASK      1UL << SEC_PER3_DOM13_SEC_EN_SHIFT
#define SEC_PER3_DOM12_LOCK_SHIFT       SEC_PER3_DOM12_LOCK_FIELD_OFFSET
#define SEC_PER3_DOM12_LOCK_MASK        1UL << SEC_PER3_DOM12_LOCK_SHIFT
#define SEC_PER3_DOM12_NSE_PER_SHIFT    SEC_PER3_DOM12_NSE_PER_FIELD_OFFSET
#define SEC_PER3_DOM12_NSE_PER_MASK     3UL << SEC_PER3_DOM12_NSE_PER_SHIFT
#define SEC_PER3_DOM12_SEC_PER_SHIFT    SEC_PER3_DOM12_SEC_PER_FIELD_OFFSET
#define SEC_PER3_DOM12_SEC_PER_MASK     3UL << SEC_PER3_DOM12_SEC_PER_SHIFT
#define SEC_PER3_DOM12_SEC_EN_SHIFT     SEC_PER3_DOM12_SEC_EN_FIELD_OFFSET
#define SEC_PER3_DOM12_SEC_EN_MASK      1UL << SEC_PER3_DOM12_SEC_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC/PPC/RPC_PRI_PER0
// Register Offset : 0x1c
// Description     : register structure are the same, use unified shift/mask
//--------------------------------------------------------------------------
#define PRI_PER0_DOM3_LOCK_SHIFT        PRI_PER0_DOM3_LOCK_FIELD_OFFSET
#define PRI_PER0_DOM3_LOCK_MASK         1UL << PRI_PER0_DOM3_LOCK_SHIFT
#define PRI_PER0_DOM3_USE_PER_SHIFT     PRI_PER0_DOM3_USE_PER_FIELD_OFFSET
#define PRI_PER0_DOM3_USE_PER_MASK      3UL << PRI_PER0_DOM3_USE_PER_SHIFT
#define PRI_PER0_DOM3_PRI_PER_SHIFT     PRI_PER0_DOM3_PRI_PER_FIELD_OFFSET
#define PRI_PER0_DOM3_PRI_PER_MASK      3UL << PRI_PER0_DOM3_PRI_PER_SHIFT
#define PRI_PER0_DOM3_PRI_EN_SHIFT      PRI_PER0_DOM3_PRI_EN_FIELD_OFFSET
#define PRI_PER0_DOM3_PRI_EN_MASK       1UL << PRI_PER0_DOM3_PRI_EN_SHIFT
#define PRI_PER0_DOM2_LOCK_SHIFT        PRI_PER0_DOM2_LOCK_FIELD_OFFSET
#define PRI_PER0_DOM2_LOCK_MASK         1UL << PRI_PER0_DOM2_LOCK_SHIFT
#define PRI_PER0_DOM2_USE_PER_SHIFT     PRI_PER0_DOM2_USE_PER_FIELD_OFFSET
#define PRI_PER0_DOM2_USE_PER_MASK      3UL << PRI_PER0_DOM2_USE_PER_SHIFT
#define PRI_PER0_DOM2_PRI_PER_SHIFT     PRI_PER0_DOM2_PRI_PER_FIELD_OFFSET
#define PRI_PER0_DOM2_PRI_PER_MASK      3UL << PRI_PER0_DOM2_PRI_PER_SHIFT
#define PRI_PER0_DOM2_PRI_EN_SHIFT      PRI_PER0_DOM2_PRI_EN_FIELD_OFFSET
#define PRI_PER0_DOM2_PRI_EN_MASK       1UL << PRI_PER0_DOM2_PRI_EN_SHIFT
#define PRI_PER0_DOM1_LOCK_SHIFT        PRI_PER0_DOM1_LOCK_FIELD_OFFSET
#define PRI_PER0_DOM1_LOCK_MASK         1UL << PRI_PER0_DOM1_LOCK_SHIFT
#define PRI_PER0_DOM1_USE_PER_SHIFT     PRI_PER0_DOM1_USE_PER_FIELD_OFFSET
#define PRI_PER0_DOM1_USE_PER_MASK      3UL << PRI_PER0_DOM1_USE_PER_SHIFT
#define PRI_PER0_DOM1_PRI_PER_SHIFT     PRI_PER0_DOM1_PRI_PER_FIELD_OFFSET
#define PRI_PER0_DOM1_PRI_PER_MASK      3UL << PRI_PER0_DOM1_PRI_PER_SHIFT
#define PRI_PER0_DOM1_PRI_EN_SHIFT      PRI_PER0_DOM1_PRI_EN_FIELD_OFFSET
#define PRI_PER0_DOM1_PRI_EN_MASK       1UL << PRI_PER0_DOM1_PRI_EN_SHIFT
#define PRI_PER0_DOM0_LOCK_SHIFT        PRI_PER0_DOM0_LOCK_FIELD_OFFSET
#define PRI_PER0_DOM0_LOCK_MASK         1UL << PRI_PER0_DOM0_LOCK_SHIFT
#define PRI_PER0_DOM0_USE_PER_SHIFT     PRI_PER0_DOM0_USE_PER_FIELD_OFFSET
#define PRI_PER0_DOM0_USE_PER_MASK      3UL << PRI_PER0_DOM0_USE_PER_SHIFT
#define PRI_PER0_DOM0_PRI_PER_SHIFT     PRI_PER0_DOM0_PRI_PER_FIELD_OFFSET
#define PRI_PER0_DOM0_PRI_PER_MASK      3UL << PRI_PER0_DOM0_PRI_PER_SHIFT
#define PRI_PER0_DOM0_PRI_EN_SHIFT      PRI_PER0_DOM0_PRI_EN_FIELD_OFFSET
#define PRI_PER0_DOM0_PRI_EN_MASK       1UL << PRI_PER0_DOM0_PRI_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC/PPC/RPC_PRI_PER1
// Register Offset : 0x20
// Description     : register structure are the same, use unified shift/mask
//--------------------------------------------------------------------------
#define PRI_PER1_DOM7_LOCK_SHIFT        PRI_PER1_DOM7_LOCK_FIELD_OFFSET
#define PRI_PER1_DOM7_LOCK_MASK         1UL << PRI_PER1_DOM7_LOCK_SHIFT
#define PRI_PER1_DOM7_USE_PER_SHIFT     PRI_PER1_DOM7_USE_PER_FIELD_OFFSET
#define PRI_PER1_DOM7_USE_PER_MASK      3UL << PRI_PER1_DOM7_USE_PER_SHIFT
#define PRI_PER1_DOM7_PRI_PER_SHIFT     PRI_PER1_DOM7_PRI_PER_FIELD_OFFSET
#define PRI_PER1_DOM7_PRI_PER_MASK      3UL << PRI_PER1_DOM7_PRI_PER_SHIFT
#define PRI_PER1_DOM7_PRI_EN_SHIFT      PRI_PER1_DOM7_PRI_EN_FIELD_OFFSET
#define PRI_PER1_DOM7_PRI_EN_MASK       1UL << PRI_PER1_DOM7_PRI_EN_SHIFT
#define PRI_PER1_DOM6_LOCK_SHIFT        PRI_PER1_DOM6_LOCK_FIELD_OFFSET
#define PRI_PER1_DOM6_LOCK_MASK         1UL << PRI_PER1_DOM6_LOCK_SHIFT
#define PRI_PER1_DOM6_USE_PER_SHIFT     PRI_PER1_DOM6_USE_PER_FIELD_OFFSET
#define PRI_PER1_DOM6_USE_PER_MASK      3UL << PRI_PER1_DOM6_USE_PER_SHIFT
#define PRI_PER1_DOM6_PRI_PER_SHIFT     PRI_PER1_DOM6_PRI_PER_FIELD_OFFSET
#define PRI_PER1_DOM6_PRI_PER_MASK      3UL << PRI_PER1_DOM6_PRI_PER_SHIFT
#define PRI_PER1_DOM6_PRI_EN_SHIFT      PRI_PER1_DOM6_PRI_EN_FIELD_OFFSET
#define PRI_PER1_DOM6_PRI_EN_MASK       1UL << PRI_PER1_DOM6_PRI_EN_SHIFT
#define PRI_PER1_DOM5_LOCK_SHIFT        PRI_PER1_DOM5_LOCK_FIELD_OFFSET
#define PRI_PER1_DOM5_LOCK_MASK         1UL << PRI_PER1_DOM5_LOCK_SHIFT
#define PRI_PER1_DOM5_USE_PER_SHIFT     PRI_PER1_DOM5_USE_PER_FIELD_OFFSET
#define PRI_PER1_DOM5_USE_PER_MASK      3UL << PRI_PER1_DOM5_USE_PER_SHIFT
#define PRI_PER1_DOM5_PRI_PER_SHIFT     PRI_PER1_DOM5_PRI_PER_FIELD_OFFSET
#define PRI_PER1_DOM5_PRI_PER_MASK      3UL << PRI_PER1_DOM5_PRI_PER_SHIFT
#define PRI_PER1_DOM5_PRI_EN_SHIFT      PRI_PER1_DOM5_PRI_EN_FIELD_OFFSET
#define PRI_PER1_DOM5_PRI_EN_MASK       1UL << PRI_PER1_DOM5_PRI_EN_SHIFT
#define PRI_PER1_DOM4_LOCK_SHIFT        PRI_PER1_DOM4_LOCK_FIELD_OFFSET
#define PRI_PER1_DOM4_LOCK_MASK         1UL << PRI_PER1_DOM4_LOCK_SHIFT
#define PRI_PER1_DOM4_USE_PER_SHIFT     PRI_PER1_DOM4_USE_PER_FIELD_OFFSET
#define PRI_PER1_DOM4_USE_PER_MASK      3UL << PRI_PER1_DOM4_USE_PER_SHIFT
#define PRI_PER1_DOM4_PRI_PER_SHIFT     PRI_PER1_DOM4_PRI_PER_FIELD_OFFSET
#define PRI_PER1_DOM4_PRI_PER_MASK      3UL << PRI_PER1_DOM4_PRI_PER_SHIFT
#define PRI_PER1_DOM4_PRI_EN_SHIFT      PRI_PER1_DOM4_PRI_EN_FIELD_OFFSET
#define PRI_PER1_DOM4_PRI_EN_MASK       1UL << PRI_PER1_DOM4_PRI_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC/PPC/RPC_PRI_PER2
// Register Offset : 0x24
// Description     : register structure are the same, use unified shift/mask
//--------------------------------------------------------------------------
#define PRI_PER2_DOM11_LOCK_SHIFT       PRI_PER2_DOM11_LOCK_FIELD_OFFSET
#define PRI_PER2_DOM11_LOCK_MASK        1UL << PRI_PER2_DOM11_LOCK_SHIFT
#define PRI_PER2_DOM11_USE_PER_SHIFT    PRI_PER2_DOM11_USE_PER_FIELD_OFFSET
#define PRI_PER2_DOM11_USE_PER_MASK     3UL << PRI_PER2_DOM11_USE_PER_SHIFT
#define PRI_PER2_DOM11_PRI_PER_SHIFT    PRI_PER2_DOM11_PRI_PER_FIELD_OFFSET
#define PRI_PER2_DOM11_PRI_PER_MASK     3UL << PRI_PER2_DOM11_PRI_PER_SHIFT
#define PRI_PER2_DOM11_PRI_EN_SHIFT     PRI_PER2_DOM11_PRI_EN_FIELD_OFFSET
#define PRI_PER2_DOM11_PRI_EN_MASK      1UL << PRI_PER2_DOM11_PRI_EN_SHIFT
#define PRI_PER2_DOM10_LOCK_SHIFT       PRI_PER2_DOM10_LOCK_FIELD_OFFSET
#define PRI_PER2_DOM10_LOCK_MASK        1UL << PRI_PER2_DOM10_LOCK_SHIFT
#define PRI_PER2_DOM10_USE_PER_SHIFT    PRI_PER2_DOM10_USE_PER_FIELD_OFFSET
#define PRI_PER2_DOM10_USE_PER_MASK     3UL << PRI_PER2_DOM10_USE_PER_SHIFT
#define PRI_PER2_DOM10_PRI_PER_SHIFT    PRI_PER2_DOM10_PRI_PER_FIELD_OFFSET
#define PRI_PER2_DOM10_PRI_PER_MASK     3UL << PRI_PER2_DOM10_PRI_PER_SHIFT
#define PRI_PER2_DOM10_PRI_EN_SHIFT     PRI_PER2_DOM10_PRI_EN_FIELD_OFFSET
#define PRI_PER2_DOM10_PRI_EN_MASK      1UL << PRI_PER2_DOM10_PRI_EN_SHIFT
#define PRI_PER2_DOM9_LOCK_SHIFT        PRI_PER2_DOM9_LOCK_FIELD_OFFSET
#define PRI_PER2_DOM9_LOCK_MASK         1UL << PRI_PER2_DOM9_LOCK_SHIFT
#define PRI_PER2_DOM9_USE_PER_SHIFT     PRI_PER2_DOM9_USE_PER_FIELD_OFFSET
#define PRI_PER2_DOM9_USE_PER_MASK      3UL << PRI_PER2_DOM9_USE_PER_SHIFT
#define PRI_PER2_DOM9_PRI_PER_SHIFT     PRI_PER2_DOM9_PRI_PER_FIELD_OFFSET
#define PRI_PER2_DOM9_PRI_PER_MASK      3UL << PRI_PER2_DOM9_PRI_PER_SHIFT
#define PRI_PER2_DOM9_PRI_EN_SHIFT      PRI_PER2_DOM9_PRI_EN_FIELD_OFFSET
#define PRI_PER2_DOM9_PRI_EN_MASK       1UL << PRI_PER2_DOM9_PRI_EN_SHIFT
#define PRI_PER2_DOM8_LOCK_SHIFT        PRI_PER2_DOM8_LOCK_FIELD_OFFSET
#define PRI_PER2_DOM8_LOCK_MASK         1UL << PRI_PER2_DOM8_LOCK_SHIFT
#define PRI_PER2_DOM8_USE_PER_SHIFT     PRI_PER2_DOM8_USE_PER_FIELD_OFFSET
#define PRI_PER2_DOM8_USE_PER_MASK      3UL << PRI_PER2_DOM8_USE_PER_SHIFT
#define PRI_PER2_DOM8_PRI_PER_SHIFT     PRI_PER2_DOM8_PRI_PER_FIELD_OFFSET
#define PRI_PER2_DOM8_PRI_PER_MASK      3UL << PRI_PER2_DOM8_PRI_PER_SHIFT
#define PRI_PER2_DOM8_PRI_EN_SHIFT      PRI_PER2_DOM8_PRI_EN_FIELD_OFFSET
#define PRI_PER2_DOM8_PRI_EN_MASK       1UL << PRI_PER2_DOM8_PRI_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC/PPC/RPC_PRI_PER3
// Register Offset : 0x28
// Description     : register structure are the same, use unified shift/mask
//--------------------------------------------------------------------------
#define PRI_PER3_DOM15_LOCK_SHIFT       PRI_PER3_DOM15_LOCK_FIELD_OFFSET
#define PRI_PER3_DOM15_LOCK_MASK        1UL << PRI_PER3_DOM15_LOCK_SHIFT
#define PRI_PER3_DOM15_USE_PER_SHIFT    PRI_PER3_DOM15_USE_PER_FIELD_OFFSET
#define PRI_PER3_DOM15_USE_PER_MASK     3UL << PRI_PER3_DOM15_USE_PER_SHIFT
#define PRI_PER3_DOM15_PRI_PER_SHIFT    PRI_PER3_DOM15_PRI_PER_FIELD_OFFSET
#define PRI_PER3_DOM15_PRI_PER_MASK     3UL << PRI_PER3_DOM15_PRI_PER_SHIFT
#define PRI_PER3_DOM15_PRI_EN_SHIFT     PRI_PER3_DOM15_PRI_EN_FIELD_OFFSET
#define PRI_PER3_DOM15_PRI_EN_MASK      1UL << PRI_PER3_DOM15_PRI_EN_SHIFT
#define PRI_PER3_DOM14_LOCK_SHIFT       PRI_PER3_DOM14_LOCK_FIELD_OFFSET
#define PRI_PER3_DOM14_LOCK_MASK        1UL << PRI_PER3_DOM14_LOCK_SHIFT
#define PRI_PER3_DOM14_USE_PER_SHIFT    PRI_PER3_DOM14_USE_PER_FIELD_OFFSET
#define PRI_PER3_DOM14_USE_PER_MASK     3UL << PRI_PER3_DOM14_USE_PER_SHIFT
#define PRI_PER3_DOM14_PRI_PER_SHIFT    PRI_PER3_DOM14_PRI_PER_FIELD_OFFSET
#define PRI_PER3_DOM14_PRI_PER_MASK     3UL << PRI_PER3_DOM14_PRI_PER_SHIFT
#define PRI_PER3_DOM14_PRI_EN_SHIFT     PRI_PER3_DOM14_PRI_EN_FIELD_OFFSET
#define PRI_PER3_DOM14_PRI_EN_MASK      1UL << PRI_PER3_DOM14_PRI_EN_SHIFT
#define PRI_PER3_DOM13_LOCK_SHIFT       PRI_PER3_DOM13_LOCK_FIELD_OFFSET
#define PRI_PER3_DOM13_LOCK_MASK        1UL << PRI_PER3_DOM13_LOCK_SHIFT
#define PRI_PER3_DOM13_USE_PER_SHIFT    PRI_PER3_DOM13_USE_PER_FIELD_OFFSET
#define PRI_PER3_DOM13_USE_PER_MASK     3UL << PRI_PER3_DOM13_USE_PER_SHIFT
#define PRI_PER3_DOM13_PRI_PER_SHIFT    PRI_PER3_DOM13_PRI_PER_FIELD_OFFSET
#define PRI_PER3_DOM13_PRI_PER_MASK     3UL << PRI_PER3_DOM13_PRI_PER_SHIFT
#define PRI_PER3_DOM13_PRI_EN_SHIFT     PRI_PER3_DOM13_PRI_EN_FIELD_OFFSET
#define PRI_PER3_DOM13_PRI_EN_MASK      1UL << PRI_PER3_DOM13_PRI_EN_SHIFT
#define PRI_PER3_DOM12_LOCK_SHIFT       PRI_PER3_DOM12_LOCK_FIELD_OFFSET
#define PRI_PER3_DOM12_LOCK_MASK        1UL << PRI_PER3_DOM12_LOCK_SHIFT
#define PRI_PER3_DOM12_USE_PER_SHIFT    PRI_PER3_DOM12_USE_PER_FIELD_OFFSET
#define PRI_PER3_DOM12_USE_PER_MASK     3UL << PRI_PER3_DOM12_USE_PER_SHIFT
#define PRI_PER3_DOM12_PRI_PER_SHIFT    PRI_PER3_DOM12_PRI_PER_FIELD_OFFSET
#define PRI_PER3_DOM12_PRI_PER_MASK     3UL << PRI_PER3_DOM12_PRI_PER_SHIFT
#define PRI_PER3_DOM12_PRI_EN_SHIFT     PRI_PER3_DOM12_PRI_EN_FIELD_OFFSET
#define PRI_PER3_DOM12_PRI_EN_MASK      1UL << PRI_PER3_DOM12_PRI_EN_SHIFT

/* Domain owner for peripheral,
   configured only by resource and group manager */
typedef struct dom_assign_t {
    addr_t    base_addr;
    uint32_t  lock;
    uint32_t  set;
    uint32_t  did;
} dom_assign_t;

/* domain permission configration,
   configured only by resource manager and domain owner. */
typedef struct dom_per_t {
    addr_t    base_addr;
    uint32_t  dom_lock[DOM_MAX_COUNT];
    uint32_t  dom_per[DOM_MAX_COUNT];
    uint32_t  dom_en[DOM_MAX_COUNT];
} dom_per_t;

/* secure permission configuration,
   configured by resource/group manager. */
typedef struct sec_per_t {
    addr_t    base_addr;
    uint32_t  dom_lock[DOM_MAX_COUNT];
    uint32_t  dom_nse_per[DOM_MAX_COUNT];
    uint32_t  dom_sec_per[DOM_MAX_COUNT];
    uint32_t  dom_sec_en[DOM_MAX_COUNT];
} sec_per_t;

/* privilege permission configuration,
   configured only by resource/group manager. */
typedef struct pri_per_t {
    addr_t    base_addr;
    uint32_t  dom_lock[DOM_MAX_COUNT];
    uint32_t  dom_use_per[DOM_MAX_COUNT];
    uint32_t  dom_pri_per[DOM_MAX_COUNT];
    uint32_t  dom_pri_en[DOM_MAX_COUNT];
} pri_per_t;

int writel_(uint32_t val, uint32_t reg);
int readl_(uint32_t reg);
int fw_writel(uint32_t val, uint32_t reg);
int fw_readl(uint32_t reg);

void dom_assign_init(dom_assign_t* dom_assign);
void access_ctl_init(dom_per_t* dom_per);
void sec_per_ctl_init(sec_per_t* sec_per);
void pri_per_ctl_init(pri_per_t* pri_per);
int mac_init(const addr_t base_addr, bool glb_mac);

#endif
