/*
 * Copyright (c) Semidrive
 */

#ifndef _MAC_REG_H
#define _MAC_REG_H

#include "__regs_ap_mac.h"

#if WITH_VIRT_PLATFORM
#define GLB_MAC_BASE_ADDR 0x41000000
#else
#if ARM_CPU_CORTEX_R5
#define GLB_MAC_BASE_ADDR 0xf0BC0000
#else
#define GLB_MAC_BASE_ADDR 0x30BC0000
#endif
#endif

/* Resource Manager -- Global control */
#define MAC_GLB_CTL                       REG(REG_AP_APB_MAC_GLB_CTL)
#define MAC_GLB_CTL_DOM_CFG_LOCK_SHIFT    GLB_CTL_DOM_CFG_LOCK_FIELD_OFFSET
#define MAC_GLB_CTL_DOM_CFG_LOCK_MASK     1UL << MAC_GLB_CTL_DOM_CFG_LOCK_SHIFT
#define MAC_GLB_CTL_DOM_CFG_MODE_SHIFT    GLB_CTL_DOM_CFG_MODE_FIELD_OFFSET
#define MAC_GLB_CTL_DOM_CFG_MODE_MASK     1UL << MAC_GLB_CTL_DOM_CFG_MODE_SHIFT
#define MAC_GLB_CTL_PERCK_DIS_LOCK_SHIFT  GLB_CTL_PERCK_DIS_LOCK_FIELD_OFFSET
#define MAC_GLB_CTL_PERCK_DIS_LOCK_MASK   1UL << MAC_GLB_CTL_PERCK_DIS_LOCK_SHIFT
#define MAC_GLB_CTL_PERCK_DIS_SHIFT       GLB_CTL_PERCK_DIS_FIELD_OFFSET
#define MAC_GLB_CTL_PERCK_DIS_MASK        1UL << MAC_GLB_CTL_PERCK_DIS_SHIFT
#define MAC_GLB_CTL_DOM_PRO_LOCK_SHIFT    GLB_CTL_DOM_PRO_LOCK_FIELD_OFFSET
#define MAC_GLB_CTL_DOM_PRO_LOCK_MASK     1UL << MAC_GLB_CTL_DOM_PRO_LOCK_SHIFT
#define MAC_GLB_CTL_DOM_PRO_EN_SHIFT      GLB_CTL_DOM_PRO_EN_FIELD_OFFSET
#define MAC_GLB_CTL_DOM_PRO_EN_MASK       1UL << MAC_GLB_CTL_DOM_PRO_EN_SHIFT

/* Resource Manager */
#define MAC_RES_MGR                       REG(REG_AP_APB_MAC_RES_MGR)
#define MAC_RES_MGR_MID_LOCK_SHIFT        RES_MGR_MID_LOCK_FIELD_OFFSET
#define MAC_RES_MGR_MID_LOCK_MASK         1UL << MAC_RES_MGR_MID_LOCK_SHIFT
#define MAC_RES_MGR_MID_EN_SHIFT          RES_MGR_MID_EN_FIELD_OFFSET
#define MAC_RES_MGR_MID_EN_MASK           1UL << MAC_RES_MGR_MID_EN_SHIFT
#define MAC_RES_MGR_PRI_PER_LOCK_SHIFT    RES_MGR_PRI_PER_LOCK_FIELD_OFFSET
#define MAC_RES_MGR_PRI_PER_LOCK_MASK     1UL << MAC_RES_MGR_PRI_PER_LOCK_SHIFT
#define MAC_RES_MGR_PRI_PER_SHIFT         RES_MGR_PRI_PER_FIELD_OFFSET
#define MAC_RES_MGR_PRI_PER_MASK          3UL << MAC_RES_MGR_PRI_PER_SHIFT
#define MAC_RES_MGR_PRI_PER_EN_SHIFT      RES_MGR_PRI_PER_EN_FIELD_OFFSET
#define MAC_RES_MGR_PRI_PER_EN_MASK       1UL << MAC_RES_MGR_PRI_PER_EN_SHIFT
#define MAC_RES_MGR_SEC_PER_LOCK_SHIFT    RES_MGR_SEC_PER_LOCK_FIELD_OFFSET
#define MAC_RES_MGR_SEC_PER_LOCK_MASK     1UL << MAC_RES_MGR_SEC_PER_LOCK_SHIFT
#define MAC_RES_MGR_SEC_PER_SHIFT         RES_MGR_SEC_PER_FIELD_OFFSET
#define MAC_RES_MGR_SEC_PER_MASK          3UL << MAC_RES_MGR_SEC_PER_SHIFT
#define MAC_RES_MGR_SEC_PER_EN_SHIFT      RES_MGR_SEC_PER_EN_FIELD_OFFSET
#define MAC_RES_MGR_SEC_PER_EN_MASK       1UL << MAC_RES_MGR_SEC_PER_EN_SHIFT
#define MAC_RES_MGR_DID_LOCK_SHIFT        RES_MGR_DID_LOCK_FIELD_OFFSET
#define MAC_RES_MGR_DID_LOCK_MASK         1UL << MAC_RES_MGR_DID_LOCK_SHIFT
#define MAC_RES_MGR_DID_SHIFT             RES_MGR_DID_FIELD_OFFSET
#define MAC_RES_MGR_DID_MASK              0xF << MAC_RES_MGR_DID_SHIFT
#define MAC_RES_MGR_DID_EN_SHIFT          RES_MGR_DID_EN_FIELD_OFFSET
#define MAC_RES_MGR_DID_EN_MASK           1UL << MAC_RES_MGR_DID_EN_SHIFT
#define MAC_RES_MGR_RES_MGR_EN_LOCK_SHIFT RES_MGR_RES_MGR_EN_LOCK_FIELD_OFFSET
#define MAC_RES_MGR_RES_MGR_EN_LOCK_MASK  1UL << MAC_RES_MGR_RES_MGR_EN_LOCK_SHIFT
#define MAC_RES_MGR_RES_MGR_EN_SHIFT      RES_MGR_RES_MGR_EN_FIELD_OFFSET
#define MAC_RES_MGR_RES_MGR_EN_MASK       1UL << MAC_RES_MGR_RES_MGR_EN_SHIFT

/* Resource Manager MASTER-0 (MASTER ID: 0 ~ 31) */
#define MAC_RES_MGR_MA0                   REG(REG_AP_APB_MAC_RES_MGR_MA0)
#define MAC_RES_MGR_MA0_MID_SHIFT         RES_MGR_MA0_MID_FIELD_OFFSET
#define MAC_RES_MGR_MA0_MID_MASK          0xFFFFFFFF

/* Resource Manager MASTER-1 (MASTER ID: 32 ~ 63) */
#define MAC_RES_MGR_MA1                   REG(REG_AP_APB_MAC_RES_MGR_MA1)
#define MAC_RES_MGR_MA1_MID_SHIFT         RES_MGR_MA1_MID_FIELD_OFFSET
#define MAC_RES_MGR_MA1_MID_MASK          0xFFFFFFFF

/* Resource Manager MASTER-2 (MASTER ID: 64 ~ 95) */
#define MAC_RES_MGR_MA2                   REG(REG_AP_APB_MAC_RES_MGR_MA2)
#define MAC_RES_MGR_MA2_MID_SHIFT         RES_MGR_MA2_MID_FIELD_OFFSET
#define MAC_RES_MGR_MA2_MID_MASK          0xFFFFFFFF

/* Resource Manager MASTER-3 (MASTER ID: 96 ~ 127) */
#define MAC_RES_MGR_MA3                   REG(REG_AP_APB_MAC_RES_MGR_MA3)
#define MAC_RES_MGR_MA3_MID_SHIFT         RES_MGR_MA3_MID_FIELD_OFFSET
#define MAC_RES_MGR_MA3_MID_MASK          0xFFFFFFFF


/* Group manager, support 8 groups */
#define MAC_GROUP_MANAGER_MAX             0x8
#define MAC_GRP_MGR_JUMP                  0x14
#define MAC_GRP_MGR_(i)                   (REG(REG_AP_APB_MAC_GRP_MGR) + (i) * MAC_GRP_MGR_JUMP)
#define MAC_GRP_MGR_MID_LOCK_SHIFT        GRP_MGR_MID_LOCK_FIELD_OFFSET
#define MAC_GRP_MGR_MID_LOCK_MASK         1UL << MAC_GRP_MGR_MID_LOCK_SHIFT
#define MAC_GRP_MGR_MID_EN_SHIFT          GRP_MGR_MID_EN_FIELD_OFFSET
#define MAC_GRP_MGR_MID_EN_MASK           1UL << MAC_GRP_MGR_MID_EN_SHIFT
#define MAC_GRP_MGR_PRI_PER_LOCK_SHIFT    GRP_MGR_PRI_PER_LOCK_FIELD_OFFSET
#define MAC_GRP_MGR_PRI_PER_LOCK_MASK     1UL << MAC_GRP_MGR_PRI_PER_LOCK_SHIFT
#define MAC_GRP_MGR_PRI_PER_SHIFT         GRP_MGR_PRI_PER_FIELD_OFFSET
#define MAC_GRP_MGR_PRI_PER_MASK          3UL << MAC_GRP_MGR_PRI_PER_SHIFT
#define MAC_GRP_MGR_PRI_PER_EN_SHIFT      GRP_MGR_PRI_PER_EN_FIELD_OFFSET
#define MAC_GRP_MGR_PRI_PER_EN_MASK       1UL << MAC_GRP_MGR_PRI_PER_EN_SHIFT
#define MAC_GRP_MGR_SEC_PER_LOCK_SHIFT    GRP_MGR_SEC_PER_LOCK_FIELD_OFFSET
#define MAC_GRP_MGR_SEC_PER_LOCK_MASK     1UL << MAC_GRP_MGR_SEC_PER_LOCK_SHIFT
#define MAC_GRP_MGR_SEC_PER_SHIFT         GRP_MGR_SEC_PER_FIELD_OFFSET
#define MAC_GRP_MGR_SEC_PER_MASK          3UL << MAC_GRP_MGR_SEC_PER_SHIFT
#define MAC_GRP_MGR_SEC_PER_EN_SHIFT      GRP_MGR_SEC_PER_EN_FIELD_OFFSET
#define MAC_GRP_MGR_SEC_PER_EN_MASK       1UL << MAC_GRP_MGR_SEC_PER_EN_SHIFT
#define MAC_GRP_MGR_DID_LOCK_SHIFT        GRP_MGR_DID_LOCK_FIELD_OFFSET
#define MAC_GRP_MGR_DID_LOCK_MASK         1UL << MAC_GRP_MGR_DID_LOCK_SHIFT
#define MAC_GRP_MGR_DID_SHIFT             GRP_MGR_DID_FIELD_OFFSET
#define MAC_GRP_MGR_DID_MASK              0xF << MAC_GRP_MGR_DID_SHIFT
#define MAC_GRP_MGR_DID_EN_SHIFT          GRP_MGR_DID_EN_FIELD_OFFSET
#define MAC_GRP_MGR_DID_EN_MASK           1UL << MAC_GRP_MGR_DID_EN_SHIFT
#define MAC_GRP_MGR_GRP_MGR_EN_LOCK_SHIFT GRP_MGR_GRP_MGR_EN_LOCK_FIELD_OFFSET
#define MAC_GRP_MGR_GRP_MGR_EN_LOCK_MASK  1UL << MAC_GRP_MGR_GRP_MGR_EN_LOCK_SHIFT
#define MAC_GRP_MGR_GRP_MGR_EN_SHIFT      GRP_MGR_GRP_MGR_EN_FIELD_OFFSET
#define MAC_GRP_MGR_GRP_MGR_EN_MASK       1UL << MAC_GRP_MGR_GRP_MGR_EN_SHIFT

/* Group Manager MASTER-0 (MASTER ID: 0 ~ 31) */
#define MAC_GRP_MGR_MA0_(i)               (REG(REG_AP_APB_MAC_GRP_MGR_MA0) + (i) * MAC_GRP_MGR_JUMP)
#define MAC_GRP_MGR_MA0_MID_SHIFT         GRP_MGR_MA0_MID_FIELD_OFFSET
#define MAC_GRP_MGR_MA0_MID_MASK          0xFFFFFFFF

/* Group Manager MASTER-1 (MASTER ID: 32 ~ 63) */
#define MAC_GRP_MGR_MA1_(i)               (REG(REG_AP_APB_MAC_GRP_MGR_MA1) + (i) * MAC_GRP_MGR_JUMP)
#define MAC_GRP_MGR_MA1_MID_SHIFT         GRP_MGR_MA1_MID_FIELD_OFFSET
#define MAC_GRP_MGR_MA1_MID_MASK          0xFFFFFFFF

/* Group Manager MASTER-2 (MASTER ID: 64 ~ 95) */
#define MAC_GRP_MGR_MA2_(i)               (REG(REG_AP_APB_MAC_GRP_MGR_MA2) + (i) * MAC_GRP_MGR_JUMP)
#define MAC_GRP_MGR_MA2_MID_SHIFT         GRP_MGR_MA2_MID_FIELD_OFFSET
#define MAC_GRP_MGR_MA2_MID_MASK          0xFFFFFFFF

/* Group Manager MASTER-3 (MASTER ID: 96 ~ 127) */
#define MAC_GRP_MGR_MA3_(i)               (REG(REG_AP_APB_MAC_GRP_MGR_MA3) + (i) * MAC_GRP_MGR_JUMP)
#define MAC_GRP_MGR_MA3_MID_SHIFT         GRP_MGR_MA3_MID_FIELD_OFFSET
#define MAC_GRP_MGR_MA3_MID_MASK          0xFFFFFFFF

/* Domain - Group assignment, support 16 domains */
#define MAC_DOMAIN_OWNER_MAX              0x10
#define MAC_DOMAIN_OWNER_JUMP             0x18
#define MAC_DOM_GID_(i)                   (REG(REG_AP_APB_MAC_DOM_GID) + (i) * MAC_DOMAIN_OWNER_JUMP)
#define MAC_DOM_GID_LOCK_SHIFT            DOM_GID_LOCK_FIELD_OFFSET
#define MAC_DOM_GID_LOCK_MASK             1UL << MAC_DOM_GID_LOCK_SHIFT
#define MAC_DOM_GID_GID_SHIFT             DOM_GID_GID_FIELD_OFFSET
#define MAC_DOM_GID_GID_MASK              7UL << MAC_DOM_GID_GID_SHIFT

/* Domain owner, support 16 domains */
#define MAC_DOM_OWN_(i)                   (REG(REG_AP_APB_MAC_DOM_OWN) + (i) * MAC_DOMAIN_OWNER_JUMP)
#define MAC_DOM_OWN_MID_LOCK_SHIFT        DOM_OWN_MID_LOCK_FIELD_OFFSET
#define MAC_DOM_OWN_MID_LOCK_MASK         1UL << MAC_DOM_OWN_MID_LOCK_SHIFT
#define MAC_DOM_OWN_MID_EN_SHIFT          DOM_OWN_MID_EN_FIELD_OFFSET
#define MAC_DOM_OWN_MID_EN_MASK           1UL << MAC_DOM_OWN_MID_EN_SHIFT
#define MAC_DOM_OWN_PRI_PER_LOCK_SHIFT    DOM_OWN_PRI_PER_LOCK_FIELD_OFFSET
#define MAC_DOM_OWN_PRI_PER_LOCK_MASK     1UL << MAC_DOM_OWN_PRI_PER_LOCK_SHIFT
#define MAC_DOM_OWN_PRI_PER_SHIFT         DOM_OWN_PRI_PER_FIELD_OFFSET
#define MAC_DOM_OWN_PRI_PER_MASK          3UL << MAC_DOM_OWN_PRI_PER_SHIFT
#define MAC_DOM_OWN_PRI_PER_EN_SHIFT      DOM_OWN_PRI_PER_EN_FIELD_OFFSET
#define MAC_DOM_OWN_PRI_PER_EN_MASK       1UL << MAC_DOM_OWN_PRI_PER_EN_SHIFT
#define MAC_DOM_OWN_SEC_PER_LOCK_SHIFT    DOM_OWN_SEC_PER_LOCK_FIELD_OFFSET
#define MAC_DOM_OWN_SEC_PER_LOCK_MASK     1UL << MAC_DOM_OWN_SEC_PER_LOCK_SHIFT
#define MAC_DOM_OWN_SEC_PER_SHIFT         DOM_OWN_SEC_PER_FIELD_OFFSET
#define MAC_DOM_OWN_SEC_PER_MASK          3UL << MAC_DOM_OWN_SEC_PER_SHIFT
#define MAC_DOM_OWN_SEC_PER_EN_SHIFT      DOM_OWN_SEC_PER_EN_FIELD_OFFSET
#define MAC_DOM_OWN_SEC_PER_EN_MASK       1UL << MAC_DOM_OWN_SEC_PER_EN_SHIFT
#define MAC_DOM_OWN_EN_LOCK_SHIFT         DOM_OWN_DOM_OWN_EN_LOCK_FIELD_OFFSET
#define MAC_DOM_OWN_EN_LOCK_MASK          1UL << MAC_DOM_OWN_EN_LOCK_SHIFT
#define MAC_DOM_OWN_EN_SHIFT              DOM_OWN_DOM_OWN_EN_FIELD_OFFSET
#define MAC_DOM_OWN_EN_MASK               1UL << MAC_DOM_OWN_EN_SHIFT

/* Domain Owner MASTER-0 (MASTER ID: 0 ~ 31) */
#define MAC_DOM_OWN_MA0_(i)               (REG(REG_AP_APB_MAC_DOM_OWN_MA0) + (i) * MAC_DOMAIN_OWNER_JUMP)
#define MAC_DOM_OWN_MA0_MID_SHIFT         DOM_OWN_MA0_MID_FIELD_OFFSET
#define MAC_DOM_OWN_MA0_MID_MASK          0xFFFFFFFF

/* Domain Owner MASTER-1 (MASTER ID: 32 ~ 63) */
#define MAC_DOM_OWN_MA1_(i)               (REG(REG_AP_APB_MAC_DOM_OWN_MA1) + (i) * MAC_DOMAIN_OWNER_JUMP)
#define MAC_DOM_OWN_MA1_MID_SHIFT         DOM_OWN_MA1_MID_FIELD_OFFSET
#define MAC_DOM_OWN_MA1_MID_MASK          0xFFFFFFFF

/* Domain Ownerr MASTER-2 (MASTER ID: 64 ~ 95) */
#define MAC_DOM_OWN_MA2_(i)               (REG(REG_AP_APB_MAC_DOM_OWN_MA2) + (i) * MAC_DOMAIN_OWNER_JUMP)
#define MAC_DOM_OWN_MA2_MID_SHIFT         DOM_OWN_MA2_MID_FIELD_OFFSET
#define MAC_DOM_OWN_MA2_MID_MASK          0xFFFFFFFF

/* Domain Owner MASTER-3 (MASTER ID: 96 ~ 127) */
#define MAC_DOM_OWN_MA3_(i)               (REG(REG_AP_APB_MAC_DOM_OWN_MA3) + (i) * MAC_DOMAIN_OWNER_JUMP)
#define MAC_DOM_OWN_MA3_MID_SHIFT         DOM_OWN_MA3_MID_FIELD_OFFSET
#define MAC_DOM_OWN_MA3_MID_MASK          0xFFFFFFFF

/* Master - Domain assignment, support 64/128 masters */
#define MAC_MASTER_COUNT                  0x80
#define MAC_MASTER_JUMP                   0x8
#define MAC_MDA_(i)                       (REG(REG_AP_APB_MAC_MDA) + (i) * MAC_MASTER_JUMP)
#define MAC_MDA_LOCK_SHIFT                MDA_LOCK_FIELD_OFFSET
#define MAC_MDA_LOCK_MASK                 1UL << MAC_MDA_LOCK_SHIFT
#define MAC_MDA_DID_SHIFT                 MDA_DID_FIELD_OFFSET
#define MAC_MDA_DID_MASK                  0xF << MAC_MDA_DID_SHIFT

/* Master attribute assignment */
#define MAC_MAA_(i)                       (REG(REG_AP_APB_MAC_MAA) + (i) * MAC_MASTER_JUMP)
#define MAC_MAA_SRID_LOCK_SHIFT           MAA_SRID_LOCK_FIELD_OFFSET
#define MAC_MAA_SRID_LOCK_MASK            1UL << MAC_MAA_SRID_LOCK_SHIFT
#define MAC_MAA_SRID_SHIFT                MAA_SRID_FIELD_OFFSET
#define MAC_MAA_SRID_MASK                 0xFF << MAC_MAA_SRID_SHIFT
#define MAC_MAA_PRI_LOCK_SHIFT            MAA_PRI_LOCK_FIELD_OFFSET
#define MAC_MAA_PRI_LOCK_MASK             1UL << MAC_MAA_PRI_LOCK_SHIFT
#define MAC_MAA_PRI_OV_EN_SHIFT           MAA_PRI_OV_EN_FIELD_OFFSET
#define MAC_MAA_PRI_OV_EN_MASK            1UL << MAC_MAA_PRI_OV_EN_SHIFT
#define MAC_MAA_PRI_SHIFT                 MAA_PRI_FIELD_OFFSET
#define MAC_MAA_PRI_MASK                  1UL << MAC_MAA_PRI_SHIFT
#define MAC_MAA_SEC_LOCK_SHIFT            MAA_SEC_LOCK_FIELD_OFFSET
#define MAC_MAA_SEC_LOCK_MASK             1UL << MAC_MAA_SEC_LOCK_SHIFT
#define MAC_MAA_SEC_OV_EN_SHIFT           MAA_SEC_OV_EN_FIELD_OFFSET
#define MAC_MAA_SEC_OV_EN_MASK            1UL << MAC_MAA_SEC_OV_EN_SHIFT
#define MAC_MAA_SEC_SHIFT                 MAA_SEC_FIELD_OFFSET
#define MAC_MAA_SEC_MASK                  1UL << MAC_MAA_SEC_SHIFT

#endif
