/*
 * Copyright (c) Semidrive
 */

#ifndef _MPC_REG_H
#define _MPC_REG_H

#include "__regs_ap_mpc.h"

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_DOM
// Register Offset : 0x0
// Description     :
//--------------------------------------------------------------------------
#define MPC_CTRL_JUMP                       0x38
#define MPC_DOM_(i)                         (REG_AP_APB_MPC_DOM + (i) * MPC_CTRL_JUMP)
#define MPC_DOM_LOCK_SHIFT                  DOM_LOCK_FIELD_OFFSET
#define MPC_DOM_LOCK_MASK                   1UL << MPC_DOM_LOCK_SHIFT
#define MPC_DOM_SET_SHIFT                   DOM_SET_FIELD_OFFSET
#define MPC_DOM_SET_MASK                    1UL << MPC_DOM_SET_SHIFT
#define MPC_DOM_DID_SHIFT                   DOM_DID_FIELD_OFFSET
#define MPC_DOM_DID_MASK                    0xF << MPC_DOM_DID_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_DOM_PER0
// Register Offset : 0x4
// Description     :
//--------------------------------------------------------------------------
#define MPC_DOM_PER0_(i)                    (REG_AP_APB_MPC_DOM_PER0 + (i) * MPC_CTRL_JUMP)
#define MPC_DOM_PER0_DOM7_LOCK_SHIFT        DOM_PER0_DOM7_LOCK_FIELD_OFFSET
#define MPC_DOM_PER0_DOM7_LOCK_MASK         1UL << MPC_DOM_PER0_DOM7_LOCK_SHIFT
#define MPC_DOM_PER0_DOM7_PER_SHIFT         DOM_PER0_DOM7_PER_FIELD_OFFSET
#define MPC_DOM_PER0_DOM7_PER_MASK          3UL << MPC_DOM_PER0_DOM7_PER_SHIFT
#define MPC_DOM_PER0_DOM7_EN_SHIFT          DOM_PER0_DOM7_EN_FIELD_OFFSET
#define MPC_DOM_PER0_DOM7_EN_MASK           1UL << MPC_DOM_PER0_DOM7_EN_SHIFT
#define MPC_DOM_PER0_DOM6_LOCK_SHIFT        DOM_PER0_DOM6_LOCK_FIELD_OFFSET
#define MPC_DOM_PER0_DOM6_LOCK_MASK         1UL << MPC_DOM_PER0_DOM6_LOCK_SHIFT
#define MPC_DOM_PER0_DOM6_PER_SHIFT         DOM_PER0_DOM6_PER_FIELD_OFFSET
#define MPC_DOM_PER0_DOM6_PER_MASK          3UL << MPC_DOM_PER0_DOM6_PER_SHIFT
#define MPC_DOM_PER0_DOM6_EN_SHIFT          DOM_PER0_DOM6_EN_FIELD_OFFSET
#define MPC_DOM_PER0_DOM6_EN_MASK           1UL << MPC_DOM_PER0_DOM6_EN_SHIFT
#define MPC_DOM_PER0_DOM5_LOCK_SHIFT        DOM_PER0_DOM5_LOCK_FIELD_OFFSET
#define MPC_DOM_PER0_DOM5_LOCK_MASK         1UL << MPC_DOM_PER0_DOM5_LOCK_SHIFT
#define MPC_DOM_PER0_DOM5_PER_SHIFT         DOM_PER0_DOM5_PER_FIELD_OFFSET
#define MPC_DOM_PER0_DOM5_PER_MASK          3UL << MPC_DOM_PER0_DOM5_PER_SHIFT
#define MPC_DOM_PER0_DOM5_EN_SHIFT          DOM_PER0_DOM5_EN_FIELD_OFFSET
#define MPC_DOM_PER0_DOM5_EN_MASK           1UL << MPC_DOM_PER0_DOM5_EN_SHIFT
#define MPC_DOM_PER0_DOM4_LOCK_SHIFT        DOM_PER0_DOM4_LOCK_FIELD_OFFSET
#define MPC_DOM_PER0_DOM4_LOCK_MASK         1UL << MPC_DOM_PER0_DOM4_LOCK_SHIFT
#define MPC_DOM_PER0_DOM4_PER_SHIFT         DOM_PER0_DOM4_PER_FIELD_OFFSET
#define MPC_DOM_PER0_DOM4_PER_MASK          3UL << MPC_DOM_PER0_DOM4_PER_SHIFT
#define MPC_DOM_PER0_DOM4_EN_SHIFT          DOM_PER0_DOM4_EN_FIELD_OFFSET
#define MPC_DOM_PER0_DOM4_EN_MASK           1UL << MPC_DOM_PER0_DOM4_EN_SHIFT
#define MPC_DOM_PER0_DOM3_LOCK_SHIFT        DOM_PER0_DOM3_LOCK_FIELD_OFFSET
#define MPC_DOM_PER0_DOM3_LOCK_MASK         1UL << MPC_DOM_PER0_DOM3_LOCK_SHIFT
#define MPC_DOM_PER0_DOM3_PER_SHIFT         DOM_PER0_DOM3_PER_FIELD_OFFSET
#define MPC_DOM_PER0_DOM3_PER_MASK          3UL << MPC_DOM_PER0_DOM3_PER_SHIFT
#define MPC_DOM_PER0_DOM3_EN_SHIFT          DOM_PER0_DOM3_EN_FIELD_OFFSET
#define MPC_DOM_PER0_DOM3_EN_MASK           1UL << MPC_DOM_PER0_DOM3_EN_SHIFT
#define MPC_DOM_PER0_DOM2_LOCK_SHIFT        DOM_PER0_DOM2_LOCK_FIELD_OFFSET
#define MPC_DOM_PER0_DOM2_LOCK_MASK         1UL << MPC_DOM_PER0_DOM2_LOCK_SHIFT
#define MPC_DOM_PER0_DOM2_PER_SHIFT         DOM_PER0_DOM2_PER_FIELD_OFFSET
#define MPC_DOM_PER0_DOM2_PER_MASK          3UL << MPC_DOM_PER0_DOM2_PER_SHIFT
#define MPC_DOM_PER0_DOM2_EN_SHIFT          DOM_PER0_DOM2_EN_FIELD_OFFSET
#define MPC_DOM_PER0_DOM2_EN_MASK           1UL << MPC_DOM_PER0_DOM2_EN_SHIFT
#define MPC_DOM_PER0_DOM1_LOCK_SHIFT        DOM_PER0_DOM1_LOCK_FIELD_OFFSET
#define MPC_DOM_PER0_DOM1_LOCK_MASK         1UL << MPC_DOM_PER0_DOM1_LOCK_SHIFT
#define MPC_DOM_PER0_DOM1_PER_SHIFT         DOM_PER0_DOM1_PER_FIELD_OFFSET
#define MPC_DOM_PER0_DOM1_PER_MASK          3UL << MPC_DOM_PER0_DOM1_PER_SHIFT
#define MPC_DOM_PER0_DOM1_EN_SHIFT          DOM_PER0_DOM1_EN_FIELD_OFFSET
#define MPC_DOM_PER0_DOM1_EN_MASK           1UL << MPC_DOM_PER0_DOM1_EN_SHIFT
#define MPC_DOM_PER0_DOM0_LOCK_SHIFT        DOM_PER0_DOM0_LOCK_FIELD_OFFSET
#define MPC_DOM_PER0_DOM0_LOCK_MASK         1UL << MPC_DOM_PER0_DOM0_LOCK_SHIFT
#define MPC_DOM_PER0_DOM0_PER_SHIFT         DOM_PER0_DOM0_PER_FIELD_OFFSET
#define MPC_DOM_PER0_DOM0_PER_MASK          3UL << MPC_DOM_PER0_DOM0_PER_SHIFT
#define MPC_DOM_PER0_DOM0_EN_SHIFT          DOM_PER0_DOM0_EN_FIELD_OFFSET
#define MPC_DOM_PER0_DOM0_EN_MASK           1UL << MPC_DOM_PER0_DOM0_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_DOM_PER1
// Register Offset : 0x8
// Description     :
//--------------------------------------------------------------------------
#define MPC_DOM_PER1_(i)                    (REG_AP_APB_MPC_DOM_PER1 + (i) * MPC_CTRL_JUMP)
#define MPC_DOM_PER1_DOM15_LOCK_SHIFT       DOM_PER1_DOM15_LOCK_FIELD_OFFSET
#define MPC_DOM_PER1_DOM15_LOCK_MASK        1UL << MPC_DOM_PER1_DOM15_LOCK_SHIFT
#define MPC_DOM_PER1_DOM15_PER_SHIFT        DOM_PER1_DOM15_PER_FIELD_OFFSET
#define MPC_DOM_PER1_DOM15_PER_MASK         3UL << MPC_DOM_PER1_DOM15_PER_SHIFT
#define MPC_DOM_PER1_DOM15_EN_SHIFT         DOM_PER1_DOM15_EN_FIELD_OFFSET
#define MPC_DOM_PER1_DOM15_EN_MASK          1UL << MPC_DOM_PER1_DOM15_EN_SHIFT
#define MPC_DOM_PER1_DOM14_LOCK_SHIFT       DOM_PER1_DOM14_LOCK_FIELD_OFFSET
#define MPC_DOM_PER1_DOM14_LOCK_MASK        1UL << MPC_DOM_PER1_DOM14_LOCK_SHIFT
#define MPC_DOM_PER1_DOM14_PER_SHIFT        DOM_PER1_DOM14_PER_FIELD_OFFSET
#define MPC_DOM_PER1_DOM14_PER_MASK         3UL << MPC_DOM_PER1_DOM14_PER_SHIFT
#define MPC_DOM_PER1_DOM14_EN_SHIFT         DOM_PER1_DOM14_EN_FIELD_OFFSET
#define MPC_DOM_PER1_DOM14_EN_MASK          1UL << MPC_DOM_PER1_DOM14_EN_SHIFT
#define MPC_DOM_PER1_DOM13_LOCK_SHIFT       DOM_PER1_DOM13_LOCK_FIELD_OFFSET
#define MPC_DOM_PER1_DOM13_LOCK_MASK        1UL << MPC_DOM_PER1_DOM13_LOCK_SHIFT
#define MPC_DOM_PER1_DOM13_PER_SHIFT        DOM_PER1_DOM13_PER_FIELD_OFFSET
#define MPC_DOM_PER1_DOM13_PER_MASK         3UL << MPC_DOM_PER1_DOM13_PER_SHIFT
#define MPC_DOM_PER1_DOM13_EN_SHIFT         DOM_PER1_DOM13_EN_FIELD_OFFSET
#define MPC_DOM_PER1_DOM13_EN_MASK          1UL << MPC_DOM_PER1_DOM13_EN_SHIFT
#define MPC_DOM_PER1_DOM12_LOCK_SHIFT       DOM_PER1_DOM12_LOCK_FIELD_OFFSET
#define MPC_DOM_PER1_DOM12_LOCK_MASK        1UL << MPC_DOM_PER1_DOM12_LOCK_SHIFT
#define MPC_DOM_PER1_DOM12_PER_SHIFT        DOM_PER1_DOM12_PER_FIELD_OFFSET
#define MPC_DOM_PER1_DOM12_PER_MASK         3UL << MPC_DOM_PER1_DOM12_PER_SHIFT
#define MPC_DOM_PER1_DOM12_EN_SHIFT         DOM_PER1_DOM12_EN_FIELD_OFFSET
#define MPC_DOM_PER1_DOM12_EN_MASK          1UL << MPC_DOM_PER1_DOM12_EN_SHIFT
#define MPC_DOM_PER1_DOM11_LOCK_SHIFT       DOM_PER1_DOM11_LOCK_FIELD_OFFSET
#define MPC_DOM_PER1_DOM11_LOCK_MASK        1UL << MPC_DOM_PER1_DOM11_LOCK_SHIFT
#define MPC_DOM_PER1_DOM11_PER_SHIFT        DOM_PER1_DOM11_PER_FIELD_OFFSET
#define MPC_DOM_PER1_DOM11_PER_MASK         3UL << MPC_DOM_PER1_DOM11_PER_SHIFT
#define MPC_DOM_PER1_DOM11_EN_SHIFT         DOM_PER1_DOM11_EN_FIELD_OFFSET
#define MPC_DOM_PER1_DOM11_EN_MASK          1UL << MPC_DOM_PER1_DOM11_EN_SHIFT
#define MPC_DOM_PER1_DOM10_LOCK_SHIFT       DOM_PER1_DOM10_LOCK_FIELD_OFFSET
#define MPC_DOM_PER1_DOM10_LOCK_MASK        1UL << MPC_DOM_PER1_DOM10_LOCK_SHIFT
#define MPC_DOM_PER1_DOM10_PER_SHIFT        DOM_PER1_DOM10_PER_FIELD_OFFSET
#define MPC_DOM_PER1_DOM10_PER_MASK         3UL << MPC_DOM_PER1_DOM10_PER_SHIFT
#define MPC_DOM_PER1_DOM10_EN_SHIFT         DOM_PER1_DOM10_EN_FIELD_OFFSET
#define MPC_DOM_PER1_DOM10_EN_MASK          1UL << MPC_DOM_PER1_DOM10_EN_SHIFT
#define MPC_DOM_PER1_DOM9_LOCK_SHIFT        DOM_PER1_DOM9_LOCK_FIELD_OFFSET
#define MPC_DOM_PER1_DOM9_LOCK_MASK         1UL << MPC_DOM_PER1_DOM9_LOCK_SHIFT
#define MPC_DOM_PER1_DOM9_PER_SHIFT         DOM_PER1_DOM9_PER_FIELD_OFFSET
#define MPC_DOM_PER1_DOM9_PER_MASK          3UL << MPC_DOM_PER1_DOM9_PER_SHIFT
#define MPC_DOM_PER1_DOM9_EN_SHIFT          DOM_PER1_DOM9_EN_FIELD_OFFSET
#define MPC_DOM_PER1_DOM9_EN_MASK           1UL << MPC_DOM_PER1_DOM9_EN_SHIFT
#define MPC_DOM_PER1_DOM8_LOCK_SHIFT        DOM_PER1_DOM8_LOCK_FIELD_OFFSET
#define MPC_DOM_PER1_DOM8_LOCK_MASK         1UL << MPC_DOM_PER1_DOM8_LOCK_SHIFT
#define MPC_DOM_PER1_DOM8_PER_SHIFT         DOM_PER1_DOM8_PER_FIELD_OFFSET
#define MPC_DOM_PER1_DOM8_PER_MASK          3UL << MPC_DOM_PER1_DOM8_PER_SHIFT
#define MPC_DOM_PER1_DOM8_EN_SHIFT          DOM_PER1_DOM8_EN_FIELD_OFFSET
#define MPC_DOM_PER1_DOM8_EN_MASK           1UL << MPC_DOM_PER1_DOM8_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_SEC_PER0
// Register Offset : 0xc
// Description     :
//--------------------------------------------------------------------------
#define MPC_SEC_PER0_(i)                    (REG_AP_APB_MPC_SEC_PER0 + (i) * MPC_CTRL_JUMP)
#define MPC_SEC_PER0_DOM3_LOCK_SHIFT        SEC_PER0_DOM3_LOCK_FIELD_OFFSET
#define MPC_SEC_PER0_DOM3_LOCK_MASK         1UL << MPC_SEC_PER0_DOM3_LOCK_SHIFT
#define MPC_SEC_PER0_DOM3_NSE_PER_SHIFT     SEC_PER0_DOM3_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER0_DOM3_NSE_PER_MASK      3UL << MPC_SEC_PER0_DOM3_NSE_PER_SHIFT
#define MPC_SEC_PER0_DOM3_SEC_PER_SHIFT     SEC_PER0_DOM3_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER0_DOM3_SEC_PER_MASK      3UL << MPC_SEC_PER0_DOM3_SEC_PER_SHIFT
#define MPC_SEC_PER0_DOM3_SEC_EN_SHIFT      SEC_PER0_DOM3_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER0_DOM3_SEC_EN_MASK       1UL << MPC_SEC_PER0_DOM3_SEC_EN_SHIFT
#define MPC_SEC_PER0_DOM2_LOCK_SHIFT        SEC_PER0_DOM2_LOCK_FIELD_OFFSET
#define MPC_SEC_PER0_DOM2_LOCK_MASK         1UL << MPC_SEC_PER0_DOM2_LOCK_SHIFT
#define MPC_SEC_PER0_DOM2_NSE_PER_SHIFT     SEC_PER0_DOM2_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER0_DOM2_NSE_PER_MASK      3UL << MPC_SEC_PER0_DOM2_NSE_PER_SHIFT
#define MPC_SEC_PER0_DOM2_SEC_PER_SHIFT     SEC_PER0_DOM2_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER0_DOM2_SEC_PER_MASK      3UL << MPC_SEC_PER0_DOM2_SEC_PER_SHIFT
#define MPC_SEC_PER0_DOM2_SEC_EN_SHIFT      SEC_PER0_DOM2_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER0_DOM2_SEC_EN_MASK       1UL << MPC_SEC_PER0_DOM2_SEC_EN_SHIFT
#define MPC_SEC_PER0_DOM1_LOCK_SHIFT        SEC_PER0_DOM1_LOCK_FIELD_OFFSET
#define MPC_SEC_PER0_DOM1_LOCK_MASK         1UL << MPC_SEC_PER0_DOM1_LOCK_SHIFT
#define MPC_SEC_PER0_DOM1_NSE_PER_SHIFT     SEC_PER0_DOM1_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER0_DOM1_NSE_PER_MASK      3UL << MPC_SEC_PER0_DOM1_NSE_PER_SHIFT
#define MPC_SEC_PER0_DOM1_SEC_PER_SHIFT     SEC_PER0_DOM1_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER0_DOM1_SEC_PER_MASK      3UL << MPC_SEC_PER0_DOM1_SEC_PER_SHIFT
#define MPC_SEC_PER0_DOM1_SEC_EN_SHIFT      SEC_PER0_DOM1_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER0_DOM1_SEC_EN_MASK       1UL << MPC_SEC_PER0_DOM1_SEC_EN_SHIFT
#define MPC_SEC_PER0_DOM0_LOCK_SHIFT        SEC_PER0_DOM0_LOCK_FIELD_OFFSET
#define MPC_SEC_PER0_DOM0_LOCK_MASK         1UL << MPC_SEC_PER0_DOM0_LOCK_SHIFT
#define MPC_SEC_PER0_DOM0_NSE_PER_SHIFT     SEC_PER0_DOM0_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER0_DOM0_NSE_PER_MASK      3UL << MPC_SEC_PER0_DOM0_NSE_PER_SHIFT
#define MPC_SEC_PER0_DOM0_SEC_PER_SHIFT     SEC_PER0_DOM0_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER0_DOM0_SEC_PER_MASK      3UL << MPC_SEC_PER0_DOM0_SEC_PER_SHIFT
#define MPC_SEC_PER0_DOM0_SEC_EN_SHIFT      SEC_PER0_DOM0_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER0_DOM0_SEC_EN_MASK       1UL << MPC_SEC_PER0_DOM0_SEC_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_SEC_PER1
// Register Offset : 0x10
// Description     :
//--------------------------------------------------------------------------
#define MPC_SEC_PER1_(i)                    (REG_AP_APB_MPC_SEC_PER1 + (i) * MPC_CTRL_JUMP)
#define MPC_SEC_PER1_DOM7_LOCK_SHIFT        SEC_PER1_DOM7_LOCK_FIELD_OFFSET
#define MPC_SEC_PER1_DOM7_LOCK_MASK         1UL << MPC_SEC_PER1_DOM7_LOCK_SHIFT
#define MPC_SEC_PER1_DOM7_NSE_PER_SHIFT      SEC_PER1_DOM7_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER1_DOM7_NSE_PER_MASK      3UL << MPC_SEC_PER1_DOM7_NSE_PER_SHIFT
#define MPC_SEC_PER1_DOM7_SEC_PER_SHIFT     SEC_PER1_DOM7_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER1_DOM7_SEC_PER_MASK      3UL << MPC_SEC_PER1_DOM7_SEC_PER_SHIFT
#define MPC_SEC_PER1_DOM7_SEC_EN_SHIFT      SEC_PER1_DOM7_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER1_DOM7_SEC_EN_MASK       1UL << MPC_SEC_PER1_DOM7_SEC_EN_SHIFT
#define MPC_SEC_PER1_DOM6_LOCK_SHIFT        SEC_PER1_DOM6_LOCK_FIELD_OFFSET
#define MPC_SEC_PER1_DOM6_LOCK_MASK         1UL << MPC_SEC_PER1_DOM6_LOCK_SHIFT
#define MPC_SEC_PER1_DOM6_NSE_PER_SHIFT     SEC_PER1_DOM6_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER1_DOM6_NSE_PER_MASK      3UL << MPC_SEC_PER1_DOM6_NSE_PER_SHIFT
#define MPC_SEC_PER1_DOM6_SEC_PER_SHIFT     SEC_PER1_DOM6_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER1_DOM6_SEC_PER_MASK      3UL << MPC_SEC_PER1_DOM6_SEC_PER_SHIFT
#define MPC_SEC_PER1_DOM6_SEC_EN_SHIFT      SEC_PER1_DOM6_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER1_DOM6_SEC_EN_MASK       1UL << MPC_SEC_PER1_DOM6_SEC_EN_SHIFT
#define MPC_SEC_PER1_DOM5_LOCK_SHIFT        SEC_PER1_DOM5_LOCK_FIELD_OFFSET
#define MPC_SEC_PER1_DOM5_LOCK_MASK         1UL << MPC_SEC_PER1_DOM5_LOCK_SHIFT
#define MPC_SEC_PER1_DOM5_NSE_PER_SHIFT     SEC_PER1_DOM5_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER1_DOM5_NSE_PER_MASK      3UL << MPC_SEC_PER1_DOM5_NSE_PER_SHIFT
#define MPC_SEC_PER1_DOM5_SEC_PER_SHIFT     SEC_PER1_DOM5_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER1_DOM5_SEC_PER_MASK      3UL << MPC_SEC_PER1_DOM5_SEC_PER_SHIFT
#define MPC_SEC_PER1_DOM5_SEC_EN_SHIFT      SEC_PER1_DOM5_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER1_DOM5_SEC_EN_MASK       1UL << MPC_SEC_PER1_DOM5_SEC_EN_SHIFT
#define MPC_SEC_PER1_DOM4_LOCK_SHIFT        SEC_PER1_DOM4_LOCK_FIELD_OFFSET
#define MPC_SEC_PER1_DOM4_LOCK_MASK         1UL << MPC_SEC_PER1_DOM4_LOCK_SHIFT
#define MPC_SEC_PER1_DOM4_NSE_PER_SHIFT     SEC_PER1_DOM4_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER1_DOM4_NSE_PER_MASK      3UL << MPC_SEC_PER1_DOM4_NSE_PER_SHIFT
#define MPC_SEC_PER1_DOM4_SEC_PER_SHIFT     SEC_PER1_DOM4_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER1_DOM4_SEC_PER_MASK      3UL << MPC_SEC_PER1_DOM4_SEC_PER_SHIFT
#define MPC_SEC_PER1_DOM4_SEC_EN_SHIFT      SEC_PER1_DOM4_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER1_DOM4_SEC_EN_MASK       1UL << MPC_SEC_PER1_DOM4_SEC_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_SEC_PER2
// Register Offset : 0x14
// Description     :
//--------------------------------------------------------------------------
#define MPC_SEC_PER2_(i)                    (REG_AP_APB_MPC_SEC_PER2 + (i) * MPC_CTRL_JUMP)
#define MPC_SEC_PER2_DOM11_LOCK_SHIFT       SEC_PER2_DOM11_LOCK_FIELD_OFFSET
#define MPC_SEC_PER2_DOM11_LOCK_MASK        1UL << MPC_SEC_PER2_DOM11_LOCK_SHIFT
#define MPC_SEC_PER2_DOM11_NSE_PER_SHIFT    SEC_PER2_DOM11_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER2_DOM11_NSE_PER_MASK     3UL << MPC_SEC_PER2_DOM11_NSE_PER_SHIFT
#define MPC_SEC_PER2_DOM11_SEC_PER_SHIFT    SEC_PER2_DOM11_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER2_DOM11_SEC_PER_MASK     3UL << MPC_SEC_PER2_DOM11_SEC_PER_SHIFT
#define MPC_SEC_PER2_DOM11_SEC_EN_SHIFT     SEC_PER2_DOM11_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER2_DOM11_SEC_EN_MASK      1UL << MPC_SEC_PER2_DOM11_SEC_EN_SHIFT
#define MPC_SEC_PER2_DOM10_LOCK_SHIFT       SEC_PER2_DOM10_LOCK_FIELD_OFFSET
#define MPC_SEC_PER2_DOM10_LOCK_MASK        1UL << MPC_SEC_PER2_DOM10_LOCK_SHIFT
#define MPC_SEC_PER2_DOM10_NSE_PER_SHIFT    SEC_PER2_DOM10_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER2_DOM10_NSE_PER_MASK     3UL << MPC_SEC_PER2_DOM10_NSE_PER_SHIFT
#define MPC_SEC_PER2_DOM10_SEC_PER_SHIFT    SEC_PER2_DOM10_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER2_DOM10_SEC_PER_MASK     3UL << MPC_SEC_PER2_DOM10_SEC_PER_SHIFT
#define MPC_SEC_PER2_DOM10_SEC_EN_SHIFT     SEC_PER2_DOM10_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER2_DOM10_SEC_EN_MASK      1UL << MPC_SEC_PER2_DOM10_SEC_EN_SHIFT
#define MPC_SEC_PER2_DOM9_LOCK_SHIFT        SEC_PER2_DOM9_LOCK_FIELD_OFFSET
#define MPC_SEC_PER2_DOM9_LOCK_MASK         1UL << MPC_SEC_PER2_DOM9_LOCK_SHIFT
#define MPC_SEC_PER2_DOM9_NSE_PER_SHIFT     SEC_PER2_DOM9_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER2_DOM9_NSE_PER_MASK      3UL << MPC_SEC_PER2_DOM9_NSE_PER_SHIFT
#define MPC_SEC_PER2_DOM9_SEC_PER_SHIFT     SEC_PER2_DOM9_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER2_DOM9_SEC_PER_MASK      3UL << MPC_SEC_PER2_DOM9_SEC_PER_SHIFT
#define MPC_SEC_PER2_DOM9_SEC_EN_SHIFT      SEC_PER2_DOM9_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER2_DOM9_SEC_EN_MASK       1UL << MPC_SEC_PER2_DOM9_SEC_EN_SHIFT
#define MPC_SEC_PER2_DOM8_LOCK_SHIFT        SEC_PER2_DOM8_LOCK_FIELD_OFFSET
#define MPC_SEC_PER2_DOM8_LOCK_MASK         1UL << MPC_SEC_PER2_DOM8_LOCK_SHIFT
#define MPC_SEC_PER2_DOM8_NSE_PER_SHIFT     SEC_PER2_DOM8_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER2_DOM8_NSE_PER_MASK      3UL << MPC_SEC_PER2_DOM8_NSE_PER_SHIFT
#define MPC_SEC_PER2_DOM8_SEC_PER_SHIFT     SEC_PER2_DOM8_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER2_DOM8_SEC_PER_MASK      3UL << MPC_SEC_PER2_DOM8_SEC_PER_SHIFT
#define MPC_SEC_PER2_DOM8_SEC_EN_SHIFT      SEC_PER2_DOM8_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER2_DOM8_SEC_EN_MASK       1UL << MPC_SEC_PER2_DOM8_SEC_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_SEC_PER3
// Register Offset : 0x18
// Description     :
//--------------------------------------------------------------------------
#define MPC_SEC_PER3_(i)                    (REG_AP_APB_MPC_SEC_PER3 + (i) * MPC_CTRL_JUMP)
#define MPC_SEC_PER3_DOM15_LOCK_SHIFT       SEC_PER3_DOM15_LOCK_FIELD_OFFSET
#define MPC_SEC_PER3_DOM15_LOCK_MASK        1UL << MPC_SEC_PER3_DOM15_LOCK_SHIFT
#define MPC_SEC_PER3_DOM15_NSE_PER_SHIFT    SEC_PER3_DOM15_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER3_DOM15_NSE_PER_MASK     3UL << MPC_SEC_PER3_DOM15_NSE_PER_SHIFT
#define MPC_SEC_PER3_DOM15_SEC_PER_SHIFT    SEC_PER3_DOM15_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER3_DOM15_SEC_PER_MASK     3UL << MPC_SEC_PER3_DOM15_SEC_PER_SHIFT
#define MPC_SEC_PER3_DOM15_SEC_EN_SHIFT     SEC_PER3_DOM15_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER3_DOM15_SEC_EN_MASK      1UL << MPC_SEC_PER3_DOM15_SEC_EN_SHIFT
#define MPC_SEC_PER3_DOM14_LOCK_SHIFT       SEC_PER3_DOM14_LOCK_FIELD_OFFSET
#define MPC_SEC_PER3_DOM14_LOCK_MASK        1UL << MPC_SEC_PER3_DOM14_LOCK_SHIFT
#define MPC_SEC_PER3_DOM14_NSE_PER_SHIFT    SEC_PER3_DOM14_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER3_DOM14_NSE_PER_MASK     3UL << MPC_SEC_PER3_DOM14_NSE_PER_SHIFT
#define MPC_SEC_PER3_DOM14_SEC_PER_SHIFT    SEC_PER3_DOM14_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER3_DOM14_SEC_PER_MASK     3UL << MPC_SEC_PER3_DOM14_SEC_PER_SHIFT
#define MPC_SEC_PER3_DOM14_SEC_EN_SHIFT     SEC_PER3_DOM14_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER3_DOM14_SEC_EN_MASK      1UL << MPC_SEC_PER3_DOM14_SEC_EN_SHIFT
#define MPC_SEC_PER3_DOM13_LOCK_SHIFT       SEC_PER3_DOM13_LOCK_FIELD_OFFSET
#define MPC_SEC_PER3_DOM13_LOCK_MASK        1UL << MPC_SEC_PER3_DOM13_LOCK_SHIFT
#define MPC_SEC_PER3_DOM13_NSE_PER_SHIFT    SEC_PER3_DOM13_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER3_DOM13_NSE_PER_MASK     3UL << MPC_SEC_PER3_DOM13_NSE_PER_SHIFT
#define MPC_SEC_PER3_DOM13_SEC_PER_SHIFT    SEC_PER3_DOM13_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER3_DOM13_SEC_PER_MASK     3UL << MPC_SEC_PER3_DOM13_SEC_PER_SHIFT
#define MPC_SEC_PER3_DOM13_SEC_EN_SHIFT     SEC_PER3_DOM13_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER3_DOM13_SEC_EN_MASK      1UL << MPC_SEC_PER3_DOM13_SEC_EN_SHIFT
#define MPC_SEC_PER3_DOM12_LOCK_SHIFT       SEC_PER3_DOM12_LOCK_FIELD_OFFSET
#define MPC_SEC_PER3_DOM12_LOCK_MASK        1UL << MPC_SEC_PER3_DOM12_LOCK_SHIFT
#define MPC_SEC_PER3_DOM12_NSE_PER_SHIFT    SEC_PER3_DOM12_NSE_PER_FIELD_OFFSET
#define MPC_SEC_PER3_DOM12_NSE_PER_MASK     3UL << MPC_SEC_PER3_DOM12_NSE_PER_SHIFT
#define MPC_SEC_PER3_DOM12_SEC_PER_SHIFT    SEC_PER3_DOM12_SEC_PER_FIELD_OFFSET
#define MPC_SEC_PER3_DOM12_SEC_PER_MASK     3UL << MPC_SEC_PER3_DOM12_SEC_PER_SHIFT
#define MPC_SEC_PER3_DOM12_SEC_EN_SHIFT     SEC_PER3_DOM12_SEC_EN_FIELD_OFFSET
#define MPC_SEC_PER3_DOM12_SEC_EN_MASK      1UL << MPC_SEC_PER3_DOM12_SEC_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_PRI_PER0
// Register Offset : 0x1c
// Description     :
//--------------------------------------------------------------------------
#define MPC_PRI_PER0_(i)                    (REG_AP_APB_MPC_PRI_PER0 + (i) * MPC_CTRL_JUMP)
#define MPC_PRI_PER0_DOM3_LOCK_SHIFT        PRI_PER0_DOM3_LOCK_FIELD_OFFSET
#define MPC_PRI_PER0_DOM3_LOCK_MASK         1UL << MPC_PRI_PER0_DOM3_LOCK_SHIFT
#define MPC_PRI_PER0_DOM3_USE_PER_SHIFT     PRI_PER0_DOM3_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER0_DOM3_USE_PER_MASK      3UL << MPC_PRI_PER0_DOM3_USE_PER_SHIFT
#define MPC_PRI_PER0_DOM3_PRI_PER_SHIFT     PRI_PER0_DOM3_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER0_DOM3_PRI_PER_MASK      3UL << MPC_PRI_PER0_DOM3_PRI_PER_SHIFT
#define MPC_PRI_PER0_DOM3_PRI_EN_SHIFT      PRI_PER0_DOM3_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER0_DOM3_PRI_EN_MASK       1UL << MPC_PRI_PER0_DOM3_PRI_EN_SHIFT
#define MPC_PRI_PER0_DOM2_LOCK_SHIFT        PRI_PER0_DOM2_LOCK_FIELD_OFFSET
#define MPC_PRI_PER0_DOM2_LOCK_MASK         1UL << MPC_PRI_PER0_DOM2_LOCK_SHIFT
#define MPC_PRI_PER0_DOM2_USE_PER_SHIFT     PRI_PER0_DOM2_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER0_DOM2_USE_PER_MASK      3UL << MPC_PRI_PER0_DOM2_USE_PER_SHIFT
#define MPC_PRI_PER0_DOM2_PRI_PER_SHIFT     PRI_PER0_DOM2_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER0_DOM2_PRI_PER_MASK      3UL << MPC_PRI_PER0_DOM2_PRI_PER_SHIFT
#define MPC_PRI_PER0_DOM2_PRI_EN_SHIFT      PRI_PER0_DOM2_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER0_DOM2_PRI_EN_MASK       1UL << MPC_PRI_PER0_DOM2_PRI_EN_SHIFT
#define MPC_PRI_PER0_DOM1_LOCK_SHIFT        PRI_PER0_DOM1_LOCK_FIELD_OFFSET
#define MPC_PRI_PER0_DOM1_LOCK_MASK         1UL << MPC_PRI_PER0_DOM1_LOCK_SHIFT
#define MPC_PRI_PER0_DOM1_USE_PER_SHIFT     PRI_PER0_DOM1_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER0_DOM1_USE_PER_MASK      3UL << MPC_PRI_PER0_DOM1_USE_PER_SHIFT
#define MPC_PRI_PER0_DOM1_PRI_PER_SHIFT     PRI_PER0_DOM1_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER0_DOM1_PRI_PER_MASK      3UL << MPC_PRI_PER0_DOM1_PRI_PER_SHIFT
#define MPC_PRI_PER0_DOM1_PRI_EN_SHIFT      PRI_PER0_DOM1_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER0_DOM1_PRI_EN_MASK       1UL << MPC_PRI_PER0_DOM1_PRI_EN_SHIFT
#define MPC_PRI_PER0_DOM0_LOCK_SHIFT        PRI_PER0_DOM0_LOCK_FIELD_OFFSET
#define MPC_PRI_PER0_DOM0_LOCK_MASK         1UL << MPC_PRI_PER0_DOM0_LOCK_SHIFT
#define MPC_PRI_PER0_DOM0_USE_PER_SHIFT     PRI_PER0_DOM0_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER0_DOM0_USE_PER_MASK      3UL << MPC_PRI_PER0_DOM0_USE_PER_SHIFT
#define MPC_PRI_PER0_DOM0_PRI_PER_SHIFT     PRI_PER0_DOM0_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER0_DOM0_PRI_PER_MASK      3UL << MPC_PRI_PER0_DOM0_PRI_PER_SHIFT
#define MPC_PRI_PER0_DOM0_PRI_EN_SHIFT      PRI_PER0_DOM0_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER0_DOM0_PRI_EN_MASK       1UL << MPC_PRI_PER0_DOM0_PRI_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_PRI_PER1
// Register Offset : 0x20
// Description     :
//--------------------------------------------------------------------------
#define MPC_PRI_PER1_(i)                    (REG_AP_APB_MPC_PRI_PER1 + (i) * MPC_CTRL_JUMP)
#define MPC_PRI_PER1_DOM7_LOCK_SHIFT        PRI_PER1_DOM7_LOCK_FIELD_OFFSET
#define MPC_PRI_PER1_DOM7_LOCK_MASK         1UL << MPC_PRI_PER1_DOM7_LOCK_SHIFT
#define MPC_PRI_PER1_DOM7_USE_PER_SHIFT     PRI_PER1_DOM7_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER1_DOM7_USE_PER_MASK      3UL << MPC_PRI_PER1_DOM7_USE_PER_SHIFT
#define MPC_PRI_PER1_DOM7_PRI_PER_SHIFT     PRI_PER1_DOM7_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER1_DOM7_PRI_PER_MASK      3UL << MPC_PRI_PER1_DOM7_PRI_PER_SHIFT
#define MPC_PRI_PER1_DOM7_PRI_EN_SHIFT      PRI_PER1_DOM7_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER1_DOM7_PRI_EN_MASK       1UL << MPC_PRI_PER1_DOM7_PRI_EN_SHIFT
#define MPC_PRI_PER1_DOM6_LOCK_SHIFT        PRI_PER1_DOM6_LOCK_FIELD_OFFSET
#define MPC_PRI_PER1_DOM6_LOCK_MASK         1UL << MPC_PRI_PER1_DOM6_LOCK_SHIFT
#define MPC_PRI_PER1_DOM6_USE_PER_SHIFT     PRI_PER1_DOM6_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER1_DOM6_USE_PER_MASK      3UL << MPC_PRI_PER1_DOM6_USE_PER_SHIFT
#define MPC_PRI_PER1_DOM6_PRI_PER_SHIFT     PRI_PER1_DOM6_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER1_DOM6_PRI_PER_MASK      3UL << MPC_PRI_PER1_DOM6_PRI_PER_SHIFT
#define MPC_PRI_PER1_DOM6_PRI_EN_SHIFT      PRI_PER1_DOM6_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER1_DOM6_PRI_EN_MASK       1UL << MPC_PRI_PER1_DOM6_PRI_EN_SHIFT
#define MPC_PRI_PER1_DOM5_LOCK_SHIFT        PRI_PER1_DOM5_LOCK_FIELD_OFFSET
#define MPC_PRI_PER1_DOM5_LOCK_MASK         1UL << MPC_PRI_PER1_DOM5_LOCK_SHIFT
#define MPC_PRI_PER1_DOM5_USE_PER_SHIFT     PRI_PER1_DOM5_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER1_DOM5_USE_PER_MASK      3UL << MPC_PRI_PER1_DOM5_USE_PER_SHIFT
#define MPC_PRI_PER1_DOM5_PRI_PER_SHIFT     PRI_PER1_DOM5_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER1_DOM5_PRI_PER_MASK      3UL << MPC_PRI_PER1_DOM5_PRI_PER_SHIFT
#define MPC_PRI_PER1_DOM5_PRI_EN_SHIFT      PRI_PER1_DOM5_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER1_DOM5_PRI_EN_MASK       1UL << MPC_PRI_PER1_DOM5_PRI_EN_SHIFT
#define MPC_PRI_PER1_DOM4_LOCK_SHIFT        PRI_PER1_DOM4_LOCK_FIELD_OFFSET
#define MPC_PRI_PER1_DOM4_LOCK_MASK         1UL << MPC_PRI_PER1_DOM4_LOCK_SHIFT
#define MPC_PRI_PER1_DOM4_USE_PER_SHIFT     PRI_PER1_DOM4_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER1_DOM4_USE_PER_MASK      3UL << MPC_PRI_PER1_DOM4_USE_PER_SHIFT
#define MPC_PRI_PER1_DOM4_PRI_PER_SHIFT     PRI_PER1_DOM4_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER1_DOM4_PRI_PER_MASK      3UL << MPC_PRI_PER1_DOM4_PRI_PER_SHIFT
#define MPC_PRI_PER1_DOM4_PRI_EN_SHIFT      PRI_PER1_DOM4_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER1_DOM4_PRI_EN_MASK       1UL << MPC_PRI_PER1_DOM4_PRI_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_PRI_PER2
// Register Offset : 0x24
// Description     :
//--------------------------------------------------------------------------
#define MPC_PRI_PER2_(i)                    (REG_AP_APB_MPC_PRI_PER2 + (i) * MPC_CTRL_JUMP)
#define MPC_PRI_PER2_DOM11_LOCK_SHIFT       PRI_PER2_DOM11_LOCK_FIELD_OFFSET
#define MPC_PRI_PER2_DOM11_LOCK_MASK        1UL << MPC_PRI_PER2_DOM11_LOCK_SHIFT
#define MPC_PRI_PER2_DOM11_USE_PER_SHIFT    PRI_PER2_DOM11_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER2_DOM11_USE_PER_MASK     3UL << MPC_PRI_PER2_DOM11_USE_PER_SHIFT
#define MPC_PRI_PER2_DOM11_PRI_PER_SHIFT    PRI_PER2_DOM11_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER2_DOM11_PRI_PER_MASK     3UL << MPC_PRI_PER2_DOM11_PRI_PER_SHIFT
#define MPC_PRI_PER2_DOM11_PRI_EN_SHIFT     PRI_PER2_DOM11_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER2_DOM11_PRI_EN_MASK      1UL << MPC_PRI_PER2_DOM11_PRI_EN_SHIFT
#define MPC_PRI_PER2_DOM10_LOCK_SHIFT       PRI_PER2_DOM10_LOCK_FIELD_OFFSET
#define MPC_PRI_PER2_DOM10_LOCK_MASK        1UL << MPC_PRI_PER2_DOM10_LOCK_SHIFT
#define MPC_PRI_PER2_DOM10_USE_PER_SHIFT    PRI_PER2_DOM10_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER2_DOM10_USE_PER_MASK     3UL << MPC_PRI_PER2_DOM10_USE_PER_SHIFT
#define MPC_PRI_PER2_DOM10_PRI_PER_SHIFT    PRI_PER2_DOM10_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER2_DOM10_PRI_PER_MASK     3UL << MPC_PRI_PER2_DOM10_PRI_PER_SHIFT
#define MPC_PRI_PER2_DOM10_PRI_EN_SHIFT     PRI_PER2_DOM10_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER2_DOM10_PRI_EN_MASK      1UL << MPC_PRI_PER2_DOM10_PRI_EN_SHIFT
#define MPC_PRI_PER2_DOM9_LOCK_SHIFT        PRI_PER2_DOM9_LOCK_FIELD_OFFSET
#define MPC_PRI_PER2_DOM9_LOCK_MASK         1UL << MPC_PRI_PER2_DOM9_LOCK_SHIFT
#define MPC_PRI_PER2_DOM9_USE_PER_SHIFT     PRI_PER2_DOM9_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER2_DOM9_USE_PER_MASK      3UL << MPC_PRI_PER2_DOM9_USE_PER_SHIFT
#define MPC_PRI_PER2_DOM9_PRI_PER_SHIFT     PRI_PER2_DOM9_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER2_DOM9_PRI_PER_MASK      3UL << MPC_PRI_PER2_DOM9_PRI_PER_SHIFT
#define MPC_PRI_PER2_DOM9_PRI_EN_SHIFT      PRI_PER2_DOM9_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER2_DOM9_PRI_EN_MASK       1UL << MPC_PRI_PER2_DOM9_PRI_EN_SHIFT
#define MPC_PRI_PER2_DOM8_LOCK_SHIFT        PRI_PER2_DOM8_LOCK_FIELD_OFFSET
#define MPC_PRI_PER2_DOM8_LOCK_MASK         1UL << MPC_PRI_PER2_DOM8_LOCK_SHIFT
#define MPC_PRI_PER2_DOM8_USE_PER_SHIFT     PRI_PER2_DOM8_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER2_DOM8_USE_PER_MASK      3UL << MPC_PRI_PER2_DOM8_USE_PER_SHIFT
#define MPC_PRI_PER2_DOM8_PRI_PER_SHIFT     PRI_PER2_DOM8_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER2_DOM8_PRI_PER_MASK      3UL << MPC_PRI_PER2_DOM8_PRI_PER_SHIFT
#define MPC_PRI_PER2_DOM8_PRI_EN_SHIFT      PRI_PER2_DOM8_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER2_DOM8_PRI_EN_MASK       1UL << MPC_PRI_PER2_DOM8_PRI_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_PRI_PER3
// Register Offset : 0x28
// Description     :
//--------------------------------------------------------------------------
#define MPC_PRI_PER3_(i)                    (REG_AP_APB_MPC_PRI_PER3 + (i) * MPC_CTRL_JUMP)
#define MPC_PRI_PER3_DOM15_LOCK_SHIFT       PRI_PER3_DOM15_LOCK_FIELD_OFFSET
#define MPC_PRI_PER3_DOM15_LOCK_MASK        1UL << MPC_PRI_PER3_DOM15_LOCK_SHIFT
#define MPC_PRI_PER3_DOM15_USE_PER_SHIFT    PRI_PER3_DOM15_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER3_DOM15_USE_PER_MASK     3UL << MPC_PRI_PER3_DOM15_USE_PER_SHIFT
#define MPC_PRI_PER3_DOM15_PRI_PER_SHIFT    PRI_PER3_DOM15_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER3_DOM15_PRI_PER_MASK     3UL << MPC_PRI_PER3_DOM15_PRI_PER_SHIFT
#define MPC_PRI_PER3_DOM15_PRI_EN_SHIFT     PRI_PER3_DOM15_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER3_DOM15_PRI_EN_MASK      1UL << MPC_PRI_PER3_DOM15_PRI_EN_SHIFT
#define MPC_PRI_PER3_DOM14_LOCK_SHIFT       PRI_PER3_DOM14_LOCK_FIELD_OFFSET
#define MPC_PRI_PER3_DOM14_LOCK_MASK        1UL << MPC_PRI_PER3_DOM14_LOCK_SHIFT
#define MPC_PRI_PER3_DOM14_USE_PER_SHIFT    PRI_PER3_DOM14_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER3_DOM14_USE_PER_MASK     3UL << MPC_PRI_PER3_DOM14_USE_PER_SHIFT
#define MPC_PRI_PER3_DOM14_PRI_PER_SHIFT    PRI_PER3_DOM14_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER3_DOM14_PRI_PER_MASK     3UL << MPC_PRI_PER3_DOM14_PRI_PER_SHIFT
#define MPC_PRI_PER3_DOM14_PRI_EN_SHIFT     PRI_PER3_DOM14_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER3_DOM14_PRI_EN_MASK      1UL << MPC_PRI_PER3_DOM14_PRI_EN_SHIFT
#define MPC_PRI_PER3_DOM13_LOCK_SHIFT       PRI_PER3_DOM13_LOCK_FIELD_OFFSET
#define MPC_PRI_PER3_DOM13_LOCK_MASK        1UL << MPC_PRI_PER3_DOM13_LOCK_SHIFT
#define MPC_PRI_PER3_DOM13_USE_PER_SHIFT    PRI_PER3_DOM13_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER3_DOM13_USE_PER_MASK     3UL << MPC_PRI_PER3_DOM13_USE_PER_SHIFT
#define MPC_PRI_PER3_DOM13_PRI_PER_SHIFT    PRI_PER3_DOM13_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER3_DOM13_PRI_PER_MASK     3UL << MPC_PRI_PER3_DOM13_PRI_PER_SHIFT
#define MPC_PRI_PER3_DOM13_PRI_EN_SHIFT     PRI_PER3_DOM13_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER3_DOM13_PRI_EN_MASK      1UL << MPC_PRI_PER3_DOM13_PRI_EN_SHIFT
#define MPC_PRI_PER3_DOM12_LOCK_SHIFT       PRI_PER3_DOM12_LOCK_FIELD_OFFSET
#define MPC_PRI_PER3_DOM12_LOCK_MASK        1UL << MPC_PRI_PER3_DOM12_LOCK_SHIFT
#define MPC_PRI_PER3_DOM12_USE_PER_SHIFT    PRI_PER3_DOM12_USE_PER_FIELD_OFFSET
#define MPC_PRI_PER3_DOM12_USE_PER_MASK     3UL << MPC_PRI_PER3_DOM12_USE_PER_SHIFT
#define MPC_PRI_PER3_DOM12_PRI_PER_SHIFT    PRI_PER3_DOM12_PRI_PER_FIELD_OFFSET
#define MPC_PRI_PER3_DOM12_PRI_PER_MASK     3UL << MPC_PRI_PER3_DOM12_PRI_PER_SHIFT
#define MPC_PRI_PER3_DOM12_PRI_EN_SHIFT     PRI_PER3_DOM12_PRI_EN_FIELD_OFFSET
#define MPC_PRI_PER3_DOM12_PRI_EN_MASK      1UL << MPC_PRI_PER3_DOM12_PRI_EN_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_RGN_START_ADDR
// Register Offset : 0x800
// Description     :
//--------------------------------------------------------------------------
#define MPC_RNG_JUMP                        0x10
#define MPC_RGN_START_ADDR_(i)              (REG_AP_APB_MPC_RGN_START_ADDR + (i) * MPC_RNG_JUMP)
#define MPC_RGN_START_ADDR_SHIFT            RGN_START_ADDR_START_ADDR_FIELD_OFFSET
#define MPC_RGN_START_ADDR_MASK             0x3FFFFFFF << MPC_RGN_START_ADDR_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_RGN_END_ADDR
// Register Offset : 0x804
// Description     :
//--------------------------------------------------------------------------
#define MPC_RGN_END_ADDR_(i)                (REG_AP_APB_MPC_RGN_END_ADDR + (i) * MPC_RNG_JUMP)
#define MPC_RGN_LOCK_SHIFT                  RGN_END_ADDR_LOCK_FIELD_OFFSET
#define MPC_RGN_LOCK_MASK                   1UL << MPC_RGN_LOCK_SHIFT
#define MPC_RGN_RGN_EN_SHIFT                RGN_END_ADDR_RGN_EN_FIELD_OFFSET
#define MPC_RGN_RGN_EN_MASK                 1UL << MPC_RGN_RGN_EN_SHIFT
#define MPC_RGN_END_ADDR_SHIFT              RGN_END_ADDR_END_ADDR_FIELD_OFFSET
#define MPC_RGN_END_ADDR_MASK               0x3FFFFFFF << MPC_RGN_END_ADDR_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_RGN_LOW_LIM
// Register Offset : 0x808
// Description     :
//--------------------------------------------------------------------------
#define MPC_RGN_LOW_LIM_(i)                 (REG_AP_APB_MPC_RGN_LOW_LIM + (i) * MPC_RNG_JUMP)
#define MPC_RGN_LOW_LIM_SHIFT               RGN_LOW_LIM_LOW_LIM_FIELD_OFFSET
#define MPC_RGN_LOW_LIM_MASK                0x3FFFFFFF << MPC_RGN_LOW_LIM_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_RGN_UP_LIM
// Register Offset : 0x80c
// Description     :
//--------------------------------------------------------------------------
#define MPC_RGN_UP_LIM_(i)                  (REG_AP_APB_MPC_RGN_UP_LIM + (i) * MPC_RNG_JUMP)
#define MPC_RGN_LIM_LOCK_SHIFT              RGN_UP_LIM_LOCK_FIELD_OFFSET
#define MPC_RGN_LIM_LOCK_MASK               1UL << MPC_RGN_LIM_LOCK_SHIFT
#define MPC_RGN_UP_LIM_SHIFT                RGN_UP_LIM_UP_LIM_FIELD_OFFSET
#define MPC_RGN_UP_LIM_MASK                 0x3FFFFFFF << MPC_RGN_UP_LIM_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_UNCERR_INT_STA/EN/SIG
// Register Offset : 0xf00/0xf04/0xf08
// Description     : shift/mash abstract for 3 uncorrect error registers
//--------------------------------------------------------------------------
#define MPC_UNCERR_INT_BREADY_SHIFT         UNCERR_INT_STA_BREADY_FIELD_OFFSET
#define MPC_UNCERR_INT_BREADY_MASK          1UL << MPC_UNCERR_INT_BREADY_SHIFT
#define MPC_UNCERR_INT_BVALID_SHIFT         UNCERR_INT_STA_BVALID_FIELD_OFFSET
#define MPC_UNCERR_INT_BVALID_MASK          1UL << MPC_UNCERR_INT_BVALID_SHIFT
#define MPC_UNCERR_INT_BID_SHIFT            UNCERR_INT_STA_BID_FIELD_OFFSET
#define MPC_UNCERR_INT_BID_MASK             1UL << MPC_UNCERR_INT_BID_SHIFT
#define MPC_UNCERR_INT_WREADY_SHIFT         UNCERR_INT_STA_WREADY_FIELD_OFFSET
#define MPC_UNCERR_INT_WREADY_MASK          1UL << MPC_UNCERR_INT_WREADY_SHIFT
#define MPC_UNCERR_INT_WVALID_SHIFT         UNCERR_INT_STA_WVALID_FIELD_OFFSET
#define MPC_UNCERR_INT_WVALID_MASK          1UL << MPC_UNCERR_INT_WVALID_SHIFT
#define MPC_UNCERR_INT_WCTL_SHIFT           UNCERR_INT_STA_WCTL_FIELD_OFFSET
#define MPC_UNCERR_INT_WCTL_MASK            1UL << MPC_UNCERR_INT_WCTL_SHIFT
#define MPC_UNCERR_INT_RREADY_SHIFT         UNCERR_INT_STA_RREADY_FIELD_OFFSET
#define MPC_UNCERR_INT_RREADY_MASK          1UL << MPC_UNCERR_INT_RREADY_SHIFT
#define MPC_UNCERR_INT_RVALID_SHIFT         UNCERR_INT_STA_RVALID_FIELD_OFFSET
#define MPC_UNCERR_INT_RVALID_MASK          1UL << MPC_UNCERR_INT_RVALID_SHIFT
#define MPC_UNCERR_INT_REOBI_SHIFT          UNCERR_INT_STA_REOBI_FIELD_OFFSET
#define MPC_UNCERR_INT_REOBI_MASK           1UL << MPC_UNCERR_INT_REOBI_SHIFT
#define MPC_UNCERR_INT_RCTL_SHIFT           UNCERR_INT_STA_RCTL_FIELD_OFFSET
#define MPC_UNCERR_INT_RCTL_MASK            1UL << MPC_UNCERR_INT_RCTL_SHIFT
#define MPC_UNCERR_INT_RID_SHIFT            UNCERR_INT_STA_RID_FIELD_OFFSET
#define MPC_UNCERR_INT_RID_MASK             1UL << MPC_UNCERR_INT_RID_SHIFT
#define MPC_UNCERR_INT_AWREADY_SHIFT        UNCERR_INT_STA_AWREADY_FIELD_OFFSET
#define MPC_UNCERR_INT_AWREADY_MASK         1UL << MPC_UNCERR_INT_AWREADY_SHIFT
#define MPC_UNCERR_INT_AWVALID_SHIFT        UNCERR_INT_STA_AWVALID_FIELD_OFFSET
#define MPC_UNCERR_INT_AWVALID_MASK         1UL << MPC_UNCERR_INT_AWVALID_SHIFT
#define MPC_UNCERR_INT_AWCTL1_SHIFT         UNCERR_INT_STA_AWCTL1_FIELD_OFFSET
#define MPC_UNCERR_INT_AWCTL1_MASK          1UL << MPC_UNCERR_INT_AWCTL1_SHIFT
#define MPC_UNCERR_INT_AWCTL0_SHIFT         UNCERR_INT_STA_AWCTL0_FIELD_OFFSET
#define MPC_UNCERR_INT_AWCTL0_MASK          1UL << MPC_UNCERR_INT_AWCTL0_SHIFT
#define MPC_UNCERR_INT_AWADDR_SHIFT         UNCERR_INT_STA_AWADDR_FIELD_OFFSET
#define MPC_UNCERR_INT_AWADDR_MASK          1UL << MPC_UNCERR_INT_AWADDR_SHIFT
#define MPC_UNCERR_INT_AWID_SHIFT           UNCERR_INT_STA_AWID_FIELD_OFFSET
#define MPC_UNCERR_INT_AWID_MASK            1UL << MPC_UNCERR_INT_AWID_SHIFT
#define MPC_UNCERR_INT_ARREADY_SHIFT        UNCERR_INT_STA_ARREADY_FIELD_OFFSET
#define MPC_UNCERR_INT_ARREADY_MASK         1UL << MPC_UNCERR_INT_ARREADY_SHIFT
#define MPC_UNCERR_INT_ARVALID_SHIFT        UNCERR_INT_STA_ARVALID_FIELD_OFFSET
#define MPC_UNCERR_INT_ARVALID_MASK         1UL << MPC_UNCERR_INT_ARVALID_SHIFT
#define MPC_UNCERR_INT_ARCTL1_SHIFT         UNCERR_INT_STA_ARCTL1_FIELD_OFFSET
#define MPC_UNCERR_INT_ARCTL1_MASK          1UL << MPC_UNCERR_INT_ARCTL1_SHIFT
#define MPC_UNCERR_INT_ARCTL0_SHIFT         UNCERR_INT_STA_ARCTL0_FIELD_OFFSET
#define MPC_UNCERR_INT_ARCTL0_MASK          1UL << MPC_UNCERR_INT_ARCTL0_SHIFT
#define MPC_UNCERR_INT_ARADDR_SHIFT         UNCERR_INT_STA_ARADDR_FIELD_OFFSET
#define MPC_UNCERR_INT_ARADDR_MASK          1UL << MPC_UNCERR_INT_ARADDR_SHIFT
#define MPC_UNCERR_INT_ARID_SHIFT           UNCERR_INT_STA_ARID_FIELD_OFFSET
#define MPC_UNCERR_INT_ARID_MASK            1UL << MPC_UNCERR_INT_ARID_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_UNCERR_INT_STA
// Register Offset : 0xf00
// Description     :
//--------------------------------------------------------------------------
#define MPC_UNCERR_INT_STA (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf00<<0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_UNCERR_INT_STA_EN
// Register Offset : 0xf04
// Description     :
//--------------------------------------------------------------------------
#define MPC_UNCERR_INT_STA_EN (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf04<<0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_UNCERR_INT_SIG_EN
// Register Offset : 0xf08
// Description     :
//--------------------------------------------------------------------------
#define MPC_UNCERR_INT_SIG_EN (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf08<<0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_CORERR_INT_STA/EN/SIG
// Register Offset : 0xf0c/0xf10/0xf14
// Description     : shift/mash abstract for 3 correct error registers
//--------------------------------------------------------------------------
#define MPC_CORERR_INT_AWADDR_SHIFT         CORERR_INT_STA_AWADDR_FIELD_OFFSET
#define MPC_CORERR_INT_AWADDR_MASK          1UL << MPC_CORERR_INT_AWADDR_SHIFT
#define MPC_CORERR_INT_ARADDR_SHIFT         CORERR_INT_STA_ARADDR_FIELD_OFFSET
#define MPC_CORERR_INT_ARADDR_MASK          1UL << MPC_CORERR_INT_ARADDR_SHIFT

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_CORERR_INT_STA
// Register Offset : 0xf0c
// Description     :
//--------------------------------------------------------------------------
#define MPC_CORERR_INT_STA (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf0c<<0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_CORERR_INT_STA_EN
// Register Offset : 0xf10
// Description     :
//--------------------------------------------------------------------------
#define MPC_CORERR_INT_STA_EN (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf10<<0))

//--------------------------------------------------------------------------
// Register Name   : REG_AP_APB_MPC_CORERR_INT_SIG_EN
// Register Offset : 0xf14
// Description     :
//--------------------------------------------------------------------------
#define MPC_CORERR_INT_SIG_EN (MPC_APB_MPC_APB_AB_0_BASE_ADDR + (0xf14<<0))
#endif
