LOCAL_DIR := $(GET_LOCAL_DIR)
MODULE := $(LOCAL_DIR)

ARCH    := arm
ARM_CPU := cortex-r5
CPU     := generic

GLOBAL_INCLUDES += \
	$(LOCAL_DIR)/

MODULE_SRCS += \
	$(LOCAL_DIR)/platform.c	\
	$(LOCAL_DIR)/debug.c \
	$(LOCAL_DIR)/uart.c \
	$(LOCAL_DIR)/interrupt.c \
	$(LOCAL_DIR)/reboot.c

MODULE_DEPS += platform/$(PLATFORM)/common

ifeq ($(SUPPORT_VIRT_UART), true)
MODULE_SRCS += \
	$(LOCAL_DIR)/vuart.c
endif

ifeq ($(SUPPORT_VIRT_CONSOLE), true)
MODULE_DEPS += framework/service/sdshell
endif

ifeq ($(SYSTEM_TIMER),sdrv_timer)
MODULE_SRCS += $(LOCAL_DIR)/timer.c

GLOBAL_DEFINES += \
        PLATFORM_HAS_DYNAMIC_TIMER=1
endif

ifeq ($(SUPPORT_DCF),true)
MODULE_SRCS += \
	$(LOCAL_DIR)/domain_config.c

ifeq ($(CHIPVERSION),x9_high)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=1 CONFIG_DCF_HAS_AP2=0 CONFIG_DCF_HAS_MP=0
else ifeq ($(CHIPVERSION),x9_mid)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=1 CONFIG_DCF_HAS_AP2=0 CONFIG_DCF_HAS_MP=0
else ifeq ($(CHIPVERSION),x9_eco)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=1 CONFIG_DCF_HAS_AP2=0 CONFIG_DCF_HAS_MP=0
else ifeq ($(CHIPVERSION),x9_high-plus)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=1 CONFIG_DCF_HAS_AP2=1 CONFIG_DCF_HAS_MP=1
else ifeq ($(CHIPVERSION),x9_ultra)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=1 CONFIG_DCF_HAS_AP2=1 CONFIG_DCF_HAS_MP=1
else ifeq ($(CHIPVERSION),g9x)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=0 CONFIG_DCF_HAS_AP2=1 CONFIG_DCF_HAS_MP=1
else ifeq ($(CHIPVERSION),g9q)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=1 CONFIG_DCF_HAS_AP2=0 CONFIG_DCF_HAS_MP=1
else ifeq ($(CHIPVERSION),d9)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=1 CONFIG_DCF_HAS_AP2=0 CONFIG_DCF_HAS_MP=0
else ifeq ($(CHIPVERSION),d9lite)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=0 CONFIG_DCF_HAS_AP2=1 CONFIG_DCF_HAS_MP=0
else ifeq ($(CHIPVERSION),d9plus)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=1 CONFIG_DCF_HAS_AP2=1 CONFIG_DCF_HAS_MP=0
else ifeq ($(CHIPVERSION),v9f)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=0 CONFIG_DCF_HAS_AP2=1 CONFIG_DCF_HAS_MP=0
else ifeq ($(CHIPVERSION),v9t)
GLOBAL_DEFINES += CONFIG_DCF_HAS_AP1=1 CONFIG_DCF_HAS_AP2=0 CONFIG_DCF_HAS_MP=0
endif

endif

GLOBAL_DEFINES += \
        LOCKSTEP_SCR_ADDR=0xf82ad000 \
        LOCKSTEP_SCR_BIT=0

MODULE_DEPS += chipdev/earlycopy
EXTRA_LINKER_SCRIPTS += $(LOCAL_DIR)/earlycopy.ld

include make/module.mk
