/********************************************************
 *          Copyright(c) 2019   Semidrive               *
 ********************************************************/

/* Generated by tool. Do not modify manually. */

#ifndef __XTAL_24M_REG_H__
#define __XTAL_24M_REG_H__

#define XTAL_SETTING_OFF    0x0U

#define BM_XTAL_SETTING_XTAL_LOCK   (0x01U << 31U)

#define FM_XTAL_SETTING_XTAL_GAIN   (0x3U << 2U)
#define FV_XTAL_SETTING_XTAL_GAIN(v) \
    (((v) << 2U) & FM_XTAL_SETTING_XTAL_GAIN)
#define GFV_XTAL_SETTING_XTAL_GAIN(v) \
    (((v) & FM_XTAL_SETTING_XTAL_GAIN) >> 2U)

#define BM_XTAL_SETTING_XTAL_EN (0x01U << 1U)

#define BM_XTAL_SETTING_XTAL_PD (0x01U << 0U)

#define XTAL_CHK_OFF    0x4U

#define FM_XTAL_CHK_LOST_RAT    (0xfU << 27U)
#define FV_XTAL_CHK_LOST_RAT(v) \
    (((v) << 27U) & FM_XTAL_CHK_LOST_RAT)
#define GFV_XTAL_CHK_LOST_RAT(v) \
    (((v) & FM_XTAL_CHK_LOST_RAT) >> 27U)

#define FM_XTAL_CHK_COMP_WIN    (0x3ffU << 17U)
#define FV_XTAL_CHK_COMP_WIN(v) \
    (((v) << 17U) & FM_XTAL_CHK_COMP_WIN)
#define GFV_XTAL_CHK_COMP_WIN(v) \
    (((v) & FM_XTAL_CHK_COMP_WIN) >> 17U)

#define FM_XTAL_CHK_TRIG_BIT    (0x1fU << 12U)
#define FV_XTAL_CHK_TRIG_BIT(v) \
    (((v) << 12U) & FM_XTAL_CHK_TRIG_BIT)
#define GFV_XTAL_CHK_TRIG_BIT(v) \
    (((v) & FM_XTAL_CHK_TRIG_BIT) >> 12U)

#define FM_XTAL_CHK_UNST_THRD   (0x3ffU << 2U)
#define FV_XTAL_CHK_UNST_THRD(v) \
    (((v) << 2U) & FM_XTAL_CHK_UNST_THRD)
#define GFV_XTAL_CHK_UNST_THRD(v) \
    (((v) & FM_XTAL_CHK_UNST_THRD) >> 2U)

#define BM_XTAL_CHK_TRIG_EN (0x01U << 0U)

#define XTAL_INT_OFF    0x8U

#define BM_XTAL_INT_FR_UNST_INT_CLR (0x01U << 8U)

#define BM_XTAL_INT_TO_LOST_INT_CLR (0x01U << 7U)

#define BM_XTAL_INT_TO_UNST_INT_CLR (0x01U << 6U)

#define BM_XTAL_INT_FR_UNST_INT_STATUS  (0x01U << 5U)

#define BM_XTAL_INT_TO_LOST_INT_STATUS  (0x01U << 4U)

#define BM_XTAL_INT_TO_UNST_INT_STATUS  (0x01U << 3U)

#define BM_XTAL_INT_FR_UNST_INT_EN  (0x01U << 2U)

#define BM_XTAL_INT_TO_LOST_INT_EN  (0x01U << 1U)

#define BM_XTAL_INT_TO_UNST_INT_EN  (0x01U << 0U)

typedef struct {
    volatile U32 xtal_setting;  /* offset: 0x0 */
    volatile U32 xtal_chk;  /* offset: 0x4 */
    volatile U32 xtal_int;  /* offset: 0x8 */
} xtal_24m_t;

#endif  /* __XTAL_24M_REG_H__ */