// Test comment dealing

DDR_W32(APB_DDRCTRL_BASE + UMCTL2_REGS_DBG1_OFF, 0x1);

DDR_W32( APB_DDRCTRL_BASE +    UMCTL2_REGS_DBG1_OFF, 0x1);

DDR_W32(APB_DDRPHY_BASE + 0x54000 * 4, 0x0)

DDR_W32(APB_DDRPHY_BASE, 0x400, 0x1);

Invalid_cmd(x, y, z)

LOAD_DDR_TRAINING_FW(ICCM, DDRPHY_FW_LPDDR4X_1D);
CFG_RST(DDR_AXI_RSTN, 0x1);
DDR_POLL_BITS(APB_DDRCTRL_BASE + UMCTL2_REGS_SWSTAT_OFF, 0x1, 0x0, 0x3e8);
DDR_W32_BITS(APB_DDRCTRL_BASE + UMCTL2_REGS_DFIMISC_OFF, 0x0, 0x1, 0x0);
LOAD_DDR_TRAINING_FW(ICCM, DDRPHY_FW_LPDDR4X_1D);
timing_reg_update_after_training();
DDRPHY_WAITFWDONE(DDRPHY_FW_LPDDR4X_2D);
dwc_ddrphy_phyinit_userCustom_H_readMsgBlock(0);
