/********************************************************
 *          Copyright(c) 2019   Semidrive               *
 ********************************************************/

/* Generated by tool. Do not modify manually. */

#ifndef __GPIO_REG_H__
#define __GPIO_REG_H__

#define GPIO_CTRL_OFF(n)    (0x0U + 16U*(n))

#define BM_GPIO_CTRL_PCLK_ACTIVE    (0x01U << 14U)

#define BM_GPIO_CTRL_INT_CLK_SEL    (0x01U << 13U)

#define BM_GPIO_CTRL_INT_DEB_EN (0x01U << 12U)

#define BM_GPIO_CTRL_INT_LEV_SYNC   (0x01U << 11U)

#define BM_GPIO_CTRL_INT_EDGE_CLR   (0x01U << 10U)

#define BM_GPIO_CTRL_INT_STATUS_UNMASK  (0x01U << 9U)

#define BM_GPIO_CTRL_INT_STATUS (0x01U << 8U)

#define BM_GPIO_CTRL_INT_BOTH_EDGE  (0x01U << 7U)

#define BM_GPIO_CTRL_INT_POL    (0x01U << 6U)

#define BM_GPIO_CTRL_INT_TYPE   (0x01U << 5U)

#define BM_GPIO_CTRL_INT_MASK   (0x01U << 4U)

#define BM_GPIO_CTRL_INT_EN (0x01U << 3U)

#define BM_GPIO_CTRL_DATA_OUT   (0x01U << 2U)

#define BM_GPIO_CTRL_DATA_IN    (0x01U << 1U)

#define BM_GPIO_CTRL_DIR    (0x01U << 0U)

#define GPIO_DIR_OFF(n) (0x2000U + 16U*(n))

#define FM_GPIO_DIR_DIR (0xffffffffU << 0U)
#define FV_GPIO_DIR_DIR(v) \
    (((v) << 0U) & FM_GPIO_DIR_DIR)
#define GFV_GPIO_DIR_DIR(v) \
    (((v) & FM_GPIO_DIR_DIR) >> 0U)

#define GPIO_DATA_IN_OFF(n) (0x2200U + 16U*(n))

#define FM_GPIO_DATA_IN_DATA_IN (0xffffffffU << 0U)
#define FV_GPIO_DATA_IN_DATA_IN(v) \
    (((v) << 0U) & FM_GPIO_DATA_IN_DATA_IN)
#define GFV_GPIO_DATA_IN_DATA_IN(v) \
    (((v) & FM_GPIO_DATA_IN_DATA_IN) >> 0U)

#define GPIO_DATA_OUT_OFF(n)    (0x2400U + 16U*(n))

#define FM_GPIO_DATA_OUT_DATA_OUT   (0xffffffffU << 0U)
#define FV_GPIO_DATA_OUT_DATA_OUT(v) \
    (((v) << 0U) & FM_GPIO_DATA_OUT_DATA_OUT)
#define GFV_GPIO_DATA_OUT_DATA_OUT(v) \
    (((v) & FM_GPIO_DATA_OUT_DATA_OUT) >> 0U)

#define GPIO_INT_EN_OFF(n)  (0x2600U + 16U*(n))

#define FM_GPIO_INT_EN_INT_EN   (0xffffffffU << 0U)
#define FV_GPIO_INT_EN_INT_EN(v) \
    (((v) << 0U) & FM_GPIO_INT_EN_INT_EN)
#define GFV_GPIO_INT_EN_INT_EN(v) \
    (((v) & FM_GPIO_INT_EN_INT_EN) >> 0U)

#define GPIO_INT_MASK_OFF(n)    (0x2800U + 16U*(n))

#define FM_GPIO_INT_MASK_INT_MASK   (0xffffffffU << 0U)
#define FV_GPIO_INT_MASK_INT_MASK(v) \
    (((v) << 0U) & FM_GPIO_INT_MASK_INT_MASK)
#define GFV_GPIO_INT_MASK_INT_MASK(v) \
    (((v) & FM_GPIO_INT_MASK_INT_MASK) >> 0U)

#define GPIO_INT_TYPE_OFF(n)    (0x2a00U + 16U*(n))

#define FM_GPIO_INT_TYPE_INT_TYPE   (0xffffffffU << 0U)
#define FV_GPIO_INT_TYPE_INT_TYPE(v) \
    (((v) << 0U) & FM_GPIO_INT_TYPE_INT_TYPE)
#define GFV_GPIO_INT_TYPE_INT_TYPE(v) \
    (((v) & FM_GPIO_INT_TYPE_INT_TYPE) >> 0U)

#define GPIO_INT_POL_OFF(n) (0x2c00U + 16U*(n))

#define FM_GPIO_INT_POL_INT_POL (0xffffffffU << 0U)
#define FV_GPIO_INT_POL_INT_POL(v) \
    (((v) << 0U) & FM_GPIO_INT_POL_INT_POL)
#define GFV_GPIO_INT_POL_INT_POL(v) \
    (((v) & FM_GPIO_INT_POL_INT_POL) >> 0U)

#define GPIO_INT_BOTH_EDGE_OFF(n)   (0x2e00U + 16U*(n))

#define FM_GPIO_INT_BOTH_EDGE_INT_BOTH_EDGE (0xffffffffU << 0U)
#define FV_GPIO_INT_BOTH_EDGE_INT_BOTH_EDGE(v) \
    (((v) << 0U) & FM_GPIO_INT_BOTH_EDGE_INT_BOTH_EDGE)
#define GFV_GPIO_INT_BOTH_EDGE_INT_BOTH_EDGE(v) \
    (((v) & FM_GPIO_INT_BOTH_EDGE_INT_BOTH_EDGE) >> 0U)

#define GPIO_INT_STATUS_OFF(n)  (0x3000U + 16U*(n))

#define FM_GPIO_INT_STATUS_INT_STATUS   (0xffffffffU << 0U)
#define FV_GPIO_INT_STATUS_INT_STATUS(v) \
    (((v) << 0U) & FM_GPIO_INT_STATUS_INT_STATUS)
#define GFV_GPIO_INT_STATUS_INT_STATUS(v) \
    (((v) & FM_GPIO_INT_STATUS_INT_STATUS) >> 0U)

#define GPIO_INT_STATUS_UNMASK_OFF(n)   (0x3200U + 16U*(n))

#define FM_GPIO_INT_STATUS_UNMASK_INT_STATUS_UNMASK (0xffffffffU << 0U)
#define FV_GPIO_INT_STATUS_UNMASK_INT_STATUS_UNMASK(v) \
    (((v) << 0U) & FM_GPIO_INT_STATUS_UNMASK_INT_STATUS_UNMASK)
#define GFV_GPIO_INT_STATUS_UNMASK_INT_STATUS_UNMASK(v) \
    (((v) & FM_GPIO_INT_STATUS_UNMASK_INT_STATUS_UNMASK) >> 0U)

#define GPIO_INT_EDGE_CLR_OFF(n)    (0x3400U + 16U*(n))

#define FM_GPIO_INT_EDGE_CLR_INT_EDGE_CLR   (0xffffffffU << 0U)
#define FV_GPIO_INT_EDGE_CLR_INT_EDGE_CLR(v) \
    (((v) << 0U) & FM_GPIO_INT_EDGE_CLR_INT_EDGE_CLR)
#define GFV_GPIO_INT_EDGE_CLR_INT_EDGE_CLR(v) \
    (((v) & FM_GPIO_INT_EDGE_CLR_INT_EDGE_CLR) >> 0U)

#define GPIO_INT_LEV_SYNC_OFF(n)    (0x3600U + 16U*(n))

#define FM_GPIO_INT_LEV_SYNC_INT_LEV_SYNC   (0xffffffffU << 0U)
#define FV_GPIO_INT_LEV_SYNC_INT_LEV_SYNC(v) \
    (((v) << 0U) & FM_GPIO_INT_LEV_SYNC_INT_LEV_SYNC)
#define GFV_GPIO_INT_LEV_SYNC_INT_LEV_SYNC(v) \
    (((v) & FM_GPIO_INT_LEV_SYNC_INT_LEV_SYNC) >> 0U)

#define GPIO_INT_DEB_EN_OFF(n)  (0x3800U + 16U*(n))

#define FM_GPIO_INT_DEB_EN_INT_DEB_EN   (0xffffffffU << 0U)
#define FV_GPIO_INT_DEB_EN_INT_DEB_EN(v) \
    (((v) << 0U) & FM_GPIO_INT_DEB_EN_INT_DEB_EN)
#define GFV_GPIO_INT_DEB_EN_INT_DEB_EN(v) \
    (((v) & FM_GPIO_INT_DEB_EN_INT_DEB_EN) >> 0U)

#define GPIO_INT_CLK_SEL_OFF(n) (0x3a00U + 16U*(n))

#define FM_GPIO_INT_CLK_SEL_INT_CLK_SEL (0xffffffffU << 0U)
#define FV_GPIO_INT_CLK_SEL_INT_CLK_SEL(v) \
    (((v) << 0U) & FM_GPIO_INT_CLK_SEL_INT_CLK_SEL)
#define GFV_GPIO_INT_CLK_SEL_INT_CLK_SEL(v) \
    (((v) & FM_GPIO_INT_CLK_SEL_INT_CLK_SEL) >> 0U)

#define GPIO_INT_PCLK_ACTIVE_OFF(n) (0x3c00U + 16U*(n))

#define FM_GPIO_INT_PCLK_ACTIVE_PCLK_ACTIVE (0xffffffffU << 0U)
#define FV_GPIO_INT_PCLK_ACTIVE_PCLK_ACTIVE(v) \
    (((v) << 0U) & FM_GPIO_INT_PCLK_ACTIVE_PCLK_ACTIVE)
#define GFV_GPIO_INT_PCLK_ACTIVE_PCLK_ACTIVE(v) \
    (((v) & FM_GPIO_INT_PCLK_ACTIVE_PCLK_ACTIVE) >> 0U)

#endif  /* __GPIO_REG_H__ */
