include $(MKDIR)/build.mk

SUBDIRS += $(CRYPTO_MODULE_LIST)

C_SRC = crypto.c pkcs1_v1p5.c ecc_curve.c crypto_helper.c bn.c crypto_cipher.c crypto_hash.c crypto_engs.c

include $(MKDIR)/objs_subdir.mk
include $(MKDIR)/rules.mk
