/*
 * sd_csi_reg.h
 *
 * Copyright (c) 2019 Semidrive Semiconductor.
 * All rights reserved.
 *
 * Description: Semidrive csi register info.
 *
 * Revision History:
 * -----------------
 */
#ifndef _SD_CSI_REG_H
#define _SD_CSI_REG_H

/* all registers in csi ip */

/* 0x000: csi enable */
#define CSI_ENABLE 0x0
#define CSI_ENABLE_GLOBAL_RESET_FIELD_OFFSET 8
#define CSI_ENABLE_GLOBAL_RESET_FIELD_SIZE 1
#define CSI_ENABLE_SOFT_RESET_FIELD_OFFSET 4
#define CSI_ENABLE_SOFT_RESET_FIELD_SIZE 4
#define CSI_ENABLE_IMAGE_EN_FIELD_OFFSET 0
#define CSI_ENABLE_IMAGE_EN_FIELD_SIZE 4

#define CSI_ENABLE_GLOBAL_RESET_SHIFT      CSI_ENABLE_GLOBAL_RESET_FIELD_OFFSET
#define CSI_ENABLE_GLOBAL_RESET_MASK       \
    ((1<<CSI_ENABLE_GLOBAL_RESET_FIELD_SIZE)-1) << CSI_ENABLE_GLOBAL_RESET_SHIFT

#define CSI_ENABLE_SOFT_RESET_SHIFT        CSI_ENABLE_SOFT_RESET_FIELD_OFFSET
#define CSI_ENABLE_SOFT_RESET_MASK         \
    ((1<<CSI_ENABLE_SOFT_RESET_FIELD_SIZE)-1) << CSI_ENABLE_SOFT_RESET_SHIFT

#define CSI_ENABLE_IMAGE_EN_SHIFT          CSI_ENABLE_IMAGE_EN_FIELD_OFFSET
#define CSI_ENABLE_IMAGE_EN_MASK           \
    ((1<<CSI_ENABLE_IMAGE_EN_FIELD_SIZE)-1) << CSI_ENABLE_IMAGE_EN_SHIFT


/* 0x004: csi interrupt status 0 */
#define CSI_INT_STAT0 0x4
#define CSI_INT_ST0_BT_COF_FIELD_OFFSET 10
#define CSI_INT_ST0_BT_COF_FIELD_SIZE 1
#define CSI_INT_ST0_BT_FATAL_FIELD_OFFSET 9
#define CSI_INT_ST0_BT_FATAL_FIELD_SIZE 1
#define CSI_INT_ST0_BT_ERR_FIELD_OFFSET 8
#define CSI_INT_ST0_BT_ERR_FIELD_SIZE 1
#define CSI_INT_ST0_SDW_SET3_FIELD_OFFSET 7
#define CSI_INT_ST0_SDW_SET3_FIELD_SIZE 1
#define CSI_INT_ST0_SDW_SET2_FIELD_OFFSET 6
#define CSI_INT_ST0_SDW_SET2_FIELD_SIZE 1
#define CSI_INT_ST0_SDW_SET1_FIELD_OFFSET 5
#define CSI_INT_ST0_SDW_SET1_FIELD_SIZE 1
#define CSI_INT_ST0_SDW_SET0_FIELD_OFFSET 4
#define CSI_INT_ST0_SDW_SET0_FIELD_SIZE 1
#define CSI_INT_ST0_STORE_DONE3_FIELD_OFFSET 3
#define CSI_INT_ST0_STORE_DONE3_FIELD_SIZE 1
#define CSI_INT_ST0_STORE_DONE2_FIELD_OFFSET 2
#define CSI_INT_ST0_STORE_DONE2_FIELD_SIZE 1
#define CSI_INT_ST0_STORE_DONE1_FIELD_OFFSET 1
#define CSI_INT_ST0_STORE_DONE1_FIELD_SIZE 1
#define CSI_INT_ST0_STORE_DONE0_FIELD_OFFSET 0
#define CSI_INT_ST0_STORE_DONE0_FIELD_SIZE 1

#define CSI_INT_STAT0_COF_INT_OFFSET          CSI_INT_ST0_BT_COF_FIELD_OFFSET
#define CSI_INT_STAT0_COF_INT_MASK            0x1 << CSI_INT_STAT0_COF_INT_OFFSET
#define CSI_INT_STAT0_BT_FATAL_INT_OFFSET     CSI_INT_ST0_BT_FATAL_FIELD_OFFSET
#define CSI_INT_STAT0_BT_FATAL_INT_MASK       0x1 << CSI_INT_STAT0_BT_FATAL_INT_OFFSET
#define CSI_INT_STAT0_BT_ERR_INT_OFFSET       CSI_INT_ST0_BT_ERR_FIELD_OFFSET
#define CSI_INT_STAT0_BT_ERR_INT_MASK         0x1 << CSI_INT_STAT0_BT_ERR_INT_OFFSET
#define CSI_INT_STAT0_SDW_SET_INT_OFFSET      CSI_INT_ST0_SDW_SET0_FIELD_OFFSET
#define CSI_INT_STAT0_SDW_SET_INT_MASK        0xF << CSI_INT_STAT0_SDW_SET_INT_OFFSET
#define CSI_INT_STAT0_STORE_DONE_INT_OFFSET   CSI_INT_ST0_STORE_DONE0_FIELD_OFFSET
#define CSI_INT_STAT0_STORE_DONE_INT_MASK     0xF << CSI_INT_STAT0_STORE_DONE_INT_OFFSET


/* 0x004: csi interrupt status 1 */
#define CSI_INT_STAT1 0x8
#define CSI_INT_ST1_BUS_ERR11_FIELD_OFFSET 23
#define CSI_INT_ST1_BUS_ERR11_FIELD_SIZE 1
#define CSI_INT_ST1_BUS_ERR10_FIELD_OFFSET 22
#define CSI_INT_ST1_BUS_ERR10_FIELD_SIZE 1
#define CSI_INT_ST1_BUS_ERR9_FIELD_OFFSET 21
#define CSI_INT_ST1_BUS_ERR9_FIELD_SIZE 1
#define CSI_INT_ST1_BUS_ERR8_FIELD_OFFSET 20
#define CSI_INT_ST1_BUS_ERR8_FIELD_SIZE 1
#define CSI_INT_ST1_BUS_ERR7_FIELD_OFFSET 19
#define CSI_INT_ST1_BUS_ERR7_FIELD_SIZE 1
#define CSI_INT_ST1_BUS_ERR6_FIELD_OFFSET 18
#define CSI_INT_ST1_BUS_ERR6_FIELD_SIZE 1
#define CSI_INT_ST1_BUS_ERR5_FIELD_OFFSET 17
#define CSI_INT_ST1_BUS_ERR5_FIELD_SIZE 1
#define CSI_INT_ST1_BUS_ERR4_FIELD_OFFSET 16
#define CSI_INT_ST1_BUS_ERR4_FIELD_SIZE 1
#define CSI_INT_ST1_BUS_ERR3_FIELD_OFFSET 15
#define CSI_INT_ST1_BUS_ERR3_FIELD_SIZE 1
#define CSI_INT_ST1_BUS_ERR2_FIELD_OFFSET 14
#define CSI_INT_ST1_BUS_ERR2_FIELD_SIZE 1
#define CSI_INT_ST1_BUS_ERR1_FIELD_OFFSET 13
#define CSI_INT_ST1_BUS_ERR1_FIELD_SIZE 1
#define CSI_INT_ST1_BUS_ERR0_FIELD_OFFSET 12
#define CSI_INT_ST1_BUS_ERR0_FIELD_SIZE 1
#define CSI_INT_ST1_OVERFLOW3_FIELD_OFFSET 11
#define CSI_INT_ST1_OVERFLOW3_FIELD_SIZE 1
#define CSI_INT_ST1_OVERFLOW2_FIELD_OFFSET 10
#define CSI_INT_ST1_OVERFLOW2_FIELD_SIZE 1
#define CSI_INT_ST1_OVERFLOW1_FIELD_OFFSET 9
#define CSI_INT_ST1_OVERFLOW1_FIELD_SIZE 1
#define CSI_INT_ST1_OVERFLOW0_FIELD_OFFSET 8
#define CSI_INT_ST1_OVERFLOW0_FIELD_SIZE 1
#define CSI_INT_ST1_PIXEL_ERR3_FIELD_OFFSET 7
#define CSI_INT_ST1_PIXEL_ERR3_FIELD_SIZE 1
#define CSI_INT_ST1_PIXEL_ERR2_FIELD_OFFSET 6
#define CSI_INT_ST1_PIXEL_ERR2_FIELD_SIZE 1
#define CSI_INT_ST1_PIXEL_ERR1_FIELD_OFFSET 5
#define CSI_INT_ST1_PIXEL_ERR1_FIELD_SIZE 1
#define CSI_INT_ST1_PIXEL_ERR0_FIELD_OFFSET 4
#define CSI_INT_ST1_PIXEL_ERR0_FIELD_SIZE 1
#define CSI_INT_ST1_CROP_ERR3_FIELD_OFFSET 3
#define CSI_INT_ST1_CROP_ERR3_FIELD_SIZE 1
#define CSI_INT_ST1_CROP_ERR2_FIELD_OFFSET 2
#define CSI_INT_ST1_CROP_ERR2_FIELD_SIZE 1
#define CSI_INT_ST1_CROP_ERR1_FIELD_OFFSET 1
#define CSI_INT_ST1_CROP_ERR1_FIELD_SIZE 1
#define CSI_INT_ST1_CROP_ERR0_FIELD_OFFSET 0
#define CSI_INT_ST1_CROP_ERR0_FIELD_SIZE 1

#define CSI_INT_STAT1_BUS_ERR11_INT_OFFSET    CSI_INT_ST1_BUS_ERR11_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR11_INT_MASK      0x1 << CSI_INT_STAT1_BUS_ERR11_INT_OFFSET
#define CSI_INT_STAT1_BUS_ERR10_INT_OFFSET    CSI_INT_ST1_BUS_ERR10_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR10_INT_MASK      0x1 << CSI_INT_STAT1_BUS_ERR10_INT_OFFSET
#define CSI_INT_STAT1_BUS_ERR9_INT_OFFSET     CSI_INT_ST1_BUS_ERR9_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR9_INT_MASK       0x1 << CSI_INT_STAT1_BUS_ERR9_INT_OFFSET
#define CSI_INT_STAT1_BUS_ERR8_INT_OFFSET     CSI_INT_ST1_BUS_ERR8_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR8_INT_MASK       0x1 << CSI_INT_STAT1_BUS_ERR8_INT_OFFSET
#define CSI_INT_STAT1_BUS_ERR7_INT_OFFSET     CSI_INT_ST1_BUS_ERR7_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR7_INT_MASK       0x1 << CSI_INT_STAT1_BUS_ERR7_INT_OFFSET
#define CSI_INT_STAT1_BUS_ERR6_INT_OFFSET     CSI_INT_ST1_BUS_ERR6_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR6_INT_MASK       0x1 << CSI_INT_STAT1_BUS_ERR6_INT_OFFSET
#define CSI_INT_STAT1_BUS_ERR5_INT_OFFSET     CSI_INT_ST1_BUS_ERR5_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR5_INT_MASK       0x1 << CSI_INT_STAT1_BUS_ERR5_INT_OFFSET
#define CSI_INT_STAT1_BUS_ERR4_INT_OFFSET     CSI_INT_ST1_BUS_ERR4_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR4_INT_MASK       0x1 << CSI_INT_STAT1_BUS_ERR4_INT_OFFSET
#define CSI_INT_STAT1_BUS_ERR3_INT_OFFSET     CSI_INT_ST1_BUS_ERR3_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR3_INT_MASK       0x1 << CSI_INT_STAT1_BUS_ERR3_INT_OFFSET
#define CSI_INT_STAT1_BUS_ERR2_INT_OFFSET     CSI_INT_ST1_BUS_ERR2_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR2_INT_MASK       0x1 << CSI_INT_STAT1_BUS_ERR2_INT_OFFSET
#define CSI_INT_STAT1_BUS_ERR1_INT_OFFSET     CSI_INT_ST1_BUS_ERR1_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR1_INT_MASK       0x1 << CSI_INT_STAT1_BUS_ERR1_INT_OFFSET
#define CSI_INT_STAT1_BUS_ERR0_INT_OFFSET     CSI_INT_ST1_BUS_ERR0_FIELD_OFFSET
#define CSI_INT_STAT1_BUS_ERR0_INT_MASK       0x1 << CSI_INT_STAT1_BUS_ERR0_INT_OFFSET
#define CSI_INT_STAT1_OVERFLOW3_INT_OFFSET    CSI_INT_ST1_OVERFLOW3_FIELD_OFFSET
#define CSI_INT_STAT1_OVERFLOW3_INT_MASK      0x1 << CSI_INT_STAT1_OVERFLOW3_INT_OFFSET
#define CSI_INT_STAT1_OVERFLOW2_INT_OFFSET    CSI_INT_ST1_OVERFLOW2_FIELD_OFFSET
#define CSI_INT_STAT1_OVERFLOW2_INT_MASK      0x1 << CSI_INT_STAT1_OVERFLOW2_INT_OFFSET
#define CSI_INT_STAT1_OVERFLOW1_INT_OFFSET    CSI_INT_ST1_OVERFLOW1_FIELD_OFFSET
#define CSI_INT_STAT1_OVERFLOW1_INT_MASK      0x1 << CSI_INT_STAT1_OVERFLOW1_INT_OFFSET
#define CSI_INT_STAT1_OVERFLOW0_INT_OFFSET    CSI_INT_ST1_OVERFLOW0_FIELD_OFFSET
#define CSI_INT_STAT1_OVERFLOW0_INT_MASK      0x1 << CSI_INT_STAT1_OVERFLOW0_INT_OFFSET
#define CSI_INT_STAT1_PIXEL_ERR3_INT_OFFSET   CSI_INT_ST1_PIXEL_ERR3_FIELD_OFFSET
#define CSI_INT_STAT1_PIXEL_ERR3_INT_MASK     0x1 << CSI_INT_STAT1_PIXEL_ERR3_INT_OFFSET
#define CSI_INT_STAT1_PIXEL_ERR2_INT_OFFSET   CSI_INT_ST1_PIXEL_ERR2_FIELD_OFFSET
#define CSI_INT_STAT1_PIXEL_ERR2_INT_MASK     0x1 << CSI_INT_STAT1_PIXEL_ERR2_INT_OFFSET
#define CSI_INT_STAT1_PIXEL_ERR1_INT_OFFSET   CSI_INT_ST1_PIXEL_ERR1_FIELD_OFFSET
#define CSI_INT_STAT1_PIXEL_ERR1_INT_MASK     0x1 << CSI_INT_STAT1_PIXEL_ERR1_INT_OFFSET
#define CSI_INT_STAT1_PIXEL_ERR0_INT_OFFSET   CSI_INT_ST1_PIXEL_ERR0_FIELD_OFFSET
#define CSI_INT_STAT1_PIXEL_ERR0_INT_MASK     0x1 << CSI_INT_STAT1_PIXEL_ERR0_INT_OFFSET
#define CSI_INT_STAT1_CROP_ERR3_INT_OFFSET    CSI_INT_ST1_CROP_ERR3_FIELD_OFFSET
#define CSI_INT_STAT1_CROP_ERR3_INT_MASK      0x1 << CSI_INT_STAT1_CROP_ERR3_INT_OFFSET
#define CSI_INT_STAT1_CROP_ERR2_INT_OFFSET    CSI_INT_ST1_CROP_ERR2_FIELD_OFFSET
#define CSI_INT_STAT1_CROP_ERR2_INT_MASK      0x1 << CSI_INT_STAT1_CROP_ERR2_INT_OFFSET
#define CSI_INT_STAT1_CROP_ERR1_INT_OFFSET    CSI_INT_ST1_CROP_ERR1_FIELD_OFFSET
#define CSI_INT_STAT1_CROP_ERR1_INT_MASK      0x1 << CSI_INT_STAT1_CROP_ERR1_INT_OFFSET
#define CSI_INT_STAT1_CROP_ERR0_INT_OFFSET    CSI_INT_ST1_CROP_ERR0_FIELD_OFFSET
#define CSI_INT_STAT1_CROP_ERR0_INT_MASK      0x1 << CSI_INT_STAT1_CROP_ERR0_INT_OFFSET


/* 0x00c: csi interrupt mask0 */
#define CSI_INT_MASK0 0xc
#define CSI_INT_MSK0_INT_MASK_FIELD_OFFSET 0
#define CSI_INT_MSK0_INT_MASK_FIELD_SIZE 11


/* 0x010: csi interrupt mask1 */
#define CSI_INT_MASK1 0x10
#define CSI_INT_MSK1_INT_MASK_FIELD_OFFSET 0
#define CSI_INT_MSK1_INT_MASK_FIELD_SIZE 24


/* 0x014: csi register load */
#define CSI_REG_LOAD 0x14
#define CSI_REG_LOAD_WDMA_CFG_LOAD_FIELD_OFFSET 17
#define CSI_REG_LOAD_WDMA_CFG_LOAD_FIELD_SIZE 1
#define CSI_REG_LOAD_WDMA_ARB_SEL_FIELD_OFFSET 16
#define CSI_REG_LOAD_WDMA_ARB_SEL_FIELD_SIZE 1
#define CSI_REG_LOAD_UPDATE_MASK_FIELD_OFFSET 8
#define CSI_REG_LOAD_UPDATE_MASK_FIELD_SIZE 8
#define CSI_REG_LOAD_SHADOW_UPDATE3_FIELD_OFFSET 7
#define CSI_REG_LOAD_SHADOW_UPDATE3_FIELD_SIZE 1
#define CSI_REG_LOAD_SHADOW_UPDATE2_FIELD_OFFSET 6
#define CSI_REG_LOAD_SHADOW_UPDATE2_FIELD_SIZE 1
#define CSI_REG_LOAD_SHADOW_UPDATE1_FIELD_OFFSET 5
#define CSI_REG_LOAD_SHADOW_UPDATE1_FIELD_SIZE 1
#define CSI_REG_LOAD_SHADOW_UPDATE0_FIELD_OFFSET 4
#define CSI_REG_LOAD_SHADOW_UPDATE0_FIELD_SIZE 1
#define CSI_REG_LOAD_SHADOW_SET3_FIELD_OFFSET 3
#define CSI_REG_LOAD_SHADOW_SET3_FIELD_SIZE 1
#define CSI_REG_LOAD_SHADOW_SET2_FIELD_OFFSET 2
#define CSI_REG_LOAD_SHADOW_SET2_FIELD_SIZE 1
#define CSI_REG_LOAD_SHADOW_SET1_FIELD_OFFSET 1
#define CSI_REG_LOAD_SHADOW_SET1_FIELD_SIZE 1
#define CSI_REG_LOAD_SHADOW_SET0_FIELD_OFFSET 0
#define CSI_REG_LOAD_SHADOW_SET0_FIELD_SIZE 1

#define CSI_REG_LOAD_WDMA_CFG_LOAD_OFFSET    CSI_REG_LOAD_WDMA_CFG_LOAD_FIELD_OFFSET
#define CSI_REG_LOAD_WDMA_CFG_LOAD_MASK      \
    ((1<<CSI_REG_LOAD_WDMA_CFG_LOAD_FIELD_SIZE)-1) << CSI_REG_LOAD_WDMA_CFG_LOAD_OFFSET

#define CSI_REG_LOAD_WDMA_ARB_SET_OFFSET     CSI_REG_LOAD_WDMA_ARB_SEL_FIELD_OFFSET
#define CSI_REG_LOAD_WDMA_ARB_SET_MASK       \
    ((1<<CSI_REG_LOAD_WDMA_ARB_SEL_FIELD_SIZE)-1) << CSI_REG_LOAD_WDMA_ARB_SET_OFFSET

#define CSI_REG_LOAD_UPDATE_MASK_OFFSET      CSI_REG_LOAD_UPDATE_MASK_FIELD_OFFSET
#define CSI_REG_LOAD_UPDATE_MASK_MASK        \
    ((1<<CSI_REG_LOAD_UPDATE_MASK_FIELD_SIZE)-1) << CSI_REG_LOAD_UPDATE_MASK_OFFSET

#define CSI_REG_LOAD_SHADOW_UPDATE_OFFSET    CSI_REG_LOAD_SHADOW_UPDATE0_FIELD_OFFSET
#define CSI_REG_LOAD_SHADOW_UPDATE_MASK      \
    ((1<<CSI_REG_LOAD_SHADOW_UPDATE0_FIELD_SIZE)-1) << CSI_REG_LOAD_SHADOW_UPDATE_OFFSET

#define CSI_REG_LOAD_SHADOW_SET_OFFSET       CSI_REG_LOAD_SHADOW_SET0_FIELD_OFFSET
#define CSI_REG_LOAD_SHADOW_SET_MASK     \
    ((1<<CSI_REG_LOAD_SHADOW_SET0_FIELD_SIZE)-1) << CSI_REG_LOAD_SHADOW_SET_OFFSET


/* 0x100: image rgby baddr_h */
#define CSI_IMG_RGBY_BADDR_H 0x100
#define CSI_IMG_RGBY_BADDR_H_CSI_IMG_RGBY_BADDR_H_FIELD_OFFSET 0
#define CSI_IMG_RGBY_BADDR_H_CSI_IMG_RGBY_BADDR_H_FIELD_SIZE 8

#define CSI_IMG_BADDR_H_SHIFT       0x0
#define CSI_IMG_BADDR_H_MASK        0xFF << CSI_IMG_BADDR_H_SHIFT


/* 0x104: image rgby baddr_l */
#define CSI_IMG_RGBY_BADDR_L 0x104
#define CSI_IMG_RGBY_BADDR_L_CSI_IMG_RGBY_BADDR_L_FIELD_OFFSET 0
#define CSI_IMG_RGBY_BADDR_L_CSI_IMG_RGBY_BADDR_L_FIELD_SIZE 32

#define CSI_IMG_BADDR_L_SHIFT       0x0
#define CSI_IMG_BADDR_L_MASK        0xFFFFFFFF << CSI_IMG_BADDR_L_SHIFT
#define CSI_IMG_BADDR_L_SIZE        32


/* 0x108: image u baddr_h */
#define CSI_IMG_U_BADDR_H 0x108
#define CSI_IMG_U_BADDR_H_CSI_IMG_U_BADDR_H_FIELD_OFFSET 0
#define CSI_IMG_U_BADDR_H_CSI_IMG_U_BADDR_H_FIELD_SIZE 8


/* 0x10c: image u baddr_l */
#define CSI_IMG_U_BADDR_L 0x10c
#define CSI_IMG_U_BADDR_L_CSI_IMG_U_BADDR_L_FIELD_OFFSET 0
#define CSI_IMG_U_BADDR_L_CSI_IMG_U_BADDR_L_FIELD_SIZE 32


/* 0x110: image v baddr_l */
#define CSI_IMG_V_BADDR_H 0x110
#define CSI_IMG_V_BADDR_H_CSI_IMG_V_BADDR_H_FIELD_OFFSET 0
#define CSI_IMG_V_BADDR_H_CSI_IMG_V_BADDR_H_FIELD_SIZE 8


/* 0x114: image v baddr_l */
#define CSI_IMG_V_BADDR_L 0x114
#define CSI_IMG_V_BADDR_L_CSI_IMG_V_BADDR_L_FIELD_OFFSET 0
#define CSI_IMG_V_BADDR_L_CSI_IMG_V_BADDR_L_FIELD_SIZE 32


/* 0x118: image rgby stride */
#define CSI_IMG_RGBY_STRIDE 0x118
#define CSI_IMG_RGBY_STRIDE_STRIDE_FIELD_OFFSET 0
#define CSI_IMG_RGBY_STRIDE_STRIDE_FIELD_SIZE 18

#define CSI_IMG_YUV_STRIDE_SHIFT    CSI_IMG_RGBY_STRIDE_STRIDE_FIELD_OFFSET
#define CSI_IMG_YUV_STRIDE_MASK     \
    ((1<<CSI_IMG_RGBY_STRIDE_STRIDE_FIELD_SIZE)-1) << CSI_IMG_YUV_STRIDE_SHIFT


/* 0x11c: image u stride */
#define CSI_IMG_U_STRIDE 0x11c
#define CSI_IMG_U_STRIDE_STRIDE_FIELD_OFFSET 0
#define CSI_IMG_U_STRIDE_STRIDE_FIELD_SIZE 18


/* 0x120: image v stride */
#define CSI_IMG_V_STRIDE 0x120
#define CSI_IMG_V_STRIDE_STRIDE_FIELD_OFFSET 0
#define CSI_IMG_V_STRIDE_STRIDE_FIELD_SIZE 18


/* 0x124: image size */
#define CSI_IMG_SIZE 0x124
#define CSI_IMG_SIZE_SIZE_WIDTH_FIELD_OFFSET 16
#define CSI_IMG_SIZE_SIZE_WIDTH_FIELD_SIZE 16
#define CSI_IMG_SIZE_SIZE_HEIGHT_FIELD_OFFSET 0
#define CSI_IMG_SIZE_SIZE_HEIGHT_FIELD_SIZE 16

#define CSI_IMG_SIZE_WIDTH_SHIFT    CSI_IMG_SIZE_SIZE_WIDTH_FIELD_OFFSET
#define CSI_IMG_SIZE_WIDTH_MASK     \
    ((1<<CSI_IMG_SIZE_SIZE_WIDTH_FIELD_SIZE)-1) << CSI_IMG_SIZE_WIDTH_SHIFT

#define CSI_IMG_SIZE_HEIGHT_SHIFT   CSI_IMG_SIZE_SIZE_HEIGHT_FIELD_OFFSET
#define CSI_IMG_SIZE_HEIGHT_MASK    \
    ((1<<CSI_IMG_SIZE_SIZE_HEIGHT_FIELD_SIZE)-1) << CSI_IMG_SIZE_HEIGHT_SHIFT


/* 0x128: csi image ipi ctrl */
#define CSI_IMG_IPI_CTRL 0x128
#define CSI_IMG_IPI_CTRL_VSYNC_CHN_CLR_FIELD_OFFSET 15
#define CSI_IMG_IPI_CTRL_VSYNC_CHN_CLR_FIELD_SIZE 1
#define CSI_IMG_IPI_CTRL_VSYNC_FC_CLR_FIELD_OFFSET 14
#define CSI_IMG_IPI_CTRL_VSYNC_FC_CLR_FIELD_SIZE 1
#define CSI_IMG_IPI_CTRL_DUALLINE_FIELD_OFFSET 13
#define CSI_IMG_IPI_CTRL_DUALLINE_FIELD_SIZE 1
#define CSI_IMG_IPI_CTRL_PIXEL_VLD_EVEN_FIELD_OFFSET 11
#define CSI_IMG_IPI_CTRL_PIXEL_VLD_EVEN_FIELD_SIZE 2
#define CSI_IMG_IPI_CTRL_PIXEL_VLD_ODD_FIELD_OFFSET 9
#define CSI_IMG_IPI_CTRL_PIXEL_VLD_ODD_FIELD_SIZE 2
#define CSI_IMG_IPI_CTRL_VSYNC_MASK_FIELD_OFFSET 7
#define CSI_IMG_IPI_CTRL_VSYNC_MASK_FIELD_SIZE 2
#define CSI_IMG_IPI_CTRL_YUV422_FIELD_OFFSET 6
#define CSI_IMG_IPI_CTRL_YUV422_FIELD_SIZE 1
#define CSI_IMG_IPI_CTRL_RAW_FIELD_OFFSET 5
#define CSI_IMG_IPI_CTRL_RAW_FIELD_SIZE 1
#define CSI_IMG_IPI_CTRL_YUV420_LEGACY_FIELD_OFFSET 4
#define CSI_IMG_IPI_CTRL_YUV420_LEGACY_FIELD_SIZE 1
#define CSI_IMG_IPI_CTRL_YUV420_FIELD_OFFSET 3
#define CSI_IMG_IPI_CTRL_YUV420_FIELD_SIZE 1
#define CSI_IMG_IPI_CTRL_INTERFACE_TYPE_SELECT_FIELD_OFFSET 0
#define CSI_IMG_IPI_CTRL_INTERFACE_TYPE_SELECT_FIELD_SIZE 3

#define CSI_IMG_VSYNC_CHN_CLR_SHIFT \
    CSI_IMG_IPI_CTRL_VSYNC_CHN_CLR_FIELD_OFFSET

#define CSI_IMG_VSYNC_CHN_CLR_MASK  0x01 << CSI_IMG_VSYNC_CHN_CLR_SHIFT
#define CSI_IMG_VSYNC_FC_CLR_SHIFT  \
    CSI_IMG_IPI_CTRL_VSYNC_FC_CLR_FIELD_OFFSET

#define CSI_IMG_VSYNC_FC_CLR_MASK   0x01 << CSI_IMG_VSYNC_FC_CLR_SHIFT
#define CSI_IMG_FC_DUALLINE_SHIFT   CSI_IMG_IPI_CTRL_DUALLINE_FIELD_OFFSET
#define CSI_IMG_FC_DUALLINE_MASK    0x01 << CSI_IMG_FC_DUALLINE_SHIFT
#define CSI_IMG_VLD_EVEN_SHIFT      \
    CSI_IMG_IPI_CTRL_PIXEL_VLD_EVEN_FIELD_OFFSET

#define CSI_IMG_VLD_EVEN_MASK       0x03 << CSI_IMG_VLD_EVEN_SHIFT
#define CSI_IMG_VLD_ODD_SHIFT       \
    CSI_IMG_IPI_CTRL_PIXEL_VLD_ODD_FIELD_OFFSET

#define CSI_IMG_VLD_ODD_MASK        0x03 << CSI_IMG_VLD_ODD_SHIFT
#define CSI_IMG_VSYNC_MASK_SHIFT    CSI_IMG_IPI_CTRL_VSYNC_MASK_FIELD_OFFSET
#define CSI_IMG_VSYNC_MASK_MASK     0x03 << CSI_IMG_VSYNC_MASK_SHIFT
#define CSI_IMG_YUV422_SHIFT        CSI_IMG_IPI_CTRL_YUV422_FIELD_OFFSET
#define CSI_IMG_YUV422_MASK         0x01 << CSI_IMG_YUV422_SHIFT
#define CSI_IMG_RAW_SHIFT           CSI_IMG_IPI_CTRL_RAW_FIELD_OFFSET
#define CSI_IMG_RAW_MASK            0x01 << CSI_IMG_RAW_SHIFT
#define CSI_IMG_YUV420_LEGACY_SHIFT \
    CSI_IMG_IPI_CTRL_YUV420_LEGACY_FIELD_OFFSET

#define CSI_IMG_YUV420_LEGACY_MASK  0x01 << CSI_IMG_YUV420_LEGACY_SHIFT
#define CSI_IMG_YUV420_SHIFT        CSI_IMG_IPI_CTRL_YUV420_FIELD_OFFSET
#define CSI_IMG_YUV420_MASK         0x01 << CSI_IMG_YUV420_SHIFT
#define CSI_IMG_INTERFACE_SHIFT     \
    CSI_IMG_IPI_CTRL_INTERFACE_TYPE_SELECT_FIELD_OFFSET

#define CSI_IMG_INTERFACE_MASK      0x07 << CSI_IMG_INTERFACE_SHIFT


/* 0x12c: csi image interface pixel mask0 */
#define CSI_IMG_IF_PIXEL_MASK0 0x12c
#define CSI_IMG_IF_PIXEL_MASK0_MASK0_FIELD_OFFSET 0
#define CSI_IMG_IF_PIXEL_MASK0_MASK0_FIELD_SIZE 32

#define CSI_IMG_PIXEL_MASK_SHIFT    CSI_IMG_IF_PIXEL_MASK0_MASK0_FIELD_OFFSET
#define CSI_IMG_PIXEL_MASK_MASK \
    ((1<<CSI_IMG_IF_PIXEL_MASK0_MASK0_FIELD_SIZE)-1) << \
    CSI_IMG_PIXEL_MASK0_SHIFT


/* 0x130: csi image interface pixel mask1 */
#define CSI_IMG_IF_PIXEL_MASK1 0x130
#define CSI_IMG_IF_PIXEL_MASK1_MASK1_FIELD_OFFSET 0
#define CSI_IMG_IF_PIXEL_MASK1_MASK1_FIELD_SIZE 32


/* 0x134: csi image channel contrl */
#define CSI_IMG_CHN_CTRL 0x134
#define CSI_IMG_CHN_CTRL_ENDIAN_CTRL_FIELD_OFFSET 7
#define CSI_IMG_CHN_CTRL_ENDIAN_CTRL_FIELD_SIZE 3
#define CSI_IMG_CHN_CTRL_ROUNDING_FIELD_OFFSET 6
#define CSI_IMG_CHN_CTRL_ROUNDING_FIELD_SIZE 1
#define CSI_IMG_CHN_CTRL_CROP_ENABLE_FIELD_OFFSET 3
#define CSI_IMG_CHN_CTRL_CROP_ENABLE_FIELD_SIZE 3
#define CSI_IMG_CHN_CTRL_STREAM_ENABLE_FIELD_OFFSET 0
#define CSI_IMG_CHN_CTRL_STREAM_ENABLE_FIELD_SIZE 3

#define CSI_IMG_ENDIAN_CTRL_SHIFT   CSI_IMG_CHN_CTRL_ENDIAN_CTRL_FIELD_OFFSET
#define CSI_IMG_ENDIAN_CTRL_MASK    \
    ((1<<CSI_IMG_CHN_CTRL_ENDIAN_CTRL_FIELD_SIZE)-1) << \
    CSI_IMG_ENDIAN_CTRL_SHIFT

#define CSI_IMG_ROUNDING_SHIFT      CSI_IMG_CHN_CTRL_ROUNDING_FIELD_OFFSET
#define CSI_IMG_ROUNDING_MASK       \
    ((1<<CSI_IMG_CHN_CTRL_ROUNDING_FIELD_OFFSET)-1) << \
    CSI_IMG_ROUNDING_SHIFT

#define CSI_IMG_CROP_ENABLE_SHIFT   CSI_IMG_CHN_CTRL_CROP_ENABLE_FIELD_OFFSET
#define CSI_IMG_CROP_ENABLE_MASK    \
    ((1<< CSI_IMG_CHN_CTRL_CROP_ENABLE_FIELD_SIZE)-1) << \
     CSI_IMG_CROP_ENABLE_SHIFT

#define CSI_IMG_STREAM_ENABLE_SHIFT CSI_IMG_CHN_CTRL_STREAM_ENABLE_FIELD_OFFSET
#define CSI_IMG_STREAM_ENABLE_MASK  \
     ((1<<CSI_IMG_CHN_CTRL_STREAM_ENABLE_FIELD_SIZE)-1) << \
     CSI_IMG_STREAM_ENABLE_SHIFT


/* 0x138: csi image channel split0 */
#define CSI_IMG_CHN_SPLIT0 0x138
#define CSI_IMG_CHN_SPLIT0_VALID_SEL_FIELD_OFFSET 12
#define CSI_IMG_CHN_SPLIT0_VALID_SEL_FIELD_SIZE 2
#define CSI_IMG_CHN_SPLIT0_DATA_SEL_FIELD_OFFSET 0
#define CSI_IMG_CHN_SPLIT0_DATA_SEL_FIELD_SIZE 12

#define CSI_IMG_CHN_SPLIT0_VALID_SEL_SHIFT  \
     CSI_IMG_CHN_SPLIT0_VALID_SEL_FIELD_OFFSET

#define CSI_IMG_CHN_SPLIT0_VALID_SEL_MASK   \
     ((1<<CSI_IMG_CHN_SPLIT0_VALID_SEL_FIELD_SIZE)-1) << \
     CSI_IMG_CHN_SPLIT0_VALID_SEL_SHIFT

#define CSI_IMG_SPLIT0_DATA_SEL_SHIFT       \
     CSI_IMG_CHN_SPLIT0_DATA_SEL_FIELD_OFFSET

#define CSI_IMG_SPLIT0_DATA_SEL_MASK        \
     ((1<<CSI_IMG_CHN_SPLIT0_DATA_SEL_FIELD_SIZE)-1) << \
     CSI_IMG_SPLIT0_DATA_SEL_SHIFT


/* 0x13c: csi image channel split1 */
#define CSI_IMG_CHN_SPLIT1 0x13c
#define CSI_IMG_CHN_SPLIT1_VALID_SEL_FIELD_OFFSET 6
#define CSI_IMG_CHN_SPLIT1_VALID_SEL_FIELD_SIZE 2
#define CSI_IMG_CHN_SPLIT1_DATA_SEL_FIELD_OFFSET 0
#define CSI_IMG_CHN_SPLIT1_DATA_SEL_FIELD_SIZE 6

#define CSI_IMG_CHN_SPLIT1_VALID_SEL_SHIFT  \
    CSI_IMG_CHN_SPLIT1_VALID_SEL_FIELD_OFFSET

#define CSI_IMG_CHN_SPLIT1_VALID_SEL_MASK   \
    ((1<<CSI_IMG_CHN_SPLIT1_VALID_SEL_FIELD_SIZE)-1) << \
    CSI_IMG_CHN_SPLIT1_VALID_SEL_SHIFT

#define CSI_IMG_CHN_SPLIT1_DATA_SEL_SHIFT   \
    CSI_IMG_CHN_SPLIT1_DATA_SEL_FIELD_OFFSET

#define CSI_IMG_CHN_SPLIT1_DATA_SEL_MASK    \
    ((1<<CSI_IMG_CHN_SPLIT1_DATA_SEL_FIELD_SIZE)-1) << \
    CSI_IMG_CHN_SPLIT1_DATA_SEL_SHIFT


/* 0x140: csi image channel split2 */
#define CSI_IMG_CHN_SPLIT2 0x140
#define CSI_IMG_CHN_SPLIT2_VALID_SEL_FIELD_OFFSET 3
#define CSI_IMG_CHN_SPLIT2_VALID_SEL_FIELD_SIZE 2
#define CSI_IMG_CHN_SPLIT2_DATA_SEL_FIELD_OFFSET 0
#define CSI_IMG_CHN_SPLIT2_DATA_SEL_FIELD_SIZE 3

#define CSI_IMG_CHN_SPLIT2_VALID_SEL_SHIFT  \
    CSI_IMG_CHN_SPLIT2_VALID_SEL_FIELD_OFFSET

#define CSI_IMG_CHN_SPLIT2_VALID_SEL_MASK   \
    ((1<<CSI_IMG_CHN_SPLIT2_VALID_SEL_FIELD_SIZE)-1) << \
    CSI_IMG_CHN_SPLIT2_VALID_SEL_SHIFT


/* 0x144: csi image channel crop0 */
#define CSI_IMG_CHN_CROP0 0x144
#define CSI_IMG_CHN_CROP0_LENGTH_FIELD_OFFSET 16
#define CSI_IMG_CHN_CROP0_LENGTH_FIELD_SIZE 16
#define CSI_IMG_CHN_CROP0_POSITION_FIELD_OFFSET 0
#define CSI_IMG_CHN_CROP0_POSITION_FIELD_SIZE 16

#define CSI_IMG_CHN_CROP_LENGTH_SHIFT   \
    CSI_IMG_CHN_CROP0_LENGTH_FIELD_OFFSET

#define CSI_IMG_CHN_CROP_LENGTH_MASK    \
    ((1<<CSI_IMG_CHN_CROP0_LENGTH_FIELD_SIZE)-1) << \
    CSI_IMG_CHN_CROP_LENGTH_SHIFT

#define CSI_IMG_CHN_CROP_POS_SHIFT      \
    CSI_IMG_CHN_CROP0_POSITION_FIELD_OFFSET

#define CSI_IMG_CHN_CROP_POS_MASK       \
    ((1<<CSI_IMG_CHN_CROP0_POSITION_FIELD_SIZE)-1) << \
    CSI_IMG_CHN_CROP_POS_SHIFT


/* 0x148: csi image channel crop1 */
#define CSI_IMG_CHN_CROP1 0x148
#define CSI_IMG_CHN_CROP1_LENGTH_FIELD_OFFSET 16
#define CSI_IMG_CHN_CROP1_LENGTH_FIELD_SIZE 16
#define CSI_IMG_CHN_CROP1_POSITION_FIELD_OFFSET 0
#define CSI_IMG_CHN_CROP1_POSITION_FIELD_SIZE 16


/* 0x148: csi image channel crop2 */
#define CSI_IMG_CHN_CROP2 0x14c
#define CSI_IMG_CHN_CROP2_LENGTH_FIELD_OFFSET 16
#define CSI_IMG_CHN_CROP2_LENGTH_FIELD_SIZE 16
#define CSI_IMG_CHN_CROP2_POSITION_FIELD_OFFSET 0
#define CSI_IMG_CHN_CROP2_POSITION_FIELD_SIZE 16


/* 0x150: csi image channel pack0 */
#define CSI_IMG_CHN_PACK0 0x150
#define CSI_IMG_CHN_PACK0_COLOR_DEPTH3_FIELD_OFFSET 15
#define CSI_IMG_CHN_PACK0_COLOR_DEPTH3_FIELD_SIZE 5
#define CSI_IMG_CHN_PACK0_COLOR_DEPTH2_FIELD_OFFSET 10
#define CSI_IMG_CHN_PACK0_COLOR_DEPTH2_FIELD_SIZE 5
#define CSI_IMG_CHN_PACK0_COLOR_DEPTH1_FIELD_OFFSET 5
#define CSI_IMG_CHN_PACK0_COLOR_DEPTH1_FIELD_SIZE 5
#define CSI_IMG_CHN_PACK0_COLOR_DEPTH0_FIELD_OFFSET 0
#define CSI_IMG_CHN_PACK0_COLOR_DEPTH0_FIELD_SIZE 5

#define CSI_IMG_CHN_PACK_COLOR_DEPTH3_SHIFT     \
    CSI_IMG_CHN_PACK0_COLOR_DEPTH3_FIELD_OFFSET

#define CSI_IMG_CHN_PACK_COLOR_DEPTH3_MASK      \
    ((1<<CSI_IMG_CHN_PACK0_COLOR_DEPTH3_FIELD_SIZE)-1) << \
    CSI_IMG_CHN_PACK_COLOR_DEPTH3_SHIFT

#define CSI_IMG_CHN_PACK_COLOR_DEPTH2_SHIFT     \
    CSI_IMG_CHN_PACK0_COLOR_DEPTH2_FIELD_OFFSET

#define CSI_IMG_CHN_PACK_COLOR_DEPTH2_MASK      \
    ((1<<CSI_IMG_CHN_PACK0_COLOR_DEPTH2_FIELD_SIZE)-1) << \
    CSI_IMG_CHN_PACK_COLOR_DEPTH2_SHIFT

#define CSI_IMG_CHN_PACK_COLOR_DEPTH1_SHIFT     \
    CSI_IMG_CHN_PACK0_COLOR_DEPTH1_FIELD_OFFSET

#define CSI_IMG_CHN_PACK_COLOR_DEPTH1_MASK      \
    ((1<<CSI_IMG_CHN_PACK0_COLOR_DEPTH1_FIELD_SIZE)-1) << \
    CSI_IMG_CHN_PACK_COLOR_DEPTH1_SHIFT

#define CSI_IMG_CHN_PACK_COLOR_DEPTH0_SHIFT     \
    CSI_IMG_CHN_PACK0_COLOR_DEPTH0_FIELD_OFFSET

#define CSI_IMG_CHN_PACK_COLOR_DEPTH0_MASK      \
    ((1<<CSI_IMG_CHN_PACK0_COLOR_DEPTH0_FIELD_SIZE)-1) << \
    CSI_IMG_CHN_PACK_COLOR_DEPTH0_SHIFT


/* 0x154: csi image channel pack1 */
#define CSI_IMG_CHN_PACK1 0x154
#define CSI_IMG_CHN_PACK1_COLOR_DEPTH1_FIELD_OFFSET 5
#define CSI_IMG_CHN_PACK1_COLOR_DEPTH1_FIELD_SIZE 5
#define CSI_IMG_CHN_PACK1_COLOR_DEPTH0_FIELD_OFFSET 0
#define CSI_IMG_CHN_PACK1_COLOR_DEPTH0_FIELD_SIZE 5


/* 0x158: csi image channel pack2 */
#define CSI_IMG_CHN_PACK2 0x158
#define CSI_IMG_CHN_PACK2_COLOR_DEPTH0_FIELD_OFFSET 0
#define CSI_IMG_CHN_PACK2_COLOR_DEPTH0_FIELD_SIZE 5


/* 0x300: csi wdma channel dfifo */
#define CSI_WDMA_CHN_DFIFO 0x300
#define CSI_WDMA_CHN_DFIFO_DFIFO_WML_FIELD_OFFSET 16
#define CSI_WDMA_CHN_DFIFO_DFIFO_WML_FIELD_SIZE 16
#define CSI_WDMA_CHN_DFIFO_DFIFO_DEPTH_FIELD_OFFSET 0
#define CSI_WDMA_CHN_DFIFO_DFIFO_DEPTH_FIELD_SIZE 16

#define CSI_WDMA_DFIFO_WML_SHIFT    \
    CSI_WDMA_CHN_DFIFO_DFIFO_WML_FIELD_OFFSET

#define CSI_WDMA_DFIFO_WML_MASK     \
    ((1<<CSI_WDMA_CHN_DFIFO_DFIFO_WML_FIELD_SIZE)-1) << \
    CSI_WDMA_DFIFO_WML_SHIFT

#define CSI_WDMA_DFIFO_DEPTH_SHIFT  \
    CSI_WDMA_CHN_DFIFO_DFIFO_DEPTH_FIELD_OFFSET

#define CSI_WDMA_DFIFO_DEPTH_MASK   \
    ((1<<CSI_WDMA_CHN_DFIFO_DFIFO_DEPTH_FIELD_SIZE)-1) << \
    CSI_WDMA_DFIFO_DEPTH_SHIFT


/* 0x304: csi wdma channel cfifo */
#define CSI_WDMA_CHN_CFIFO 0x304
#define CSI_WDMA_CHN_CFIFO_CFIFO_DEPTH_FIELD_OFFSET 0
#define CSI_WDMA_CHN_CFIFO_CFIFO_DEPTH_FIELD_SIZE 16

#define CSI_WDMA_CFIFO_DEPTH_SHIFT  \
    CSI_WDMA_CHN_CFIFO_CFIFO_DEPTH_FIELD_OFFSET

#define CSI_WDMA_CFIFO_DEPTH_MASK   \
    ((1<<CSI_WDMA_CHN_CFIFO_CFIFO_DEPTH_FIELD_SIZE)-1) << \
    CSI_WDMA_CFIFO_DEPTH_SHIFT


/* 0x308: csi wdma channel axi ctrl0 */
#define CSI_WDMA_CHN_AXI_CTRL0 0x308
#define CSI_WDMA_CHN_AXI_CTRL0_SCHE_FIELD_OFFSET 12
#define CSI_WDMA_CHN_AXI_CTRL0_SCHE_FIELD_SIZE 6
#define CSI_WDMA_CHN_AXI_CTRL0_PRIO_1_FIELD_OFFSET 6
#define CSI_WDMA_CHN_AXI_CTRL0_PRIO_1_FIELD_SIZE 6
#define CSI_WDMA_CHN_AXI_CTRL0_PRIO_0_FIELD_OFFSET 0
#define CSI_WDMA_CHN_AXI_CTRL0_PRIO_0_FIELD_SIZE 6

#define CSI_WDMA_AXI_SCHE_SHIFT     CSI_WDMA_CHN_AXI_CTRL0_SCHE_FIELD_OFFSET
#define CSI_WDMA_AXI_SCHE_MASK      \
    ((1<<CSI_WDMA_CHN_AXI_CTRL0_SCHE_FIELD_SIZE)-1) << \
    CSI_WDMA_AXI_SCHE_SHIFT

#define CSI_WDMA_AXI_PRIO_1_SHIF    \
    CSI_WDMA_CHN_AXI_CTRL0_PRIO_1_FIELD_OFFSET

#define CSI_WDMA_AXI_PRIO_1_MASK    \
    ((1<<CSI_WDMA_CHN_AXI_CTRL0_PRIO_1_FIELD_SIZE)-1) << \
    CSI_WDMA_AXI_PRIO_1_SHIF

#define CSI_WDMA_AXI_PRIO_0_SHIF    \
    CSI_WDMA_CHN_AXI_CTRL0_PRIO_0_FIELD_OFFSET

#define CSI_WDMA_AXI_PRIO_0_MASK    \
    ((1<<CSI_WDMA_CHN_AXI_CTRL0_PRIO_0_FIELD_SIZE)-1) << \
    CSI_WDMA_AXI_PRIO_0_SHIF


/* 0x31c: csi wdma channel axi ctrl1 */
#define CSI_WDMA_CHN_AXI_CTRL1 0x30c
#define CSI_WDMA_CHN_AXI_CTRL1_USER_FIELD_OFFSET 6
#define CSI_WDMA_CHN_AXI_CTRL1_USER_FIELD_SIZE 26
#define CSI_WDMA_CHN_AXI_CTRL1_PROT_FIELD_OFFSET 4
#define CSI_WDMA_CHN_AXI_CTRL1_PROT_FIELD_SIZE 2
#define CSI_WDMA_CHN_AXI_CTRL1_CACHE_FIELD_OFFSET 0
#define CSI_WDMA_CHN_AXI_CTRL1_CACHE_FIELD_SIZE 4

#define CSI_WDMA_AXI_USER_SHIFT     CSI_WDMA_CHN_AXI_CTRL1_USER_FIELD_OFFSET
#define CSI_WDMA_AXI_USER_MASK      \
    ((1<<CSI_WDMA_CHN_AXI_CTRL1_USER_FIELD_SIZE)-1) << \
    CSI_WDMA_AXI_USER_SHIFT

#define CSI_WDMA_AXI_PROT_SHIFT     CSI_WDMA_CHN_AXI_CTRL1_PROT_FIELD_OFFSET
#define CSI_WDMA_AXI_PROT_MASK      \
    ((1<<CSI_WDMA_CHN_AXI_CTRL1_PROT_FIELD_SIZE)-1) << \
    CSI_WDMA_AXI_PROT_SHIFT

#define CSI_WDMA_AXI_CACHE_SHIFT    CSI_WDMA_CHN_AXI_CTRL1_CACHE_FIELD_OFFSET
#define CSI_WDMA_AXI_CACHE_MASK     \
    ((1<<CSI_WDMA_CHN_AXI_CTRL1_CACHE_FIELD_SIZE)-1) << \
    CSI_WDMA_AXI_CACHE_SHIFT


/* 0x310: csi wdma channel axi ctrl2 */
#define CSI_WDMA_CHN_AXI_CTRL2 0x310
#define CSI_WDMA_CHN_AXI_CTRL2_BUFAB_FIELD_OFFSET 4
#define CSI_WDMA_CHN_AXI_CTRL2_BUFAB_FIELD_SIZE 1
#define CSI_WDMA_CHN_AXI_CTRL2_BUR_MODE_FIELD_OFFSET 3
#define CSI_WDMA_CHN_AXI_CTRL2_BUR_MODE_FIELD_SIZE 1
#define CSI_WDMA_CHN_AXI_CTRL2_LEN_FIELD_OFFSET 0
#define CSI_WDMA_CHN_AXI_CTRL2_LEN_FIELD_SIZE 3

#define CSI_WDMA_AXI_BUFAB_SHIFT    CSI_WDMA_CHN_AXI_CTRL2_BUFAB_FIELD_OFFSET
#define CSI_WDMA_AXI_BUFAB_MASK     \
    ((1<<CSI_WDMA_CHN_AXI_CTRL2_BUFAB_FIELD_SIZE)-1) << \
    CSI_WDMA_AXI_BUFAB_SHIFT

#define CSI_WDMA_AXI_BUR_MODE_SHIFT \
    CSI_WDMA_CHN_AXI_CTRL2_BUR_MODE_FIELD_OFFSET

#define CSI_WDMA_AXI_BUR_MODE_MASK  \
    ((1<<CSI_WDMA_CHN_AXI_CTRL2_BUR_MODE_FIELD_SIZE)-1) << \
    CSI_WDMA_AXI_BUR_MODE_SHIFT

#define CSI_WDMA_AXI_LEN_SHIFT      CSI_WDMA_CHN_AXI_CTRL2_LEN_FIELD_OFFSET
#define CSI_WDMA_AXI_LEN_MASK       \
    ((1<<CSI_WDMA_CHN_AXI_CTRL2_LEN_FIELD_SIZE)-1) << CSI_WDMA_AXI_LEN_SHIFT


/* 0x314: csi wdma channel state */
#define CSI_WDMA_CHN_STATE 0x314
#define CSI_WDMA_CHN_STATE_CNT_FIELD_OFFSET 0
#define CSI_WDMA_CHN_STATE_CNT_FIELD_SIZE 8

#define CSI_WDMA_CHN_STATE_SHIFT    CSI_WDMA_CHN_STATE_CNT_FIELD_OFFSET
#define CSI_WDMA_CHN_STATE_MASK     \
    ((1<<CSI_WDMA_CHN_STATE_CNT_FIELD_SIZE)-1) << CSI_WDMA_CHN_STATE_SHIFT


/* 0x500: csi para bt ctrl0 */
#define CSI_PARA_BT_CTRL0 0x500
#define CSI_PARA2_BT_CTRL0 0x540

#define CSI_PARA_BT_CTRL0_EVEN_HEGHT_FIELD_OFFSET 15
#define CSI_PARA_BT_CTRL0_EVEN_HEGHT_FIELD_SIZE 16
#define CSI_PARA_BT_CTRL0_EVEN_EN_FIELD_OFFSET 14
#define CSI_PARA_BT_CTRL0_EVEN_EN_FIELD_SIZE 1
#define CSI_PARA_BT_CTRL0_CLK_POL_FIELD_OFFSET 13
#define CSI_PARA_BT_CTRL0_CLK_POL_FIELD_SIZE 1
#define CSI_PARA_BT_CTRL0_HSYNC_POL_FIELD_OFFSET 12
#define CSI_PARA_BT_CTRL0_HSYNC_POL_FIELD_SIZE 1
#define CSI_PARA_BT_CTRL0_VSYNC_POL_FIELD_OFFSET 11
#define CSI_PARA_BT_CTRL0_VSYNC_POL_FIELD_SIZE 1
#define CSI_PARA_BT_CTRL0_DATA_EN_POL_FIELD_OFFSET 10
#define CSI_PARA_BT_CTRL0_DATA_EN_POL_FIELD_SIZE 1
#define CSI_PARA_BT_CTRL0_PAPA_UV_PACK_CYCLE_EVEN_FIELD_OFFSET 8
#define CSI_PARA_BT_CTRL0_PAPA_UV_PACK_CYCLE_EVEN_FIELD_SIZE 2
#define CSI_PARA_BT_CTRL0_PAPA_UV_PACK_CYCLE_ODD_FIELD_OFFSET 6
#define CSI_PARA_BT_CTRL0_PAPA_UV_PACK_CYCLE_ODD_FIELD_SIZE 2
#define CSI_PARA_BT_CTRL0_YUV422_20BIT_FIELD_OFFSET 5
#define CSI_PARA_BT_CTRL0_YUV422_20BIT_FIELD_SIZE 1
#define CSI_PARA_BT_CTRL0_PARA_PACK_CYCLE_EVEN_FIELD_OFFSET 3
#define CSI_PARA_BT_CTRL0_PARA_PACK_CYCLE_EVEN_FIELD_SIZE 2
#define CSI_PARA_BT_CTRL0_PAPA_PACK_CYCLE_ODD_FIELD_OFFSET 1
#define CSI_PARA_BT_CTRL0_PAPA_PACK_CYCLE_ODD_FIELD_SIZE 2
#define CSI_PARA_BT_CTRL0_EXIST_FIELD_OFFSET 0
#define CSI_PARA_BT_CTRL0_EXIST_FIELD_SIZE 1

#define CSI_PARA_BT_EVEN_HEIGHT_SHIFT   \
    CSI_PARA_BT_CTRL0_EVEN_HEGHT_FIELD_OFFSET
#define CSI_PARA_BT_EVEN_HEIGHT_MASK    \
    ((1<<CSI_PARA_BT_CTRL0_EVEN_HEGHT_FIELD_SIZE)-1) << \
    CSI_PARA_BT_EVEN_HEIGHT_SHIFT

#define CSI_PARA_BT_EVEN_EN_SHIFT   \
    CSI_PARA_BT_CTRL0_EVEN_EN_FIELD_OFFSET
#define CSI_PARA_BT_EVEN_EN_MASK    \
    ((1<<CSI_PARA_BT_CTRL0_EVEN_EN_FIELD_SIZE)-1) << \
    CSI_PARA_BT_EVEN_EN_SHIFT

#define CSI_PARA_CLK_POL_SHIFT      CSI_PARA_BT_CTRL0_CLK_POL_FIELD_OFFSET
#define CSI_PARA_CLK_POL_MASK       \
    ((1<<CSI_PARA_BT_CTRL0_CLK_POL_FIELD_SIZE)-1) << \
    CSI_PARA_CLK_POL_SHIFT

#define CSI_PARA_HSYNC_POL_SHIFT    CSI_PARA_BT_CTRL0_HSYNC_POL_FIELD_OFFSET
#define CSI_PARA_HSYNC_POL_MASK     \
    ((1<<CSI_PARA_BT_CTRL0_HSYNC_POL_FIELD_SIZE)-1) << \
    CSI_PARA_HSYNC_POL_SHIFT

#define CSI_PARA_VSYNC_POL_SHIFT    CSI_PARA_BT_CTRL0_VSYNC_POL_FIELD_OFFSET
#define CSI_PARA_VSYNC_POL_MASK     \
    ((1<<CSI_PARA_BT_CTRL0_VSYNC_POL_FIELD_SIZE)-1) << \
    CSI_PARA_VSYNC_POL_SHIFT

#define CSI_PARA_DATA_EN_POL_SHIFT  \
    CSI_PARA_BT_CTRL0_DATA_EN_POL_FIELD_OFFSET
#define CSI_PARA_DATA_EN_POL_MASK   \
    ((1<<CSI_PARA_BT_CTRL0_DATA_EN_POL_FIELD_SIZE)-1) << \
    CSI_PARA_DATA_EN_POL_SHIFT

#define CSI_PARA_UV_PACK_CYCLE_EVEN_SHIFT   \
    CSI_PARA_BT_CTRL0_PAPA_UV_PACK_CYCLE_EVEN_FIELD_OFFSET

#define CSI_PARA_UV_PACK_CYCLE_EVEN_MASK    \
    ((1<<CSI_PARA_BT_CTRL0_PAPA_UV_PACK_CYCLE_EVEN_FIELD_SIZE)-1) << \
    CSI_PARA_UV_PACK_CYCLE_EVEN_SHIFT

#define CSI_PARA_UV_PACK_CYCLE_ODD_SHIFT    \
    CSI_PARA_BT_CTRL0_PAPA_UV_PACK_CYCLE_ODD_FIELD_OFFSET

#define CSI_PARA_UV_PACK_CYCLE_ODD_MASK     \
    ((1<<CSI_PARA_BT_CTRL0_PAPA_UV_PACK_CYCLE_ODD_FIELD_SIZE)-1) << \
    CSI_PARA_UV_PACK_CYCLE_ODD_SHIFT

#define CSI_PARA_YUV422_20BIT_SHIFT \
    CSI_PARA_BT_CTRL0_YUV422_20BIT_FIELD_OFFSET

#define CSI_PARA_YUV422_20BIT_MASK  \
    ((1<<CSI_PARA_BT_CTRL0_YUV422_20BIT_FIELD_SIZE)-1) << \
    CSI_PARA_YUV422_20BIT_SHIFT

#define CSI_PARA_PACK_CYCLE_EVEN_SHIFT  \
    CSI_PARA_BT_CTRL0_PARA_PACK_CYCLE_EVEN_FIELD_OFFSET

#define CSI_PARA_PACK_CYCLE_EVEN_MASK   \
    ((1<<CSI_PARA_BT_CTRL0_PARA_PACK_CYCLE_EVEN_FIELD_OFFSET)-1) << \
    CSI_PARA_PACK_CYCLE_EVEN_SHIFT

#define CSI_PARA_PACK_CYCLE_ODD_SHIFT   \
    CSI_PARA_BT_CTRL0_PAPA_PACK_CYCLE_ODD_FIELD_OFFSET

#define CSI_PARA_PACK_CYCLE_ODD_MASK    \
    ((1<< CSI_PARA_BT_CTRL0_PAPA_PACK_CYCLE_ODD_FIELD_SIZE)-1) << \
    CSI_PARA_PACK_CYCLE_ODD_SHIFT

#define CSI_PARA_BT_CTRL0_EXIST_SHIFT   CSI_PARA_BT_CTRL0_EXIST_FIELD_OFFSET
#define CSI_PARA_BT_CTRL0_EXIST_MASK    \
    ((1<<CSI_PARA_BT_CTRL0_EXIST_FIELD_SIZE)-1) << \
    CSI_PARA_BT_CTRL0_EXIST_SHIFT




/* 0x504: csi para bt ctrl1 */
#define CSI_PARA_BT_CTRL1 0x504
#define CSI_PARA2_BT_CTRL1 0x544
#define CSI_PARA_BT_CTRL1_BT_VSYNC_POSTPONE_FIELD_OFFSET 16
#define CSI_PARA_BT_CTRL1_BT_VSYNC_POSTPONE_FIELD_SIZE 16
#define CSI_PARA_BT_CTRL1_BT_FIELD_SEL_FIELD_OFFSET 2
#define CSI_PARA_BT_CTRL1_BT_FIELD_SEL_FIELD_SIZE 1
#define CSI_PARA_BT_CTRL1_BT_VSYNC_SEL_FIELD_OFFSET 1
#define CSI_PARA_BT_CTRL1_BT_VSYNC_SEL_FIELD_SIZE 1
#define CSI_PARA_BT_CTRL1_BT_PROGRESSIVE_FIELD_OFFSET 0
#define CSI_PARA_BT_CTRL1_BT_PROGRESSIVE_FIELD_SIZE 1

#define CSI_PARA_BT_VSYNC_POSTPONE_SHIFT    \
    CSI_PARA_BT_CTRL1_BT_VSYNC_POSTPONE_FIELD_OFFSET

#define CSI_PARA_BT_VSYNC_POSTPONE_MASK     \
    ((1<<CSI_PARA_BT_CTRL1_BT_VSYNC_POSTPONE_FIELD_SIZE)-1) << \
    CSI_PARA_BT_VSYNC_POSTPONE_SHIFT

#define CSI_PARA_BT_FIELD_SEL_SHIFT \
    CSI_PARA_BT_CTRL1_BT_FIELD_SEL_FIELD_OFFSET

#define CSI_PARA_BT_FIELD_SEL_MASK  \
    ((1<<CSI_PARA_BT_CTRL1_BT_FIELD_SEL_FIELD_SIZE)-1) << \
    CSI_PARA_BT_FIELD_SEL_SHIFT

#define CSI_PARA_BT_VSYNC_SEL_SHIFT \
    CSI_PARA_BT_CTRL1_BT_VSYNC_SEL_FIELD_OFFSET

#define CSI_PARA_BT_VSYNC_SEL_MASK  \
    ((1<<CSI_PARA_BT_CTRL1_BT_VSYNC_SEL_FIELD_SIZE)-1) << \
    CSI_PARA_BT_VSYNC_SEL_SHIFT

#define CSI_PARA_BT_PROGRESSIVE_SHIFT   \
    CSI_PARA_BT_CTRL1_BT_PROGRESSIVE_FIELD_OFFSET

#define CSI_PARA_BT_PROGRESSIVE_MASK    \
    ((1<<CSI_PARA_BT_CTRL1_BT_PROGRESSIVE_FIELD_SIZE)-1) << \
    CSI_PARA_BT_PROGRESSIVE_SHIFT


/* 0x508: csi para bt ctrl2 */
#define CSI_PARA_BT_CTRL2 0x508
#define CSI_PARA2_BT_CTRL2 0x548
#define CSI_PARA_BT_CTRL2_BT_VSYNC_EDGE_SEL_FIELD_OFFSET 17
#define CSI_PARA_BT_CTRL2_BT_VSYNC_EDGE_SEL_FIELD_SIZE 1
#define CSI_PARA_BT_CTRL2_BT_FILTER_CNT_FIELD_OFFSET 1
#define CSI_PARA_BT_CTRL2_BT_FILTER_CNT_FIELD_SIZE 16
#define CSI_PARA_BT_CTRL2_BT_FILTER_EN_FIELD_OFFSET 0
#define CSI_PARA_BT_CTRL2_BT_FILTER_EN_FIELD_SIZE 1

#define CSI_PARA_PACK_SWAP_SHIFT            18
#define CSI_PARA_PACK_SWAP_MASK             (1 << 18)

#define CSI_PARA_BT_VSYNC_EDGE_SEL_SHIFT    \
    CSI_PARA_BT_CTRL2_BT_VSYNC_EDGE_SEL_FIELD_OFFSET

#define CSI_PARA_BT_VSYNC_EDGE_SEL_MASK     \
    ((1<<CSI_PARA_BT_CTRL2_BT_VSYNC_EDGE_SEL_FIELD_SIZE)-1) << \
    CSI_PARA_BT_VSYNC_EDGE_SEL_SHIFT

#define CSI_PARA_BT_FILTER_CNT_SHIFT        \
    CSI_PARA_BT_CTRL2_BT_FILTER_CNT_FIELD_OFFSET

#define CSI_PARA_BT_FILTER_CNT_MASK         \
    ((1<<CSI_PARA_BT_CTRL2_BT_FILTER_CNT_FIELD_SIZE)-1) << \
    CSI_PARA_BT_FILTER_CNT_SHIFT

#define CSI_PARA_BT_FILTER_EN_SHIFT     \
    CSI_PARA_BT_CTRL2_BT_FILTER_EN_FIELD_OFFSET

#define CSI_PARA_BT_FILTER_EN_MASK          \
    ((1<<CSI_PARA_BT_CTRL2_BT_FILTER_EN_FIELD_SIZE)-1) << \
    CSI_PARA_BT_FILTER_EN_SHIFT


/* 0x50c: csi pixel map */
#define CSI_PIXEL_MAP 0x50c
#define CSI_PIXEL2_MAP 0x54c
#define CSI_PIXEL_MAP_MAP_FIELD_OFFSET 0
#define CSI_PIXEL_MAP_MAP_FIELD_SIZE 32

#define CSI_PIXEL_MAP_SHIFT         CSI_PIXEL_MAP_MAP_FIELD_OFFSET
#define CSI_PIXEL_MAP_MASK          \
    ((1<<CSI_PIXEL_MAP_MAP_FIELD_SIZE)-1) << CSI_PIXEL_MAP_SHIFT


/* 0x600: csi wdma debug0 */
#define CSI_WDMA_DEBUG_0 0x600
#define WDMA_DEBUG_0_CHN_SEL_FIELD_OFFSET 0
#define WDMA_DEBUG_0_CHN_SEL_FIELD_SIZE 8

#define CSI_WDMA_DEBUG0_CHN_SEL_SHIFT   WDMA_DEBUG_0_CHN_SEL_FIELD_OFFSET
#define CSI_WDMA_DEBUG0_CHN_SEL_MASK    \
    ((1<<WDMA_DEBUG_0_CHN_SEL_FIELD_SIZE)-1) << \
    CSI_WDMA_DEBUG0_CHN_SEL_SHIFT


/* 0x604: csi wdma debug1 */
#define CSI_WDMA_DEBUG_1 0x604
#define WDMA_DEBUG_1_CFIFO_FIELD_OFFSET 16
#define WDMA_DEBUG_1_CFIFO_FIELD_SIZE 16
#define WDMA_DEBUG_1_DFIFO_FIELD_OFFSET 0
#define WDMA_DEBUG_1_DFIFO_FIELD_SIZE 16

#define CSI_WDMA_DEBUG1_CFIFO_SHIFT WDMA_DEBUG_1_CFIFO_FIELD_OFFSET
#define CSI_WDMA_DEBUG1_CFIFO_MASK  \
    ((1<<WDMA_DEBUG_1_CFIFO_FIELD_SIZE)-1) << CSI_WDMA_DEBUG1_CFIFO_SHIFT

#define CSI_WDMA_DEBUG1_DFIFO_SHIFT WDMA_DEBUG_1_DFIFO_FIELD_OFFSET
#define CSI_WDMA_DEBUG1_DFIFO_MASK  \
    ((1<<WDMA_DEBUG_1_DFIFO_FIELD_SIZE)-1) << CSI_WDMA_DEBUG1_DFIFO_SHIFT


/* 0x608: csi wdma debug2 */
#define CSI_WDMA_DEBUG_2 0x608
#define WDMA_DEBUG_2_DFIFO_FIELD_OFFSET 0
#define WDMA_DEBUG_2_DFIFO_FIELD_SIZE 32

#define CSI_WDMA_DEBUG2_DFIFO_SHIFT WDMA_DEBUG_2_DFIFO_FIELD_OFFSET
#define CSI_WDMA_DEBUG2_DFIFO_MASK  \
    ((1<<WDMA_DEBUG_2_DFIFO_FIELD_SIZE)-1) << CSI_WDMA_DEBUG2_DFIFO_SHIFT


/* 0x60c: csi wdma debug3 */
#define CSI_WDMA_DEBUG_3 0x60c
#define WDMA_DEBUG_3_CFIFO_FIELD_OFFSET 0
#define WDMA_DEBUG_3_CFIFO_FIELD_SIZE 32

#define CSI_WDMA_DEBUG3_CFIFO_SHIFT WDMA_DEBUG_3_CFIFO_FIELD_OFFSET
#define CSI_WDMA_DEBUG3_CFIFO_MASK  \
    ((1<<WDMA_DEBUG_3_CFIFO_FIELD_SIZE)-1) << CSI_WDMA_DEBUG3_CFIFO_SHIFT


/* 0x610: csi image debug0 */
#define CSI_IMG_DEBUG_0 0x610
#define IMG_DEBUG_0_HEIGHT_FIELD_OFFSET 16
#define IMG_DEBUG_0_HEIGHT_FIELD_SIZE 16
#define IMG_DEBUG_0_WIDTH_FIELD_OFFSET 0
#define IMG_DEBUG_0_WIDTH_FIELD_SIZE 16

#define CSI_IMG_DEBUG_HEIGHT_SHIFT  IMG_DEBUG_0_HEIGHT_FIELD_OFFSET
#define CSI_IMG_DEBUG_HEIGHT_MASK   \
    ((1<<IMG_DEBUG_0_HEIGHT_FIELD_SIZE)-1) << CSI_IMG_DEBUG_HEIGHT_SHIFT

#define CSI_IMG_DEBUG_WIDTH_SHIFT   IMG_DEBUG_0_WIDTH_FIELD_OFFSET
#define CSI_IMG_DEBUG_WIDTH_MASK    \
    ((1<<IMG_DEBUG_0_WIDTH_FIELD_SIZE)-1) << CSI_IMG_DEBUG_WIDTH_SHIFT


/* 0x614: csi image debug1 */
#define CSI_IMG_DEBUG_1 0x614
#define IMG_DEBUG_1_HEIGHT_FIELD_OFFSET 16
#define IMG_DEBUG_1_HEIGHT_FIELD_SIZE 16
#define IMG_DEBUG_1_WIDTH_FIELD_OFFSET 0
#define IMG_DEBUG_1_WIDTH_FIELD_SIZE 16


/* 0x618: csi image debug2 */
#define CSI_IMG_DEBUG_2 0x618
#define IMG_DEBUG_2_HEIGHT_FIELD_OFFSET 16
#define IMG_DEBUG_2_HEIGHT_FIELD_SIZE 16
#define IMG_DEBUG_2_WIDTH_FIELD_OFFSET 0
#define IMG_DEBUG_2_WIDTH_FIELD_SIZE 16


/* 0x61c: csi image debug3 */
#define CSI_IMG_DEBUG_3 0x61c
#define IMG_DEBUG_3_HEIGHT_FIELD_OFFSET 16
#define IMG_DEBUG_3_HEIGHT_FIELD_SIZE 16
#define IMG_DEBUG_3_WIDTH_FIELD_OFFSET 0
#define IMG_DEBUG_3_WIDTH_FIELD_SIZE 16

#endif
