/*
 * Copyright (c) Semidrive
 */
#include <app.h>
#include <compiler.h>
#include <stdio.h>
#include <platform.h>

#include <err.h>
#include <kernel/semaphore.h>
#include <lib/console.h>
#include <platform/interrupts.h>
#include <bits.h>

#include "__regs_base.h"
#include "scr_hal.h"
#include "sdunittest.h"

struct scr_signal {
    const char      *name;
    scr_signal_t     signal;
};

#define SCR_SIGNAL(x) { \
    .name = #x, \
    .signal = x, \
}

#define SIZEOF(a)   (sizeof (a) / sizeof (a[0]))

static const struct scr_signal scr_safety_signals[] = {
    SCR_SIGNAL(SCR_SAFETY__RO__rstgen_saf_boot_mode_scr_3_0),
    SCR_SIGNAL(SCR_SAFETY__RO__efusec_manu_cfg_87_64),
    SCR_SIGNAL(SCR_SAFETY__RO__efusec_misc_cfg_7),
    SCR_SIGNAL(SCR_SAFETY__RO__efusec_manu_cfg_88),
    SCR_SIGNAL(SCR_SAFETY__RO__efusec_fa_cfg_0),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_m_0_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_m_1_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_m_2_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_m_3_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_m_4_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_m_5_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_m_6_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_0_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_10_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_11_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_1_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_2_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_3_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_4_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_5_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_6_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_7_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_8_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_s_9_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_svreg_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_saf_svreg_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_mainb_m_0_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_mainb_m_1_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_mainb_m_2_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_mainb_noc_reg_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_mainb_noc_reg_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_mainb_s_0_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_mainb_s_1_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_mainb_s_2_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_mainb_s_3_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_mainb_s_4_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__RO__noc_mainb_s_5_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_sem1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_ce1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_pwrctrl_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_ospi1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_canfd1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_canfd2_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_canfd3_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_canfd4_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_i2c1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_i2c2_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_i2c3_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_i2c4_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_timer1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_timer2_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_uart1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_uart2_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_uart3_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_uart4_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_uart5_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_uart6_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_uart7_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_uart8_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_enet1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_pwm1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_pwm2_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_wdt1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_dma1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_rc_24m_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_iram1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_pll1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_pll2_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_pvt_sns_saf_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_bipc_enet1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_i2s_sc1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_i2s_sc2_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_spi1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_spi2_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_spi3_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_spi4_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_xtal_saf_select),
    SCR_SIGNAL(SCR_SAFETY__L16__axislvmux_iram1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__axislvmux_ospi1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__axislvmux_dma1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__axislvmux_ce1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_tm_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_rc_rtc_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_iomux_ctrl_rtc_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_xtal_rtc_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_rtc1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_rtc2_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_pmu_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_rstgen_rtc_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_sec_storage1_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_sec_storage2_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_eic_safe_select),
    SCR_SIGNAL(SCR_SAFETY__L16__apbmux2_gpv_hpib_select),
    SCR_SIGNAL(SCR_SAFETY__L16__ce1_key_perctrl_scr_key_enable_15_0),
    SCR_SIGNAL(SCR_SAFETY__L16__mpc_dma1_resp_err_dis),
    SCR_SIGNAL(SCR_SAFETY__L16__mpc_ce1_resp_err_dis),
    SCR_SIGNAL(SCR_SAFETY__L16__mpc_iram1_resp_err_dis),
    SCR_SIGNAL(SCR_SAFETY__L16__mpc_ospi1_resp_err_dis),
    SCR_SIGNAL(SCR_SAFETY__L16__ppc_apbdecmux1b_resp_err_dis),
    SCR_SIGNAL(SCR_SAFETY__L16__rpc_saf_resp_err_dis),
    SCR_SIGNAL(SCR_SAFETY__L16__gpio_mux1_gpio_sel_15_0),
    SCR_SIGNAL(SCR_SAFETY__L16__gpio_mux1_gpio_sel_31_16),
    SCR_SIGNAL(SCR_SAFETY__L16__gpio_mux1_gpio_sel_47_32),
    SCR_SIGNAL(SCR_SAFETY__L16__gpio_mux_saf_gpio_sel_15_0),
    SCR_SIGNAL(SCR_SAFETY__L16__gpio_mux_saf_gpio_sel_31_16),
    SCR_SIGNAL(SCR_SAFETY__L16__gpio_mux_saf_gpio_sel_47_32),
    SCR_SIGNAL(SCR_SAFETY__L16__gpio_mux_saf_gpio_sel_63_48),
    SCR_SIGNAL(SCR_SAFETY__L16__gpio_mux_saf_gpio_sel_79_64),
    SCR_SIGNAL(SCR_SAFETY__L16__gpio_mux_saf_gpio_sel_95_80),
    SCR_SIGNAL(SCR_SAFETY__L16__tbu11_byp_mux_bypass),
    SCR_SIGNAL(SCR_SAFETY__L16__tbu12_byp_mux_bypass),
    SCR_SIGNAL(SCR_SAFETY__L16__tbu13_byp_mux_bypass),
    SCR_SIGNAL(SCR_SAFETY__L16__fsrefclk_saf_src_sel_1_0),
    SCR_SIGNAL(SCR_SAFETY__L16__fsrefclk_saf_xtal_cg_en),
    SCR_SIGNAL(SCR_SAFETY__L16__fsrefclk_saf_fs_rc_en),
    SCR_SIGNAL(SCR_SAFETY__L16__fsrefclk_saf_fs_xtal_en),
    SCR_SIGNAL(SCR_SAFETY__L16__cr5_saf_dccminp_0),
    SCR_SIGNAL(SCR_SAFETY__L16__cr5_saf_dccminp2_0),
    SCR_SIGNAL(SCR_SAFETY__L31__remap_cr5_saf_aw_addr_offset_19_0),
    SCR_SIGNAL(SCR_SAFETY__L31__remap_cr5_saf_aw_remap_ovrd_en),
    SCR_SIGNAL(SCR_SAFETY__L31__remap_cr5_saf_ar_addr_offset_19_0),
    SCR_SIGNAL(SCR_SAFETY__L31__remap_cr5_saf_ar_remap_ovrd_en),
    SCR_SIGNAL(SCR_SAFETY__L31__noc_saf_firewall_mainfw_enable),
    SCR_SIGNAL(SCR_SAFETY__L31__cr5_saf_dbgen),
    SCR_SIGNAL(SCR_SAFETY__L31__cr5_saf_niden),
    SCR_SIGNAL(SCR_SAFETY__L31__remap_ospi1_imagd_2nd_offset_19_0),
    SCR_SIGNAL(SCR_SAFETY__L31__remap_ospi1_remap_en),
    SCR_SIGNAL(SCR_SAFETY__L31__remap_ospi1_imagd_2nd_low_limit_19_0),
    SCR_SIGNAL(SCR_SAFETY__L31__remap_ospi1_imagd_2nd_up_limit_19_0),
    SCR_SIGNAL(SCR_SAFETY__L31__pvt_sns_saf_fuse_pvt_11_0),
    SCR_SIGNAL(SCR_SAFETY__L31__por_rtc_hyst0_1_0),
    SCR_SIGNAL(SCR_SAFETY__L31__por_rtc_hyst1_1_0),
    SCR_SIGNAL(SCR_SAFETY__L31__por_saf_hyst0_1_0),
    SCR_SIGNAL(SCR_SAFETY__L31__por_saf_hyst1_1_0),
    SCR_SIGNAL(SCR_SAFETY__L31__por_saf_por_pd),
    SCR_SIGNAL(SCR_SAFETY__L31__por_saf_vddio_val_on_2_0),
    SCR_SIGNAL(SCR_SAFETY__L31__por_saf_vddio_val_off_2_0),
    SCR_SIGNAL(SCR_SAFETY__L31__por_saf_vdd_val_on_2_0),
    SCR_SIGNAL(SCR_SAFETY__L31__por_saf_vdd_val_off_2_0),
    SCR_SIGNAL(SCR_SAFETY__L31__por_saf_wait_time_2_0),
    SCR_SIGNAL(SCR_SAFETY__RW__remap_cr5_saf_aw_irq_en),
    SCR_SIGNAL(SCR_SAFETY__RW__remap_cr5_saf_aw_irq_w1c),
    SCR_SIGNAL(SCR_SAFETY__RW__remap_cr5_saf_ar_irq_en),
    SCR_SIGNAL(SCR_SAFETY__RW__remap_cr5_saf_ar_irq_w1c),
    SCR_SIGNAL(SCR_SAFETY__RW__ce1_security_violation_6),
    SCR_SIGNAL(SCR_SAFETY__RW__ce2_security_violation_6),
    SCR_SIGNAL(SCR_SAFETY__RW__sec_storage1_secure_violation_6),
    SCR_SIGNAL(SCR_SAFETY__RW__sec_storage2_secure_violation_6),
    SCR_SIGNAL(SCR_SAFETY__RW__spi1_i_opmode),
    SCR_SIGNAL(SCR_SAFETY__RW__spi2_i_opmode),
    SCR_SIGNAL(SCR_SAFETY__RW__spi3_i_opmode),
    SCR_SIGNAL(SCR_SAFETY__RW__spi4_i_opmode),
    SCR_SIGNAL(SCR_SAFETY__RW__timer1_lp_mode),
    SCR_SIGNAL(SCR_SAFETY__RW__timer2_lp_mode),
    SCR_SIGNAL(SCR_SAFETY__RW__pio_i2s_sc12_oectrl_1_0),
    SCR_SIGNAL(SCR_SAFETY__RW__saf_debug_mode),
    SCR_SIGNAL(SCR_SAFETY__RW__enet1_pps_stretch_cfg_i_31_0),
    SCR_SIGNAL(SCR_SAFETY__RW__io_safe_prefgen_vddio_jtag_lpm),
    SCR_SIGNAL(SCR_SAFETY__RW__io_safe_prefgen_vddio_qspi1_lpm),
    SCR_SIGNAL(SCR_SAFETY__RW__io_safe_prefgen_vddio_rgmii1_lpm),
    SCR_SIGNAL(SCR_SAFETY__RW__io_safe_prefgen_vddio_gpio_a_lpm),
    SCR_SIGNAL(SCR_SAFETY__RW__io_safe_prefgen_vddio_gpio_b_lpm),
    SCR_SIGNAL(SCR_SAFETY__RW__ddr_ss_pwrokin_aon),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd1_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd1_ipg_stop),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd1_ipg_doze),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd2_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd2_ipg_stop),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd2_ipg_doze),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd3_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd3_ipg_stop),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd3_ipg_doze),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd4_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd4_ipg_stop),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd4_ipg_doze),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_csysreq_i),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_cmp_sel),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_cpt_sel),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_phy_intf_sel_i_2_0),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_sbd_flowctrl_i_4_0),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_rmii_clk_oe),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_cap_comp_0_oe),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_cap_comp_1_oe),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_cap_comp_2_oe),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_cap_comp_3_oe),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu11_pmusnapshot_req),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu11_qreqn_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu12_pmusnapshot_req),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu12_qreqn_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu13_pmusnapshot_req),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu13_qreqn_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_rtc_power_lat_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_saf_power_lat_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_ap_power_lat_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_rtc_power_lat_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_saf_power_lat_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_ap_power_lat_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_0_maindupl_sgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_0_mainmain_sgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_1_maindupl_sgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_1_mainmain_sgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_mainmain_sglaraddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_mainmain_sglawaddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_mainmain_sgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_maindupl_sglaraddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_maindupl_sglawaddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_maindupl_sgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_mainb_m_0_mainsglaraddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_mainb_m_0_mainsglawaddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_mainb_m_0_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_0_maindupl_sgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_0_mainmain_sgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_1_maindupl_sgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_1_mainmain_sgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_2_maindupl_sgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_2_mainmain_sgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_4_maindupl_sgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_4_mainmain_sgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximcorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axiscorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxcorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_pphcorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximfatal0_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximfatal0_1_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximfatal0_2_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximfatal0_3_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximfatal0_4_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axisfatal0_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axisfatal0_1_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axisfatal0_2_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axisfatal0_3_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axisfatal0_4_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxfatal0_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxfatal0_1_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxfatal0_2_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxfatal0_3_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxfatal0_4_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_dccmout_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_dccmout2_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd1_ipg_stop_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd1_can_lpm_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd2_ipg_stop_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd2_can_lpm_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd3_ipg_stop_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd3_can_lpm_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd4_ipg_stop_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__canfd4_can_lpm_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_csysack_o),
    SCR_SIGNAL(SCR_SAFETY__R16W16__enet1_cactive_o),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu11_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu11_qacceptn_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu11_qactive_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu11_qdeny_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu12_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu12_qacceptn_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu12_qactive_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu12_qdeny_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu13_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu13_qacceptn_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu13_qactive_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__tbu13_qdeny_cg),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_rtc_power_loss),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_saf_power_loss),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_ap_power_loss),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_rtc_power_lat),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_saf_power_lat),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_ap_power_lat),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_rtc_power_lat_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_saf_power_lat_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_rtc_ap_power_lat_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_rtc_power_loss),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_saf_power_loss),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_ap_power_loss),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_rtc_power_lat),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_saf_power_lat),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_ap_power_lat),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_rtc_power_lat_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_saf_power_lat_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__pwr_lat_saf_ap_power_lat_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_0_maindupl_sgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_0_mainmain_sgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_1_maindupl_sgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_1_mainmain_sgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_mainmain_sglaraddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_mainmain_sglawaddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_mainmain_sgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_maindupl_sglaraddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_maindupl_sglawaddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_m_4_maindupl_sgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_mainb_m_0_mainsglaraddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_mainb_m_0_mainsglawaddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_mainb_m_0_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_0_maindupl_sgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_0_mainmain_sgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_1_maindupl_sgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_1_mainmain_sgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_2_maindupl_sgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_2_mainmain_sgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_4_maindupl_sgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__noc_saf_s_4_mainmain_sgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximcorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axiscorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxcorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_pphcorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximfatal0_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximfatal0_1_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximfatal0_2_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximfatal0_3_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_aximfatal0_4_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axisfatal0_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axisfatal0_1_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axisfatal0_2_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axisfatal0_3_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_axisfatal0_4_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxfatal0_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxfatal0_1_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxfatal0_2_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxfatal0_3_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_ppxfatal0_4_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_dccmout_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SAFETY__R16W16__cr5_saf_dccmout2_0_siglat_scr_clr_ack),
};

static const struct scr_signal scr_sec_signals[] = {
    SCR_SIGNAL(SCR_SEC__L16__ce2_key_perctrl_scr_key_enable_15_0),
    SCR_SIGNAL(SCR_SEC__L16__ce2_key_perctrl_scr_key_enable_31_16),
    SCR_SIGNAL(SCR_SEC__L16__ce2_key_perctrl_scr_key_enable_47_32),
    SCR_SIGNAL(SCR_SEC__L16__ce2_key_perctrl_scr_key_enable_63_48),
    SCR_SIGNAL(SCR_SEC__L16__ce2_key_perctrl_scr_key_enable_79_64),
    SCR_SIGNAL(SCR_SEC__L16__ce2_key_perctrl_scr_key_enable_95_80),
    SCR_SIGNAL(SCR_SEC__L16__ce2_key_perctrl_scr_key_enable_111_96),
    SCR_SIGNAL(SCR_SEC__L16__ce2_key_perctrl_scr_key_enable_127_112),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_15_0),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_31_16),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_47_32),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_63_48),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_79_64),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_95_80),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_111_96),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_127_112),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_143_128),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_159_144),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_175_160),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_191_176),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_207_192),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux_sec_gpio_sel_215_208),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux2_gpio_sel_15_0),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux2_gpio_sel_31_16),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux2_gpio_sel_47_32),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux2_gpio_sel_63_48),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux2_gpio_sel_79_64),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux2_gpio_sel_95_80),
    SCR_SIGNAL(SCR_SEC__L16__gpio_mux2_gpio_sel_107_96),
    SCR_SIGNAL(SCR_SEC__L16__tbu0_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__tbu1_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__tbu2_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__tbu3_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__tbu4_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__tbu5_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__tbu6_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__tbu8_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__tbu9_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__tbu10_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__tbu14_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__tbu15_byp_mux_bypass),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_sec_src_sel_1_0),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_sec_xtal_cg_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_sec_fs_rc_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_sec_fs_xtal_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_hpi_src_sel_1_0),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_hpi_xtal_cg_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_hpi_fs_rc_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_hpi_fs_xtal_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_cpu1_src_sel_1_0),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_cpu1_xtal_cg_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_cpu1_fs_rc_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_cpu1_fs_xtal_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_cpu2_src_sel_1_0),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_cpu2_xtal_cg_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_cpu2_fs_rc_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_cpu2_fs_xtal_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_gpu1_src_sel_1_0),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_gpu1_xtal_cg_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_gpu1_fs_rc_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_gpu1_fs_xtal_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_gpu2_src_sel_1_0),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_gpu2_xtal_cg_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_gpu2_fs_rc_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_gpu2_fs_xtal_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_his_src_sel_1_0),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_his_xtal_cg_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_his_fs_rc_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_his_fs_xtal_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_vpu_src_sel_1_0),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_vpu_xtal_cg_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_vpu_fs_rc_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_vpu_fs_xtal_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_vsn_src_sel_1_0),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_vsn_xtal_cg_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_vsn_fs_rc_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_vsn_fs_xtal_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_disp_src_sel_1_0),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_disp_xtal_cg_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_disp_fs_rc_en),
    SCR_SIGNAL(SCR_SEC__L16__fsrefclk_disp_fs_xtal_en),
    SCR_SIGNAL(SCR_SEC__L16__ddr_ss_fsrefclk_src_sel_1_0),
    SCR_SIGNAL(SCR_SEC__L16__ddr_ss_fsrefclk_xtal_cg_en),
    SCR_SIGNAL(SCR_SEC__L16__ddr_ss_fsrefclk_fs_rc_en),
    SCR_SIGNAL(SCR_SEC__L16__ddr_ss_fsrefclk_fs_xtal_en),
    SCR_SIGNAL(SCR_SEC__L16__mac_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_ce2_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_iram2_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_iram3_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_iram4_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_sec_platform_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_mp_platform_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_romc2_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_ospi2_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_gic2_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_gic3_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_mu_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_apbdecmux2_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_apbdecmux3_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_ce2_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_apbdecmux4_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_apbdecmux5_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_apbdecmux6_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_apbdecmux7b_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_apbdecmux8_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_ddr_cfg_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_tcu_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_cssys_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_scr4k_sid_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__ppc_scr4k_ssid_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_pciex1_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_pciex2_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_ddr_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_vdsp_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_gic4_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_gic5_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_gpu1_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_gpu2_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__rpc_sec_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__rpc_soc_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__mpc_iram5_resp_err_dis),
    SCR_SIGNAL(SCR_SEC__L16__cr5_sec_dccminp_0),
    SCR_SIGNAL(SCR_SEC__L16__cr5_sec_dccminp2_0),
    SCR_SIGNAL(SCR_SEC__L16__cr5_mp_dccminp_0),
    SCR_SIGNAL(SCR_SEC__L16__cr5_mp_dccminp2_0),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_dbgen),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_niden),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_spiden),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_spniden),
    SCR_SIGNAL(SCR_SEC__L31__cpu2_rvbaraddr0_29_2),
    SCR_SIGNAL(SCR_SEC__L31__cpu2_rvbaraddr0_39_30),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr0_29_2),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr0_39_30),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr1_29_2),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr1_39_30),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr2_29_2),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr2_39_30),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr3_29_2),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr3_39_30),
    SCR_SIGNAL(SCR_SEC__L31__pvt_sns_sec_fuse_pvt_11_0),
    SCR_SIGNAL(SCR_SEC__L31__remap_cr5_sec_aw_addr_offset_19_0),
    SCR_SIGNAL(SCR_SEC__L31__remap_cr5_sec_aw_remap_ovrd_en),
    SCR_SIGNAL(SCR_SEC__L31__remap_cr5_sec_ar_addr_offset_19_0),
    SCR_SIGNAL(SCR_SEC__L31__remap_cr5_sec_ar_remap_ovrd_en),
    SCR_SIGNAL(SCR_SEC__L31__cr5_sec_dbgen),
    SCR_SIGNAL(SCR_SEC__L31__cr5_sec_niden),
    SCR_SIGNAL(SCR_SEC__L31__remap_cr5_mp_aw_addr_offset_19_0),
    SCR_SIGNAL(SCR_SEC__L31__remap_cr5_mp_aw_remap_en),
    SCR_SIGNAL(SCR_SEC__L31__remap_cr5_mp_ar_addr_offset_19_0),
    SCR_SIGNAL(SCR_SEC__L31__remap_cr5_mp_ar_remap_en),
    SCR_SIGNAL(SCR_SEC__L31__cr5_mp_dbgen),
    SCR_SIGNAL(SCR_SEC__L31__cr5_mp_niden),
    SCR_SIGNAL(SCR_SEC__L31__cssys_dbgen),
    SCR_SIGNAL(SCR_SEC__L31__cssys_niden),
    SCR_SIGNAL(SCR_SEC__L31__cssys_spiden),
    SCR_SIGNAL(SCR_SEC__L31__cssys_spniden),
    SCR_SIGNAL(SCR_SEC__L31__remap_ospi2_imagd_2nd_offset_19_0),
    SCR_SIGNAL(SCR_SEC__L31__remap_ospi2_remap_en),
    SCR_SIGNAL(SCR_SEC__L31__remap_ospi2_imagd_2nd_low_limit_19_0),
    SCR_SIGNAL(SCR_SEC__L31__remap_ospi2_imagd_2nd_up_limit_19_0),
    SCR_SIGNAL(SCR_SEC__L31__vdsp_altresetvec_31_4),
    SCR_SIGNAL(SCR_SEC__L31__cmdtag_i_nocsheduler_bypss),
    SCR_SIGNAL(SCR_SEC__L31__noc2ddr_fifo_wrap_bypass),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr4_29_2),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr4_39_30),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr5_29_2),
    SCR_SIGNAL(SCR_SEC__L31__cpu1_rvbaraddr5_39_30),
    SCR_SIGNAL(SCR_SEC__L31__cssys_tp_maxdatasize_3_0),
    SCR_SIGNAL(SCR_SEC__L31__iomux_wrap_ap_pio_disp_mux__data1__oe),
    SCR_SIGNAL(SCR_SEC__L31__iomux_wrap_ap_pio_disp_mux__data3__oe),
    SCR_SIGNAL(SCR_SEC__L31__iomux_wrap_ap_pio_disp_mux__data5__oe),
    SCR_SIGNAL(SCR_SEC__L31__iomux_wrap_ap_pio_disp_mux__data7__oe),
    SCR_SIGNAL(SCR_SEC__L31__iomux_wrap_ap_pio_disp_mux__data9__oe),
    SCR_SIGNAL(SCR_SEC__L31__iomux_wrap_ap_pio_disp_mux__data11__oe),
    SCR_SIGNAL(SCR_SEC__L31__iomux_wrap_ap_pio_disp_mux__data13__oe),
    SCR_SIGNAL(SCR_SEC__L31__iomux_wrap_ap_pio_disp_mux__data15__oe),
    SCR_SIGNAL(SCR_SEC__L31__iomux_wrap_ap_pio_disp_mux__data17__oe),
    SCR_SIGNAL(SCR_SEC__L31__iomux_wrap_ap_pio_disp_mux__data19__oe),
    SCR_SIGNAL(SCR_SEC__L31__cpu2_dbgen),
    SCR_SIGNAL(SCR_SEC__L31__cpu2_niden),
    SCR_SIGNAL(SCR_SEC__L31__cpu2_spiden),
    SCR_SIGNAL(SCR_SEC__L31__cpu2_spniden),
    SCR_SIGNAL(SCR_SEC__RW__ce1_security_violation_7),
    SCR_SIGNAL(SCR_SEC__RW__ce2_security_violation_7),
    SCR_SIGNAL(SCR_SEC__RW__sec_storage1_secure_violation_7),
    SCR_SIGNAL(SCR_SEC__RW__sec_storage2_secure_violation_7),
    SCR_SIGNAL(SCR_SEC__RW__dbg_mux_pu_sel1_1_0),
    SCR_SIGNAL(SCR_SEC__RW__dbg_mux_pu_sel2_1_0),
    SCR_SIGNAL(SCR_SEC__RW__pio_i2s_sc_sdo_sdi_ctrl_5_0),
    SCR_SIGNAL(SCR_SEC__RW__mshc1_ddr_mode),
    SCR_SIGNAL(SCR_SEC__RW__mshc1_phy_resetb_scr),
    SCR_SIGNAL(SCR_SEC__RW__mshc2_ddr_mode),
    SCR_SIGNAL(SCR_SEC__RW__mshc2_phy_resetb_scr),
    SCR_SIGNAL(SCR_SEC__RW__mshc3_ddr_mode),
    SCR_SIGNAL(SCR_SEC__RW__mshc4_ddr_mode),
    SCR_SIGNAL(SCR_SEC__RW__remap_cr5_sec_aw_irq_en),
    SCR_SIGNAL(SCR_SEC__RW__remap_cr5_sec_aw_irq_w1c),
    SCR_SIGNAL(SCR_SEC__RW__remap_cr5_sec_ar_irq_en),
    SCR_SIGNAL(SCR_SEC__RW__remap_cr5_sec_ar_irq_w1c),
    SCR_SIGNAL(SCR_SEC__RW__remap_cr5_mp_aw_irq_en),
    SCR_SIGNAL(SCR_SEC__RW__remap_cr5_mp_aw_irq_w1c),
    SCR_SIGNAL(SCR_SEC__RW__remap_cr5_mp_ar_irq_en),
    SCR_SIGNAL(SCR_SEC__RW__remap_cr5_mp_ar_irq_w1c),
    SCR_SIGNAL(SCR_SEC__RW__spi5_i_opmode),
    SCR_SIGNAL(SCR_SEC__RW__spi6_i_opmode),
    SCR_SIGNAL(SCR_SEC__RW__spi7_i_opmode),
    SCR_SIGNAL(SCR_SEC__RW__spi8_i_opmode),
    SCR_SIGNAL(SCR_SEC__RW__timer3_lp_mode),
    SCR_SIGNAL(SCR_SEC__RW__timer4_lp_mode),
    SCR_SIGNAL(SCR_SEC__RW__timer5_lp_mode),
    SCR_SIGNAL(SCR_SEC__RW__timer6_lp_mode),
    SCR_SIGNAL(SCR_SEC__RW__timer7_lp_mode),
    SCR_SIGNAL(SCR_SEC__RW__timer8_lp_mode),
    SCR_SIGNAL(SCR_SEC__RW__vpu2_i_linebuffer_cfg_1_0),
    SCR_SIGNAL(SCR_SEC__RW__sec_debug_mode),
    SCR_SIGNAL(SCR_SEC__RW__enet2_pps_stretch_cfg_i_31_0),
    SCR_SIGNAL(SCR_SEC__RW__io_ap_prefgen_vddio_gpio_c_lpm),
    SCR_SIGNAL(SCR_SEC__RW__io_ap_prefgen_vddio_gpio_d_lpm),
    SCR_SIGNAL(SCR_SEC__RW__io_ap_prefgen_vddio_qspi2_lpm),
    SCR_SIGNAL(SCR_SEC__RW__io_ap_prefgen_vddio_rgmii2_lpm),
    SCR_SIGNAL(SCR_SEC__RW__io_ap_prefgen_vddio_i2s_sc_lpm),
    SCR_SIGNAL(SCR_SEC__RW__io_ap_prefgen_vddio_i2s_mc_lpm),
    SCR_SIGNAL(SCR_SEC__RW__ddr_ss_pwrokin_aon),
    SCR_SIGNAL(SCR_SEC__RW__noc_main_disp_press_hurry_en),
    SCR_SIGNAL(SCR_SEC__RW__noc_main_nondisp_press_hurry_en),
    SCR_SIGNAL(SCR_SEC__RW___spare4spi_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd5_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd5_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd5_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd6_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd6_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd6_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd7_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd7_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd7_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd8_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd8_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd8_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__ddr_ss_csysreq_ddrc),
    SCR_SIGNAL(SCR_SEC__R16W16__cmdtag_i_cmftag_cfg_aful_th_2_0),
    SCR_SIGNAL(SCR_SEC__R16W16__enet2_csysreq_i),
    SCR_SIGNAL(SCR_SEC__R16W16__enet2_cmp_sel),
    SCR_SIGNAL(SCR_SEC__R16W16__enet2_cpt_sel),
    SCR_SIGNAL(SCR_SEC__R16W16__enet2_phy_intf_sel_i_2_0),
    SCR_SIGNAL(SCR_SEC__R16W16__enet2_sbd_flowctrl_i_4_0),
    SCR_SIGNAL(SCR_SEC__R16W16__enet2_rmii_clk_oe),
    SCR_SIGNAL(SCR_SEC__R16W16__enet2_cap_comp_0_oe),
    SCR_SIGNAL(SCR_SEC__R16W16__enet2_cap_comp_1_oe),
    SCR_SIGNAL(SCR_SEC__R16W16__enet2_cap_comp_2_oe),
    SCR_SIGNAL(SCR_SEC__R16W16__gpu1_core_clk_en),
    SCR_SIGNAL(SCR_SEC__R16W16__gpu1_sys_clk_en),
    SCR_SIGNAL(SCR_SEC__R16W16__gpu1_mem_clk_en),
    SCR_SIGNAL(SCR_SEC__R16W16__gpu1_debug_enable),
    SCR_SIGNAL(SCR_SEC__R16W16__gpu2_core_clk_en),
    SCR_SIGNAL(SCR_SEC__R16W16__gpu2_sys_clk_en),
    SCR_SIGNAL(SCR_SEC__R16W16__gpu2_mem_clk_en),
    SCR_SIGNAL(SCR_SEC__R16W16__gpu2_debug_enable),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_i_pciex1_mstr_csysreq),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_i_pciex1_slv_csysreq),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_i_pciex2_mstr_csysreq),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_i_pciex2_slv_csysreq),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu0_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu0_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu1_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu1_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu2_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu2_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu3_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu3_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu4_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu4_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu5_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu5_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu6_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu6_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu8_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu8_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu9_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu9_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu10_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu10_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu14_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu14_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu15_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu15_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tcu_pmusnapshot_req),
    SCR_SIGNAL(SCR_SEC__R16W16__tcu_qreqn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__usb_ss_i_usb1_xm_csysreq),
    SCR_SIGNAL(SCR_SEC__R16W16__usb_ss_i_usb2_xm_csysreq),
    SCR_SIGNAL(SCR_SEC__R16W16__vdsp_statvectorsel),
    SCR_SIGNAL(SCR_SEC__R16W16__vdsp_runstall),
    SCR_SIGNAL(SCR_SEC__R16W16__vdsp_debug_enable),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_0_mainsgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_1_mainsgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_2_mainsgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_3_mainsgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_5_mainsglaraddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_5_mainsglawaddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_5_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_0_mainsgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_1_mainsgleccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_2_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_3_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_13_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_14_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_17_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_11_mainsglaraddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_11_mainsglawaddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_11_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_12_mainsglaraddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_12_mainsglawaddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_12_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_24_mainsglaraddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_24_mainsglawaddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_24_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_s_0_sbp_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_s_3_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_s_4_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_s_11_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_0_mainsglaraddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_0_mainsglawaddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_0_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_1_mainsglaraddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_1_mainsglawaddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_1_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_2_mainsglaraddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_2_mainsglawaddreccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_2_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_s_0_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_s_3_mainsgldataeccerr_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__vdsp_doubleexceptionerror_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximcorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axiscorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxcorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_pphcorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximfatal0_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximfatal0_1_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximfatal0_2_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximfatal0_3_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximfatal0_4_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axisfatal0_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axisfatal0_1_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axisfatal0_2_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axisfatal0_3_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axisfatal0_4_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxfatal0_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxfatal0_1_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxfatal0_2_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxfatal0_3_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxfatal0_4_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_dccmout_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_dccmout2_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximcorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axiscorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxcorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_pphcorr0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximfatal0_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximfatal0_1_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximfatal0_2_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximfatal0_3_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximfatal0_4_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axisfatal0_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axisfatal0_1_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axisfatal0_2_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axisfatal0_3_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axisfatal0_4_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxfatal0_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxfatal0_1_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxfatal0_2_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxfatal0_3_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxfatal0_4_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_dccmout_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_dccmout2_0_siglat_scr_clr),
    SCR_SIGNAL(SCR_SEC__R16W16__can9_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can9_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can9_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__can10_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can10_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can10_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__can11_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can11_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can11_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__can12_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can12_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can12_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__can13_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can13_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can13_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__can14_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can14_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can14_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__can15_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can15_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can15_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__can16_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can16_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can16_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__can17_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can17_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can17_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__can18_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can18_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can18_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__can19_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can19_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can19_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__can20_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_SEC__R16W16__can20_ipg_stop),
    SCR_SIGNAL(SCR_SEC__R16W16__can20_ipg_doze),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd5_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd5_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd6_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd6_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd7_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd7_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd8_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__canfd8_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__ddr_ss_csysack_ddrc),
    SCR_SIGNAL(SCR_SEC__R16W16__ddr_ss_cactive_ddrc),
    SCR_SIGNAL(SCR_SEC__R16W16__cmdtag_o_cmdtag_fifo_ovf),
    SCR_SIGNAL(SCR_SEC__R16W16__enet2_csysack_o),
    SCR_SIGNAL(SCR_SEC__R16W16__enet2_cactive_o),
    SCR_SIGNAL(SCR_SEC__R16W16__gpu1_idle),
    SCR_SIGNAL(SCR_SEC__R16W16__gpu2_idle),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_o_pciex1_mstr_csysack),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_o_pciex1_mstr_cactive),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_o_pciex1_slv_csysack),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_o_pciex1_slv_cactive),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_o_pciex2_mstr_csysack),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_o_pciex2_mstr_cactive),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_o_pciex2_slv_csysack),
    SCR_SIGNAL(SCR_SEC__R16W16__pcie_ss_o_pciex2_slv_cactive),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu0_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu0_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu0_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu0_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu1_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu1_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu1_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu1_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu2_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu2_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu2_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu2_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu3_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu3_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu3_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu3_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu4_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu4_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu4_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu4_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu5_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu5_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu5_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu5_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu6_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu6_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu6_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu6_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu8_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu8_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu8_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu8_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu9_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu9_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu9_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu9_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu10_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu10_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu10_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu10_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu14_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu14_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu14_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu14_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu15_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu15_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu15_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tbu15_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tcu_pmusnapshot_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__tcu_qacceptn_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tcu_qactive_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__tcu_qdeny_cg),
    SCR_SIGNAL(SCR_SEC__R16W16__usb_ss_o_usb1_xm_csysack),
    SCR_SIGNAL(SCR_SEC__R16W16__usb_ss_o_usb1_xm_cactive),
    SCR_SIGNAL(SCR_SEC__R16W16__usb_ss_o_usb2_xm_csysack),
    SCR_SIGNAL(SCR_SEC__R16W16__usb_ss_o_usb2_xm_cactive),
    SCR_SIGNAL(SCR_SEC__R16W16__vdsp_parithmeticexception),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_0_mainsgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_1_mainsgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_2_mainsgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_3_mainsgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_5_mainsglaraddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_5_mainsglawaddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_m_5_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_0_mainsgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_1_mainsgleccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_2_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_3_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_13_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_14_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_sec_s_17_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_11_mainsglaraddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_11_mainsglawaddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_11_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_12_mainsglaraddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_12_mainsglawaddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_12_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_24_mainsglaraddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_24_mainsglawaddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_m_24_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_s_0_sbp_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_s_3_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_s_4_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_main_s_11_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_0_mainsglaraddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_0_mainsglawaddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_0_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_1_mainsglaraddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_1_mainsglawaddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_1_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_2_mainsglaraddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_2_mainsglawaddreccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_m_2_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_s_0_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__noc_vsn_s_3_mainsgldataeccerr_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__vdsp_doubleexceptionerror_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximcorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axiscorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxcorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_pphcorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximfatal0_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximfatal0_1_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximfatal0_2_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximfatal0_3_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_aximfatal0_4_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axisfatal0_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axisfatal0_1_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axisfatal0_2_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axisfatal0_3_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_axisfatal0_4_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxfatal0_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxfatal0_1_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxfatal0_2_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxfatal0_3_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_ppxfatal0_4_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_dccmout_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_sec_dccmout2_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximcorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axiscorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxcorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_pphcorr0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximfatal0_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximfatal0_1_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximfatal0_2_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximfatal0_3_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_aximfatal0_4_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axisfatal0_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axisfatal0_1_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axisfatal0_2_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axisfatal0_3_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_axisfatal0_4_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxfatal0_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxfatal0_1_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxfatal0_2_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxfatal0_3_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_ppxfatal0_4_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_dccmout_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__cr5_mp_dccmout2_0_siglat_scr_clr_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can9_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can9_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can10_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can10_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can11_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can11_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can12_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can12_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can13_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can13_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can14_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can14_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can15_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can15_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can16_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can16_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can17_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can17_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can18_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can18_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can19_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can19_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can20_ipg_stop_ack),
    SCR_SIGNAL(SCR_SEC__R16W16__can20_can_lpm_ack),
    SCR_SIGNAL(SCR_SEC__RO__rstgen_saf_boot_mode_scr_3_0),
    SCR_SIGNAL(SCR_SEC__RO__efusec_manu_cfg_87_64),
    SCR_SIGNAL(SCR_SEC__RO__efusec_misc_cfg_7),
    SCR_SIGNAL(SCR_SEC__RO__efusec_manu_cfg_88),
    SCR_SIGNAL(SCR_SEC__RO__efusec_fa_cfg_0),
    SCR_SIGNAL(SCR_SEC__RO__rstgen_sec_main_rst_b_and_main_gating_en),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_0_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_1_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_2_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_3_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_5_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_6_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_7_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_8_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_9_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_0_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_1_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_2_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_3_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_4_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_5_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_6_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_9_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_10_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_11_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_12_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_13_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_14_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_15_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_16_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_17_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_18_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_19_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_20_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_21_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_22_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_23_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_24_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_25_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_26_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_27_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_28_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_29_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_s_30_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_svreg_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_svreg_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_0_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_8_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_9_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_10_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_11_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_12_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_13_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_14_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_15_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_16_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_17_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_18_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_19_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_m_20_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_s_0_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_s_1_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_s_2_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_s_3_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_svreg_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_sec_m_svreg_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_0_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_1_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_2_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_3_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_4_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_5_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_6_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_7_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_8_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_9_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_10_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_11_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_12_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_13_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_14_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_16_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_17_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_18_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_19_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_20_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_21_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_22_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_23_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_m_24_i_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_0_sbp_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_1_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_2_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_3_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_4_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_5_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_6_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_7_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_8_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_9_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_10_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_11_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_15_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_16_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_17_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_18_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_19_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_20_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_s_21_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_noc_reg_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__noc_main_noc_reg_t_mainnopendingtrans),
    SCR_SIGNAL(SCR_SEC__RO__u_info_cmp_o_faultinfo_13_0),
    SCR_SIGNAL(SCR_SEC__RO__xtal_saf_xtal_rdy),
};

static const struct scr_signal scr_hpi_signals[] = {
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data1__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd9_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data3__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd10_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data5__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd11_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data7__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd12_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data9__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd13_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data11__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd14_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data13__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd15_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data15__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd16_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data17__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd17_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data19__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd18_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data21__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd19_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__L31__iomux_wrap_ap_pio_disp_mux__data23__oe),
    SCR_SIGNAL(SCR_HPI__L31__canfd20_canfd_debounce_time_3_0),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd9_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd9_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd9_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd9_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd9_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd10_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd10_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd10_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd10_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd10_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd11_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd11_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd11_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd11_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd11_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd12_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd12_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd12_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd12_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd12_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd13_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd13_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd13_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd13_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd13_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd14_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd14_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd14_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd14_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd14_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd15_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd15_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd15_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd15_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd15_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd16_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd16_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd16_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd16_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd16_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd17_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd17_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd17_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd17_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd17_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd18_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd18_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd18_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd18_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd18_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd19_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd19_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd19_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd19_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd19_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd20_ipg_stop),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd20_ipg_doze),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd20_sw_gating_en),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd20_sw_gating_dis),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd20_ipg_soft_reset_b),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd9_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd9_can_lpm_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd10_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd10_can_lpm_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd11_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd11_can_lpm_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd12_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd12_can_lpm_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd13_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd13_can_lpm_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd14_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd14_can_lpm_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd15_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd15_can_lpm_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd16_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd16_can_lpm_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd17_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd17_can_lpm_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd18_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd18_can_lpm_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd19_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd19_can_lpm_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd20_ipg_stop_ack),
    SCR_SIGNAL(SCR_HPI__R16W16__canfd20_can_lpm_ack),
};

static bool scr_read_signal(const struct scr_signal *signal, uint32_t *val)
{
    scr_handle_t handle;

    handle = hal_scr_create_handle(signal->signal);

    if (handle) {
        *val = hal_scr_get(handle);
        hal_scr_delete_handle(handle);
        return true;
    }
    else {
        printf("Can not get handle for %s\n", signal->name);
        return false;
    }
}

static bool scr_write_signal(const struct scr_signal *signal, uint32_t val)
{
    scr_handle_t handle;

    handle = hal_scr_create_handle(signal->signal);

    if (handle) {
        bool ret = hal_scr_set(handle, val);
        if (!ret)
            printf("Failed to set %s\n", signal->name);
        hal_scr_delete_handle(handle);
        return ret;
    }
    else {
        printf("Can not get handle for %s\n", signal->name);
        return false;
    }
}

static bool scr_signal_is_locked(const struct scr_signal *signal, bool *locked)
{
    scr_handle_t handle;

    handle = hal_scr_create_handle(signal->signal);

    if (handle) {
        *locked = hal_scr_is_locked(handle);
        hal_scr_delete_handle(handle);
        return true;
    }
    else {
        printf("Can not get handle for %s\n", signal->name);
        return false;
    }
}

static int scr_read_test(int argc, const cmd_args *argv)
{
    uint32_t val;
    uint32_t i;

    printf("Reading SCR_SAFETY\n");
    for (i = 0; i < SIZEOF(scr_safety_signals); i++) {
        const struct scr_signal *signal = &scr_safety_signals[i];
        if (scr_read_signal(signal, &val))
            printf("%s: 0x%x\n", signal->name, val);
    }

    printf("Reading SCR_SEC\n");
    for (i = 0; i < SIZEOF(scr_sec_signals); i++) {
        const struct scr_signal *signal = &scr_sec_signals[i];
        if (scr_read_signal(signal, &val))
            printf("%s: 0x%x\n", signal->name, val);
    };

    printf("Reading SCR_HPI\n");
    for (i = 0; i < SIZEOF(scr_hpi_signals); i++) {
        const struct scr_signal *signal = &scr_hpi_signals[i];
        if (scr_read_signal(signal, &val))
            printf("%s: 0x%x\n", signal->name, val);
    }

    return 0;
}

static int scr_lock_test(int argc, const cmd_args *argv)
{
    bool locked;
    uint32_t i;

    printf("Checking SCR_SAFETY lock status\n");
    for (i = 0; i < SIZEOF(scr_safety_signals); i++) {
        const struct scr_signal *signal = &scr_safety_signals[i];
        if (scr_signal_is_locked(signal, &locked))
            printf("%s: locked %d\n", signal->name, locked);
        else
            printf("%s: failed to get lock status\n", signal->name);
    }

    printf("Checking SCR_SEC lock status\n");
    for (i = 0; i < SIZEOF(scr_sec_signals); i++) {
        const struct scr_signal *signal = &scr_sec_signals[i];
        if (scr_signal_is_locked(signal, &locked))
            printf("%s: locked %d\n", signal->name, locked);
        else
            printf("%s: failed to get lock status\n", signal->name);
    }

    printf("Checking SCR_HPI lock status\n");
    for (i = 0; i < SIZEOF(scr_hpi_signals); i++) {
        const struct scr_signal *signal = &scr_hpi_signals[i];
        if (scr_signal_is_locked(signal, &locked))
            printf("%s: locked %d\n", signal->name, locked);
        else
            printf("%s: failed to get lock status\n", signal->name);
    }

    return 0;
}

static int scr_write_test(int argc, const cmd_args *argv)
{
    uint32_t val1, val2;
    uint32_t i;

    printf("Writing SCR_SAFETY\n");
    for (i = 0; i < SIZEOF(scr_safety_signals); i++) {
        const struct scr_signal *signal = &scr_safety_signals[i];

        if (scr_read_signal(signal, &val1)) {
            scr_write_signal(signal, BIT_MASK(_scr_width(signal->signal)));
            scr_read_signal(signal, &val2);
            printf("%s: 0x%x 0x%x\n", signal->name, val1, val2);
        }
        else {
            printf("Failed to read signal %s\n", signal->name);
        }
    }

    printf("Writing SCR_SEC\n");
    for (i = 0; i < SIZEOF(scr_sec_signals); i++) {
        const struct scr_signal *signal = &scr_sec_signals[i];

        if (scr_read_signal(signal, &val1)) {
            scr_write_signal(signal, BIT_MASK(_scr_width(signal->signal)));
            scr_read_signal(signal, &val2);
            printf("%s: 0x%x 0x%x\n", signal->name, val1, val2);
        }
        else {
            printf("Failed to read signal %s\n", signal->name);
        }
    }

    printf("Writing SCR_HPI\n");
    for (i = 0; i < SIZEOF(scr_hpi_signals); i++) {
        const struct scr_signal *signal = &scr_hpi_signals[i];

        if (scr_read_signal(signal, &val1)) {
            scr_write_signal(signal, BIT_MASK(_scr_width(signal->signal)));
            scr_read_signal(signal, &val2);
            printf("%s: 0x%x 0x%x\n", signal->name, val1, val2);
        }
        else {
            printf("Failed to read signal %s\n", signal->name);
        }
    }

    return 0;
}

DEFINE_REGISTER_TEST_COMMAND(read, scr, scr-read-test)
DEFINE_REGISTER_TEST_COMMAND(lock, scr, scr-lock-test)
DEFINE_REGISTER_TEST_COMMAND(write, scr, scr-write-test)

#if defined(WITH_LIB_CONSOLE)
#include <lib/console.h>

STATIC_COMMAND_START
    STATIC_COMMAND("scr-read-test", "scr-read-test", (console_cmd)&scr_read_test)
    STATIC_COMMAND("scr-lock-test", "scr-lock-test", (console_cmd)&scr_lock_test)
    STATIC_COMMAND("scr-write-test", "scr-write-test", (console_cmd)&scr_write_test)
STATIC_COMMAND_END(scr_test);

#endif
