#ifndef __build_safety_d9_ref_chipdev_disp_sd_disp_module_config_h_H
#define __build_safety_d9_ref_chipdev_disp_sd_disp_module_config_h_H
#define MODULE_COMPILEFLAGS ""
#define MODULE_CFLAGS "__DDISP_VERSION "2022_07_19_15:45:07""
#define MODULE_CPPFLAGS ""
#define MODULE_ASMFLAGS ""
#define MODULE_LDFLAGS ""
#define MODULE_OPTFLAGS ""
#define MODULE_INCLUDES ""
#define MODULE_SRCDEPS ""
#define MODULE_DEPS ""
#define MODULE_SRCS "_CHIPDEV_DISP_SD_DISP_DSI_DWC_MIPI_DSI_HOST_C_CHIPDEV_DISP_SD_DISP_DSI_DISP_DSI_API_C_CHIPDEV_DISP_SD_DISP_DSI_DISP_DSI_C_CHIPDEV_DISP_SD_DISP_CORE_DISP_DRV_C_CHIPDEV_DISP_SD_DISP_CORE_DISP_INTERFACE_C_CHIPDEV_DISP_SD_DISP_CORE_DISP_PANEL_C"
#endif
